### ISSUE TITLE
Zip semantics

### ISSUE THREAD

**Issue by devinrsmith** [dhall-lang/dhall-lang#1002]
```dhall
let Prelude = https://prelude.dhall-lang.org/v16.0.0/package.dhall

in  Prelude.List.zip Text [ "a", "b", "c", "d" ] Natural [ 0, 1, 2, 3 ]
```

produces

```
$ dhall --file zip-test.dhall
[ { _1 = "a", _2 = 3 }
, { _1 = "b", _2 = 2 }
, { _1 = "c", _2 = 1 }
, { _1 = "d", _2 = 0 }
]
```

I would have assumed that zip preserves the order of the lists. Is the output correct wrt the semantics of zip?

**Comment by Gabriel439** [comment]
@devinrsmith: This is a known issue.  See https://github.com/dhall-lang/dhall-lang/pull/995, which fixes this

**Comment by devinrsmith** [comment]
I think I searched on the wrong repo! Thanks.

**Comment by Gabriel439** [comment]
@devinrsmith: You're welcome! :slightly_smiling_face:
