### ISSUE TITLE
dhall-lang/standard/dhall.abnf is not quite valid ABNF

### ISSUE THREAD

**Issue by declaresub** [dhall-lang/dhall-lang#1003]
My attempt to parse the contents of dhall.abnf failed because of the use of unicode > 127 in a comment.

https://github.com/dhall-lang/dhall-lang/blob/12d5a99dc658653e653c23940acae8ce26f85bd1/standard/dhall.abnf#L373

**Comment by Nadrieril** [comment]
I had that problem too with the Rust abnf library. I think it's allowed though.
If I'm reading this https://tools.ietf.org/html/rfc5234#section-2.4 correctly, ABNF doesn't specify encodings and allowed characters (except for character strings).

> Encoding details are beyond the scope of ABNF, although Appendix B provides definitions for a 7-bit US-ASCII environment as has been common to much of the Internet.
> By separating external encoding from the syntax, it is intended that alternate encoding environments can be used for the same syntax.

So I would think your ABNF library is to blame, though that might not be a very helpful reply. I guess we don't have many such comments in the abnf so we could remove them if it's a big problem, but it's rather helpful :/

**Comment by declaresub** [comment]
Comments in an ABNF grammar are part of ABNF.  See https://tools.ietf.org/html/rfc5234#section-4 :

    comment        =  ";" *(WSP / VCHAR) CRLF

 As you say, having those characters in the comments is helpful, so perhaps a reasonable solution would be to warn of their presence in the header comments, with a suggestion that users wanting to parse the grammar file preprocess to remove the offending characters.

Or perhaps i should the unicode-in-abnf draft spec.

**Comment by Gabriel439** [comment]
It's such a small change that I'd be fine removing the `∀` and replacing it with, say, "Unicode FOR ALL"

**Comment by Nadrieril** [comment]
Oh, is it just that one character? Yeah I'd be fine to remove it too. I thought we used it for the other Unicode operators but we don't.

**Comment by Gabriel439** [comment]
I have a fix up here: https://github.com/dhall-lang/dhall-lang/pull/1004
