### ISSUE TITLE
Question: How do I write eliminators for "private" types?

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-lang#101]
In `dhall-to-cabal` I learnt the really useful trick of encoding a "private" type by a function containing the type and arguments for each possible constructor:

```haskell
forall ( foo : Type ) -> forall ( fromText : Text -> Foo ) -> forall ( fromInteger : Integer -> Foo ) -> Foo
```

In another project, I'd like my users to pull out information from `Foo`, but keep `Foo`'s implementation private. I'd like to offer an accessor into `Foo`, `blah : ./Foo -> Text`. Continuing the above example, this might do some arbitrary IO in my interpret that uses the `fromText` or `fromInteger` values appropriately.

Can this be done? If so, how do I write `blah`? I could do it with a custom type checking context, but I'm wondering if this is also possible in pristine Dhall.

**Comment by ocharles** [comment]
I wonder now if maybe the solution is to provide a top level function argument:

```
\ ( blah : ./Foo -> Text ) ->
blah ( ./Foo/fromText "Hello" )
```

If this is correct, I think it'd be worth having this in some kind of FAQ somewhere. I'm happy to write that up. If you have a better idea, I'm all ears.

**Comment by Profpatsch** [comment]
There is a `How-to guide` heading on the wiki of this repo.

**Comment by ocharles** [comment]
I only see https://github.com/dhall-lang/dhall-lang/wiki/How-to-translate-recursive-code-to-Dhall, but we could make a new section that includes that.

**Comment by Gabriel439** [comment]
The general trick is still the same: decide what you want your API to be and then you just do the same thing you did before when encoding a recursive API: just introduce one lambda abstraction per type or term that you want to expose.

For example, suppose that you had this example Haskell API with a private implementation:

```haskell
module Example (NonNegative, get, validate)

data NonNegative = NonNegative Integer

get :: NonNegative -> Integer
get (NonNegative x) = x

validate :: Integer -> Maybe NonNegative
validate x = if x < 0 then Nothing else NonNegative x
```

... and another module that used that API:

```haskell
example :: Maybe Integer
example = fmap get (validate 3)
```

The translation of `example` to `Dhall` would be:

```haskell
  λ(NonNegative : Type)
→ λ(validate : Integer → Optional NonNegative)
→ λ(get : NonNegative → Integer)
→ Optional/fold
  NonNegative
  (validate 3)
  (Optional Integer)
  (λ(x : NonNegative) → [ get x ] : Optional Integer)
  ([] : Optional Integer)
```

**Comment by ocharles** [comment]
Ok, I think in the `dhall-to-cabal` case we got kind of "lucky" in the sense that all of these lambda abstractions could be pushed down out of the top-level into individual files, so people aren't even aware of those. The moment you need to do more than construct private values though, the lambda abstractions have to be pushed up further. 

I mention this, because if we consider the Dhall you provided as "user written" code, they have to introduce *all* lambda abstractions, even if they don't plan to use them at all. For example, if I didn't want to use `NonNegative` at all, I would still have to write

```haskell
  λ(NonNegative : Type)
→ λ(_ : Integer → Optional NonNegative)
→ λ(_ : NonNegative → Integer)
→ True
```

Again, with `dhall-to-cabal` we were lucky that because we were only constructing things, you didn't need any opening bindings.

A more minimal translation of your example is probably something like

```haskell
  λ(get : ./NonNegative → Integer)
→ Optional/fold
  ./NonNegative
  (./NonNegative/validate 3)
  (Optional Integer)
  (λ(x : ./NonNegative) → [ get x ] : Optional Integer)
  ([] : Optional Integer)
```

**Comment by Gabriel439** [comment]
Yeah, in general you can't get self-contained values; you have to thread the "context" explicitly.  For example, try to write `validate : Integer → Optional ./NonNegative` and you will see the limitation.

I think the right approach in general is not require private behavior in the first place and see if any invariants can be modeled in the type system and if any `IO` can be done via the import system.

**Comment by ocharles** [comment]
> I think the right approach in general is not require private behavior in the first place and see if any invariants can be modeled in the type system and if any IO can be done via the import system.

This is new to me, but I think what you were trying to get at in one your recent blog posts. It would make a great example (or blog post!) that expands on this.

**Comment by Gabriel439** [comment]
Yeah, I plan to do so.  A really simple example would be the following Haskell program:

```haskell
main :: IO ()
main = do
    n <- readLn
    print (n + 1)
```

... which the user would use like this:

```bash
$ ./example
1<Enter>
2
```

The equivalent Dhall program would just be:

```bash
λ(n : Natural) → n + +1
```

... and the equivalent command line interaction would be:

```bash
$ dhall <<< './example.dhall +1'
```

That's a simple example of how if some uses of `IO` can become superfluous if you change the user workflow (the user specifies the value on the command line instead of via `stdout`) or into the interpreter (Dhall's import system + the fact that the executable auto prints the result)

More generally, we can in principle add new ways to import values or new input formats if they are supported by stable non-proprietary standards.  For example, at some point we might want to be able to import values from a database or in JSON format (although that has issues to be resolved) so that more `IO` can be handled transparently by the interpreter.

**Comment by Gabriel439** [comment]
For example, it's not really surprising at all if you think about parallels to memory management: in languages with manual memory management the act of managing memory is done via explicit commands whereas in automatic memory management it is handled transparently by the compiler/interpreter for you in pure code.

**Comment by ocharles** [comment]
That much I get, but there's something lacking between that and connecting it to the real world, but I can't put my finger on it.

**Comment by Gabriel439** [comment]
The way I would put it is that programming is slowly gravitating towards a certain simplified and constrained programming model as we notice common architectural patterns that arise over and over again in "good code" and automate those patterns directly within the compiler/interpreter.  From my perspective the common patterns for the next generation of programming languages will be:

* Automatic memory management (a.k.a. garbage collection)
* Automatic evaluation order management (a.k.a. laziness which will evolve into optimal evaluators)
* Automatic testing (a.k.a. type checking)
* Automatic distribution/caching (i.e. content addressable systems like Git/Nix/IPFS)
* Data is code (i.e. non-Turing-complete languages like Dhall)
* Automatic input (i.e. Dhall/Nix-style imports)
* Automatic visualization/presentation (?  Not sure what this will look like)

As we push more and more of those mundane tasks into the language/compiler/interpreter, the core language that remains begins to resemble pure mathematics.  In other words, mathematics is the final destination of programming and any non-mathematical aspect of programming will eventually get pushed into the underlying infrastructure and become an implementation detail.

**Comment by ocharles** [comment]
I got the answer I was looking for here. Thanks!
