### ISSUE TITLE
Is `Some` really a keyword?

### ISSUE THREAD

**Issue by german1608** [dhall-lang/dhall-lang#1012]
@Gabriel439 filed an issue on [dhall-lang/dhall-haskell](https://github.com/dhall-lang/dhall-haskell/issues/1750) a month ago about a bug in dhall-haskell implementation. Record labels should not be a language keyword.

I was trying to fix it, and noted the following:

Standard requires that `Some` is a reserved keyword:

https://github.com/dhall-lang/dhall-lang/blob/9358ffa9c8241b0d8446d46010318758b0df38cb/standard/dhall.abnf#L380-L388

If that so, then the implementation of [Optional/length](https://github.com/dhall-lang/dhall-lang/blob/9358ffa9c8241b0d8446d46010318758b0df38cb/Prelude/Optional/length#L8) contains a syntax error:

https://github.com/dhall-lang/dhall-lang/blob/9358ffa9c8241b0d8446d46010318758b0df38cb/Prelude/Optional/length#L8

A simple solution is to remove `Some` from that list, but I'd like to read your thoughts about that.

**Comment by sjakobi** [comment]
The special treatment of `Some` was recently added to support `merge` on `Optional` values. Record keys have to have the following form:

https://github.com/dhall-lang/dhall-lang/blob/9358ffa9c8241b0d8446d46010318758b0df38cb/standard/dhall.abnf#L229-L230

But `Some` is a keyword nonetheless. This is a syntax error:

```
let Some = 1 in {=}
```

**Comment by german1608** [comment]
@sjakobi thanks for the clarification! I'll close this issue then
