### ISSUE TITLE
Feature notification: Hydra can return multiple checks into GitHub

### ISSUE THREAD

**Issue by Anton-Latukha** [dhall-lang/dhall-lang#1016]
As you informed in the dialog before, you have own Hydra deployment.

Reporting that Hydra can pass multiple checks into GitHub. I remember it was not hard to configure.

Hydra CI able to check, report multiple checks into GitHub, and so you would be able to observe that checks information right in PRs.

I wrestle with Travis myself in In https://github.com/haskell-nix/hnix/issues/593, and it is sad it and many CIs pass only one summary check.

**Comment by Gabriel439** [comment]
Hydra can report multiple statuses.  If you give Hydra a `release.nix` file with more than one attribute then Hydra will report one status per attribute.

I maintain an open source Hydra deployment here which you can study if you are interested: https://github.com/dhall-lang/dhall-lang/tree/master/nixops#dhall-infrastructure

**Comment by Anton-Latukha** [comment]
Yes, it is.

Thank you for your attention.

**Comment by Gabriel439** [comment]
@Anton-Latukha: You're welcome! 🙂
