### ISSUE TITLE
How to import a union type?

### ISSUE THREAD

**Issue by gvolpe** [dhall-lang/dhall-lang#1021]
Hi,

Sorry if this is not the place for asking a question, I really didn't want to register in the other sites.

I have a simple union type defined in a file `Foo.dhall`:

```dhall
< One | Two | Three >
```

And I want to make use of it in a different remote file, so I'm importing it:

```dhall
let Foo  = remote_url/Foo.dhall sha256: blablabla
in Foo.One
```

This gives me an error `Missing record field: One`. 

What's the right way to do it?

**Comment by gvolpe** [comment]
Okay, found the issue, in case it is helpful to someone: The constructors must be lowercase!!! 

So this works:

```dhall
< one | two | three >
```

**Comment by Gabriel439** [comment]
@gvolpe: Hmmm, that should not be necessary.  The language supports uppercase constructors and this works fine when I tested locally:

```bash
$ cat Foo.dhall 
< One | Two | Three >

$ cat Bar.dhall 
let Foo = ./Foo.dhall

in  Foo.One

$ dhall --file Bar.dhall
< One | Three | Two >.One
```

I think there must be something else going on in your case

**Comment by gvolpe** [comment]
Thanks @Gabriel439 ! 

That was working for me as well, the issue came when I imported the file from a remote URL (namely `https://raw.githubusercontent.com/........`). 

I guess it shouldn't make a difference right? Maybe I had something else going on but it magically got fixed when I switched to using lowercase...

**Comment by ari-becker** [comment]
@gvolpe are you using OS X?

I've had colleagues run into issues where the lack of case-sensitivity in OS X meant that they had tried to change the name of a file from `foo` to `Foo`, Git didn't pick up on the change, and then when it was committed then `foo` was what was actually committed. Dhall however is case sensitive, including when using remote imports.

**Comment by Gabriel439** [comment]
@gvolpe: Yeah, remote imports should not make a difference either.  There's no where in the code where Dhall is case-sensitive about identifiers/fields/labels/etc.

For future reference, if you run into this problem again, the easiest way to understand what is going on is to just ask the interpreter what the union type is by removing the constructor name, like this:

```dhall
let Foo  = remote_url/Foo.dhall sha256: blablabla
in Foo
```

The result of interpreting that should help us better understand what might have gone wrong.

**Comment by gvolpe** [comment]
Thanks, no, I'm on Linux... I'll have that in mind next time, thanks for your explanation!

**Comment by Gabriel439** [comment]
@gvolpe: You're welcome! 🙂
