### ISSUE TITLE
Typo in start page

### ISSUE THREAD

**Issue by gDanix** [dhall-lang/dhall-lang#1023]
Hi!

It's not big deal, but I've detected a typo in the start page (bill -> blil):
![imagen](https://user-images.githubusercontent.com/1117657/84037372-cc8de680-a99e-11ea-8c5c-7cf63231396c.png)

Maybe this is an opportunity to show why we need the amazing features Dhall has, but if you want it fixed, I have the PR ready :)

**Comment by gDanix** [comment]
Ok, I'm an idiot, I've read right now the comment. Nevermind...

**Comment by Gabriel439** [comment]
@gDanix: No worries! 🙂
