### ISSUE TITLE
Papercut: make `{}` the empty record instead of the empty type?

### ISSUE THREAD

**Issue by timbertson** [dhall-lang/dhall-lang#1024]
One thing that keeps tripping up my colleagues who are new to dhall (and still me, occasionally) is that the empty record is `{=}`.

Maybe I'm using it wrong, but I type empty records a lot (in particular for schemas where I'm not overriding anything, e.g. `Foo::{=}`). Meanwhile I don't think I've ever needed `{}`, the empty record type. `{}` is far more natural to type and read, so I think it should correspond to the more frequently used term.

I know it would be a long tedious process to rename -- we'd need a way to write the current `{}`, does `{:}` work or is that ambiguous to parse?

But I feel like this papercut may be particularly jarring. Dhall records look a bit like JSON, but `{=}` doesn't resemble syntax from any other language (that I know of).

**Comment by Gabriel439** [comment]
The original reason for making the empty record type simpler was because I felt that it was more important to keep types simple and readable than terms.  The reasoning is that (A) types are supposed to aid the developer in coarsely reasoning about the code and (B) types are a communication short-hand shared between developers when designing things.

**Comment by timbertson** [comment]
I should stop to ask: do you think it reasonable that the more frequently used construct should get dibs on the shorter `{}`?

FWIW I just grepped my own small codebase, `{=}` is used 18 times while `{}` is never used. I'd love to not have to explain to new users what `{=}` is, because everyone familiar with JSON already knows what `{}` is.

**Comment by Gabriel439** [comment]
@timbertson: Are all of your uses of `{=}` for record completions?  One possible solution is to add a grammatical special case for record completions to treat `Foo::{=}` the same as `Foo::{}`

There's another reason I suggest this, which is that one thing I've been contemplating is changing the right argument to the record completion operator to not be a real record but rather a special syntactic form, so that we can desugar it to use `with` instead of `//`, like this:

```dhall
Foo::{ x.y = z } = (Foo.default with x.y = z) : Foo.Type
```

... so if we would already be making the right argument a special syntactic form, then we could go all the way and add the convenient short-hand for an empty completion.

**Comment by ari-becker** [comment]
As a long-term user, I'd personally find `Foo:{}` to be more confusing. The right-hand side of `::` doesn't have to be an in-line record, it can also be e.g. `Foo::( ./extra.dhall )`.

**Comment by timbertson** [comment]
> Are all of your uses of {=} for record completions?

Most of them, yes. The rest are empty defaults in schemas, for future compatibility:

```
{ Type = { ... }, default = {=} }
```

I also have a habit of commenting out a whole record's contents during debugging to make type errors clearer, e.g:

```
{
-- , x = 1
-- , y = 2
}
```

I have to go and make the first line `{=`, which is very awkward. Maybe this is a weird thing to do, but it means the compiler can simply tell me what it _wants_, rather than doing a two way diff of what-you-gave-me-vs-what-I-expected.

I think I'd also find it a bit odd if `{}` was used for an empty completion but `{=}` still for empty records, since that'd make them even more confusing when you stumble across them as a new user.

**Comment by Gabriel439** [comment]
@timbertson: If I had to pick, I would still prefer to keep things the way they are, if only to minimize disruption.  It would be a pretty breaking change, especially given that there would not be a good migration strategy; we wouldn't be able to author code that works before and after the change

**Comment by timbertson** [comment]
Yeah it wouldn't be easy. I was imagining the first step would be to
introduce, say, `{:}` as the unambiguous form for an empty record type.

After a while you start getting `dhall lint` to prefer that, and after
longer still you could drop `{}` entirely. And then wait some more before
reintroducing it as the empty record syntax.

But yes, that's a long road if you're not that bothered by it. I just
thought I'd bring it up early in case that was a path worth starting down
now.

>

**Comment by lukestephenson-zendesk** [comment]
I can second this just caused me hours of confusion

**Comment by timbertson** [comment]
This is particularly frustrating because if `Foo::{ x = y }` isn't working due to a type error and you can't figure out why, a common debugging step is to try and simplify the example. The easiest simplification is to remove `x = y`, which only magnifies the confusion, because now you have two problems.

**Comment by timbertson** [comment]
Actually, one concrete thing that could help is for the explain output for `({Type = {}, default={=}})::{}` to:

 - highlight how `::` relates to merging, because that might not be obvious, but more importantly
 - specially call out that `{}` is a type, not a value

It'd even be worth adding a specific error message when attempting to merge `{}`, but I don't know how hard that would be to detect.

**Comment by timbertson** [comment]
Oops, I didn't read the explain in full detail. It does include:

```
You supplied this expression as one of the arguments:

↳ {}

... which is not a record, but is actually a:

↳ Type
```

This is good explain text, though I am curious how hard it would be to special-case errors when we expect a record and get a type equal to `{}`.
