### ISSUE TITLE
Prelude files with .dhall.dhall extension

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-lang#1040]
```
$ ls **.dhall.dhall
Prelude/JSON/core.dhall.dhall  Prelude/JSON/renderInteger.dhall.dhall
```

These files were introduced in https://github.com/dhall-lang/dhall-lang/pull/1026 –  inadvertently, I assume.

Shall we try to get rid of them before the next Prelude release?

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-lang/pull/1041
