### ISSUE TITLE
EOF as end of single-line comments

### ISSUE THREAD

**Issue by german1608** [dhall-lang/dhall-lang#1046]
I was testing with this file:

```dhall
let a = 1 in a --
```

without a newline after the `--` using the Haskell implementation and it gave me a parse error. Then I looked at `dhall.abnf`:

https://github.com/dhall-lang/dhall-lang/blob/728dc009c887400fc5c97341f29a078b8a9ea31e/standard/dhall.abnf#L169

and I noticed that it doesn't say anything about EOF. Is this the expected behavior of the grammar (to fail in this case)? Is this a bug on Haskell's implementation?

**Comment by philandstuff** [comment]
I would argue that all text files (dhall files included as a subset of this) should end with a newline. Newline characters are line terminators, not line separators, and lots of behaviour of text manipulation tools expects a terminating newline. 

For example: if you `cat` two files together, and the first file lacks a final newline, the last line of the first file will get joined onto the first line of the second file. 

So in this situation I’m happy with the current behaviour.

**Comment by singpolyma** [comment]
>without a newline after the `--` using the Haskell implementation and it
>gave me a parse error.

Newline terminate lines, they do not separate them. A text file is a set of 
lines, which of course must be terminated by a newline. Dhall source code is 
stored in text files, and is normally created in text editos.

So yes, the end of a Dhall file must be a newline unlesd the file is empty 
(since a nonempty file surely contains a line!)

If you created this file by hand from shell, just open in an editor and save 
will usually fix it.

If you created this file in an editor, I would report a bug in the editor.

**Comment by german1608** [comment]
> If you created this file in an editor, I would report a bug in the editor.

I didn't include the last newline un purpose, I was debugging some edge-cases for `dhall-docs` and noticed that.

> So in this situation I’m happy with the current behaviour.

I'm ok too, the purpose of this issue was to know if this was a known thing on the grammar. I'll keep this issue open in case somebody has further thoughts

**Comment by Gabriel439** [comment]
I agree that Dhall source code saved to a file should end with a newline, but we probably want to preserve the option for code that is not saved to a file to be newline-free for uses like this:

```bash
$ dhall <<< '2 + 2'
```

... so that we don't have to write:

```bash
$ dhall <<< '2 + 2\n'
```

**Comment by philandstuff** [comment]
@Gabriel439 bash appends a newline to here strings for you already. See section 3.6.7 here: https://www.gnu.org/software/bash/manual/html_node/Redirections.html

**Comment by Gabriel439** [comment]
@philandstuff: Oh, I had no idea!  TIL 🙂

**Comment by philandstuff** [comment]
I think there’s a rough consensus that this isn’ta problem, so I’ll close. Please reopen if I’ve interpreted this wrongly and you feel there is still an issue here.
