### ISSUE TITLE
Having a way to apply string/text transformation like `replace`

### ISSUE THREAD

**Issue by mikefaille** [dhall-lang/dhall-lang#1051]
As a usecase, I use dhall-kubernetes and I want to generate my config from a simple input. 

As an example, I want use the domain name `example.com` to populate my config.

But, I have a limitation due to kubernetes. I can't reuse the `.` (dot) char as `name` for the `namespace` type/object. Then, normally, with a configuration tool like `helm` I replace `.` with `-` to get a `namespace` named like `example-com`.

At the end, creating new strings by replacing char from a previous one is a go/no-go for me to use dhall (vs jsonnet). I'm not a pro in haskell even if I try. I will need assistance to make it work or community contribution. For sure, we can simply position this issue as a _feature request._ Thank you for any help ! 

PS : Sorry for my english.

**Comment by Gabriel439** [comment]
I submitted an expense proposal to fund this work for $200 if the proposal passes: https://discourse.dhall-lang.org/t/expense-proposal-standardize-text-replace-built-in/339

**Comment by mikefaille** [comment]
Ho yeah ! More sexyness to Dhall is always awesone !
