### ISSUE TITLE
Setup compression in the nix cache

### ISSUE THREAD

**Issue by basile-henry** [dhall-lang/dhall-lang#1089]
The default nix cache for dhall doesn't have any compression setup. This is not great when trying to use it all the way from Europe when the connection is already slow (I believe the server is located on the west coast of the US?).

I think unfortunately that no compression is the default for `nix-serve`, and it might not be easy to change that. However `hydra` also serves a nix cache and compresses artefacts with `xz` by default. The only thing missing is actually setting up the signing keys.

Here is an example of me getting dhall 1.36.0 from the two different caches:
```bash
➜ curl https://cache.dhall-lang.org/s2hgk76h21gnbig803933jrsylfhnk7r.narinfo
StorePath: /nix/store/s2hgk76h21gnbig803933jrsylfhnk7r-dhall-1.36.0
URL: nar/s2hgk76h21gnbig803933jrsylfhnk7r.nar
Compression: none
NarHash: sha256:0y502zlx2ac0h3fh4kzawv72347z7bjk3p1s772mf2sx3s44g3kg
NarSize: 11544416
References: 50yyyrdc416drp104zn6kx97nglbb2pc-ncurses-6.1-20190112
Deriver: k7j5609ra9lwxlkhmnicr7gacqxsyg6p-dhall-1.36.0.drv
Sig: cache.dhall-lang.org:uZXNOWtHxJyAjSzItUGmrpdfR4JNIkhVQLArPF1mBYwd9UPVBukPkl+JhhHcP0KVS3C7yJiH8IXjn79PNBb2BA==

➜ curl https://cache.dhall-lang.org/nar/s2hgk76h21gnbig803933jrsylfhnk7r.nar -s | wc -c | numfmt --to=iec-i
12Mi

➜ curl https://hydra.dhall-lang.org/s2hgk76h21gnbig803933jrsylfhnk7r.narinfo
StorePath: /nix/store/s2hgk76h21gnbig803933jrsylfhnk7r-dhall-1.36.0
URL: nar/s2hgk76h21gnbig803933jrsylfhnk7r-dhall-1.36.0
Compression: xz
NarHash: sha256:0y502zlx2ac0h3fh4kzawv72347z7bjk3p1s772mf2sx3s44g3kg
NarSize: 11544416
References: 50yyyrdc416drp104zn6kx97nglbb2pc-ncurses-6.1-20190112
Deriver: k7j5609ra9lwxlkhmnicr7gacqxsyg6p-dhall-1.36.0.drv
System: x86_64-linux

➜ curl https://hydra.dhall-lang.org/nar/s2hgk76h21gnbig803933jrsylfhnk7r-dhall-1.36.0 -s | wc -c | numfmt --to=iec-i
2.6Mi
```

I believe the way to setup the signing keys for hydra is to create a signing key and then to add:

```
binary_cache_secret_key_file = /path/to/key.sec
```

To `extraConfig` [here](https://github.com/dhall-lang/dhall-lang/blob/master/nixops/logical.nix#L125).
Unfortunately this will trigger a deprecation notice (which can be disabled by using this patch: https://github.com/NixOS/hydra/pull/820/commits/df3262e96cb55bdfaac7726896728bfef675698b)

Note: If you do decide this is a good idea and setup the signing key on hydra I would recommend against making `cache.dhall-lang.org` point to the `hydra` instance (or at least not without seriously thinking about it first). The issue is that the URL for the nar files is different between `hydra` and `nix-serve`. In itself it shouldn't be an issue but unfortunately the default setting for nix is to cache narinfos for a month. Maybe a solution could be to serve `nix-serve` as a backup for `hydra`? Or at least `nix-serve`'s nar files while transitioning?

**Comment by Gabriel439** [comment]
I have a fix up here: https://github.com/dhall-lang/dhall-lang/pull/1094

I went with just enabling a parallel cache for Hydra and leaving the `nix-serve` cache as-is for now

I'm also not sure if I can reuse the same key-pair as `nix-serve` (which is what the PR currently does)
