### ISSUE TITLE
Import resolution independent of type checking

### ISSUE THREAD

**Issue by basile-henry** [dhall-lang/dhall-lang#1113]
The standard says the following about [import resolution](https://github.com/dhall-lang/dhall-lang/blame/9e026b8b13b80dac4246d5a431c2d8a7f4aef4b7/standard/imports.md#L877-L886):

```
Resolution of expressions might not be always successful: pure expressions are
always resolved, the `missing` keyword never resolves, and imports might not 
resolve in cases like:

* an environment variable is not defined
* file doesn't exist
* URL is not reachable
* parse error
* hash mismatch
* typecheck error
```

I think `parse error` and `typecheck error` are different types of errors to the rest. The intention behind using alternative imports as far as I understand is more to control if a source is missing or not. From this, I would assume that it probably shouldn't include this type of resolution error and instead actually error out.

Are there any use cases where this behaviour is useful?

The advantage of removing these two errors (and in particular the type checking one) from import resolution logic means that it is easier to implement import resolution as a separate stage from type checking. This also means that we can optimize import resolution in a more straight forward manner, for example by batching or making http requests asynchronous.
More concretely resolving imports asynchronously is required for the Rust implementation of Dhall in order to support `wasm` (see https://github.com/Nadrieril/dhall-rust/issues/166). It is probably possible to still do type checking as part of import resolution but needlessly complicates the implementation. 

Related to https://github.com/dhall-lang/dhall-haskell/issues/1146

**Comment by Gabriel439** [comment]
@basile-henry: Yeah, I think separating import resolution errors from other errors is a good idea.  I actually thought we already had an issue to track decoupling the two, but I couldn't find it

**Comment by Gabriel439** [comment]
Proposed change is up here: https://github.com/dhall-lang/dhall-lang/pull/1181
