### ISSUE TITLE
Missing recursive merge simplification?

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-lang#1119]
What do people think about

```dhall
λ(x : {}) → λ(y : {}) → x ∧ y
```

changing to

```dhall
λ(x : {}) → λ(y : {}) → {=}
```

?

We already have simplifications for if the left or right hand side are the empty record, it seems logical to me to have one more case for when they are both empty.

**Comment by sjakobi** [comment]
> We already have simplifications for if the left or right hand side are the empty record

These simplifications only apply when one of the records is a concrete value. They don't work for example in this case:

```dhall
⊢ λ(x : {}) → λ(y : {a : Bool}) → x ∧ y

λ(x : {}) → λ(y : { a : Bool }) → x ∧ y
```

To perform the simplification you propose we'd have to preserve type information during normalization.

**Comment by ocharles** [comment]
Hmm, I see. My implementation does actually do both of those simplifications because I just treat this operator as type directed syntactic sugar

**Comment by ocharles** [comment]
Sorry, my previous comment was a little incorrect. You're right in your response, but I just wanted to mention that in my implementation of Dhall (which is presumably not standards conformant), I desugar `∧` while elaborating, and I elaborate into a subset of Dhall that doesn't even have `∧`. I can do this because there is no computational content to `∧`, it is purely type-directed syntactic sugar. For reference, https://hub.darcs.net/ocharles/dhalli/browse/lib/Dhalli/Elaboration.hs#810.

That said, this is outside the scope of how Dhall as a standardised language works, so I should probably open another issue talking about this broader idea.
