### ISSUE TITLE
Prelude support for CBOR?

### ISSUE THREAD

**Issue by ehmry** [dhall-lang/dhall-lang#1121]
I'm working on representing CBOR in Dhall, that means converting Dhall, JSON, YAML to CBOR, which can then be encoded to binary by a special utility. Implementation details aside, is this something worth including in the prelude, or better kept as an additional library?

https://git.sr.ht/~ehmry/dhall-cbor/tree
https://git.sr.ht/~ehmry/dhall-nim/tree/de0ba50c34be9f7eca6f38248db3d400450df48a/src/dhall/cbor_translation.nim

**Comment by Gabriel439** [comment]
I think it's fine to add it to the Prelude, since CBOR is widely used, and has an RFC associated with it

**Comment by ehmry** [comment]
Please re-open if there is interest in this again.
