### ISSUE TITLE
Documentation regarding TOML integration appears inaccurate

### ISSUE THREAD

**Issue by joell** [dhall-lang/dhall-lang#1125]
The Dhall documentation makes the following claim regarding integration with TOML:

> Dhall does not yet support conversion to TOML, but until then you may be able to work around this by using the fact that TOML is a superset of JSON

Unfortunately, TOML is not a superset of JSON.  (YAML is, though, and it seems a common misconception that TOML is as well.)

The [ABNF grammar of TOML](https://github.com/toml-lang/toml/blob/1.0.0-rc.3/toml.abnf) as linked from the [TOML spec](https://toml.io/en/v1.0.0-rc.3#abnf-grammar) can be consulted to verify this.  For example, note that even in inline tables the key names are not quoted in TOML, but in JSON key names must be quoted.

**Comment by sjakobi** [comment]
> For example, note that even in inline tables the key names are not quoted in TOML, but in JSON key names must be quoted.

According to https://toml.io/en/v1.0.0-rc.3#keys the keys _may_ be quoted though.

Could you possibly give us some sample JSON that isn't valid TOML, and that would therefore disprove the claim that TOML is a superset of JSON?

**Comment by joell** [comment]
Ah, my apologies in giving the wrong example.  I had somehow missed the `quoted-key` rule on my glance at the grammar.

As for another example of valid JSON that is not valid TOML, here is one I have machine-checked against the grammar as invalid:

```json
{"simple": 1}
```

This is not valid TOML.  Consulting the grammar gives multiple reasons:

* Inline tables' key-value separator must be `=`, not `:`.  (See definition of `keyval-sep`.)

* Inline tables are not permitted as a top-level `expression`.  The only place an `inline-table` is matched in the ABNF is as part of a `val` rule; in other words, inline tables can only be used as values to top-level keys.  This prevents a valid TOML document from ever starting with a `{` character.

The [ABNF TOML grammar](https://github.com/toml-lang/toml/blob/1.0.0-rc.3/toml.abnf) provides instructions in the comments at its top on how to interactively test candidate text against the grammar using an online tool they link.  You can try machine-validating this example and others against the grammar there, if you like. :-)
