### ISSUE TITLE
Can't use `with` on RHS of function call

### ISSUE THREAD

**Issue by timbertson** [dhall-lang/dhall-lang#1142]
Apologies if this is a duplicate, I tried searching but `with` doesn't narrow down search results very well ;)

I think of `with` as a recursive update operator, but I think because it only works on `import-expression` as the LHS, it isn't accepted after e.g. the result of a function call. My simplified example is using a function which applies some default config to every environment, and then uses `with` to override a few deeply-nested attributes:

```dhall
let Config = { size: Natural }
let base = \(common: Config) -> {
	, development = common
	, staging = common
	, production = common
}

in
(base { size = 10}) with development.size = 1
```

But I get:
```bash
dhall:
Error: Invalid input

(input):9:21:
  |
9 | (base { size = 10}) with development.size = 1
  |                     ^
unexpected 'w'
expecting ->, :, end of input, or whitespace
```

**Comment by Gabriel439** [comment]
@timbertson: What version of the interpreter are you using?  The reason I ask is that I tested your example on `master` and I can't reproduce the problem:

```bash
$ dhall 
let Config = { size: Natural }
let base = \(common: Config) -> {
	, development = common
	, staging = common
	, production = common
}

in
(base { size = 10}) with development.size = 1
<Ctrl-D>
{ development.size = 1, production.size = 10, staging.size = 10 }
```

**Comment by timbertson** [comment]
Oops, sorry I should have checked, I was on an old version (1.33.1). I did check the language grammar on `master`, but clearly `import-expression` isn't as restrictive as I had assumed.

**Comment by Gabriel439** [comment]
No problem! 🙂
