### ISSUE TITLE
Support for multiple output files

### ISSUE THREAD

**Issue by elverkilde** [dhall-lang/dhall-lang#1149]
Thank you for Dhall! We use it for all our Kubernetes configs. It's great, but we've found one major drawback; we use Dhall to generate k8s deployments *for many different envs*. This can be test/prod, but also e.g. different AWS regions.

Our current solution is to define one Dhall file per environment, all calling the same function with different parameters. It takes a long time to render one k8s config, let alone doing it N times for N > 30.. We could ofc. generate all envs in one file, which would be a lot more efficient, but we would need to manually split them up somehow.

I am wondering if it would be possible to support multiple outputs somehow, I am imagining either:

 * A top level keyword that would take a Dhall value and an output file, so you could write something like 
 ```dhall
 let deployment = \(region : Text) -> ... derive config from region
 
 compile deployment "us-east-1"
 compile deployment "us-east-2"
 ``` 
 
 Which would only need to generate the "thunk" of the unapplied deployment function once and then apply the 2 different strings for each output file.
 
 * Some way to cache the AST/type info between runs to achieve the same as above.
 
 Is this already possible (outside of generating a list and splitting it afterwards)? I would be happy to contribute to this with some direction.

**Comment by TristanCacqueray** [comment]
I can't tell if it is currently possible to do that with the provided command line, but for what its worth, we solved a similar issue using the haskell library. Here is an example script you could use as `./multi-dhall.hs "./deployment-function.dhall" "us-east-1" "us-east-2"` to create both deployment in one shot:

```haskell
#!/usr/bin/env nix-shell                                                                                                                                                                                                                                                                                                                                                                                                                     
#! nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/d4f19a218cbb15a242864a49f8b9f16fb7d48ec8.tar.gz                                                                                                                                                                                                                                                                                                                             
#! nix-shell --pure -i runghc -p "haskellPackages.ghcWithPackages (p: [ p.dhall p.text p.dhall-json ])"                                                                                                                                                                                                                                                                                                                                      

-- | Evaluate a function multiple times in one pass                                                                                                                                                                                                                                                                                                                                                                                          
module MultiDhall where

import Data.Aeson (encodeFile)
import Data.Text (pack)
import Dhall (inputExpr)
import Dhall.Core (Expr (App))
import Dhall.JSON (convertToHomogeneousMaps, defaultConversion, dhallToJSON, omitNull)
import System.Environment (getArgs)

main :: IO ()
main =
  getArgs >>= \args -> case args of
    (fun : xs) -> do
      -- Load the function expression                                                                                                                                                                                                                                                                                                                                                                                                        
      funExpr <- inputExpr (pack fun)
      mapM_ (go funExpr) xs
    _ -> putStrLn "usage: multi-dhall function [arg]"
  where
    go funExpr arg = do
      -- Load an argument and apply the function
      argExpr <- inputExpr (pack arg)
      case dhallToJSON (convertToHomogeneousMaps defaultConversion (App funExpr argExpr)) of
        Left err -> error (show err)
        Right v -> encodeFile (arg <> ".json") (omitNull v)

```

**Comment by elverkilde** [comment]
Thanks @TristanCacqueray, this was also a temporary hack I considered, thanks for sharing! I will leave this issue open to see if there are any maintainers interested in any sort of official support for this.

Given that this is fairly easy to implement already with the library I should probably have opened the issue on that repo instead.

**Comment by Gabriel439** [comment]
@elverkilde: There is a `dhall to-directory-tree` subcommand that would let you generate multiple files from a single input file.  For example, if you have a file like this:

```dhall
let renderYAML = https://prelude.dhall-lang.org/v20.0.0/JSON/renderYAML.dhall

let deployment = …

in  { `us-east-1.yaml` = renderYAML (deployment "us-east-1")
    , `us-east-2.yaml` = renderYAML (deployment "us-east-2")
    …
    }
```

However, this would also entail changing `deployment` to return a `Prelude.JSON.Type`, which would be a bit unergonomic until https://github.com/dhall-lang/dhall-lang/issues/336 is standardized.

I am working on ways to improve the performance on large Kubernetes configurations by (among other things) improving caching, like you suggested, but it will be a while out because there are some preliminary things I need to standardize first.

**Comment by joneshf** [comment]
Could [adding support for `to-directory-tree`](https://github.com/dhall-lang/dhall-haskell/issues/2073) to `dhall-to-json`/`dhall-to-yaml` help here?
