### ISSUE TITLE
Add shebang #! support

### ISSUE THREAD

**Issue by stergiotis** [dhall-lang/dhall-lang#1157]
It would be very nice if dhall would honor the unix shebang convention. 

This would then be a runnable script:
```
#!/usr/bin/env -S dhall text --file
'''
hello!
'''
```

**Comment by Gabriel439** [comment]
The fix is up here: https://github.com/dhall-lang/dhall-lang/pull/1158

**Comment by stergiotis** [comment]
Wow, that was quick! Many thanks.
