### ISSUE TITLE
Add support for CSV export

### ISSUE THREAD

**Issue by ad-si** [dhall-lang/dhall-lang#1165]
It would be cool if there was a `dhall-to-csv` command. This could also be very restricted in that it only works for a list of records where each field must be a JSON primitive (or similar).

**Comment by Gabriel439** [comment]
@sjakobi: If we get a 2nd slot for Dhall in GSoC this would be a good student project

**Comment by TristanCacqueray** [comment]
Should this issue be moved to the dhall-haskell project?

**Comment by Gabriel439** [comment]
@TristanCacqueray: Technically it doesn't have to be implemented in Haskell, so I think it's okay to keep the issue here.  However, if we were to implement it in Haskell then subsequent `dhall-csv` issues would belong there

**Comment by Gabriel439** [comment]
I just wanted to mention that we were in fact able to get a second student to work on Dhall for Google Summer of Code so they will be implementing CSV support for Dhall.  See the announcement thread here: https://discourse.dhall-lang.org/t/google-summer-of-code-projects-toml-and-csv-support/475

**Comment by ad-si** [comment]
Congratulations @MarcosJLR for successfully completing GSoC! 😁🎉
I'm looking forward to making good use of dhall-csv! ☺️

**Comment by sjakobi** [comment]
Let's close this issue then. :)

`dhall-csv` is available on [Hackage](https://hackage.haskell.org/package/dhall-csv). Binary executables are included in the `dhall-haskell` releases: https://github.com/dhall-lang/dhall-haskell/releases.

For the final project report, see https://discourse.dhall-lang.org/t/dhall-bindings-to-csv-gsoc-project/517.
