### ISSUE TITLE
Use more insightful examples

### ISSUE THREAD

**Issue by ad-si** [dhall-lang/dhall-lang#1166]
I think many examples could be more insightful in showing how code behaves.
E.g. This is the [current example for fold](https://github.com/dhall-lang/dhall-lang/blob/62ae55d1f8a88f348a32b6e2aebef964b3e70058/Prelude/List/fold.dhall#L16):

```dhall
fold
    Natural
    [ 2, 3, 5 ]
    Natural
    (λ(x : Natural) → λ(y : Natural) → x + y)
    0
≡ 10
```

I think better would be e.g.

```dhall
fold
    Natural
    [ 2, 3, 5 ]
    Text
    (λ(x : Natural) → λ(y : Text) → y ++ Natural/show x)
    "0"
≡ "0532"
```
It shows:

1. Which of the two Types is for the input and which one for the output
2. In which order the Array elements are iterated over

There are a few (many?) other examples with similar shortcomings. So this should probably be improved in all examples in a coherent way.

**Comment by Gabriel439** [comment]
I put up a change that I believe addresses your feedback:

https://github.com/dhall-lang/dhall-lang/pull/1168

The only part I didn't incorporate was reversing the order of arguments.  I think that's more likely to confuse people than help.  Also, I believe the second example for `List/fold` and `Natural/fold` already covers the abstract case of the order in which arguments are processed.

**Comment by ad-si** [comment]
Cool, looks good 👍.

> The only part I didn't incorporate was reversing the order of arguments. I think that's more likely to confuse people than help.

Yes definitely! It wasn't intentional on my side, I just copied the code like this from some of my own code 😅
