### ISSUE TITLE
Use foldl instead of foldr for fold

### ISSUE THREAD

**Issue by ad-si** [dhall-lang/dhall-lang#1169]
It's probably too late for this, but I want to bring it up for completeness sake. I think `foldl` is the more natural choice in terms of expectations and habits coming from other languages. The accumulator is the value you start with, and not what you add in the end:

Dhall:

```dhall
fold
  Natural
  [ 1, 2, 3 ]
  Text
  (λ(val : Natural) → λ(acc : Text) → Natural/show val ++ acc)
  "0"
≡ "1230"
```

Haskell:
```hs
λ foldr (++) "0" ["1","2","3"]
"1230"
λ foldl (++) "0" ["1","2","3"]
"0123"
```

Rust:
```rust
vec!["1","2","3"].iter()
  .fold("0".to_string(), |mut acc,val| {acc.push_str(*val); acc});
// 0123
```

JavaScript:
```js
["1","2","3"].reduce(
  (acc, val) => acc + val,
  "0"
) === "0123"
```

Python:
```py
functools.reduce(
  lambda acc,val: acc + val, 
  ["1", "2", "3"], 
  "0"
)  == "0123"
```

Of course there is also the question whether it should be `acc -> val -> …` or `val -> acc -> …`, but I think that's just secondary. What matters is what the input order and the expected output order looks like.

**Comment by Gabriel439** [comment]
Here is a pull request for adding `foldLeft` to the Prelude: https://github.com/dhall-lang/dhall-lang/pull/1170
