### ISSUE TITLE
dhall-format trailing whitespace

### ISSUE THREAD

**Issue by FintanH** [dhall-lang/dhall-lang#118]
Minor issue, but when using `dhall-format` it often leaves trailing whitespace. Would it be possible to avoid this?

**Comment by Gabriel439** [comment]
See: https://github.com/dhall-lang/dhall-haskell/issues/183

**Comment by FintanH** [comment]
Thanks! I didn't see that on my first scan 😬

**Comment by Gabriel439** [comment]
No problem :)
