### ISSUE TITLE
Suggestion for "copy path path to clipboard" behavior in the store website

### ISSUE THREAD

**Issue by ear7h** [dhall-lang/dhall-lang#1183]
<img width="281" alt="Screen Shot 2021-06-02 at 16 32 25" src="https://user-images.githubusercontent.com/23175084/120564837-a1c34c00-c3c0-11eb-835b-45ce721802ea.png">

The link currently just copies the path (`/`) to the clipboard, but I think it would be more helpful to copy the whole URL that you'd use as an import (`https://prelude.dhall-lang.org/v20.2.0/package.dhall`)

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/2215

**Comment by Gabriel439** [comment]
Note that I'm still working on incorporating this change into store.dhall-lang.org

**Comment by Gabriel439** [comment]
Alright, this is completely fixed now.  store.dhall-lang.org now copies full URLs to the clipboard
