### ISSUE TITLE
catOptionals in prelude

### ISSUE THREAD

**Issue by locallycompact** [dhall-lang/dhall-lang#1202]
I don't think this exists?

```
let catOptionals
    : ∀(a : Type) → List (Optional a) → List a
    = λ(a : Type) →
      λ(xs : List (Optional a)) →
        Prelude.List.concatMap (Optional a) a (Prelude.Optional.toList a) xs
```

Unless I'm wrong, may I add it?

**Comment by sjakobi** [comment]
We do have it, but under a different name: https://store.dhall-lang.org/Prelude-v20.2.0/List/unpackOptionals.dhall.html

**Comment by winitzki** [comment]
Need something like `dhallage` to be able to search library methods by type.

**Comment by Gabriel439** [comment]
I'll mark this complete since we have `unpackOptionals` in the Prelude
