### ISSUE TITLE
Type annotations for arbitrary record types and homogeneous record types

### ISSUE THREAD

**Issue by mschwaig** [dhall-lang/dhall-lang#1219]
I have been working on a toy project to learn Dhall and ran into an ergonomic issue with the available complex types that I wanted to bring up.

<details>
<summary>TLDR: motivation/how I got to my questions</summary>
My use case is working with a collection of named values of the same type. I will use `Natural` as an example here, in realty I was working with individual values of a more complex type.

These are the provided options that I considered:
1. If I put them into a record, a value of a different type might sneak in undetected if the field in question is unused.
2. Putting them into a list gives up on access by field name and deduplication by name.
3. An association list would at least preserve the duplicate detection by name at the point when the list is constructed using `toMap`, but otherwise seems like an inferior datatype better suited for applications that require programmatically created keys and not ergonomic access to individual elements.

I decided to use a record like this:
```
let record = {
  one = 1,
  two = 2
}
```
I was still bothered by not being able to limit the field types with this approach, so my next idea was to write a validation function which calls `toMap` on the passed record to ensure that all fields have the same type.

This is not possible, because there is no `Record` or other type besides the exact record type such a function could accept that would allow a call to `toMap` on a provided input to typecheck. So while this can be done (see below), it cannot be implemented as a function.

```
let record = { one = 1, two = 2}
let elemType = Natural
let values = https://raw.githubusercontent.com/dhall-lang/dhall-lang/v20.2.0/Prelude/Map/values.dhall
let v =
  values
    Text
    elemType
    (toMap record)
in record
```
</details>

In the end I was left with the following questions.  

**What do people think about a record type annotation e.g.`Record` or `{*}` that accepts/matches arbitrary records?**

This would be the parameter type annotation for record operations like `toMap`, `//`as well as for the function I failed to define in my journey above:

```
let ensure_homogeneous =         
\(elemType : Type) -> \(record: Record) ->
[..]
```
I saw that such a type already came up in the context of row polymorphism here: https://github.com/dhall-lang/dhall-lang/issues/828#issuecomment-557984110

**What do people think about a type annotation to enforce that all records fields are of a specific type?**

I'm thinking of something along these lines:

```
let record = {
  a = 1,
  b = 2
} : { * : Natural }
```

This would fail to typecheck if a field of a type other than `Natural` is added to the record, but allows for arbitrarily named fields of type `Natural` type otherwise.

EDIT:
Wanted to explicitly mention that this would enable modeling homogeneous maps as homogeneous records as an alternative to the association lists discussed here: https://github.com/dhall-lang/dhall-json/issues/27

**Comment by Gabriel439** [comment]
What if you wrote a validation function for the homogeneous `Map` and then converted the record to the `Map` using `toMap` at the point where the validation function is called?

In other words, something like this:

```dhall
let Prelude = https://prelude.dhall-lang.org/v20.2.0/package.dhall

let record = { x = 1, y = 2 }

let validation
    : Prelude.Map.Type Text Natural → Bool
    = Prelude.List.any
        { mapKey : Text, mapValue : Natural }
        ( λ(x : { mapKey : Text, mapValue : Natural }) →
            Prelude.Natural.lessThanEqual 1 x.mapValue
        )

let _ = assert : validation (toMap record) ≡ True

in  record
```

**Comment by mschwaig** [comment]
Oh, wow. I did not think of that.

Looks like I'm the guy who proposes to change the language because he cannot figure out something like that.

I hope that voicing the thought of using type annotations to validate something other than exact types brings some value, even if it might not be a good fit for Dhall.

Thanks for your great work on Dhall and for taking a look, Gabriella.

**Comment by Gabriel439** [comment]
You're welcome!  It sounds like we can close this, then, but feel free to reopen if you believe there is more to address
