### ISSUE TITLE
comment on last line without newline ending causes unexpected end of input expecting newline

### ISSUE THREAD

**Issue by safareli** [dhall-lang/dhall-lang#1222]
This is the file I have `spec.dhall`:
```dhall
1
-- comment
```
There is no new line in the end. i.e. contents can be represented using this string `"1\n-- comment"`
command:
```
dhall-to-yaml --file=spec.dhall --output=spec.dhall.yml


Error: Invalid input

spec.dhall:2:11:
  |
2 | -- comment
  |           ^
unexpected end of input
expecting newline
```

**Comment by Gabriel439** [comment]
Currently that is expected behavior as the standard grammar requires all line comments to end with a newline:

https://github.com/dhall-lang/dhall-lang/blob/e64e9aaa28a2910d7c1ce47f6ee94d92b2770f52/standard/dhall.abnf#L169

It would be possible to amend the standard to permit this, but it would complicate the grammar

**Comment by safareli** [comment]
Yeah I quickly thought that that's probably just how grammar is specified. but someone that has not written some kind of parser before will be confused and think that there is an error somewhere else and compiler just can't pick up correct location. I literally installed dhall, copy pasted some sample and compiled it, worked fine. Then I commented out that snippet and above it, added another one. And as my editor was not adding newlines automatically in the end got this error. it's case that is very likely for someone to hit in first day of using dhall.

**Comment by Nadrieril** [comment]
It's easy if we can assume an EOF rule:
```abnf
line-comment = "--" *not-end-of-line (end-of-line / EOF)
```

**Comment by Gabriel439** [comment]
@Nadrieril: I think it would be simpler to just have something like:

```abnf
[ "--" *not-end-of-line ]
```

… at the end of the grammar

**Comment by Nadrieril** [comment]
Meh, that means two different places in the grammar that can generate a comment. But yeah we agree it's not hard.
Could be a good first issue: small tweak to the grammar and parser plus a test

**Comment by Gabriel439** [comment]
https://github.com/dhall-lang/dhall-lang/pull/1226
