### ISSUE TITLE
Boehm-Berarducci encoding issue 

### ISSUE THREAD

**Issue by swizard0** [dhall-lang/dhall-lang#125]
I have read the [HowTo](https://github.com/dhall-lang/dhall-lang/wiki/How-to-translate-recursive-code-to-Dhall) about recursive code, but it seems that I'm still missing something. 

As an exercise I've managed to design a primitive expression tree and even an evaluator for it:

```  
    let Exp
        : Type
        =   ∀(Exp : Type)
          → ∀(lit : Natural → Exp)
          → ∀(add : Exp → Exp → Exp)
          → Exp

in  let formula
        : Exp
        =   λ(Exp : Type)
          → λ(lit : Natural → Exp)
          → λ(add : Exp → Exp → Exp)
          → add (lit +3) (add (lit +7) (lit +4))

in  let eval
        : Exp → Natural
        =   λ(e : Exp)
          → e
            Natural
            (λ(n : Natural) → n)
            (λ(a : Natural) → λ(b : Natural) → a + b)

in  eval formula
```

What I'm trying to do next is to translate `formula` into a record like this: 

```
{ add =
    { left =
        { lit = +3 }
    , right =
        { add = { left = { lit = +7 }, right = { lit = +4 } } }
    }
}
```

But it looks like I cannot do this via folding similar to `eval` function, because the `Exp` type has to be different at every tree level.

Is it even possible with Boehm Berarducci encoding?

**Comment by Gabriel439** [comment]
Would this work for you?

```haskell
    let Exp
        : Type
        =   ∀(Exp : Type)
          → ∀(lit : Natural → Exp)
          → ∀(add : { left : Exp, right : Exp } → Exp)
          → Exp

in  let formula
        : Exp
        =   λ(Exp : Type)
          → λ(lit : Natural → Exp)
          → λ(add : { left : Exp, right : Exp } → Exp)
          → add { left = lit +3, right = add { left = lit +7, right = lit +4 } }

in  let eval
        : Exp → Natural
        =   λ(e : Exp)
          → e
            Natural
            (λ(n : Natural) → n)
            (λ(x : { left : Natural, right : Natural }) → x.left + x.right)

in  eval formula
```

**Comment by swizard0** [comment]
Probably not.

I just want to be able to export my data outside of dhall keeping its recursive structure, for example, like this:

```
{"add":{"left":{"lit":3},"right":{"add":{"left":{"lit":7},"right":{"lit":4}}}}}
```

I doesn't have to be exactly a record of course, nested `List` should be fine too.

The only way I could imaginе for now is to fold the tree into plain `List` encoding its structure somehow using some tags or ids.

**Comment by Gabriel439** [comment]
Oh, if the goal is to produce a data type suitable for conversion to JSON (i.e. via `dhall-to-json`) then I can say for certain that what you want is not possible using the existing command line tools.  You would need to use the Haskell API to do what you want.

The high-level approach would be:

*   Start from the `Dhall.JSON.codeToValue` function which shows how the pieces of the Haskell API fit together:

    https://github.com/dhall-lang/dhall-json/blob/c45a25e79532a1a52cef8ab3298a4a9d707ae5bb/src/Dhall/JSON.hs#L202-L225

*   Keep parsing the same (i.e. `Dhall.Parser.exprFromText`).  You don't need to customize it

*   Keep import resolution the same (i.e. `Dhall.Import.load`).  You don't need to customize it

*   Replace the use of `Dhall.TypeCheck.typeOf` with `Dhall.TypeCheck.typeWith` so that you can type-check the expression with a custom context where `Expr`, `add`, and `lit` are already in scope with the following types:

    ```haskell
    -- `Const Type` in the Haskell API
    Expr : Type

    -- `Pi "_" "Expr" (Pi "_" "Expr" "Expr")` in the Haskell API
    add : Expr → Expr → Expr

    -- `Pi "_" Natural "Expr"` in the Haskell API
    lit : Natural → Expr
    ```

    This also give you the nice bonus that users of the tool you build won't have to introduce `Expr`/`add`/`lit` via lambda abstraction since they will already be in scope.  That means that they would just write:

    ```haskell
    add (lit +3) (add (lit +7) (lit +4))
    ```

*   Keep normalization the same (i.e. `Dhall.Core.normalize`).  You don't have to customize it

*   Write your own `dhallToJSON` function similar to this one:

    https://github.com/dhall-lang/dhall-json/blob/c45a25e79532a1a52cef8ab3298a4a9d707ae5bb/src/Dhall/JSON.hs#L155-L185

    ... except extending it to also translate your newly added `add`/`lit` builtins like this:

    ```haskell
    -- Note: I have not type-checked this so there may be mistakes in this example
    loop e = case e of
        ...
        App "lit" (NaturalLit n) -> do
            return (object [ "lit" .= n ])
        App (App "add" x) y -> do
            x' <- loop x
            y' <- loop y
            return (object [ "add" .= object [ "left" .= x', "right" .= y' ] ])
    ```

    I would also accept a pull request to the `dhall-json` library to support customizing the behavior of the `dhallToJSON` function so that you don't have to duplicate the existing logic

Once you've written your own custom `codeToValue` function then you can consult the code for the `dhall-to-json` executable which shows how to turn your function into a command-line API:

https://github.com/dhall-lang/dhall-json/blob/c45a25e79532a1a52cef8ab3298a4a9d707ae5bb/dhall-to-json/Main.hs

**Comment by swizard0** [comment]
Thank you very much for the detailed answer!

However I suspect that crafting a specialized compiler may be an overkill for my simple task.

After [experimenting](https://gist.github.com/swizard0/2cb0231a6620c7a97fb359fb5bf05fb9) for a while I was able to translate my tree into a following data structure:

```
{ rootId =
    +4
, nodes =
    [ { id = +4, node = < Add = { left = +0, right = +3 } | Lit : Natural > }
    , { id =
          +0
      , node =
          < Lit = +3 | Add : { left : Natural, right : Natural } >
      }
    , { id = +3, node = < Add = { left = +1, right = +2 } | Lit : Natural > }
    , { id =
          +1
      , node =
          < Lit = +7 | Add : { left : Natural, right : Natural } >
      }
    , { id =
          +2
      , node =
          < Lit = +4 | Add : { left : Natural, right : Natural } >
      }
    ]
}
```

That probably should be enough to export the tree to json and then restore it back in other application. 

Or maybe there is a simpler solution?

**Comment by Gabriel439** [comment]
The problem with that is that it won't work well if you keep nesting this.  Try doing the recursion two or three levels deep and you'll see that the type of the sum type changes and grows more complex.

**Comment by Profpatsch** [comment]
Hm, I’ve been thinking, since recursive data structure seem to be a thing many people want to do, would it be possible to introduce a `Fix` builtin of sorts?
That is something that translates to Haskell’s `newtype Fix f = Fix (f (Fix f))`?

I haven’t thought through this, just a hunch.

**Comment by swizard0** [comment]
> The problem with that is that it won't work well if you keep nesting this. Try doing the recursion two or three levels deep and you'll see that the type of the sum type changes and grows more complex.

I probably didn't quite understand what you mean by "sum type changes". I expect that the final result should keep the type: `{ rootId : Natural, nodes : List Node }` regardless of recursion depth.   

I just [tried](https://gist.github.com/swizard0/6bf4c969af6c5b0f0fecd660b368ce3c) to add one more leaf type to the tree and do a deeper recursion:

```
in  let formula
        : Expr
        =   λ(E : Type)
          → λ(lit : Natural → E)
          → λ(neg : E → E)
          → λ(add : E → E → E)
          → add
            (neg (lit +3))
            (add (neg (add (lit +7) (add (lit +0) (lit +9)))) (lit +4))
```

 This is the json conversion result:

```
{"rootId":10,"nodes":[{"node":{"add":{"left":1,"right":9}},"id":10},{"node":{"neg":0},"id":1},{"node":{"lit":3},"id":0},{"node":{"add":{"left":7,"right":8}},"id":9},{"node":{"neg":6},"id":7},{"node":{"add":{"left":2,"right":5}},"id":6},{"node":{"lit":7},"id":2},{"node":{"add":{"left":3,"right":4}},"id":5},{"node":{"lit":0},"id":3},{"node":{"lit":9},"id":4},{"node":{"lit":4},"id":8}]}
```
   
And I can even interpret it with an external tool:

```
cat exp_neg_collapse | dhall-to-json | perl -MJSON -nle '$e=decode_json$_;map{$q{$_->{id}}=$_->{node}}@{$e->{nodes}};sub eva{$i = shift;$k=(keys%{$q{$i}})[0];my$n=$q{$i}{$k};if($k eq"lit"){$n}elsif($k eq"neg"){-eva($n)}elsif($k eq"add"){eva($n->{left})+eva($n->{right})}};print eva($e->{rootId})'

-15
```

Am I missing something?

**Comment by Gabriel439** [comment]
Oh yeah, you can nest a value of type `Expr` (like `formula`) to arbitrary depth.  What I meant is that the final data type that you convert to JSON (i.e. `Context` in your example) needs to be flat, but it looks like you are fine with that restriction

**Comment by sellout** [comment]
@Profpatsch I’ve written https://github.com/sellout/dada, which offers `Mu` (a total cousin of `Fix`), and sort-of `Nu` for corecursion, although I haven’t published that bit yet, as it still has some warts.

And I have (currently proprietary) code that converts `Mu` from Dhall to Haskell (it’s not quite the elegant solution I’m hoping for, though).

**Comment by Profpatsch** [comment]
> And I have (currently proprietary) code that converts Mu from Dhall to Haskell (it’s not quite the elegant solution I’m hoping for, though).

Once you open-source it we can look for a more elegant solution. :)

**Comment by Gabriel439** [comment]
I will go ahead and close this.  Feel free to reopen if there is still more to do here

**Comment by akshaymankar** [comment]
Hello, I was facing a similar issue and thought instead of adding special methods for each recursive type that I needed, I would add a method called `toJSON` and a type called `JSON`. The code is [here](https://github.com/akshaymankar/dhall-recursive-json ).

I'd love to have something like this built into the language because to use this in real code and have my emacs mode help me validate and format, I'd have to rewrite the dhall binary also, which is very inconvenient. Do you think something like this could be part of the language itself?
