### ISSUE TITLE
A few questions about import/success/headerForwarding testcase

### ISSUE THREAD

**Issue by hagl** [dhall-lang/dhall-lang#1260]
I have a couple of questions about this test-case: [tests/import/success/headerForwardingA.dhall](https://github.com/dhall-lang/dhall-lang/blob/master/tests/import/success/headerForwardingA.dhall)

1) The comment in the file says 
> `test.dhall-lang.org` is the same as `prelude.dhall-lang.org` except that  `test.dhall-lang.org` rejects all requests without a `Test` header.
However, when I access [https://test.dhall-lang.org/Bool/and.dhall](https://test.dhall-lang.org/Bool/and.dhall) with curl or in a browser, the requests succeed without this header. 
So this test doesn't actually test that headers are properly forwarded.

2) In file to match against [tests/import/success/headerForwardingB.dhall](https://github.com/dhall-lang/dhall-lang/blob/master/tests/import/success/headerForwardingB.dhall), the resolved code is alpha-normalized, but from reading the language specs and test description [tests/README.md](https://github.com/dhall-lang/dhall-lang/blob/master/tests/README.md?plain=1#L119) it does not seem necessary to apply alpha-normalization after resolving imports. Or do I miss something?

I checked the behavior of the haskell implementation when it comes to resolving, and found some interesting behaviour:

```
$ dhall resolve <<< "https://prelude.dhall-lang.org/Bool/and.dhall sha256:0b2114fa33cd76652e4360f012bc082718944fe4c5b28c975483178f8d9b0a6d"
\(_ : List Bool) ->
  List/fold Bool _ Bool (\(_ : Bool) -> \(_ : Bool) -> _@1 && _) True

$ dhall resolve --no-cache <<< "https://prelude.dhall-lang.org/Bool/and.dhall sha256:0b2114fa33cd76652e4360f012bc082718944fe4c5b28c975483178f8d9b0a6d"
\(xs : List Bool) ->
  List/fold Bool xs Bool (\(l : Bool) -> \(r : Bool) -> l && r) True
```

When the resolved file is in the cache the result is alpha-normalized (because that's how the expressions are stored in the cache). But when the file is not in the cache or the cache disabled (--no-cache) it will show the original variables. 
It probably doesn't make a big difference, but from a puristic point of view, I would find it desirable that there is no visible difference when a file is cached or not. What do you think? Maybe resolved files could be always alpha-normalized?

**Comment by Gabriel439** [comment]
So I think I found the issue with (1).  The problem is that the `nginx` configuration for test.dhall-lang.org looks like this:

```
server {
        …
        server_name test.dhall-lang.org ;
        …
        location / {
                proxy_pass https://raw.githubusercontent.com;
                …
                rewrite ^/?$ https://store.dhall-lang.org/Prelude-v21.1.0 redire
ct;
                rewrite ^/(v[^/]+)$ https://github.com/dhall-lang/dhall-lang/tre
e/$1/Prelude redirect;
                rewrite ^/(v[^/]+)/(.*)$ /dhall-lang/dhall-lang/$1/Prelude/$2 br
eak;
                rewrite ^/(.*)$ /dhall-lang/dhall-lang/v21.1.0/Prelude/$1 break;
                if ($http_test = "") {
                        return 403;
                }
        }
```

… so the `rewrite` rules trigger before the `http_test` check and the header is never tested.  However, I believe I know how to fix this and I have a PR up for this: https://github.com/dhall-lang/dhall-lang/pull/1263

Regarding the α-normalization of cached imports, there are a few related discussions about that:

* https://github.com/dhall-lang/dhall-haskell/issues/1212
* https://github.com/dhall-lang/dhall-lang/issues/733
* https://github.com/dhall-lang/dhall-lang/issues/1185

**Comment by hagl** [comment]
Thank you for the fix and the links! The updated test will also no longer have an issue with alpha-normalization, so also solves my second problem.
I'll close the issue as soon as I can test against your deployed fix

**Comment by hagl** [comment]
The updated test is working fine. Thanks again! :)

**Comment by Gabriel439** [comment]
You're welcome!  Thank you for contributing these fixes 🙂
