### ISSUE TITLE
Can't use `with` as a key in a record

### ISSUE THREAD

**Issue by samuela** [dhall-lang/dhall-lang#1274]
`{ wit = "aasdfds" }` works no problem but `{ with = "aasdfds" }` gives me problems:
```
Error: Invalid input

(input):1:3:
  |
1 | { with = "aasdfds" }
  |   ^
unexpected 'w'
expecting ',', =, whitespace, or }
```
This was confusing at first (haven't gotten syntax highlighting to work yet in VSCode), but I've concluded it's because `with` is a keyword in dhall.

How can I create a record type with a `with` key? This is necessary for me to generate eg. GitHub Actions configs.

**Comment by sjakobi** [comment]
You can use keywords as labels if you quote them with backticks, e.g.:

```
⊢ { `with` = "aasdfds" }

{ `with` = "aasdfds" }
```

**Comment by samuela** [comment]
Awesome, thanks!
