### ISSUE TITLE
Cannot retrieve prelude List/concatMap

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-lang#128]
Fortunately `List/concat` and `List/map` work, but when I try and fetch https://ipfs.io/ipfs/QmQ8w5PLcsNz56dMvRtq54vbuPe9cNnCCUXAQp6xLc6Ccx/Prelude/List/concatMap I get 

```
ipfs resolve -r /ipfs/QmQ8w5PLcsNz56dMvRtq54vbuPe9cNnCCUXAQp6xLc6Ccx/Prelude/List/concatMap: Failed to get block for QmVN5Kpo3vgeKmdCD6t7CXuMhWYamgavs25myJuek37Soo: context deadline exceeded
```

I don't really know how IPFS works though, so I don't know what's going on beyond this.

**Comment by Gabriel439** [comment]
What it means is that I need to use a beefier server for mirroring the Dhall Prelude on IPFS.  If my server dies (usually due to resource exhaustion from mirroring other IPFS content) then anything that is not in some other IPFS server's cache becomes unreachable with that error

**Comment by Gabriel439** [comment]
Alright, this is fixed temporarily (I redeployed the server). I'll try to monitor it periodically to see what the root cause of the failure is
