### ISSUE TITLE
dhall-lang.org certificate expired

### ISSUE THREAD

**Issue by moinessim** [dhall-lang/dhall-lang#1284]
Expired At: Wednesday, May 4, 2022 at 12:00:31 AM Eastern

**Comment by Gabriel439** [comment]
It should be fixed now.  I ended up resolving this using `systemctl restart nginx`

I believe what happened here is that `nginx` was serving a stale certificate.  There's an automated process to renew the certificate but apparently `nginx` caches the old one and I can't find an easy way to get `nginx` to pick up the renewed certificate without a restart

**Comment by chshersh** [comment]
Did the issue happen again? I see that my browser attempts to have an insecure connection with the `dhall-lang` website:

![image](https://user-images.githubusercontent.com/4276606/182460796-37c3f411-6026-485e-9067-dcc6cc363929.png)

I had to clicked the "Advanced" button and "Proceed (insecure)"

**Comment by Gabriella439** [comment]
Yeah, same issue and the same resolution (restarting `nginx`).  I'm still not sure what is the long-term solution other than periodically restarting `nginx` as a workaround

**Comment by chshersh** [comment]
Scheduling a job to restart `nginx` periodically sounds like a decent workaround 😅

**Comment by Gabriella439** [comment]
So there is a possibility that the root cause of the issue was that timers were not triggering correctly, which was fixed by: https://github.com/dhall-lang/dhall-lang/pull/1300

I'm not 100% sure, though, so I'll wait and see if the problem returns before applying more changes
