### ISSUE TITLE
dhall hash / repl :hash discrepancy

### ISSUE THREAD

**Issue by swmichaels** [dhall-lang/dhall-lang#1285]
hello! Noticed `dhall hash` results differ from the result from `:hash` in the dhall REPL. Not sure why

Looking at notes in https://docs.dhall-lang.org/tutorials/Language-Tour.html#installing-packages it reads like these should return the same hash

Repro steps

Mac osx 12.3.1
`dhall version` returns `1.41.1`

save the following to `example.dhall` (pulled this from a language tour example)

```dhall
let Example = < Number : Natural | Boolean : Bool >

let renderExample
    : Example -> Text
    = \(example : Example) ->
        merge
          { Number = \(n : Natural) -> Natural/show n
          , Boolean = \(b : Bool) -> if b then "True" else "False"
          }
          example

let example0 = assert : renderExample (Example.Number 42) === "42"

let example1 = assert : renderExample (Example.Boolean False) === "False"

in  renderExample
```

```sh
$ dhall hash <<< ./example.dhall
sha256:d78c50c246b1e89d99b5587516b5945f9126bfaa6123acb8c9cb9685ddac4d68
$ dhall repl 
Welcome to the Dhall v1.41.1 REPL! Type :help for more information.
⊢ :hash ./example.dhall
sha256:a883670c49058243b217f39711858e821a9916a9701af7f852632b8769ed3e74
```

**Comment by Gabriella439** [comment]
Yeah, this is a bug.  The issue here is that the `:hash` REPL command is not α-normalizing the input like the `dhall hash` command does (and it should be α-normalizing the input).  I can fix this
