### ISSUE TITLE
Discussion: Caching imports protected by integrity checks

### ISSUE THREAD

**Issue by Gabriel439** [dhall-lang/dhall-lang#129]
Dhall currently has a feature (still to-be-standardized) that imports can be protected with a "semantic integrity check", as documented in this blog post:

http://www.haskellforall.com/2017/11/semantic-integrity-checks-are-next.html

I would like to reuse the hash included in an integrity check as a key used to retrieve the expression from a local cache of imported values.

The main benefit of this change is that any URL protected by a semantic integrity check would only need to be downloaded once, which would greatly accelerate repeated runs of a Dhall expression containing remote imports.

To be precise, here is the way that imports currently work:

* Check if the import is protected by a semantic integrity check
    * If there is no semantic integrity check:
        * Retrieve the imported expression
        * Accept the import
    * If there is a semantic integrity check:
        * Retrieve the imported expression
        * αβ-normalize the expression
        * Compute a SHA256 hash of some encoding of the αβ-normalized expression
        * Check if the computed hash matches the expected hash
            * If they match, accept the import
            * If they don't match, reject the import

This informal proposal is to extend the above process with the following changes (highlighted in bold):

* Check if the import is protected by a semantic integrity check
    * If there is no semantic integrity check:
        * Retrieve the imported expression
        * Accept the import
    * If there is a semantic integrity check:
        * **Check if there is a Dhall expression cached at `/dhall/${expectedHash}`**
            * **If the file exists:**
                * **Retrieve the expression from that file instead**
                * **Accept the import**
            * **If the file does not exist:**
                * Retrieve the imported expression
                * αβ-normalize the expression
                * Compute a SHA256 hash of some encoding of the αβ-normalized expression
                * Check if the computed hash matches the expected hash
                    * If they match:
                        * **Store the expression at `/dhall/${expectedHash}`**
                        * Accept the import
                    * If they don't match, reject the import

In other words, there would be some sort of local cache of Dhall values that can be used to accelerate imports by caching them locally.

The reason this is still a discussion rather than a proposal is because (A) I still have to formalize the semantics of Dhall's existing import system and (B) I'm not sure how and where Dhall should cache the values and what should be the user interface for this.  There are lots of variations on how this can be done that have different tradeoffs in terms of performance, ease of setup, and ease of distribution.

I'll throw out some example ways that this proposal can very so that people can chime in with what they prefer:

* The cached Dhall expressions could be stored in a database
* The cached Dhall expressions could be stored in memory by a long-running service
* The cached Dhall expressions could be stored in an unprivileged file path, such as:
    * Underneath the user's home directory
    * Underneath the user's current working directory
    * Underneath `/tmp`
* There could be fallback behavior if the interpreter does not have sufficient privilege to read/write some path/service/table
    * Including the obvious last-resort fallback of not using a cache at all
* Feel free to suggest any ideas or variations of your own
* Should the standard require or just recommend this functionality for a compliant implementation?

Some prior art to study here is Nix and IPFS, both of which use a local immutable append-only hashtable for caching.

In Nix's case (which I'm more familiar with), it uses a reserved `/nix/store` path which requires `root` privileges to create in the initial setup.  In multi-user mode, the `/nix/store` directory tree can only be modified by a privileged `nix-daemon` service that the Nix commands are clients to.  In single-user mode the `/nix/store` directory is owned by the user that installed Nix.

This is still a few months out from becoming a reality, which is why I'm starting the discussion now to collect ideas about how to implement this.

**Comment by Profpatsch** [comment]
Normally tools would cache under `$XDG_CACHE_HOME/dhall` (with fallback to `~/.cache/dhall`) according to the [freedesktop basedir spec](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html).

It is customary (though optional) that dhall would provide an environment variables (like `$DHALL_CACHE_DIR`) to explicitely set the directory when needed.

**Comment by ocharles** [comment]
Profpatsch beat me too it, but I was going to say the same (and would
prefer it)

**Comment by jneira** [comment]
Hi, i wonder if we could use the caching mechanism to handle the imports *without* an explicit hash.
It would add the complexity of another indirection in the form of a index file between urls and actual hashes (or another way). It would use the usual http headers to check for served file modifications.
Despite the added complexity, it would have some some significant benefits:
* It would remove for the user the need to explicitly compute and include the hash in the config file
* It would take advantage of the existing cache to get reliability and better performance for all imports
Of course the original file explicit hash would be mandatory in presence of clashes.

Otoh, another way to set the cache dir could be a command line flag, that would be mandatory over any other source.

**Comment by Gabriel439** [comment]
Yeah, I like @Profpatsch's suggestion, so I'll do that (including the extra hash verification step for cached imports)

@jneira: I would prefer to make it easier to add hashes to imports.  The idea I'm thinking of is having a `dhall-freeze` command (or a `dhall freeze` subcommand) that resolves and adds semantic integrity checks to unprotected imports in an existing expression.

**Comment by domenkozar** [comment]
As I was just implementing similar logic (XDG_CACHE_HOME) recently, there's a neat function in https://hackage.haskell.org/package/directory-1.3.2.2/docs/System-Directory.html#v:getXdgDirectory

**Comment by puffnfresh** [comment]
One thing that seems weird to me in both Nix and Dhall, is that when we're specifying fixed-hash resources, we're giving *one way* to retrieve the file. For example:

```nix
import (fetchTarball {
  url = "http://example.com/example.nix";
  sha256 = "4d30f38927620e137b33edf19f52a72389ab85e736b7e583ef09d1342e823194";
})
```

I understand that sometimes there's a canonical way to retrieve certain resources - but often there are mirrors or indirect ways of access the resources. It seems strange to give preference to just one. Maybe I have a certain mirror that's faster. Maybe I don't have HTTP access but I can SSH into a server to retrieve that file.

What would it look like to separate the example of *how* to get a resource from the *description* of the resource?

**Comment by joneshf** [comment]
What can we do to help make progress on this?

**Comment by Gabriel439** [comment]
@joneshf: The next step is standardizing how to hash Dhall expressions.  In other words: #158 

Once that is done caching imports should follow pretty quickly.  I'll dump my current notes on that ticket to update on where I am there

**Comment by joneshf** [comment]
Thanks!

**Comment by joneshf** [comment]
Think about this again, I'm a little unclear how hashing the expression is a prerequisite for caching the import. is there something about the unhashed expression that makes caching harder/not-robust/unsafe? If not, could we implement caching before we implement hashing expressions?

I ask because I was about to implement the outlined caching algorithm in a program and was worried I was missing something.

**Comment by Gabriel439** [comment]
@joneshf: It's mainly because caching an import that is not pinned means that you would need to invalidate the cache if the underlying import changed and you wanted to pick up the change.

**Comment by Gabriel439** [comment]
@joneshf: This issue is fine

When you pin an import with a semantic integrity check you do not need to protect transitive imports with a semantic integrity check.  It also is not necessary to transitively pin imports to benefit from caching.  The reason why is that the hash is computed from the normal form of the import and you also cache the normal form of the import which is import-free.

**Comment by joneshf** [comment]
That also makes sense, thanks!

Sorry for all of the questions, but I think I'm still not getting something about the interplay between caching and a binary representation for expressions. Naively, it seems like we could cache the textual form under the same rules. I'm not really understanding what the binary form does that makes it a prerequisite. If you already explained it elsewhere I'll happily re-read it if there's a link, we don't need to rehash here.

**Comment by Gabriel439** [comment]
@joneshf: See this post which explains why we don't hash and cache the textual form: http://www.haskellforall.com/2017/11/semantic-integrity-checks-are-next.html

The main reason why is that we want to preserve user ability to refactor expressions without tampering with the hash.  For example, adding/removing comments/whitespace shouldn't affect the hash.  Similarly, splitting shared functionality into a `let` expression or another import shouldn't affect the hash.

**Comment by joneshf** [comment]
Thanks for the link! I'll check it out and let it sit for a bit.

**Comment by Gabriel439** [comment]
@puffnfresh: Today I discovered a fortuitous interaction between hash-based caching and the recently introduced `missing` keyword.  You can retrieve something from the cache without specifying how to import like this:

```
$ dhall <<< 'missing sha256:2a84d3c5a420e2549f1dfb145fa2a6956481d99f022a77bc31152c29a008dbfa'
```

... which will decode and load the expression uniquely identified by that hash if it is present in the local cache.
