### ISSUE TITLE
Add show builitins for date and time types

### ISSUE THREAD

**Issue by kukimik** [dhall-lang/dhall-lang#1293]
The plan described in https://github.com/dhall-lang/dhall-lang/issues/80#issuecomment-862463847 was to add new types related to dates and time, together with the show builtins:

```dhall
Date/show : Date -> Text
Time/show : Time -> Text
TimeZone/show : TimeZone -> Text
```

As  documented in https://github.com/dhall-lang/dhall-lang/releases/tag/v21.0.0, the builtin functions are not there yet (I also tried it out and get `Error: Unbound variable: Date/show`. Converting the new types to a string is already implemented in the pretty-printer (at least in the Haskell implementation), so I presume adding the `show` builtins shouldn't be very hard. I would find them useful, because I am targeting a custom format (not YAML or JSON), and without the `show` builtins the new types seem pretty useless in my usecase.

Is there anything that is blocking this?

**Comment by Gabriella439** [comment]
There isn't anything blocking this.  Just someone needs to standardize them.

**Comment by Gabriella439** [comment]
Standardization PR is up here: https://github.com/dhall-lang/dhall-lang/pull/1328

**Comment by kukimik** [comment]
Wow! Thanks! :clap:
