### ISSUE TITLE
Pattern matching on types

### ISSUE THREAD

**Issue by mwgkgk** [dhall-lang/dhall-lang#130]
```
    let Language : Type = Text

in  let Bash : Type = Language

in  let Fish : Type = Language

in  let pr = λ(x : Bash) → "Hi, bash"

in  let pr = λ(x : Fish) → "Hi, fish"

in  let t : Bash = "What's up"

in  pr t
```

The above prints `"Hi, fish"`, which just means I'm shadowing `pr`. What's a good way to go about this? Unions? Can you provide a quick illustration? I'm trying to get different config out of it depending on requested type.

Also, is there a better place to ask noobie questions than the bug tracker? :) Thank you

**Comment by mwgkgk** [comment]
I've used http://www.haskellforall.com/2017/06/dhall-is-now-template-engine.html - which had the first example (function + value) failing with
```
$ dhall-to-text <<< './function.dhall ./value.dhall'
```
```
Error: Invalid input

function.dhall:9:3: error: expected: expression
${ if record.in_ca
  ^
```
```
$ dhall --version
1.11.1
```
Unions are well-described in https://hackage.haskell.org/package/dhall-1.12.0/docs/Dhall-Tutorial.html  - I think I gave up too early - the constructor docs have examples that are similar to this. I got lost trying to make it work without the constructor.
```
    let Language : Type = Text

in  let Bash : Type = Language

in  let Fish : Type = Language

in  let pr =
            λ(union : < Left : Bash | Right : Fish >)
          →     let handlers =
                      { Left =
                          λ(x : Bash) → "Hi, bash"
                      , Right =
                          λ(x : Fish) → "Hi, fish"
                      }
            
            in  merge handlers union : Text

in  let t : Bash = "What's up"

in  pr t
```
Which failed to typecheck on `pr t` call.

**Comment by mwgkgk** [comment]
Makes sense. I appreciate the effort you put into these explanations.

Very excited about the project and your approach, things like autoformat and --explain.

**Comment by Gabriel439** [comment]
You're welcome!  Also, thanks for opening the separate issue
