### ISSUE TITLE
`dhall-lang.org` down?

### ISSUE THREAD

**Issue by bplommer** [dhall-lang/dhall-lang#1310]

**Comment by sjakobi** [comment]
It's up for me in Germany.

**Comment by bplommer** [comment]
> It's up for me in Germany.

Interesting, I'm unable to access [prelude.dhall-lang.org](https://prelude.dhall-lang.org/v20.1.0/package.dhall) it either locally (UK) or from github actions

**Comment by arobertn** [comment]
I _cannot_ access from Norway but _can_ from the US. Seems to be a routing issue.

**Comment by Gabriella439** [comment]
Yeah, I'm unable to reproduce from the US

**Comment by jlavelle** [comment]
I am able to reproduce the issue from environments that do not support IPv6 routing, e.g. a container in a default docker setup.

**Comment by Gabriella439** [comment]
This might be related to an ongoing Linode issue (since Linode is what dhall-lang.org uses for hosting): https://status.linode.com/

However, as far as I can tell dhall-lang.org is correctly configured to respond to IPv4 and IPV6 traffic, which I just tested.

**Comment by bplommer** [comment]
The issue is now resolved for me. Before I close this, @jlavelle are you still able to reproduce it?

**Comment by jlavelle** [comment]
No @bplommer, the issue is now resolved for me as well.
