### ISSUE TITLE
Version 22.0.0 isn't published to `prelude.dhall-lang.org`

### ISSUE THREAD

**Issue by pfgray** [dhall-lang/dhall-lang#1314]
I was looking to use `List/filterMap` which was added [last year](https://github.com/dhall-lang/dhall-lang/pull/1245), but it doesn't seem to be published to `prelude.dhall-lang.org` (The lastet version is `v21.1.0`. Is this an oversight? or is the latest version published somewhere I'm not seeing? thanks!

**Comment by Gabriella439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-lang/pull/1315
