### ISSUE TITLE
import of prelude 23.0.0 is broken

### ISSUE THREAD

**Issue by christianknoepfle** [dhall-lang/dhall-lang#1334]
Hi,
since this morning importing prelude doesn’t work anymore. When running

```
let p = https://prelude.dhall-lang.org/package.dhall
in "OK"
```
it results in

```
dhall:
â†³ https://prelude.dhall-lang.org/package.dhall
  â†³ https://prelude.dhall-lang.org/Date/package.dhall
    â†³ https://prelude.dhall-lang.org/Date/show.dhall

e[1;31mErrore[0m: Unbound variable: Date/show

7â”‚       Date/show

https://prelude.dhall-lang.org/Date/show.dhall:7:7

4â”‚       ./show.dhall

https://prelude.dhall-lang.org/Date/package.dhall:4:7
```

Also posted [here](https://discourse.dhall-lang.org/t/prelude-23-0-0-import-broken-due-to-date-show/638), wasn't sure of the best place. Any ideas?

BR Christian

**Comment by Gabriella439** [comment]
This is normal.  The standard is released alongside the new Prelude whereas the corresponding change to the Haskell implementation usually follows a few days later (tomorrow, in this case).  If you import an older version of the Prelude until then (or import just the parts that you need) then that will fix things.
