### ISSUE TITLE
502 error accessing https://prelude.dhall-lang.org/List/null.

### ISSUE THREAD

**Issue by philderbeast** [dhall-lang/dhall-lang#1338]
I'm using `dhall text` and this is the second time I've seen failures accessing the prelude. Am I using a stable endpoint?

```
dhall: 
Error: Upstream failure
HTTP status code: 502
URL: https://prelude.dhall-lang.org/List/null
```

When I try to access that in my browser:

```
  missing
    sha256:2338e39637e9a50d66ae1482c0ed559bbcc11e9442bfca8f8c176bbcd9c4fc80
? ./null.dhall
```

Same thing accessing https://prelude.dhall-lang.org/Text/concatMapSep.

**Comment by philderbeast** [comment]
Going up the path, for https://prelude.dhall-lang.org/Text I get a 404 but https://prelude.dhall-lang.org redirects to https://store.dhall-lang.org/Prelude-v23.0.0/.

**Comment by philderbeast** [comment]
I saw this change shortly before the service came back:

```
Error: Server temporarily unavailable

HTTP status code: 503

URL: https://prelude.dhall-lang.org/List/filterMap.dhall

Message:

1 
2 <?xml version="1.0" encoding="utf-8"?>
3 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
4  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
5 <html>
6   <head>
7     <title>503 Backend unavailable, socket(2) failed</title>
   </head>
```

**Comment by philderbeast** [comment]
It has gone bad again, same 502 error.

**Comment by mmhat** [comment]
I can confirm the issue, I get 502s and 503s as well.

**Comment by Gabriella439** [comment]
Those endpoints should be stable, but I'm not able to reproduce the problem:

```ShellSession
$ dhall <<< 'https://prelude.dhall-lang.org/List/null'
\(_ : Type) -> \(_ : List _) -> Natural/isZero (List/length _@1 _)

$ dhall <<< 'https://prelude.dhall-lang.org/List/filterMap.dhall'
\(a : Type) ->
\(b : Type) ->
\(f : a -> Optional b) ->
\(_ : List a) ->
  List/fold
    a
    _
    (List b)
    ( \(_ : a) ->
        List/fold
          b
          (merge { None = [] : List b, Some = \(_ : b) -> [ _ ] } (f _))
          (List b)
          (\(_ : b) -> \(_ : List b) -> [ _@1 ] # _)
    )
    ([] : List b)
```

Is this problem intermittent or persistent for you?

**Comment by philderbeast** [comment]
I saw it (or something like it) for 5 or 10 mins a month or two ago but what I saw 2 days ago lasted all morning for me.

**Comment by mmhat** [comment]
@Gabriella439 It seems to work again; If @philderbeast is ok with it I suggest to close this issue.

**Comment by philderbeast** [comment]
If the problem reoccurs then this issue can be reopened. All good for now.
