### ISSUE TITLE
Reflection or converting types to values

### ISSUE THREAD

**Issue by NickSeagull** [dhall-lang/dhall-lang#1342]
Tried to search thoroughly the issues, but haven't found anything, apologies if this is a duplicate.

I'm using Dhall to generate some boilerplate code for a project, and I was wondering if it is possible to write a function of type `Type -> Text` without making my own Dhall wrapper with Haskell.

The idea behind this is to have a schema definition with Dhall like:

```dhall
let User = {
  name: Text
} in User
```

And then have a function that recursively converts the type into a Text (or whatever concrete type actually) ala GHC Generics, something like:

```dhall
let reflect = \(t: Type) ->
  -- perform pattern matching on built-in types, record would be converted to Map,
  -- so it could be traversed as a list of key-value tuples or something like that.
  merge 
  { Text: "string"
  , Natural: "number"
  , -- and so on...
  }
```

So in the end one could have a function that takes the `User` definition from above and spits out
a `*.js` file with runtime type validation for example.

Thanks in advance :)

**Comment by Gabriella439** [comment]
Yeah, there's not a way do this without extending the language using the Haskell API.  In particular, there is not a way to do introspection on types within the language like how GHC generics works.

**Comment by NickSeagull** [comment]
Thanks for the prompt response!

As a side note that might spark ideas for other folks thinking in this area, another use case for this is the generation of QuickCheck/Hedgehog specs given some properties specified in Dhall.

Closing this as it solves my question :)
