### ISSUE TITLE
Too many duplicate type annotations?

### ISSUE THREAD

**Issue by gardspirito** [dhall-lang/dhall-lang#1347]
New to Dhall. I love the ideas behind it, but, coming from Haskell, the amount of type annotations required is actually scary.

Here's my clumsy attempt at making `Map.insert`:
```dhall
let Prelude = ../Prelude.dhall

let Entry = Prelude.Map.Entry

in  λ(Key : Type) →
    λ(Value : Type) →
    λ(eq : Key → Key → Bool) →
    λ(key : Key) →
    λ(value : Value) →
    {- ^ Crucial type annotations, I'm not arguing -}
      let EntryKV = Prelude.Map.Entry Key Value

      in  λ(map : List EntryKV) →
            List/fold
              EntryKV -- Is this type annotations really necessary?
              map
              (Bool → List EntryKV) -- Important, sure
              ( λ(x : EntryKV) →
                λ(after : Bool → List EntryKV) →
                λ(search : Bool) →
                {- ^ ??? Couldn't these be inferred? -}
                  if    search && eq key x.mapKey
                  then  [ x with mapValue = value ] # after False
                  else  [ x ] # after search
              )
              ( λ(search : Bool) →
                  {- And here as well? -}
                  if    search
                  then  [ { mapKey = key, mapValue = value } ]
                  else  [] : List EntryKV
              )
              True
```
Is there some way to manage this complexity? For a beginner like me, it feels that Dhall could really benefit from a command tool to infer some types.

**Comment by Gabriella439** [comment]
Yeah, this is a known issue with Dhall.  I actually tried to investigate what Dhall might look like with type inference and the result of that was my [fall-from-grace](https://www.haskellforall.com/2021/09/fall-from-grace-ready-to-fork.html) project, and while that does work (and maybe that's what you actually want) I probably wouldn't suggest porting that type inference logic to Dhall.

The reason why is that Dhall's type-checker has to be implemented multiple times (once for each independent language bindings), so we want to keep it as simple as possible to implement.  Implementing a "good" type inference system adds a lot of complexity to the language standard and would require a substantial rewrite of each of the language bindings (and impose a high implementation cost on future language bindings).

**Comment by zmrocze** [comment]
I 'd love type inference and wouldn't care if language integrations (other than haskell probably) don't work

**Comment by Gabriella439** [comment]
You might be interested in: https://github.com/Gabriella439/grace

See also: https://www.haskellforall.com/2021/09/fall-from-grace-ready-to-fork.html

https://trygrace.dev
