### ISSUE TITLE
Should the ABNF grammar disallow shebangs inside expressions?

### ISSUE THREAD

**Issue by winitzki** [dhall-lang/dhall-lang#1357]
The ABNF grammar defines `complete-expression` as an expression that could begin by one or more "shebangs":

https://github.com/dhall-lang/dhall-lang/blob/master/standard/dhall.abnf#L1022

However, `complete-expression` is used as part of ordinary expressions:

https://github.com/dhall-lang/dhall-lang/blob/master/standard/dhall.abnf#L355

and

https://github.com/dhall-lang/dhall-lang/blob/master/standard/dhall.abnf#L976

Is this really desired that expressions contain shebangs inside? What is the meaning of those shebangs if they are inside an expression, are they just to be ignored?

In the following expression, should the sub-expression `12345` be converted to text or not?

```dhall
( 
#!/usr/bin/env -S dhall text --file
#!this is still allowed by the grammar
  12345
)
```

**Comment by mmhat** [comment]
Good catch! Interestingly the Haskell implementation does not conform to that grammar but does what you expect, i.e. allows the shebang only at the beginning of the input (https://github.com/dhall-lang/dhall-haskell/blob/55aff097b49ff85bb4eff1cc4f42c9fe40df3f49/dhall/src/Dhall/Parser.hs#L127).
