### ISSUE TITLE
Builtins operators reference: Missing record projection

### ISSUE THREAD

**Issue by maxime-didier** [dhall-lang/dhall-lang#1359]
Hello,

I noticed the `record.{ fields, ... }` and `record.(Type)` syntax is not described in the [builtins reference](https://docs.dhall-lang.org/references/Built-in-types.html). I found it in the haskell implementation's AST [definition](https://github.com/dhall-lang/dhall-haskell/blob/dfa82861ed13796f6d7b96b30139a6f11e057e7b/dhall/src/Dhall/Syntax/Expr.hs#L244-L246) and in the [cheatsheet](https://docs.dhall-lang.org/howtos/Cheatsheet.html), but I'm not sure whether the other dhall implementations do implement it. There may be some coordination required with other implementers to fix this if they missed the feature.

**Comment by winitzki** [comment]
Also, recent additions such as `as Bytes` and `as Location` are not mentioned in the builtins reference.

**Comment by Gabriella439** [comment]
Pull request up for this here: https://github.com/dhall-lang/dhall-lang/pull/1372
