### ISSUE TITLE
Value-type-constrained Records

### ISSUE THREAD

**Issue by blast-hardcheese** [dhall-lang/dhall-lang#136]
It would be very useful to be able to constrain value types of records _without_ constraining the structure of the rest of the record.

This is used to constrain structures like:

```
{
  instances = {
    server1 = makeServer "server1",
    server2 = makeServer "server2"
  }
}
```
where the _names_ of the keys are significant to the consumer, but the structures should be:
- Identical
- Instances of a Union

**Comment by Gabriel439** [comment]
In this case I believe the idiomatic way to represent this would be an explicit association list of the form:

```haskell
List { key : Text, value : a }
```

i.e.:

```haskell
{ instances =
    [ { name = "server1", instance = makeServer "server1" }
    , { name = "server2", instance = makeServer "server2" }
    ]
}
```

Once the key is demoted to the value level like that then you programmatically ensure any necessary correspondence between the key and the value, like:

```haskell
    let makeEntry = λ(name : Text) → { name = name, instance = makeServer name }

in  [ makeEntry "server1", makeEntry "server2" ]
```

Another advantage of this approach is that you no longer require language support for computed keys once you demote the keys to the value level (so #135 might not be necessary if you use this encoding).

**Comment by blast-hardcheese** [comment]
I agree, this is a much more convenient form of expression from Dhall's perspective.

To your point in #135, `dhall-to-terraform` might do some of this work, then be required to walk the generated tree to heuristically-derived points in order to do the required transformation.

This does limit adoption in other languages, as every consumer will have to have a custom `dhall-to-*` implementing some form of business logic instead of being able to generically express this use case.

(Example from Typescript of a similar feature: [Index types and string index signatures](http://www.typescriptlang.org/docs/handbook/advanced-types.html#index-types-and-string-index-signatures))

**Comment by Gabriel439** [comment]
Yeah, I'm aware that this idiom of treating records as homogeneous maps is pervasive in the dynamically typed world and in ops.

One possible solution that might not require paying this price repeatedly for each integration is to instead modify `dhall-to-json` to add a special case to translate any value of type:

```
List { key : Text, value : a }
```

... to the corresponding JSON record.  Then I think you could reuse `dhall-to-json` for all of these integrations.  Would that solution work for you?

**Comment by blast-hardcheese** [comment]
It would work, but it's just more functionality-by-convention. That definitely seems like cheapening Dhall's core value proposition instead of strengthening its position and value to the community.

**Comment by Gabriel439** [comment]
I support test-driving this in `dhall-to-terraform` or `dhall-to-json`, but I would oppose adding this to the standard even the Terraform/JSON experiment succeeded.  The reason why is that JSON is not the only backend for Dhall and the standard should not overfit the JSON use case.  JSON-specific idioms belong in the JSON integration and not in the backend-agnostic standard.

The other reason is that I believe that records doubling as homogeneous maps is a design anti-pattern that should be slowly phased out and I don't think Dhall should encourage that idiom nor should Dhall enshrine the idiom in the language standard.

**Comment by Gabriel439** [comment]
I opened an issue to discuss potential `dhall-to-json` support for homogeneous maps here: https://github.com/dhall-lang/dhall-json/issues/27

**Comment by ocharles** [comment]
I've just ran into wanting something like this. At work, I'm considering having a single Dhall expression that is the union of *all* configuration variables - secrets and all - as a big nested map. The idea then is that when we configure individual services, we just project out what we need from this and form the configuration as necessary. 

Right off the bat, I was going to have:

```dhall
{ aws = { keys = { service-1 = ..., service-2 = ... } }
```

Then, when I configure `service-1`, I can reference `(./config.dhall).aws.keys.service-1`. However, currently I don't have a way to say "anything you project out of `keys` will be of type `{access-key : Text, secret : Text }`, which is a little annoying. Of course, if I *assume* that, then other things will fail to type check later if the assumption doesn't hold, so it's not the end of the world.

As these maps are equivalent to functions, I might just use a function where the key is a union, but it feels like it might be a little cumbersome.

**Comment by ocharles** [comment]
Alright, on reflection this actually isn't too bad. I'm using a structure like:

```
{ aws =
    { key-credentials =
          λ(key : ./AWSKey.dhall )
        → merge
          { production =
                λ(_ : {})
              → { access-key-id = "whatever"
                , secret = "whatever"
                }
          }
          key
    , keys =
        constructors ./AWSKey.dhall 
    }
, postgresql =
    { database =
          λ ( database
            : ./Database.dhall 
            )
        → merge
        → merge
          { Production =
                λ ( _
                  : {}
                  )
              → { database = "foo"
                , host = "localhost"
                }
          }
          database
    }
}
```

**Comment by Gabriel439** [comment]
@ocharles: I still think it would be useful for your use case, for two reasons:

* It would allow you to specify a schema if the final type is an association list.  You might start off as a record so that you can project out the desired fields, but if you then convert the record to an association list at the end then the schema doesn't change as you add more services
* It would obsolete the need for `dhall-json`'s special-case logic to convert records to homogeneous lists if we can build that feature into the language

**Comment by ocharles** [comment]
Yes, certainly. I ultimately found this encoding to cumbersome and went for direct records and hoping they remain consistent

**Comment by Gabriel439** [comment]
I'm going to close out this issue in favor of https://github.com/dhall-lang/dhall-lang/issues/234 as I'm treating that one as the central issue for the proposed `toMap` keyword.  Feel free to reopen this if there is an additional request here beyond that.
