### ISSUE TITLE
ABNF grammar should explicitly disallow keywords as identifiers?

### ISSUE THREAD

**Issue by winitzki** [dhall-lang/dhall-lang#1360]
In the ABNF grammar, it is specified that an identifier (or an `unreserved_label`) may not be a built-in symbol (such as `Natural`, etc.)
https://github.com/dhall-lang/dhall-lang/blob/master/standard/dhall.abnf#L581-L586
However, it appears to me that the grammar must also disallow identifiers that are equal to a keyword such as `in`.

Otherwise `let x = y in z` may be parsed as an application of `y` to an identifier `in`.

**Comment by MonoidMusician** [comment]
That's covered in the `simple-label` rule:

https://github.com/dhall-lang/dhall-lang/blob/b27d2c89bc03f80a30b3e79810cee6c113ee3ca2/standard/dhall.abnf#L195-L204C38

**Comment by winitzki** [comment]
Yes, you are right. I missed that.
