### ISSUE TITLE
ABNF grammar should include a mandatory whitespace after `import-hashed`?

### ISSUE THREAD

**Issue by winitzki** [dhall-lang/dhall-lang#1361]
It appears that the rule `import = import-hashed [ whsp as whsp1 (Text / Location) ]` actually requires a mandatory whitespace before `as`.

https://github.com/dhall-lang/dhall-lang/blob/master/standard/dhall.abnf#L809

With the current grammar, whitespace may be absent and then we will have to parse these examples as valid imports:

```dhall
missingas Text
./local/pathas Location
```

This parsing does not make a lot of sense but this seems to be allowed by the grammar.

So, I'm proposing to change this rule to:

`import = import-hashed [ whsp1 as whsp1 (Text / Location / Bytes) ]`

In another issue I raised - https://github.com/dhall-lang/dhall-lang/issues/1356 - I already proposed adding ` / Bytes` to that rule.

A similar issue seems to be with the rule `http = http-raw [ whsp using whsp1 import-expression ]`.
https://github.com/dhall-lang/dhall-lang/blob/master/standard/dhall.abnf#L734

**Comment by Gabriella439** [comment]
Yeah, that seems like a reasonable change to me
