### ISSUE TITLE
Is this an incorrect test file: `dhall-lang/tests/import/success/unit/ImportRelativeToHomeB.dhall`?

### ISSUE THREAD

**Issue by winitzki** [dhall-lang/dhall-lang#1366]
According to [README.md](https://github.com/dhall-lang/dhall-lang/blob/master/tests/README.md) the import tests should read the A file, resolve all imports, and replace imports with beta-normalized expressions. The result must be equal to the B file.

In my Dhall implementation I see an unexpected failure in one test:

[ImportRelativeToHomeA](https://github.com/dhall-lang/dhall-lang/blob/master/tests/import/success/unit/ImportRelativeToHomeA.dhall) has `~/hello.dhall ++ " world"`

The file `hello.dhall` resolves to the string `"hello"`. So, the expected result is the Dhall expression `"hello" ++ " world"` if we just replace the import.

However, the expected answer in [ImportRelativeToHomeB](https://github.com/dhall-lang/dhall-lang/blob/master/tests/import/success/unit/ImportRelativeToHomeB.dhall) has `"hello world"`. This is beta-normalized.

But, according to  [README.md](https://github.com/dhall-lang/dhall-lang/blob/master/tests/README.md), we are not supposed to beta-normalize entire expressions from the `A` files. And if we do, other tests will start failing, for example, [AlternativeWithVariableB.dhall](https://github.com/dhall-lang/dhall-lang/blob/master/tests/import/success/unit/AlternativeWithVariableB.dhall) is a non-normalized expression.

I believe this is an error. The contents of [ImportRelativeToHomeB](https://github.com/dhall-lang/dhall-lang/blob/master/tests/import/success/unit/ImportRelativeToHomeB.dhall)  must not be beta-normalized, it must be `"hello" ++ " world"`. 

How can this test pass in existing Dhall implementations? Am I missing something here?

**Comment by Gabriella439** [comment]
Yes, your interpretation is correct and the result should be `"hello" ++ " world"`.  The reason the Haskell implementation doesn't fail on this test is because it skips this test (for other reasons):

https://github.com/dhall-lang/dhall-haskell/blob/8982b76934241b0fb4f801635851b54565f9cfaf/dhall/tests/Dhall/Test/Import.hs#L126-L128

**Comment by winitzki** [comment]
Thank you for the explanation. I will make a PR to fix the test.
