### ISSUE TITLE
Introduce Bytes/length and Text/length as built-ins?

### ISSUE THREAD

**Issue by winitzki** [dhall-lang/dhall-lang#1373]
It appears useful to have `Bytes/length : Bytes -> Natural` and `Text/length : Text -> Natural` as built-in functions. 

We already have `List/length` but there is no way of finding out the length of a text (this is perhaps useful for formatting and for finding out whether the text is too long).

`Bytes/length` just seems a good thing to have; for instance, if we have imported something `as Bytes` we would like to know how big it is.

Another use for `Text/length` is to find out approximately how large a given integer is. `Text/length (Natural/show x)` is approximately `floor(log10(x))`, a useful bound to have, if we want to figure out how much space a number will take when formatted, and also for numerical algorithms.

Other ideas are conversions between Natural, Bytes, and Text.

**Comment by kukimik** [comment]
Note that `Text/length` together with `Text/replace` and `Natural/isZero` allow checking for text equality, which is controversial #164.

```dhall
let Text/equal = \(a : Text) -> \(b : Text) -> Natural/isZero (Text/length (Text/replace a "" b)) && Natural/isZero (Text/length (Text/replace b "" a))
```

**Comment by winitzki** [comment]
I see. I think the vision for Dhall ("programmable configuration that involves a high degree of type safety but only a minimum of computation") should be made more clear in the standard documents.

There is interest in making Dhall a scripting language for an app, and in that case the app can easily supply all kinds of external functions.

**Comment by Gabriella439** [comment]
It is documented, but it's documented here: https://docs.dhall-lang.org/discussions/Design-choices.html
