### ISSUE TITLE
Please mention how to pronounce 'Dhall' in the README

### ISSUE THREAD

**Issue by quasicomputational** [dhall-lang/dhall-lang#144]
Some of those of us who've never played the game would like to speak the name aloud without making fools of ourselves. I'd suggest writing it in IPA, plus mentioning a word that it rhymes with. Here are the ways I can imagine it could be said:

* /dal/, to rhyme with 'pal'.
* /dɑːl/, as in 'Roald Dahl'.
* /dɔːl/, to rhyme with 'tall'.

If it starts with the same sound as 'that' instead of 'dark', then those would start with /ð/, not /d/.

**Comment by Profpatsch** [comment]
Iirc, the game didn’t have voice acting. I always pronounce it like `/dɔːl/, to rhyme with 'tall'`.

**Comment by ocharles** [comment]
Ha, I've always pronounced it /dɑːl/, as in 'Roald Dahl', as in the [Indian dish](https://en.wikipedia.org/wiki/Dal).

**Comment by f-f** [comment]
I was about to open the same issue. In my case I pronounce it "d-hall", so some IPA in the readme would definitely help.

**Comment by Gabriel439** [comment]
Pull request with proposed pronunciation: https://github.com/dhall-lang/dhall-lang/pull/146
