### ISSUE TITLE
Idea: `constructors`  + `variants`

### ISSUE THREAD

**Issue by aleator** [dhall-lang/dhall-lang#153]
This is just a quick draft, but I think I thought up a way that might help to solve the issue behind #136 in a bit roundabout way.

We currently have `constructors`, which is quite useful. In essence, if you have a
variant of type `<a:x | a:y | ...>` it will give you a record of type `{a:x -> <a:x | b:y | ...>, b:y -> <a:x | b:y | ...>, ...`}`. How about doing the converse?

Given a record `{a:x,b:y,...}` you would get a corresponding variant type `<a:x | b:y | ...>`. Let's call the latter type `FieldSum r` for lack of a better name. Now, if do the same thing as we do with `constructors`, we end up with something like `record -> [FieldSum record]`. This provides a nice path from records to lists. Let's call this operation `variants`.

Then to complete things, there would need to be something like `update : record -> FieldSum record -> record`, so you could re-insert the fields extracted by `variants`.  

All of the above can be written manually for each given type, so I think they would be implementable in the same way as `constructors`.

As the pay-off this, you would be half way towards means of turning lists into records and vice versa. All that is missing is some wildcard mechanism for sums, I think.

**Comment by Gabriel439** [comment]
Note that the original problem behind #136 seems to have been addressed by https://github.com/dhall-lang/dhall-json/pull/29.  See also: https://github.com/dhall-lang/dhall-json/issues/27

Outside of that issue, I also think that this proposal overlaps with the `//` operator.  My understanding is that this is proposing a way to update records that looks like this:

```haskell
  λ(record0 : { foo : Text, bar : Natural, baz : Bool })
→ λ(record1 : { bar : Natural, baz : Bool })
→     let updates
          : FieldSum { bar : Natural, baz : Bool }
          = variants record1

  in  update record0 updates : { foo : Text, bar : Natural, baz : Bool }
```

... but you can already do that with `//`, like this:

```haskell
  λ(record0 : { foo : Text, bar : Natural, baz : Bool })
→ λ(record1 : { bar : Natural, baz : Bool })
→ record0 // record1
```

**Comment by aleator** [comment]
Sure, but the aim with the `variants` is to be able to iterate over fields of the record, which is currently not possible.

**Comment by Gabriel439** [comment]
I think if you want to do that the appropriate solution is to use an association list (i.e. `List { mapKey : Text, mapValue : v }`)

**Comment by aleator** [comment]
But you cannot reuse a named value in dhall from association list since there is no lookup. At minimum, you'd need something like `List { mapKey : <a:{} | b:{} | ...>, mapValue: v}`. But then, the lookup function would both be huge and dependent on the base set.

Of course, if association lists are desirable, the above could be solved in many ways:

* Allowing equality for sums over unit type
* Enhancing `constructors`, or adding a similar functionality with other name, so that it could ease generation of such equality functions (ie. some macro to make a record with fields drawn from the sum and contents for each field given by user)
* Making it possible to use wildcards in merge (It is not obvious how to keep field names in this case)
* Making association lists a primitive (But then text would have equality in a roundabout way, or keys need to be sums over unit)
* Allowing automatic generation of lookup functions (seems like suspiciously special case)

But when I thought it up, the `variants` idea seemed neatly symmetric with the `constructors` so I thought I'd write it up, even though it doesn't solve the entire problem entirely.

**Comment by Gabriel439** [comment]
If the requirement is to reuse a named value from an association list then you can do that by assembling both from the same shared definition:

```haskell
    let sharedFoo = ...

in. let associationList = [ { mapKey = "foo", value = sharedFoo }, ... ]

in  { somethingElse = sharedFoo, ... }
```

... but if the goal is accurate reference tracking as you described in https://github.com/dhall-lang/dhall-lang/issues/137#issuecomment-389393756 then I think the correct solution is to use the Haskell API as I mentioned in https://github.com/dhall-lang/dhall-lang/issues/137#issuecomment-389730125.

**Comment by aleator** [comment]
Yeah. I could do that. But then I have five places with the essentially same symbol (let-binding, list key, list value, record key and record field). I am careless and bound to make a mistake with this amount of repetition :)

Accurate tracking besides "this item is drawn from this collection" hasn't really been the goal for me.

Interaction with sums and records just feels interesting to me. For example, there is `merge` that collapses a sum using a record and this instantly inspires the thought of unmerge, which extracts fields from record using a sum. Which, incidentally, also seems related to the current issue. 

This ticket is not that important in practical sense, since I already have a shake hack where importing "asList/otherFile" automatically converts the homogenous record in `otherfile` to list and places it in `asList/otherFile`.
