### ISSUE TITLE
Discussion: Dhall serialization format

### ISSUE THREAD

**Issue by Gabriel439** [dhall-lang/dhall-lang#158]
Dhall needs a standard serialization format for two related reasons:

* To support semantic integrity checks (some encoding of a Dhall expression)
* To eventually store cached expressions based on their semantic integrity checks (See: #129)

The Haskell implementation of Dhall currently uses a very dumb approach: it just renders the expression in a compact form and hashes that

The main thing to discuss here is what format Dhall should standardize on for storing expressions

The first question on my mind is whether the serialized format should be human-readable or not since that choice affects most other decisions

**Comment by Profpatsch** [comment]
How about just pretty-printing in a way that removes every superfluous whitespace? That way you can always restore a readable form by pretty-printing again and it’s still a valid dhall file.

**Comment by joneshf** [comment]
> The first question on my mind is whether the serialized format should be human-readable or not...

Human-readable formats tend to lead to humans writing in that format. I think the answer to this question is whether or not we people to write in two languages (serialized and unserialized) or one (unserialized).

**Comment by f-f** [comment]
I agree with @joneshf, and I would add that if we have to add another format, we might as well just go with a non-human-readable, compact binary format.

This would:
- make it clear that humans are not supposed to do anything with it but it's only for machines
- standardize caching and semantic integrity checks
- and provide us with an efficient transport format for exchanging expressions? This means getting in the territory of Protobuf, Thrift, etc. (but better)

**Comment by Gabriel439** [comment]
There's another benefit of a binary format I want to mention: even if parsing is expensive (which I aim to fix) you only have to pay the cost of parsing the text format once for an import cached in this way.  Parsing the binary format for cache hits would be *much* faster than parsing the original text format

You'd still have to pay the cost of parsing the text of the top-level expression, though.

Another thing to note is that if we add support for importing something by hash alone (as mentioned in https://github.com/dhall-lang/dhall-lang/issues/129#issuecomment-389896043)  then you would automatically get command line support for browsing the cache for free.  To decode any cached entry you would write:

```bash
$ dhall <<< 'sha256:...'
```

**Comment by Gabriel439** [comment]
Just updating where I am on this.  My high-level notes are:

* I plan to use CBOR as originally suggested.  It's pretty well suited to this
* The way I plan to encode each constructor of the expression sum type is as a heterogeneous list in CBOR
    * Specifically, the first element of the list is a numeric tag for the constructor and the remaining elements are any fields of the constructor
    * There are some minor details that still need to be resolved here, like whether to nest all the built-ins under one top-level tag
    * I also need to work out whether `True` and `False` will be encoded using CBOR's built-in support for boolean values (section 2.3) or encoded the same as other built-ins
* I plan to use CBOR decimal fractions (section 2.4.3) for `Double`s so that no information is loss when converting to and from the text representation
* I plan to use CBOR bignums (section 2.4.2) for `Integer`s
* I still need to work out the details of how to encode interpolated `Text`
    * The main thing I'm sure of is that I won't desugar it to `++` because I want to preserve the interpolation
* Anything that uses a `Map` (i.e. records and unions) is encoded using a CBOR map
* List and optional values are encoded as CBOR lists (wrapped in another heterogeneous list containing the tag and type information)

There are still lots of small details that I'm still working out, but that's the high-level gist of where this is going.

**Comment by joneshf** [comment]
This is great, thanks! Is there anything we can help with?

**Comment by Gabriel439** [comment]
@joneshf: Yes, the main steps for standardizing this are:

* Add a section specifying the simplified syntax for the CBOR grammar in `semantics.md`
    * This will  be similar to the simplified grammar for Dhall expressions at the top of the same file: https://github.com/dhall-lang/dhall-lang/blob/master/standard/semantics.md#expressions
    * It can even use the same tokens, too
* Add a section for a new `serialize` judgment and specify its type and which parameters are inputs and outputs
    * You can use the judgement for `canonicalize` as a template: https://github.com/dhall-lang/dhall-lang/blob/master/standard/semantics.md#canonicalization-of-directories
    * i.e. the input is a Dhall expression and the output is a CBOR expression
* Then start adding rules for the `serialize` judgment for the things we know for sure (i.e. some of the things I described above) we can expand from there

You can just start from the top and I'll jump in once I'm done finalizing the last few details

**Comment by Gabriel439** [comment]
@joneshf: Alright, I have a pull request up for the standardization of the binary encoding: https://github.com/dhall-lang/dhall-lang/pull/194

Once that is reviewed and merged then the standardization of semantic integrity checks and caching should follow rapidly

**Comment by joneshf** [comment]
That's great! Thanks for working through it. Mind assigning me as a reviewer so I don't forget?

**Comment by Gabriel439** [comment]
@joneshf: I invited you as a collaborator.  Once you join then I can add you as a reviewer
