### ISSUE TITLE
File extension not parsed as part of import

### ISSUE THREAD

**Issue by f-f** [dhall-lang/dhall-lang#159]
Parsing  the following expression: `./a.dhall` 
with the latest abnf returns the following parse tree:

```clojure
[:complete-expression
 [:whitespace]
 [:expression
  [:annotated-expression
   [:operator-expression
    [:or-expression
     [:plus-expression
      [:text-append-expression
       [:list-append-expression
        [:and-expression
         [:combine-expression
          [:prefer-expression
           [:combine-types-expression
            [:times-expression
             [:equal-expression
              [:not-equal-expression
               [:application-expression
                [:selector-expression
                 [:primitive-expression
                  [:import
                   [:import-hashed
                    [:import-type
                     [:local
                      [:local-raw
                       "."
                       [:directory]
                       [:file [:path-component "/" [:path-character "a"]]]]
                      [:whitespace]]]]]]
                 [:dot "." [:whitespace]]
                 [:label
                  [:simple-label
                   [:ALPHA "d"]
                   [:ALPHA "h"]
                   [:ALPHA "a"]
                   [:ALPHA "l"]
                   [:ALPHA "l"]]
                  [:whitespace]]]]]]]]]]]]]]]]]]]
```

Which is not correct, as the dot and the extension should be included in the `:file` rule.

I was not able to find the problem yet, but it should be [around here](https://github.com/dhall-lang/dhall-lang/blob/b69e0712889dc6fec6b98aed635509012ed9f64e/standard/dhall.abnf#L399). All the chars that should be parsed are part of the `path-character` rule, so this is weird.

**Comment by f-f** [comment]
This happens also when parsing urls, e.g. `"http://example.com/List/concat.dhall"`, where everything is fine, except the `dot` and the `label` with the extension are part of the outer `selector-expression` instead of the `import`.

**Comment by Gabriel439** [comment]
Two things to test:

* How does it parse the path `./a.`?
* What happens if you replace all occurrences of `directory file` in the grammar with `1*path-component`?

**Comment by f-f** [comment]
Nice ideas, thanks.

> How does it parse the path `./a.`?

Correctly, the dot is included in the path

> What happens if you replace all occurrences of `directory file` in the grammar with `1*path-component`?

(cutting away the non-interesting part of the trees here)

`./a.` still parses correctly:

```clojure
                    [:local
                      [:local-raw
                       "."
                       [:path-component "/" [:path-character "a"] [:path-character "."]]]
                      [:whitespace]]
```

and `./a.a` still incorrectly:

```clojure
               [:selector-expression
                 [:primitive-expression
                  [:import
                   [:import-hashed
                    [:import-type
                     [:local
                      [:local-raw "." [:path-component "/" [:path-character "a"]]]
                      [:whitespace]]]]]]
                 [:dot "." [:whitespace]]
                 [:label
                  [:simple-label [:ALPHA "a"]]
                  [:whitespace]]]
```

**Comment by Gabriel439** [comment]
This seems like an issue with `instaparse`. For some reason it seems to prioritize parsing the extension as a field access over parsing as a path component.

A few other programs worth parsing to better understand how `instaparse` prioritizes parsing alternatives:

* `./foo.bar.baz` (to see if both`.bar` and `.baz` get consistently parsed as field accesses)
* `./foo.bar~` (to see if `instaparse` backtracks from a failed attempt to parse `bar~` as a label)
* `./foo./bar` ( to see if `instaparse` parses `/bar` as a label or `./bar` as a second path)

**Comment by f-f** [comment]
> This seems like an issue with instaparse

Yes, that's what I suspect as well. I'm now looking at how the rules get translated into code in there.

The parsing of the new list is also interesting:
- ❌ `./foo.bar.baz`: import `foo`, field access `bar` and `baz`
- ✅ `./foo.bar~`: correctly parses as a filename
- ❌ `./foo./bar`: a relative import with directory`/foo.` and file `/bar`

**Comment by f-f** [comment]
Reopening this, as I think I found out that the grammar is ambiguous in this case (but I'm still not sure how to fix).

So, I first built a minimal grammar to reproduce the ambiguity:
```clojure
(def g
  "
  expr = path *(dot label)

  dot = \".\"
  label = 1*ALPHA

  path = \".\" 1*path-fragment
  path-fragment = \"/\" 1*path-char
  path-char = ALPHA / \".\"
  ")

(def p (insta/parser g :input-format :abnf :start :expr))
```

With it we can reproduce the first two tests:
```clojure
>>> (p "./a.a")      ;; This parses incorrectly
[:expr
 [:path "." [:path-fragment "/" [:path-char [:ALPHA "a"]]]]
 [:dot "."]
 [:label [:ALPHA "a"]]]

>>> (p "./a.")      ;; This is the sanity check
[:expr [:path "." [:path-fragment "/" [:path-char [:ALPHA "a"]] [:path-char "."]]]]
```

Then I read [about ambiguous grammars](https://github.com/Engelberg/instaparse#ambiguous-grammars) on the Instaparse readme, and found out about the `parses` function, which returns about all the possible parses of a string.

So I tried it out on the toy grammar, and found ambiguity; there is two possible parses for our first string, and the last one is correct:
```clojure
>>> (insta/parses p "./a.a")
([:expr
  [:path "." [:path-fragment "/" [:path-char [:ALPHA "a"]]]]
  [:dot "."]
  [:label [:ALPHA "a"]]]
 [:expr
  [:path
   "."
   [:path-fragment "/" [:path-char [:ALPHA "a"]] [:path-char "."] [:path-char [:ALPHA "a"]]]]])
```

So I run it on the full grammar, and found three possible parses for the same string, of which the last one is correct:
```clojure
>>> (insta/parses dhall-parser "./a.a")
([:complete-expression
  [:whitespace]
  [:expression
   [:annotated-expression
    [:operator-expression
     [:or-expression
      [:plus-expression
       [:text-append-expression
        [:list-append-expression
         [:and-expression
          [:combine-expression
           [:prefer-expression
            [:combine-types-expression
             [:times-expression
              [:equal-expression
               [:not-equal-expression
                [:application-expression
                 [:selector-expression
                  [:primitive-expression
                   [:import
                    [:import-hashed
                     [:import-type
                      [:local
                       [:local-raw
                        "."
                        [:directory]
                        [:file [:path-component "/" [:path-character "a"]]]]
                       [:whitespace]]]]]]
                  [:dot "." [:whitespace]]
                  [:label [:simple-label [:ALPHA "a"]] [:whitespace]]]]]]]]]]]]]]]]]]]
 [:complete-expression
  [:whitespace]
  [:expression
   [:annotated-expression
    [:operator-expression
     [:or-expression
      [:plus-expression
       [:text-append-expression
        [:list-append-expression
         [:and-expression
          [:combine-expression
           [:prefer-expression
            [:combine-types-expression
             [:times-expression
              [:equal-expression
               [:not-equal-expression
                [:application-expression
                 [:selector-expression
                  [:primitive-expression
                   [:import
                    [:import-hashed
                     [:import-type
                      [:local
                       [:local-raw
                        "."
                        [:directory]
                        [:file
                         [:path-component "/" [:path-character "a"] [:path-character "."]]]]
                       [:whitespace]]]]]]]
                 [:selector-expression
                  [:primitive-expression
                   [:identifier
                    [:label [:simple-label [:ALPHA "a"]] [:whitespace]]
                    [:whitespace]]]]]]]]]]]]]]]]]]]]
 [:complete-expression
  [:whitespace]
  [:expression
   [:annotated-expression
    [:operator-expression
     [:or-expression
      [:plus-expression
       [:text-append-expression
        [:list-append-expression
         [:and-expression
          [:combine-expression
           [:prefer-expression
            [:combine-types-expression
             [:times-expression
              [:equal-expression
               [:not-equal-expression
                [:application-expression
                 [:selector-expression
                  [:primitive-expression
                   [:import
                    [:import-hashed
                     [:import-type
                      [:local
                       [:local-raw
                        "."
                        [:directory]
                        [:file
                         [:path-component
                          "/"
                          [:path-character "a"]
                          [:path-character "."]
                          [:path-character "a"]]]]
                       [:whitespace]]]]]]]]]]]]]]]]]]]]]]])
```

**Comment by Gabriel439** [comment]
@f-f: You can fix one of those two ambiguities by moving the `import` rule higher in the parsing stack preceding the `selector-expression` rule, like this:

```abnf
application-expression = [ constructors ] 1*import-expression

import-expression = import / selector-expression
```

... and that would force users to parenthesize imports if they wanted to access their fields, avoiding ambiguity over whether a `.` represented an extension or a field access

Then I think you can also fix the second ambiguity by changing the `application-expression` rule to require at least one space in between a function and its argument, like this:

```
application-expression = [ constructors ] import-expression *(" " import-expression)
```

... so that `./ab` cannot be interpreted as `./a b`.  Note that such a change would also prohibit expressions like `f(x)`, which I think is probably fine

Try out those changes and see if that resolves the parsing ambiguity

**Comment by f-f** [comment]
Amazing, the grammar with the changes seems to be working :) Thanks a lot @Gabriel439!

I opened #161 with the changes.
