### ISSUE TITLE
Type inference: Should this var rule have a shift?

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-lang#165]
The first rule for type inference on variables is

```
    Γ ⊢ T : k
    ──────────────────
    Γ, x : T ⊢ x@0 : T
```

but I'm wondering if this is actually sound. Should it be

```
    Γ ⊢ T : k
    ──────────────────────────────
    Γ, x : T ⊢ x@0 : ↑(1, x, 0, T)
```

or something along those lines? The `var` typing rule extends the context, so if `T` were to mention any other `x`, it would be referring to the wrong `x`.

**Comment by ocharles** [comment]
This has come out of attempt to formalise the standard in Agda while being very strict at adhering to the variable naming standardisation. The following doesn't type check:

```agda
open import Data.Fin
open import Data.Nat
open import Data.Product hiding (,_)
open import Data.String
open import Data.Vec
open import Relation.Binary.PropositionalEquality 
open import Relation.Nullary
open import Relation.Nullary.Negation

Name : Set
Name = ℕ

Names : ℕ → Set
Names = Vec Name

occurances : {n : ℕ} → Name → Names n → ℕ
occurances _ [] = zero
occurances name (x ∷ _) with name Data.Nat.≟ x
occurances name (_ ∷ names) | yes refl = suc (occurances name names)
occurances name (_ ∷ names) | no _ = occurances name names

name-Fin : {n : ℕ} → Name → Names n → Set
name-Fin name names = Fin (occurances name names)

-- | The set of well-scoped expressions. 'names' is a vector of names in the
-- that they are introduced. _at_ references a name from this vector, and a
-- de Bruijn index as to how many other equal names to skip.
data Expr {n : ℕ} (names : Names n) : Set where
  _at_ : (name : Name) → (i : name-Fin name names) → Expr names
  _∙_ : Expr names → Expr names → Expr names
  ƛ_∷_⇒_ : (n : Name) → Expr (n ∷ names) → Expr names → Expr names

-- The set of well-typed well-scoped expressions.
data _⊢_∷_ : {n : ℕ} (Γ : Vec Name n) → Expr Γ → Expr Γ → Set where
  var-here : ∀ {n x} {Γ : Names n} {T k : Expr Γ} { i : name-Fin x ( x ∷ Γ ) } → Γ ⊢ T ∷ k → (x ∷ Γ) ⊢ x at i ∷ T
```

But if I change `var-here` to shift then it does

```agda
↑[_,_,_] : {n : ℕ} {Γ : Names n} → (x : Name) → ℕ → Expr Γ → Expr (x ∷ Γ)
↑[_,_,_] = {!!}

-- The set of well-typed well-scoped expressions.
data _⊢_∷_ : {n : ℕ} (Γ : Vec Name n) → Expr Γ → Expr Γ → Set where
  var-here : ∀ {n x} {Γ : Names n} {T k : Expr Γ} { i : name-Fin x ( x ∷ Γ ) } → Γ ⊢ T ∷ k → (x ∷ Γ) ⊢ x at i ∷ ↑[ x , 0 , T ]
```

**Comment by Gabriel439** [comment]
@ocharles: The thing that should (in theory) prevent this from being an error is that each judgment that adds a variable to the context shifts all prior references to that variable.  For example, the type-checking judgment for anonymous functions is:

```
↑(1, x, 0, (Γ₀, x : A)) = Γ₁   Γ₁ ⊢ b : B   Γ₀ ⊢ ∀(x : A) → B : c
─────────────────────────────────────────────────────────────────
Γ₀ ⊢ λ(x : A) → b : ∀(x : A) → B
```

However, you could also do it the way you suggested, which is that you don't shift the context when adding new variables to the context and you instead shift the result upon lookup instead.

Your version is less error-prone to implement (because you can't accidentally forget to shift the context when inserting new values) but also leads to less work being shared (because the shift has to be recomputed on every lookup and that work is not shared across lookups).

So going back to your original question: `T` should have already had `x` shifted upon insertion into the context, which is why we should not need to shift `x` again upon lookup.  However, I could be wrong since I haven't formally verified any of this 🙂

**Comment by Gabriel439** [comment]
Also, I should clarify: I would be fine with changing the standard to make it easier to formally verify even if it less efficient.  The Haskell implementation can continue to do things more efficiently as long as it is equivalent to the simpler specification.

**Comment by ocharles** [comment]
Yea, I've there definitely feels like something is odd about requiring this
short at the point of variable *usage*. I've been musing over this all day
to try and convince myself one-way or the other. I'll see if I can find
another way to convince Agra that this is cool - maybe it will be
illuminating. If anything, this will only fail to infer for free variables.

**Comment by ocharles** [comment]
I stared at this a bunch more and I think the rule is fine:

```
───────────────
Γ ⊢ Text : Type
───────────────────────
Γ,x : Text ⊢ x@0 : Text
────────────────────────
Γ,x : Text ⊢ Bool : Type
────────────────────────────────
Γ,x : Text,x : Bool ⊢ x@0 : Bool
```

That seems good to me. The inference rule says nothing else about other `x`s, and it doesn't need to. I think we're good here, I just need to work out the right way to demonstrate this to Agda.

**Comment by ocharles** [comment]
That said, where am I wrong in the following fairly bogus looking proof?

```
───────────────
Γ ⊢ Type : Kind
───────────────────────
Γ,x : Type ⊢ x@0 : Type
────────────────────────────────
Γ,x : Type,x : x@0 ⊢ x@0 : x@0
```

**Comment by ocharles** [comment]
If all the rules require a shift, everything does work out well in Agda

```agda
open import Data.Fin
open import Data.Nat
open import Data.Product hiding (,_)
open import Data.String
open import Data.Vec
open import Relation.Binary.PropositionalEquality 
open import Relation.Nullary
open import Relation.Nullary.Negation

-- TODO Parameterize on names
Name : Set
Name = ℕ

Names : ℕ → Set
Names = Vec Name

-- | The set of well-scoped expressions. 'names' is a vector of names in the
-- that they are introduced. _at_ references a name from this vector, and a
-- de Bruijn index as to how many other equal names to skip.
data Expr {n : ℕ} (names : Names n) : Set where
  _at_ :(name : Name) → (i : ℕ) → Expr names

↑[_,_,_] : {n : ℕ} {Γ : Names n} → (x : Name) → ℕ → Expr Γ → Expr (x ∷ Γ)
↑[ name , min-index , name₁ at i ] with name Data.Nat.≟ name₁
↑[ name , zero , .name at i ] | yes refl = name at suc i
↑[ name , suc min-index , .name at zero ] | yes refl = name at zero
↑[ name , suc min-index , .name at suc i ] | yes refl = ↑[ name , min-index , name at i ]
↑[ name , min-index , name₁ at i ] | no ¬p = name₁ at i

data Types : {n : ℕ} → Vec Name n → Set where
  [] : Types []
  type-cons : {n : ℕ} {names : Vec Name n} → (name : Name) → Expr names → Types names → Types (name ∷ names)

-- The set of well-typed well-scoped expressions.
data _⊢_∷_ : {n : ℕ} {names : Vec Name n} (Γ : Types names) → Expr names → Expr names → Set where
  var-here : 
     ∀ {n x} {names : Vec Name n} {Γ : Types names} {T k : Expr names} {T↑ : Expr (x ∷ names)} →
     Γ ⊢ T ∷ k → ↑[ x , 0 , T ] ≡ T↑ → (type-cons x T Γ) ⊢ x at zero ∷ T↑
  
  var-there :
     ∀ {i n x} {names : Vec Name n} {Γ : Types names} {T Δ : Expr names} {T↑ : Expr (x ∷ names)} →
     Γ ⊢ x at i ∷ T → ↑[ x , 0 , T ] ≡ T↑ → (type-cons x Δ Γ) ⊢ x at suc i ∷ T↑

  var-other :
     ∀ {i n x y} {names : Vec Name n} {Γ : Types names} {T Δ : Expr names} {T↑ : Expr (y ∷ names)} →
     Γ ⊢ x at i ∷ T → ↑[ y , 0 , T ] ≡ T↑ → ¬ y ≡ x → (type-cons y Δ Γ) ⊢ x at i ∷ T↑

infer : {n : ℕ} {names : Vec Name n} → (Γ : Types names) → (e : Expr names) → Dec (∃[ t ] (Γ ⊢ e ∷ t))
infer [] (_ at _) = no ( λ { (_ , ()) })
infer (type-cons x _ _) (y at _) with x Data.Nat.≟ y
infer (type-cons _ T Γ) (_ at zero) | yes refl with infer Γ T
infer (type-cons x T _) (_ at zero) | yes refl | yes ( _ , T-ok ) = yes ( ↑[ x , 0 , T ] , var-here T-ok refl )
infer (type-cons _ _ _) (_ at zero) | yes refl | no bad-T = no ( λ { (_ , var-here T _) → bad-T (_ , T); (_ , var-other T _ x≠y) → x≠y refl } )
infer (type-cons x _ Γ) (_ at suc i) | yes refl with infer Γ (x at i)
infer (type-cons x _ _) (_ at suc _) | yes refl | yes (t , proof) = yes ( ↑[ x , 0 , t ] , var-there proof refl)
infer (type-cons _ _ _) (_ at suc _) | yes refl | no not-later = no ( λ { (_ , var-there proof _) → not-later (_ , proof) ; (_ , var-other T _ x≠y) → x≠y refl }) 
infer (type-cons _ _ Γ) (y at i) | no x≠y with infer Γ (y at i)
infer (type-cons x _ _) (_ at _) | no x≠y | yes (T , proof) = yes (↑[ x , 0 , T ] , var-other proof refl x≠y)
infer (type-cons _ _ _) (_ at zero)  | no x≠y | no ¬p = no ( λ { (_ , var-here _ _) → x≠y refl ; (_ , var-other other _ _) → ¬p (_ , other)})
infer (type-cons _ _ _) (_ at suc _) | no x≠y | no ¬p = no ( λ { (_ , var-there _ _) → x≠y refl ; (_ , var-other other _ _) → ¬p (_ , other)})
```

**Comment by Gabriel439** [comment]
@ocharles: I think the root cause is that the current standard is missing a "well-formed" check for the context.  The standard (incorrectly) claims to work for any context but it actually only works for contexts assembled by the other typing judgments that have applied the relevant shifts

I think it might be simpler to actually change the standard to apply the shift on lookup instead of upon insertion into the context that way we can skip having to standardize what it means for a context to be well-formed.  The Haskell implementation can continue to do the more efficient thing

Does the proof work out if you only shift on lookup from the context but not shift upon insertion into the context?

**Comment by ocharles** [comment]
Yea, I've recently been playing with the assumption that everything in the context is actually a proof of a typing judgement. I need a bit more time to explore that, but it looks promising.

One problem I had over the weekend was due to the lack of this assumption: https://gist.github.com/ocharles/92605532412a9162faf550f19d9d7072#file-dhall-agda-L96. At line 96, we see recursion on `infer`, but only the second argument is smaller (the context is bigger). But due to the type inference rules for variables, we see [here](https://gist.github.com/ocharles/92605532412a9162faf550f19d9d7072#file-dhall-agda-L86) that we're recurring with neither argument getting smaller. If I didn't actually have to infer the type of things already in the context, this problem would go away.

Having a well formed context is a fairly standard presentation, so I think this is really what we want to go for. I don't think it's too complicated to formalise it, you're basically saying a context is formed by either:

1. Being empty
2. Given Γ ⊢ x ∷ k => Γ, x :: k

I think.

**Comment by Gabriel439** [comment]
@ocharles: My intuition is to go with whichever approach is easier to formally verify so I defer to your judgment here.  Both of them would be inefficient to implement if done naively (one requires shifting on every lookup and the other requires a well-formed-context check on every lookup)

**Comment by ocharles** [comment]
Alright, but it sounds like we're in agreement that something is wrong with
the standard as it stands?

**Comment by Gabriel439** [comment]
@ocharles: Yes.  I totally agree that the standard is incorrect and needs to be fixed

**Comment by ocharles** [comment]
I'll re-open this when I get back to trying to mirror the standard in Agda.
