### ISSUE TITLE
Double arithmetic?

### ISSUE THREAD

**Issue by michalrus** [dhall-lang/dhall-lang#166]
I know it’s deliberately left out, but we have quite a few of these in config files:

```
, cookieMaxAge = 1209600.0 -- 14 * 24 * 60 * 60
```

As sometimes sub-second `NominalDiffTime`s are needed:

```haskell
instance Dhall.Interpret NominalDiffTime where
  autoWith _ = fromRational . toRational <$> Dhall.double
```

What would be the best way to go here?

**Comment by Gabriel439** [comment]
How about adding a `Natural/toDouble` built-in?  Then you could do:

```haskell
cookieMaxAge = Natural/toDouble (14 * 24 * 60 * 60)
```

... or `Integer/toDouble` (since `Natural/toInteger` exists) or both

**Comment by ocharles** [comment]
I think just Integer/toDouble (or Double/fromInteger). Natural -> Double
can be derived from primitives and be done in Dhall.

**Comment by Gabriel439** [comment]
Yeah, I'm also leaning towards only providing `Integer/toDouble` to keep the built-ins as orthogonal as possible

**Comment by michalrus** [comment]
`Integer/toDouble` would be wonderful! =)

**Comment by Gabriel439** [comment]
The proposed change to the standard is here: https://github.com/dhall-lang/dhall-lang/pull/168

**Comment by michalrus** [comment]
@Gabriel439 one more thought: this won’t allow Double calculations like `0.1 * 0.5`, or this one (for which I have a use case):

```
{
  partOfInitialX = 0.00333333333333333333 -- = 5 / 1500
}
```

**Comment by Gabriel439** [comment]
@michalrus: That's correct.  The proposed change still doesn't permit double arithmetic

**Comment by michalrus** [comment]
Yes, yes, I totally understand that from the diff and this discussion above.

But, now, after going through our Dhall files, I’m thinking that m-m-maaaybe being able to say `5/1500` instead of `0.00333333333333333333 -- = 5 / 1500` could also be seen as desirable. I don’t know. :man_shrugging:

**Comment by michalrus** [comment]
I should have read all of the files when posting this issue, sorry. :crying_cat_face:

**Comment by Gabriel439** [comment]
@michalrus: No worries :)

I think I'll postpone adding `Double` arithmetic for now because that opens up a whole can of worms (like how Dhall should handle division by 0, for example)

**Comment by mafm** [comment]
Where is the rational for leaving out double arithmetic? I can see in comment from @michalrus that there are 'files' relating to this, but don't know where to find it.

FWIW, I'd really like to be able to use arithmetic in config files for numerical stuff, but maybe the rationale would explain why I don't really want it.

**Comment by FintanH** [comment]
@statusfailed What if you made a new data type that represented ratios like `{ numerator : Natural, denominator : Natural }` and then could define division and the likes for that type? I believe @sellout has described something similar to me before too.

**Comment by sellout** [comment]
@statusfailed I don’t know that it’ll provide what you want, but as @FintanH alluded to, I do have a nascent “dhall-numerics” library I’ve been working on. I can publish it later today, and you can take a look to see what’s there.

**Comment by statusfailed** [comment]
@FintanH I think I'd still need a function to get the decimal representation for my final output, right? Can this be done within Dhall?

To solve the immediate problem I might just add Double/div [in this way](https://github.com/dhall-lang/dhall-lang/wiki/How-to-add-a-new-built-in-function)

**Comment by statusfailed** [comment]
@sellout sure, I'll have a look, thanks!

**Comment by FintanH** [comment]
So the idea would be that you delay the computation until you interpret into your final language, e.g. Haskell, and then it will translate your Ratio into Double. The plus side of this is that you won't have the potential of precision errors until the very last moment :)

**Comment by Gabriel439** [comment]
@statusfailed: Yeah, I think you will probably want to add built-in `Double` operators for your use case

@FintanH: My understanding is that implementing the `Double` conversion logic in Haskell wouldn't work for this use because they want to use the resulting `Double` to template a string literal within Dhall

**Comment by FintanH** [comment]
> My understanding is that implementing the Double conversion logic in Haskell wouldn't work for this use because they want to use the resulting Double to template a string literal within Dhall

Unless you can delay the `show` to Haskell as well? :thinking: But maybe I didn't understand the use case properly :)

**Comment by statusfailed** [comment]
@FintanH @Gabriel439  I threw together a little example of how this can be done [here](https://github.com/statusfailed/double-dhall) based on the [Wiki guide](https://github.com/dhall-lang/dhall-lang/wiki/How-to-add-a-new-built-in-function).

Hopefully this helps anyone else who needs to do the same. Thanks everyone for your help!

**Comment by Gabriel439** [comment]
@statusfailed: Awesome!  Thank you 🙂

**Comment by f-f** [comment]
Probably worth adding to the Wiki guide as a working example?

**Comment by statusfailed** [comment]
Hmm... seems like I've hit another problem: I'm not able to use (in Haskell-land) functions defined in terms of my newly-added Double arithmetic functions. For example, when I define a dhall file like this:

    \(x : Double) -> \(y : Double) -> (Double/add x y)

I get this error in my Haskell program when trying to use it with `Dhall.inputWithSettings doubleArithmeticSettings Dhall.auto text`:

    *** Exception: Interpret: You cannot decode a function if it does not have the correct type

Whereas if I only use "existing" Double functions (like the below Dhall function), everything works:

    \(x : Double) -> \(y : Double) -> (Double/show x)

Is there a way I can solve this?

**Comment by ocharles** [comment]
Can you provide a full example?

**Comment by statusfailed** [comment]
I've created a full example on the branch `example/cannot-decode-function` of the [double-dhall repo](https://github.com/statusfailed/double-dhall/tree/example/cannot-decode-function). 

There are two Dhall files added. `broken.dhall` yields the below exception when run with `cat broken.dhall | cabal run`:

    double-dhall: Interpret: You cannot decode a function if it does not have the correct type
    CallStack (from HasCallStack):
      error, called at src/Dhall.hs:803:24 in dhall-1.19.1-CXfxNxFUhESEV34XV95wYt:Dhall

And `working.dhall` prints `1.0` as expected.

FWIW, I am using Nix, so running this with version 1.19.1 of Dhall - not sure if this would make a difference. Let me know if there's anything else I can provide - cheers!

**Comment by Gabriel439** [comment]
@statusfailed: I'll check this soon.  Version 1.19.1 should be new enough since we haven't changed anything related to this since then

**Comment by Gabriel439** [comment]
@statusfailed: I found the problem.  The issue is that the `Interpret` instance for functions isn't respecting your custom normalization setting:

```
instance (Inject a, Interpret b) => Interpret (a -> b) where
    autoWith opts = Type extractOut expectedOut
      where
        -- The `Dhall.Core.normalize` is ignoring your customizations
        extractOut e = Just (\i -> case extractIn (Dhall.Core.normalize (App e (embed i))) of
            Just o  -> o
            Nothing -> error "Interpret: You cannot decode a function if it does not have the correct type" )

        expectedOut = Pi "_" declared expectedIn

        InputType {..} = inject

        Type extractIn expectedIn = autoWith opts
```

This is why it works on built-in functions but not with your custom additions

I think fixing this properly requires adding a field to `InterpretOptions` to allow for a custom normalizer

**Comment by statusfailed** [comment]
Beautiful, works perfectly. I updated my branch on double-dhall to include your fix.

Thanks very much!
