### ISSUE TITLE
Use standard de Bruijn indices for type checking and normalisation?

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-lang#167]
The standard uses a fairly unique approach to scoping/name binding. It's *kind of* de Bruijn, because the `@n` notation gives you some counter of binders to step over, but it's also *kind of* a named representation, because you do have to keep track of names. However, this actually comes out to be a really complicated system to actually work with formally. I wonder if this de Bruijn-like indexing is really a parser detail, and not something the semantics are concerned with. That is, one could imagine parsing directly into de Bruijn indices and then doing type checking etc on that. The Haskell stuff can stay the same - it's semantically equivalent.

**Comment by ocharles** [comment]
I wonder now if this choice was intentional as you want to be able to print out of something useful if the normal form of an expression contains variable names (and thus you want to preserve the users original variable names). I still wonder though if that's sugar for outside the standard.

**Comment by Gabriel439** [comment]
Yeah, this choice was intentional.  The two main reasons for doing this were:

* I wanted the output of β-normalization to be human-readable
* I wanted there to be a way for users to be able to reference shadowed variables

**Comment by ocharles** [comment]
> I wanted there to be a way for users to be able to reference shadowed variables

This is a parsing problem though, not standardisation - so I don't think it has much input on whether the standard should use this binding structure. Right?

**Comment by Gabriel439** [comment]
There is still the requirement for the output of β-normalization to be human-readable

Also, even if the parser converted to De Bruijn indices, you'd still have to standardize how that worked so you're not simplifying the standard by doing so

**Comment by ocharles** [comment]
The simplification is that only the parser has to know about scoping issues, not the type checker and the normalisation routines. However, I do think I've got a representation now for well-scoped bindings in Agda, so this isn't a show stopper. I'll close this one for now.
