### ISSUE TITLE
Import whole environment as a List/Record

### ISSUE THREAD

**Issue by f-f** [dhall-lang/dhall-lang#169]
Use-case: currently we have a Jinja template (to generate a Kubernetes Deployment yaml) with this snippet:
```jinja
env:
  {%- for key,val in envars.items() %}
  - name: {{ key }}
    value: '{{ val }}'
  {%- endfor %}
```

To do this in Dhall, the best way I could think of would be to have a Dhall record in this form:
```haskell
{ "MY_VAR"    = env:MY_VAR
, "OTHER_VAR" = env:OTHER_VAR
, ...
}
```

Which feels a bit repetitive if you have 10+ variables and 10+ services (that will most likely have different vars).

EDIT: we realized that a record wouldn't be good, but a list of records would do.

After consulting with @Gabriel439 we considered that it would be good to add something to import the whole environment to a list (why not a record? because currently there's no way to iterate on key/values of a record).
For representing the key/values we would reuse the convention that `dhall-json` uses to render "generic records".

Something like:
```haskell
env as Text : List { mapKey : Text , mapValue : Text }
```

**Comment by Gabriel439** [comment]
@f-f: The main thing I would suggest is to shorten the syntax to this:

```haskell
env as List { mapKey : Text, mapValue : Text }
```

The main issue I can anticipate is that users might want a way to filter the set of environment variables returned by this and Dhall doesn't support any way to inspect `Text`.  For example, some environment variables might contain sensitive data that you don't want to pass through

**Comment by Gabriel439** [comment]
@f-f: Thinking about this more, I think we should go ahead with this and if users care about leaking sensitive information they can always go back to explicitly importing each environment variable one-at-a-time

**Comment by f-f** [comment]
@Gabriel439 Yeah I actually have the same issue myself, but I assume if I don't want to leak data I would just delete the envvars I don't want before running Dhall.

**Comment by f-f** [comment]
Re syntax:
Above I was just representing the type, the syntax I'd like would be even shorter: `env as List` - and it would return a `List { mapKey : Text , mapValue : Text }`

**Comment by Gabriel439** [comment]
Another I mentioned offline was that if you know ahead of time the set of environment variables that your program might need to pass through, you could do something like this:

```haskell
    let keyval = λ(mapKey : Text) → λ(mapValue : Text) → { mapKey = mapKey, mapValue = mapValue }

in  [ keyval "FOO" env:FOO as Text -- For required environment variables
    , keyval "BAR" env:BAR as Text
    , keyval "BAZ" ([env:BAZ as Text] : Optional Text ? [] : Optional Text)  -- Optional variables
    , ...
    ]
```

... using the operator for alternative imports suggested in https://github.com/dhall-lang/dhall-lang/issues/163

**Comment by aleator** [comment]
This is just friday evening fun, but how about:

```
let t = env as Type
in let e = env as List t
```

Which would generate a largish union type with labels representing the env keys (the `t`). Then the `e` would be a list of those. This list, in principle, could be iterated over (though the ergonomics of unions don't allow that) and could support a lookup function (though the ergonomics of unions don't allow that)

... It seems that iterating records and looking up lists is something you always end up wanting to do :)

**Comment by Gabriel439** [comment]
@aleator: Yeah, I'm starting to lean towards the idea of at least providing a way to convert a record to a list of key-value pairs if all the record fields are the same type.  That way you could start by importing a record, lookup the values you need using ordinary field access, and then convert the record to a list of key-value pairs later that you can iterate over.  Let's call that hypothetical function `toMap`

That wouldn't be enough to completely solve the original problem, though.  However, if we had an easy way to delete keys from a record then I think that would work.  Then you could delete the record fields before using `toMap` to convert the record to a list of key-value pairs to achieve the same effect.

In general, the design principle that I'm experimenting with is: any time the user needs something resembling `Text` equality we instead translate that requirement to some equivalent operation on record fields.

That still requires designing what the syntax for deleting fields would look like, though

**Comment by aleator** [comment]
I'm still thinking that unions should come to play somehow here. For example, you could drop the requirement that fields have the same type if you'd instead convert the record into list of unions. 

Then if the #164  idea of handlers would be slightly extended to provide a functionl as the wildcard you could extract the potentially unityped fields, or, even make them unityped if they're not.

**Comment by Gabriel439** [comment]
@aleator: The main issue with using a union to wrap the values is that the large handler you'd have to write to `merge` the alternatves would be as inconvenient as explicitly importing each environment variable you needed

**Comment by f-f** [comment]
My current solution for this is to:
1. Define a list of env vars I want to import, e.g.:
```haskell
-- list.dhall
[ "foo", "bar" ]
```
2. Define a templating function, to read this list in and generate more Dhall:
```haskell
-- template.dhall
let T = https://raw.githubusercontent.com/dhall-lang/Prelude/master/Text/package.dhall

in \(vars : List Text) ->

     let readVar = \(var : Text) -> "{ mapKey = \"${var}\", mapValue = env:${var} as Text}"

  in let varsStr = T.concatMapSep "\n, " Text readVar vars

  in T.concat [ "[ " , varsStr , "\n]\n" ]
```
3. Run the template: `dhall-to-text <<< "./template.dhall ./list.dhall" > envVars.dhall`
This will generate this file:
```haskell
-- envVars.dhall
[ { mapKey = "foo", mapValue = env:foo }
, { mapKey = "bar", mapValue = env:bar }
]
```
4. At this point I can just import the new file where I need

Not the most beautiful thing (as it's a two-step process), but covers my initial use-case.

**Comment by Nadrieril** [comment]
Triage: is there still a need for this ?

**Comment by f-f** [comment]
@Nadrieril: I solved my initial use-case with the two-step process described above, which works but it's clumsy. We don't have data on how many people have stumbled on this and just went with the workaround - I'm fine with it and judging from the activity other people might too. So I guess we can archive this?

**Comment by Gabriel439** [comment]
I will close this out, then, and we can reopen later if there's renewed interest.
