### ISSUE TITLE
Dhall interpreter - Continuing after Ctrl + D

### ISSUE THREAD

**Issue by psibi** [dhall-lang/dhall-lang#17]
Right now, the interpreter quits after Ctrl + D. It would be nice if it wouldn't quit and keep continuing.

**Comment by Gabriel439** [comment]
Just to clarify: do you mean that you would like something like a REPL, like this:

```
$ dhall-repl
>>> +2 * +2
Natural

+4
>>> "ABC" ++ "DEF"
Text

"ABCDEF"
>>>
```

The reason that the `dhall` executable terminates on `Ctrl+D` is because it reads all of standard input as a single Dhall expression and `Ctrl-D` signals the end of standard input

**Comment by psibi** [comment]
Ah, right. I meant a REPL like experience.

**Comment by Gabriel439** [comment]
Are there any other features that you expect besides the ability to type one Dhall expression per REPL prompt?

**Comment by psibi** [comment]
No, but I hope I can use previously defined `let` expressions in the `REPL`.
```
$ dhall-repl
>>> let x = +3
>>> +3 + x
Natural

+6
```

Not entirely necessary, but having a `:t` would be a nice addition:

```
>>> :t "hello"
Text
```

**Comment by Gabriel439** [comment]
Does it need to use `let`?  We could probably simplify it to just:

```
>>> x = +3
```

Also, if the interpreter provides a `:type` utility, would it need to output the type when evaluating expressions?  In other words, how about:

```
>>> +3 + x
+6
>>> :type +3 + x
Natural
```

The other thing I might suggest is changing the way to query a type to use a question mark at the end:

```
>>> +3 + x ?
Natural
```

... mainly because it's easier for beginners (who don't know `emacs` key-bindings like `Ctrl-A`) to add or remove question marks at the end of a query than to add or remove `:type` at the beginning

**Comment by psibi** [comment]
> Does it need to use let? 

Yeah, you're right. It doesn't need to have `let`. I guess that's just my habit coming from the Haskell world and even recent version of Haskell's ghci allow without using `let`.

> Also, if the interpreter provides a :type utility, would it need to output the type when evaluating expressions? In other words, how about:

>
```
>>> +3 + x
+6
>>> :type +3 + x
Natural
```

Yes, this is what exactly I had in my mind. But I think we can follow a idris like thing here:

```
>>> +3
+3 : Natural
>>> :t +3 + x
+6 : Natural
>>> :t (+)
(+) : Natural -> Natural -> Natural
```

> The other thing I might suggest is changing the way to query a type to use a question mark

Not sure about this one. I prefer having `:type` or `:t`. Is there any repl which supports `?` operator for quering type. Probably you can add this as an optional one, but I would still like to have `:type` for querying type information.

**Comment by Gabriel439** [comment]
The other option is that we can just always display the type and expression in the same format that the `dhall` executable already does, i.e.:

```haskell
>>> +3 + x
Natural

6
>>> -- I'm not sure if we should output anything for `let` bindings
>>> -- However, for now I'll assume that we do:
>>> replicate = http://prelude.dhall-lang.com/List/replicate
∀(n : Natural) → ∀(a : Type) → ∀(x : a) → List a

λ(n : Natural) → λ(a : Type) → λ(x : a) → List/build a (λ(list : Type) → λ(cons : a → list → list) → Natural/fold n list (cons x))
>>> replicate +3
∀(a : Type) → ∀(x : a) → List a

λ(a : Type) → λ(x : a) → [x, x, x] : List a
>>> replicate +3 Integer 2
List Integer

[2, 2, 2]
```

... that way the user doesn't have to explicitly specify which one they want

Usually the reason that a REPL like `ghci` has a separate `:type` command is because some expressions can't be evaluated or `Show`n (such as functions missing arguments), but in Dhall, that's not an issue because any well-typed expression can be normalized and displayed.  So it seems like we can always show the type and normal form instead of requiring the user to pick which one they want

**Comment by Gabriel439** [comment]
Another idea I was thinking of was that we could also support a binding like this:

```haskell
>>> ./some/path = aDhallExpression
```

... and that will save `aDhallExpression` to that path (assuming that you have permission to do so, creating directories if necessary)

For example, you could imagine supporting environment variables in this way, too (mainly for testing other Dhall expressions that had environment variable references)

```haskell
>>> env:FOO = aDhallExpression -- Set environment variable `FOO`
```

**Comment by psibi** [comment]
Saving dhall expression to a path would be a cool thing to do and would let users prototype quickly.

> The other option is that we can just always display the type and expression in the same format that the dhall executable already does

To be honest, most of the time - I'm not that interested in the expression. I just want to see the types. Also the function `replicate`'s type looks much simpler than the expression shown below.

**Comment by ramirez7** [comment]
I've rigged up a repl-as-a-library in my `dhall-extensions` exploratory repository ([code here](https://github.com/ramirez7/dhall-extensions/blob/master/src/Dhall/Repl.hs#L116)). Right now, it works for vanilla Dhall, but you can also provide your own `Parser`/`Normalizer`/`Typer` and get a repl for your own custom Dhall for free.

Here's an example session (The lambda is my ghci prompt, `>>>` is the Dhall repl prompt). The error messages (not shown) are pretty rough, but it does print the normalized expression + its type which is nice. `:let` can be used to bind variables globally.

https://gist.github.com/ramirez7/5eecb76502bdf1ad01ae45f0d30c7099

**Comment by Gabriel439** [comment]
Closing as the Haskell implementation now provides a `dhall-repl` which supports the above features:

```
$ dhall-repl
⊢ 2 * 2

4

⊢ "ABC" ++ "DEF"

"ABCDEF"

⊢ :let x = 3

x : Natural

⊢ 3 + x

6

⊢ :type "hello"

Text

⊢ :save ./foo = 3 + x
⊢ ./foo

6
```
