### ISSUE TITLE
Is there a unit/null/void type?

### ISSUE THREAD

**Issue by mafm** [dhall-lang/dhall-lang#170]
I looked at the prelude, and options don't seem to be defined as a union with a unit/null/void case - at first glance it looked like it's a primitive?

I'd like to be able to use unions where some of the alternatives had no data associated with them.

Apologies in advance, if this is the wrong place to ask - (I did read the contributing doc.)

**Comment by f-f** [comment]
Yes `Option` is a primitive, and you can have `Nothing` as (note that you have to annotate the concrete type): `[] : Optional Text`.

If you need a Union you could do something like (as done [in the Union section](http://hackage.haskell.org/package/dhall-1.14.0/docs/Dhall-Tutorial.html#g:12) of the tutorial):
```haskell
< Empty : {} | Person : { name : Text, age : Natural } >
```

**Comment by mafm** [comment]
@f-f Thanks, overlooked that.
