### ISSUE TITLE
Example real-world configurations

### ISSUE THREAD

**Issue by Gabriel439** [dhall-lang/dhall-lang#189]
In a [HackerNews](https://news.ycombinator.com/item?id=17523840) thread about Dhall some people requested a large and worked example showing off a broad set of language features in a real-world context:

> is there a single example Dhall config file anywhere that has more than a couple feature examples? It's a lot easier to grok new stuff like this if there's just one big example to look at to get an idea of what it does rather than having to navigate tons of granular documentation (which is also great, though)

> Hmm I agree with OP though, and this cheatsheet still isn’t it for me. I need to see a real world example to be able to fully grok its practical use.

One possible way to do this is to have a section with example Kubernetes, Terraform, and (possibly) CloudFormation templates encoded in Dhall that people can begin from

**Comment by quasicomputational** [comment]
dhall-to-cabal is dogfooding itself, generating [`dhall-to-cabal.cabal`](https://github.com/dhall-lang/dhall-to-cabal/blob/master/dhall-to-cabal.cabal) from [`dhall-to-cabal.dhall`](https://github.com/dhall-lang/dhall-to-cabal/blob/master/dhall-to-cabal.dhall). There are also some examples in [the test suite](https://github.com/dhall-lang/dhall-to-cabal/tree/master/golden-tests/dhall-to-cabal): I thought that the way of handling conditionals was a 'wow' moment when I saw it first, and [`compiler-options-order.dhall`](https://github.com/dhall-lang/dhall-to-cabal/blob/master/golden-tests/dhall-to-cabal/compiler-options-order.dhall) produces [`compiler-options-order.cabal`](https://github.com/dhall-lang/dhall-to-cabal/blob/master/golden-tests/dhall-to-cabal/compiler-options-order.cabal) to demonstrate that.

**Comment by ocharles** [comment]
`nix-dhall` is also somewhat functional, generating Nix expressions from Dhall files. https://github.com/nix-dhall/packages/blob/master/Bash/4.4.dhall is building `bash-4.4`.

**Comment by f-f** [comment]
In the [dhall-kubernetes](https://github.com/dhall-lang/dhall-kubernetes) readme we have two examples which are basically taken out from our production codebase.

I also have an annotated version of them, in which I demonstrate various dhall features (e.g. importa, interpolazione, etc); it would make sense to add some of these annotations to the readme there.

**Comment by changlinli** [comment]
I would also note that it seems like a bunch of people just skip over the example in the README since it needs to be actively expanded. See [https://news.ycombinator.com/item?id=15186876](https://news.ycombinator.com/item?id=15186876) and [https://news.ycombinator.com/item?id=17525451](https://news.ycombinator.com/item?id=17525451) for examples. Not sure what to do about that (it might clutter up the README if you expanded it, maybe that's okay, dunno), but figured I'd put it out there.

**Comment by Gabriel439** [comment]
Yeah, I saw that discussion.  There are three coarse solutions I can think of off the top of my head:

* Leave the case study expanded out
* Move the case study to the Dhall Wiki and replace it with a single Dhall configuration file that shows off the main features (another thing suggested in that comments section)
* Replace the case study with an asciinema video showcasing the same thing so that it's more compact

**Comment by vsund** [comment]
> Leave the case study expanded out

To leave some comments here, I really enjoyed the case study and it did a _really_ good job in explaining what it is and why it's cool. Though it took me a few times to notice that it's there (as said [here](https://news.ycombinator.com/item?id=17525451)). This little spoiler in which the case study lives is really hard to find. Very sad for the sake of this good content :)

**Comment by Gabriel439** [comment]
Alright, then I'll just expand it out.  Pull request up here:

https://github.com/dhall-lang/dhall-lang/pull/206

**Comment by Gabriel439** [comment]
Take two:

* https://github.com/dhall-lang/dhall-lang/pull/207
