### ISSUE TITLE
Unable to install when following install instructions

### ISSUE THREAD

**Issue by mkrogh** [dhall-lang/dhall-lang#190]
The [wiki](https://github.com/dhall-lang/dhall-lang/wiki/Getting-started%3A-Generate-JSON-or-YAML) suggest you use the nix package manager, which I have installed. 

When I run the suggested install method `nix-env --install --attr dhall-json` I just get an error:
```
error: attribute 'dhall-json' in selection path 'dhall-json' not found
```
What am I missing? Do I need to checkout the git repo and run the install command there (if so I would suggest not using that as the recommended install method).

OS: Ubuntu 18.04

**Comment by Gabriel439** [comment]
@mkrogh: Does this work:

```bash
$ nix-env --install --attr dhall-json --file '<nixpkgs>'
```

**Comment by mkrogh** [comment]
Yep that works.

**Comment by Gabriel439** [comment]
Alright, I'll update the guide

**Comment by Gabriel439** [comment]
Alright, the guide is fixed, so I'll go ahead and mark this closed
