### ISSUE TITLE
Add cachix as Production user

### ISSUE THREAD

**Issue by domenkozar** [dhall-lang/dhall-lang#197]
https://github.com/cachix/cachix/blob/master/cachix/src/Cachix/Client/Config.hs

Server side is using dhall as well, but it's closed source at this moment.

**Comment by ocharles** [comment]
Could you provide the sentence you'd like added to https://github.com/dhall-lang/dhall-lang/wiki/Dhall-in-production ?

**Comment by domenkozar** [comment]
## [Cachix](https://github.com/cachix/cachix)

Uses `dhall-haskell` to persist user configuration between command line interface invocations.

**Comment by Gabriel439** [comment]
I just added it 🙂

**Comment by domenkozar** [comment]
Thanks! <3

**Comment by Gabriel439** [comment]
You're welcome!
