### ISSUE TITLE
Grammar ambiguity parsing `Integer/show +3`

### ISSUE THREAD

**Issue by f-f** [dhall-lang/dhall-lang#199]
According to the grammar the string `Integer/show +3` has two possible parses (there is actually 8, but the others are due to the known issue that reserved keywords might be parsed as vars):
- `NaturalPlus IntegerShow (NaturalLit 3)`
- `App IntegerShow (IntegerLit 3)` (this is the correct one)

(I can provide the parse trees if they help contextualize)

**Comment by Gabriel439** [comment]
A really simple solution would be to require whitespace after `+`.  That's the only solution I can think of short of either using a lexer with a longest-match rule or changing the syntax of positive integer literals

**Comment by f-f** [comment]
+1 on requiring whitespace after `+`. Currently I'm looking at the Haskell implementation to see why it parses it correctly even though the rules look like the ones in the standard

**Comment by Gabriel439** [comment]
The reason the Haskell implementation parses it correctly is because the parser doesn't parse all possible alternatives.  It is biased towards the first alternative that it successfully parses, and in this case it prefers parsing `+3` as an integer literal

**Comment by f-f** [comment]
This is valid also in the case of Instaparse, but I guess the "priority of descent" is different (it looks like it's depth-first)
