### ISSUE TITLE
Native integration with C/Rust: libdhall?

### ISSUE THREAD

**Issue by Profpatsch** [dhall-lang/dhall-lang#2]
https://github.com/abiggerhammer/hammer is a parser combinator library written in C with bindings to multiple languages (C++/Python/Ruby/Perl/Go/PHP/.NET).

Building the dhall parser in hammer might give a good starting point to support these languages?

**Comment by Profpatsch** [comment]
One pain point might be that hammer is made for binary parsing, so Unicode is not supported at all.

**Comment by Gabriel439** [comment]
I think an even more important first step is to just specify the language grammar using BNF or ABNF syntax (as part of standardizing the language) and then focus on porting to specific languages or libraries

**Comment by felix91gr** [comment]
Complementing what Gabriel has said, here is a good resource on BNFs and EBNFs: [What are they and how do they work](http://www.garshol.priv.no/download/text/bnf.html).

The good thing of such formal specifications are:

- Ambiguity is not a concern anymore: the language becomes 100% defined.
- There are automatic compiler generators, like YACC, which can parse BNF and give you a compiler for your grammar.

**Comment by Gabriel439** [comment]
First pass at full ABNF grammar for Dhall here: https://github.com/dhall-lang/dhall-lang/pull/14

**Comment by Gabriel439** [comment]
I completed the first version of the standardized grammar here:

https://github.com/dhall-lang/dhall-lang/blob/bbc74064b2625d9c7635c7bfd1a55cede6a229aa/standard/dhall.abnf

Also, I think the scope of this issue should change to instead porting Dhall to natively integrate with either C, C++, or Rust, since I assume that an implementation in one of those languages can (with some effort) be reused by other languages that can bind to C

**Comment by f-f** [comment]
I'll change the title of the issue to reflect the new scope

**Comment by Nadrieril** [comment]
https://github.com/Nadrieril/dhall-rust is now a thing. Does that close this issue ?

**Comment by Profpatsch** [comment]
Basically, since I expect most languages to get FFI for rust code sooner or later. And if not, we could expose it as a C library.
