### ISSUE TITLE
Wrong example of α-normalization?

### ISSUE THREAD

**Issue by f-f** [dhall-lang/dhall-lang#201]
In the [α-normalization section of the standard](https://github.com/dhall-lang/dhall-lang/blob/master/standard/semantics.md#%CE%B1-normalization) there is the following example:

> α-normalization renames all bound variables within an expression to use De Bruijn indices. For example, the following expression:
> ```
> λ(a : Type) → λ(b : Type) → λ(x : a) → λ(y : b) → x
> ```
> ... α-normalizes to:
> ```
> λ(_ : Type) → λ(_ : Type) → λ(_ : _@1) → λ(_ : _@1) → _@1
> ```

However, if I try to `alphaNormalize` the same expression with the Haskell implementation, I get the following result:
```haskell
> a <- inputExpr "λ(a : Type) → λ(b : Type) → λ(x : a) → λ(y : b) → x"
> a
Lam "a" (Const Type) (Lam "b" (Const Type) (Lam "x" (Var (V "a" 0)) (Lam "y" (Var (V "b" 0)) (Var (V "x" 0)))))
> Dhall.Core.alphaNormalize a
Lam "_" (Const Type) (Lam "_" (Const Type) (Lam "_" (Var (V "_" 0)) (Lam "_" (Var (V "_" 0)) (Var (V "_" 0)))))
```

which corresponds to:
```
λ(_ : Type) → λ(_ : Type) → λ(_ : _@0) → λ(_ : _@0) → _@0
```

**Comment by Gabriel439** [comment]
That looks like a bug in either the spec or the Haskell implementation.  I'll dig into this soon

**Comment by Gabriel439** [comment]
Looking at this more closely this is definitely a bug in the spec.  I will put up a change to fix this soon

**Comment by Gabriel439** [comment]
Fixes up here:

* https://github.com/dhall-lang/dhall-lang/pull/203
* https://github.com/dhall-lang/dhall-haskell/pull/524
