### ISSUE TITLE
Some canonicalized paths are collapsed

### ISSUE THREAD

**Issue by f-f** [dhall-lang/dhall-lang#215]
The standard describes how import paths should be canonicalized so that they are imported only once ([here](https://github.com/dhall-lang/dhall-lang/blob/master/standard/semantics.md#duplicate-imports)):

> Importing the same canonical path twice must always return the same result within a single run of the import resolution phase.

However, some paths are canonicalized to the same thing even if they are different. E.g. `./../foo/somefile` and `./../bar/somefile`:
```haskell
> canonicalize $ Directory [ "..", "foo" ]
Directory {components = []}
> canonicalize $ Directory [ "..", "bar" ]
Directory {components = []}
```

**Comment by quasicomputational** [comment]
I think you're getting tripped up by `Directory` accepting its components in reverse order. Your two examples aren't `./../foo` and `./../bar` but rather `./foo/..` and `./bar/..`, which are both evidently `.` (in the absence of symlink trickery).

**Comment by f-f** [comment]
@quasicomputational oh right thanks, now everything makes sense.

I think this fact of the directory components is not mentioned anywhere in the standard (or at least not in the "Imports" section)?
If it's so I'll put together a small PR for adding a note about it.

**Comment by Gabriel439** [comment]
@f-f: The standard does not (and should not) specify how an implementation internally represents a directory or path.  The Haskell implementation uses a linked list storing the components in reverse order for efficiency, but another implementation could in principle use a dynamic array or some other data structure.  The place where such a note belongs is in [the Haskell documentation for the `Directory` type](http://hackage.haskell.org/package/dhall-1.16.1/docs/Dhall-Core.html#t:Directory), but it's already there:

> Internal representation of a directory that stores the path components in reverse order
> 
> In other words, the directory `/foo/bar/baz` is encoded as `Directory { components = [ "baz", "bar", "foo" ] }`

**Comment by f-f** [comment]
@Gabriel439 oh right, I got tripped up again since the rules in the standard have the path components in the right order.  
All good thanks, I'll close this 👍
