### ISSUE TITLE
IPFS link in README should point to IPFS

### ISSUE THREAD

**Issue by ebkalderon** [dhall-lang/dhall-lang#236]
The IPFS mirror to the Dhall prelude provided in the `README` is pointing to http://prelude.dhall-lang.org, which redirects to the official location on GitHub. It should probably be changed to point to https://ipfs.io/ipfs/QmQ8w5PLcsNz56dMvRtq54vbuPe9cNnCCUXAQp6xLc6Ccx/Prelude/ instead.

**Comment by Gabriel439** [comment]
@ebkalderon: I will update the README to mention that GitHub is now the official source of the Prelude.  See: https://github.com/dhall-lang/dhall-lang/issues/162

The mention of IPFS is a stale reference from before the switch

**Comment by ebkalderon** [comment]
@Gabriel439 Thanks for clarifying the situation! I'm guessing the transition is fully over to GitHub and the IPFS node will not be updated anymore?

**Comment by Gabriel439** [comment]
@ebkalderon: That's correct.  The IPFS pin that I was previous hosting is already down and existing expressions are only still alive by virtue of people still using them and/or people pinning the expressions themselves
