### ISSUE TITLE
Discuss: Version α-normalization and β-normalization?

### ISSUE THREAD

**Issue by Gabriel439** [dhall-lang/dhall-lang#242]
I would like to propose versioning α-normalization and β-normalization using the same protocol version string that we use for encoding and decoding Dhall expressions.

# The problem

The motivation for this is to fix a bug I've found in the current support for pinning protocol versions.  To illustrate the problem, suppose that you use `dhall freeze` to pin the following expression using version 1.0 of the standard (which corresponds to protocol version string "1.0"):

```haskell
[] : Optional Natural
```

That will produce a frozen expression with some hash:

```haskell
[] : Optional Natural sha256:...
```

Now suppose that you upgrade to the Haskell interpreter implementing an upcoming version 2.0 of the standard (which currently corresponds to protocol version string "1.1").  Even if you supplied the `--protocol-version 1.0` command-line flag, the newer version of the interpreter would reject the import if it was not already cached.

The root cause is that β-normalization has changed, such that `[] : Optional Natural` previously normalized to itself under version 1.0 of the standard, whereas it now normalizes to `None Natural` under version 2.0 of the standard.  Even if you use the binary encoding logic for protocol version "1.0" the hash would still be disturbed due to changing the β-normalization algorithm.

More generally, fixing this properly miplies that we need to version any judgement involved in computing the semantic integrity check if we want to be able to reliably pin semantic integrity checks.  Currently the three judgments involved are:

* `encode` (already versioned)
* α-normalization (not yet versioned)
* β-normalization (not yet versioned)

# Sketch of the solution

In other words, the two judgements for α-normalization and β-normalization:

    t₀ ↦ t₁

    t₀ ⇥ t₁

... would now take a new argument for the protocol version string (and perhaps change to named judgments to accommodate the new argument):

    α-normalize(v, t₀) = t₁

    β-normalize(v, t₀) = t₁

For example:

    ; Some judgments would be version-specific, such as the behavior for `Optional` literals

    β-normalize("1.0", t₀) = t₁   β-normalize("1.0", T₀) = T₁
    ───────────────────────────────────────────────────────────────
    β-normalize("1.0", [ t₀ ] : Optional T₀) = [ t₁ ] : Optional T₁

    β-normalize("1.1", Some t) = e
    ──────────────────────────────────────────
    β-normalize("1.1", [ t ] : Optional T) = e

    ; Most other judgments would just pass through the version

    β-normalize(v, T₀) = T₁   β-normalize(v, { xs₀… }) = { xs₁… }
    ─────────────────────────────────────────────────────────────
    β-normalize(v, { x : T₀, xs₀… }) = { x : T₁, xs₁… }

# Other

This is not an existential crisis for the standard or the interpreter.  If we need to cut a new release of the standard or the Haskell interpreter we can temporarily drop support for `--protocol-version 1.0` and restore it later.  However, people are unlikely to ever use protocol version "1.0" again once it has been dropped unless they skipped a release; if we restored support for it would be mostly as a matter of principle.

However, I think I can draft up the proposed change to both the standard and the Haskell implementation fairly quickly if people don't object.

**Comment by f-f** [comment]
@Gabriel439 Would it be an acceptable solution to just use the version standard as the protocol version?

The tradeoff is that every time the standard gets a new version the hash changes, but we'd avoid this problem of the fractalization of features to version indipendently (which gets quite hairy quite quickly).

Or am I misunderstanding the problem entirely?

**Comment by Gabriel439** [comment]
@f-f: Note that these wouldn't be versioned independently.  What I'm proposing is that α-normalization and β-normalization and binary encoding would all three be versioned in lockstep using the same protocol version string.

The main issue with using the version for the entire standard as the protocol version is that you would have to break the semantic integrity check even for changes to the standard that didn't affect it (like changes to import resolution or changes to type checking).

**Comment by Gabriel439** [comment]
Some other possible variations on this:

* Don't ever version α-normalization since its behavior shouldn't change except to fix a bug
* Don't version α-normalization yet until its behavior actually changes

**Comment by Gabriel439** [comment]
@f-f: Thinking about this more, I think you're right and we should instead just version the standard as a whole and use that version for the protocol version string (which would just be called the "version string").

The reason why is that the more I though about this the more I realized that we wouldn't be able to limit the scope of this to just α-normalization and β-normalization.  For example, if the import resolution algorithm changed (i.e. we add support for `as JSON`, for example) then that would affect whether or not a import protected by a semantic integrity check would correctly resolve to its import-free form.  Similarly, we type-check the expression before αβ-normalizing the expression and any change to the type checker would also affect whether or not that would succeed.

So, instead, I think it makes more sense to use the version string for the standard like you suggested since once you version import resolution and type-checking into the equation you're basically versioning the entire standard.  It also simplifies things because then the standard only has to specify that an implementation has to do whatever it wants for this previous git tag.

However, that also implies that, given how far-reaching the changes would be in the Haskell implementation, we'd probably need to temporarily drop support for 1.0 for the upcoming release since I should cut a release soon and doing this properly requires a bit of time to carefully generalize the Haskell API to version the whole implementation.

**Comment by Gabriel439** [comment]
Alright, I have a proposal up here: https://github.com/dhall-lang/dhall-lang/pull/243
