### ISSUE TITLE
Hurkens' paradox?

### ISSUE THREAD

**Issue by f-f** [dhall-lang/dhall-lang#250]
We were testing further the new kind-polymorphism feature with @phadej, and it looks like we can construct a term of the empty (i.e. bottom) type `∀(any : Type) → any`.
It typechecks, but normalization doesn't seen to terminate on our machines (on the biggest box I could try this on I had to stop it after 50s and 16GB of allocated memory):

```bash
$ cat hurkens.dhall | dhall type
∀(any : Type) → any

$ cat hurkens.dhall | dhall normalize
^Cuser interrupt
>>> elapsed time 53s
```

This is the expression:

```haskell
-- Ported from https://github.com/agda/agda/blob/master/test/Succeed/Hurkens.agda
-- The agda version uses type-in-type, but it's enough to have what Dhall has (System U?)

    let bottom : Type = ∀(any : Type) → any

in  let not : Type → Type = λ(p : Type) → p → bottom

in  let pow = λ(X : Kind) → X → Type

in  let U = ∀(X : Kind) → (pow (pow X) → X) → pow (pow X)

in  let tau
        : pow (pow U) → U
        =   λ(t : pow (pow U))
          → λ(X : Kind)
          → λ(f : pow (pow X) → X)
          → λ(p : pow X)
          → t (λ(x : U) → p (f (x X f)))

in  let sigma : U → pow (pow U) = λ(s : U) → s U (λ(t : pow (pow U)) → tau t)

in  let Delta
        : pow U
        = λ(y : U) → not (∀(p : pow U) → sigma y p → p (tau (sigma y)))

in  let Omega : U = tau (λ(p : pow U) → ∀(x : U) → sigma x p → p x)

in  let Theta : Type = ∀(p : pow U) → (∀(x : U) → sigma x p → p x) → p Omega

in  let D : Type = ∀(p : pow U) → sigma Omega p → p (tau (sigma Omega))

in  let lem1
        : ∀(p : pow U) → (∀(x : U) → sigma x p → p x) → p Omega
        =   λ(p : pow U)
          → λ(t1 : ∀(x : U) → sigma x p → p x)
          → t1 Omega (λ(x : U) → t1 (tau (sigma x)))

in  let lem3 : D = λ(p : pow U) → lem1 (λ(y : U) → p (tau (sigma y)))

in  let lem2
        : not D
        = lem1
          Delta
          (   λ(x : U)
            → λ(H2 : sigma x Delta)
            → λ(H3 : ∀(p : pow U) → sigma x p → p (tau (sigma x)))
            → H3 Delta H2 (λ(pp : pow U) → H3 (λ(y : U) → pp (tau (sigma y))))
          )

in  let evidence : bottom = lem2 lem3

in  evidence
```

If this is actually not-terminating (and not just inefficient normalization - though it is a big problem also in that case), @phadej's concern in https://github.com/dhall-lang/dhall-haskell/pull/563#issuecomment-426474106 seems to be substantiated.  

According to [Hurkens' paper](https://github.com/scravy/types/blob/master/A%20Simplification%20of%20Girard's%20Paradox/hurkens95tlca.pdf) the root cause seems to be the addition of the rule `Sort ↝ Kind`, which constructs a `System U-` (while `Sort ↝ Type` is fine without the previous one, though the conjunction of the two gives us a `System U` - see paragraph 2.1 of the paper)

**Comment by Gabriel439** [comment]
Oh, interesting.  I never realized that `Sort ↝ Kind` was enough to introduce inconsistency.  So, judging by the paper it looks like we definitely need to delete the judgment for `Sort ↝ Kind`.

Note that this means that we also need to drop support for records of types of mixed kinds.  For example, in order to be able to project either field from following record:

```haskell
{ x = Bool, y = List }
```

... you would need to encode it as:

```haskell
  λ(result : Kind)
→ λ(makeRecord : ∀(x : Type) → ∀(y : Type → Type) → result)
→ makeRecord Bool List
```

... but that only type-checks if you allow the `Sort ↝ Kind` judgment since that is what powers kind-polymorphic functions that return a type.  So if we're going to lose support for that then we should perhaps revert the entire kind-polymorphism change, because that was the main motivation for the change in my eyes.

Similarly, one of the other motivators for the change was kind-polymorphic utilities, which would also be similarly rejected once we remove that judgment.  cc: @sellout

**Comment by sellout** [comment]
Thanks for the heads-up. I’m pretty offline for the next few days, so if this could wait a bit, that’d be great.

**Comment by brendanzab** [comment]
Have you investigated using McBride's universe shifting stuff? I don't think it has been formalised, sadly, but it seems to give a decent amount of expressiveness for little complexity. I've implemented it in Pikelet and it's also it's also used in RedTT:

- https://pigworker.wordpress.com/2015/01/09/universe-hierarchies/
- https://github.com/pikelet-lang/pikelet/issues/10
- https://github.com/pikelet-lang/pikelet/pull/125
- https://pikelet-lang.github.io/pikelet/language/universes.html#shifting-universes
- https://pikelet-lang.github.io/pikelet/appendix/theory.html#universe-shifting

**Comment by Gabriel439** [comment]
@brendanzab: My inclination is to play it cautious and simply revert for now, even if it means a deterioration in the user experience.

I mistakenly thought that adding kind polymorphism had been proven sound (quite the opposite, apparently! 🙂 ), and I don't want to try a different type system change until it is proven sound.  Even then I'd have to still have to see for myself how easy it is to implement and standardize.

The approach I'm revisiting for reducing import bloat without kind polymorphism is to allow records whose fields are all the same kind, but loosening the type-checking judgment so that they don't have to all be the kind `Type`.  In other words, all the fields of a given record could have kind `Type → Type`, for example.  Consequently, a package would require at most N + 1 imports to import everything, where N is the number of kinds of types that the package exports (and N is usually at most 2).  That can still be encoded in System Fω and doesn't require kind polymorphism.

**Comment by phadej** [comment]
@brendanzab dhall had impredicate `Type` from the very beginning. That's the feature of System F

**Comment by sellout** [comment]
@phadej This might be enough, but I can’t sit down with it at the moment. Could `rule Sort Type = Type` be retained? That would certainly be enough.

**Comment by brendanzab** [comment]
@phadej: Oh, my mistake! 'scuse my ignorance - looking at it, yes, the rule has not actually changed, other than it being more clear with a comment! 😅 🤦‍♂️

**Comment by phadej** [comment]
@sellout, maybe `rule Sort Type` is still ok. First I didn't change it, nothing broken then either. **We need more tests for that.**

---

Trying out Coq: with `impred.v` 

```coq
Inductive Truth : Prop := tt : Truth.
Inductive Unit : Set := unit : Unit.

(* Prop is impredicative *)
Definition works : Prop := forall (x : Type), Truth.

(* Set isn't *)
Definition doesnt : Set := forall (x : Set), Unit.
Definition doesntEither : Set := forall (x : Type), Unit.
```

```
% coqc impred.v 
File "./impred.v", line 8, characters 0-50:
Error:
The term "Set -> Unit" has type "Type" while it is expected to have type
 "Set".
% coqc -impredicative-set impred.v 
% echo $?
0
```

---

I found a promising slide:
![screenshot from 2018-10-23 17-02-02](https://user-images.githubusercontent.com/51087/47366027-7abf1c80-d6e5-11e8-9179-7472db43f2aa.png)

The *CC^omega is described in https://hal.inria.fr/hal-01445835/document. Figure 2 defines base system. Figure 3 contains an impredicative universe extension.

Luo's ECC (1989) is also similar.

![screenshot from 2018-10-23 17-20-24](https://user-images.githubusercontent.com/51087/47367253-020d8f80-d6e8-11e8-90a1-610c8998de6c.png)

from *Lectures on the Curry-Howard Isomorphism*. Curiously, the next section in the book describes the Girard's paradox in System U. (I don't own the book, only read as much as Google Books let me).

---

So we can *cut* CC^omega by using only "star, box_0, box_1" universes.
And forbidding *full* dependent types.
Similarly we had used only "star, box_0" universes, resulting in System F_omega.

```diff
diff --git a/src/Dhall/TypeCheck.hs b/src/Dhall/TypeCheck.hs
index 92fb449..20b5e48 100644
--- a/src/Dhall/TypeCheck.hs
+++ b/src/Dhall/TypeCheck.hs
@@ -59,10 +59,10 @@ axiom Sort = Left (TypeError Dhall.Context.empty (Const Sort) Untyped)
 
 rule :: Const -> Const -> Either () Const
 rule Type Type = return Type
-rule Kind Type = return Type
+rule Kind Type = return Type -- 'Type' is impredicative, bottom universe
 rule Kind Kind = return Kind
-rule Sort Type = return Type
-rule Sort Kind = return Kind
+rule Sort Type = return Type
+rule Sort Kind = return Sort  -- 'Kind' is predicative!
 rule Sort Sort = return Sort
 -- This forbids dependent types. If this ever changes, then the fast
 -- path in the Let case of typeWithA will become unsound.
```

or alternatively (adding Ord Const)

```diff
--- a/src/Dhall/TypeCheck.hs
+++ b/src/Dhall/TypeCheck.hs
@@ -58,15 +58,11 @@ axiom Kind = return Sort
 axiom Sort = Left (TypeError Dhall.Context.empty (Const Sort) Untyped)
 
 rule :: Const -> Const -> Either () Const
-rule Type Type = return Type
-rule Kind Type = return Type
-rule Kind Kind = return Kind
-rule Sort Type = return Type
-rule Sort Kind = return Kind
-rule Sort Sort = return Sort
--- This forbids dependent types. If this ever changes, then the fast
+-- This forbids "full" dependent types. If this ever changes, then the fast
 -- path in the Let case of typeWithA will become unsound.
-rule _    _    = Left ()
+rule i    j | i < j = Left ()           -- "bigger" things cannot depend on "smaller"
+rule _    Type      = return Type       -- Type is impredicative
+rule i    j         = return (max i j)
 
 {-| Type-check an expression and return the expression's type if type-checking
     succeeds or an error if type-checking fails
```

---

**Disclaimer** take all this with a grain of salt, I'm an amateur. I have only a M.Sc. (in electrical engineering ;)

**Comment by Gabriel439** [comment]
Yeah, I'm in favor of adopting the CCω system.  The two obvious things I can think of to add to the test suite are:

* The Hurkens' paradox (to verify that it does not type-check)
* The equivalent encoding of records of types of mixed kinds (to verify that it does type-check)

More generally, we should probably add the equivalent encodings of all language features to the test suite to ensure that they are sound

**Comment by sellout** [comment]
Thanks, @Gabriel439. Yeah, I’m totally on-board with CCω.

**Comment by Gabriel439** [comment]
@ocharles: I believe we can still have records of mixed levels.  My understanding is that in Agda the type of a record is an upper bound on the universe of things that can be stored in it.  So, if we were to follow Agda then you would have something like:

```haskell
{ x = True } : { x : Bool } : Type

{ x = Bool } : { x : Type } : Sort

{ x = True, y = Bool } : { x : Bool, y : Type } : Sort
```

**Comment by Nadrieril** [comment]
Don't you mean `{ x = Bool } : { x : Type } : Kind` ?

**Comment by Gabriel439** [comment]
@Nadrieril: Oops!  Yes, fixed

**Comment by ocharles** [comment]
That would be a very welcome change if true. Being able to distribute something with just one URL or develop in one file if significantly easier that multiple.

**Comment by phadej** [comment]
Typing merges will become a bit more involved (spec-wise), as you'd need to take a "maximum" of types. But it might result into simpler implementation, in fact.

The downside is that you

**Comment by Gabriel439** [comment]
@ocharles: I agree!  I just haven't gotten around to it, yet
