### ISSUE TITLE
Formatter converts unicode characters to unicode codepoints

### ISSUE THREAD

**Issue by eliezercabrera** [dhall-lang/dhall-lang#267]
For example, compare the following file:

    $ cat src/templates/default-bar.dhall
      λ(isActive : Bool)
    →   { barLeftEnd =
            [ "┨" ] : Optional Text
        , barRightEnd =
            [ "┠" ] : Optional Text
        , separator =
            [ "┃" ] : Optional Text
        , alignment =
              < ToTheLeft = {=} | ToTheRight : {} | Centered : {} >
            : ./Alignment.dhall
        , barWidth =
            [] : Optional Natural
        , barSegments =
            [ "index", "command", "path", "title" ]
        }
      : ./Bar.dhall

to itself passed through `dhall format`:

    $ cat src/templates/default-bar.dhall | dhall format
      λ(isActive : Bool)
    →   { barLeftEnd =
            [ "\u2528" ] : Optional Text
        , barRightEnd =
            [ "\u2520" ] : Optional Text
        , separator =
            [ "\u2503" ] : Optional Text
        , alignment =
              < ToTheLeft = {=} | ToTheRight : {} | Centered : {} >
            : ./Alignment.dhall
        , barWidth =
            [] : Optional Natural
        , barSegments =
            [ "index", "command", "path", "title" ]
        }
      : ./Bar.dhall

I'm writing a utility to format tmux panes. In essence, the goal of this tool is to make pretty and informative lines of text, describing the tmux pane they are associated with.

I want this tool to be highly configurable, so I chose to have the settings in dhall files.

I realize my use case is probably very niche, and maybe not really what dhall is meant for.

Changing unicode characters to unicode codepoints by default might make dhall incompatible with tools that don't understand unicode, and maybe it would break some people's system. If so, consider this a feature request for a simple command line option, e.g. `dhall format --keep-unicode`, instead of an issue.

I also found [this stackoverflow thread](
https://stackoverflow.com/questions/52970029/how-to-avoid-dhall-format-convert-natural-language-text-to-code-point) asking whether or not there was a way to solve this issue.

**Comment by Gabriel439** [comment]
@eliezercabrera: Actually, I think it's fine to have Dhall just preserve Unicode by default.  I will try to fix this soon
