### ISSUE TITLE
Accessing types inside record type

### ISSUE THREAD

**Issue by madjar** [dhall-lang/dhall-lang#268]
Hi there!

Is there a syntax to access types inside a record type? For example,
```
⊢ {x: Integer}.x
Integer
```

The use case is: I'm toying with dhall to generate some yaml config file, and I there are multiple dynamic records in the config. I ended up defining multiples types of the form
```
# Job.dhall
{ mapKey :
    Text
, mapValue :
    { group :
        Text
    , stages :
        List ./Stage.dhall
    }
}
```

And the function `let kv = \(T: Type) -> \(k: Text) -> \(v: T) -> {mapKey = k, mapValue = v}`
To avoid having to defined two different types for each of these types (one being the `Body`, and the other one being `{mapKey: Text, mapValue: Body}`, I would have like to call the `kv` function as `kv Job.mapValue "someThing" {...}`. Is it possible?

Thanks a lot!

**Comment by f-f** [comment]
@madjar this should work:

```haskell
⊢ { x = Integer }.x
Integer
```

(note the `=` instead of the `:`)

**Comment by Gabriel439** [comment]
@madjar: Note that the `kv` function you described is in the Prelude, so you can do:

```haskell
let kv = https://prelude.dhall-lang.org/JSON/keyValue

in  ...
```

Do you need to be able to project the type, though?  Couldn't you use Dhall's support for type synonyms to reuse the `Body` type within the larger type, like this:

```haskell
    let Body = { group : Text, stages : List ./Stage.dhall }

in  let LargerType = { mapKey : Text, mapValue : Body }

in  ...
```

**Comment by Gabriel439** [comment]
You're welcome! :slightly_smiling_face: 

Alright, then I'll go ahead and close this, then.
