### ISSUE TITLE
Question: Handling `merge` as reserved?

### ISSUE THREAD

**Issue by SupraSummus** [dhall-lang/dhall-lang#281]
This is purely a question.

Why `merge` expression has its own rules in the grammar? Can't it be handled by `reserved` rule?

Is it because of semantics? Interpretation as a reserved would probably mean that `merge` is a two argument function, can be partially applicated, etc.

**Comment by sellout** [comment]
I have a new version of the PR (and dhall-lang changes), just need to tidy up and push.

Then it can be partially applied (but the handler argument still needs to be applied directly).

**Comment by SupraSummus** [comment]
Ok, this is clear.

Do you plan to make `merge` a standalone function/reserved someday?

**Comment by Gabriel439** [comment]
@SupraSummus: I'm slightly against making it a standalone function since it's not valid in isolation (similar to why `Some` is not valid as a standalone function).  This is why I currently treat it as a keyword.  However, I'm not that strongly opposed.

**Comment by SupraSummus** [comment]
My two arguments for handling merge as reserved are
 * grammar would be more DRY
 * users could alias `merge` (`let m = merge in m handlers union`) - this adds some more freedom to constructing expressions, which is nice in my opinion

However I don't think these arguments are particularly strong. I'm going to close this issue now, as I got answer to my question. Thanks.
