### ISSUE TITLE
Question mark and "as" in README

### ISSUE THREAD

**Issue by koterpillar** [dhall-lang/dhall-lang#302]
The introduction in README contains this expression (shortened):

```
[ makeUser (env:USER as Text) ]
? ([] : List User)
```

However, neither the `as` nor the question mark operator (operator?) are mentioned in the Cheatsheet, ABNF or FAQ.

Found explanations for both of those while writing this issue:

* https://github.com/dhall-lang/dhall-lang/issues/261 (`as Text`)
* https://github.com/dhall-lang/dhall-lang/issues/163 (`?`)

I think _all_ the features should be included on some page in the docs so users can consult that when they encounter unfamiliar syntax.

**Comment by Gabriel439** [comment]
@koterpillar: I just added both to the cheatsheet.

The `?` operator is in the ABNF (See [here](https://github.com/dhall-lang/dhall-lang/blob/master/standard/dhall.abnf#L367)), but `as Text` support is one of the last features of the Haskell implementation that had not yet been standardized yet and I'll address that shortly

**Comment by Gabriel439** [comment]
Here is the matching change to the standard to fully standardize `as Text` support: https://github.com/dhall-lang/dhall-lang/pull/303

**Comment by koterpillar** [comment]
Thank you!

**Comment by Gabriel439** [comment]
@koterpillar: You're welcome! 🙂
