### ISSUE TITLE
Half-float encoding of Doubles

### ISSUE THREAD

**Issue by f-f** [dhall-lang/dhall-lang#310]
The standard instructs to encode doubles using the smallest representation available:

> Encode `Double` literals using the smallest available numeric representation.
when converting to and from their textual representation:
CBOR has 16-bit, 32-bit, and 64-bit IEEE 754 floating point representations.

However, the JVM apparently has no native support for half-precision (16 bit) floats, making working with them (and doing interop Dhall-Java) possibly cumbersome - e.g. one could decode them to 32-bit floats and then treat them normally (but then re-encoding them would change the representation) or keep them "wrapped" into some container to preserve the information about them being 16-bit, then making it harder to write generic code with them.

Would it make sense to up the lower bound to 32-bit?
Of course we'd need to still encode to 16-bit the "special values" like `+Inf`, `-Inf`, and `NaN`.
I guess I'm mostly worried about "binary compatibility", where two different implementation might output slightly different binary encodings (and changing the hash?) due to these "native" differencies

**Comment by Gabriel439** [comment]
@f-f: I'm fine dropping support for using half-precision floats.  I don't expect that they will come up that often in Dhall code that the space savings would matter.
