### ISSUE TITLE
Create Dhall language server

### ISSUE THREAD

**Issue by Gabriel439** [dhall-lang/dhall-lang#312]
The [language server](https://langserver.org/) project allows languages to build a server that implement the [language server protocol](https://microsoft.github.io/language-server-protocol/specification) and get widespread support for every editor that implements the language server client.  As a bonus, many languages have already library support for the language server protocol.  Language server implementations are not an all-or-nothing proposition.  You can implement subsets of functionality and gradually support more as time goes on.

Note that I'm opening this against the `dhall-lang` repository and not the `dhall-haskell` repository because this server might not necessarily be implemented in Haskell.

**Comment by jbmusso** [comment]
On syntax highlighting. As of today it looks like this isn't yet supported at the language server level but must be handled by clients. There's an ongoing pull request https://github.com/Microsoft/vscode-languageserver-node/pull/367
Related: https://github.com/Microsoft/language-server-protocol/issues/513

**Comment by PanAeon** [comment]
Hi, I'm interested in learning LSP protocol, and have some spare time at the moment. So if nobody is working on this at the moment I can pick it up.

**Comment by Gabriel439** [comment]
@PanAeon: Yeah, go for it!

**Comment by Profpatsch** [comment]
In the meantime, here’s a minimal flycheck plugin for emacs that kind of works: https://github.com/Profpatsch/dhall-flycheck

**Comment by PanAeon** [comment]
Hi, as soon as I said that "I have some spare time" suddenly it disappeared, as usual :) 
In principle, I've got something usable at this point:
![diagnostics](https://user-images.githubusercontent.com/686076/52813097-e9f3be80-3090-11e9-82bc-c976ce9c6b9b.gif)
I'm deliberately using https://github.com/alanz/haskell-lsp for the server part, as we both can get existing functionality from it and contribute back to the project.
At this point I want to clean-up the code, and add syntax highlighting before going "public".
For now I suggest we support only latest released version of the language, and add multi version support as the need arise.  Users would likely have to build/install a separate server executable for each version of dhall, which is a bit inconvinient in my opinion.

**Comment by Gabriel439** [comment]
@PanAeon: Very nice work!  I'm really impressed

I also think it's fine to only support the latest version of the language.  I expect newer versions to be reasonably backwards compatible with older versions, especially now that hashes are more stable.  The main exception is when we occasionally remove language features after a long deprecation cycle (such as the `constructors` keyword).

Whenever you are ready to release I can also help set up CI to automatically build downloadable executables that people can use.

**Comment by Profpatsch** [comment]
@PanAeon Do you handle caching imports in-memory? That’s the thing I stumbled over with `dhall-flycheck`, because some imports take half a second or more to be read, even from disk cache on an SSD.

**Comment by PanAeon** [comment]
@Profpatsch I'm not there yet. At this stage I just want to make sure that users will get diagnostic errors on file save, nothing will blow apart and users get more or less straitforward way to build/install the lsp server. I'll create an issue for the import caching, and add `dhall-flycheck` reference to it.

**Comment by Gabriel439** [comment]
@PanAeon: Right now I'm writing up a Google Summer of Code project idea (see: https://github.com/haskell-org/summer-of-haskell/issues/90) for a student to work on a Dhall language server, preferably building on what you have done so far.  Would you be interested in co-mentoring a student on this project with me?

**Comment by Gabriel439** [comment]
Here is the Google Summer of Code project sketch for reference: https://github.com/haskell-org/summer-of-haskell/pull/103

**Comment by Profpatsch** [comment]
@PanAeon I found a way to cache remote files in-memory, upgrading `dhall-flycheck` to something like a LSP light: https://github.com/Profpatsch/dhall-flycheck/commit/f7a06c1f7607deb2063eae7b670c9a7a789e96bc

Though I haven’t integrated it into the emacs source yet, `dhall-flycheck --forever` checks files and caches imports.

The support was already there, all I did was push an initial cache to `loadWith` and add some threading. This is the interesting part:

https://github.com/Profpatsch/dhall-flycheck/blob/f7a06c1f7607deb2063eae7b670c9a7a789e96bc/src/Dhall/Flycheck.hs#L222-L236

**Comment by PanAeon** [comment]
@Gabriel439 Well, I can provide a technical help for the student. I'm less confident in evaluating work, setting deadlines, etc...

**Comment by PanAeon** [comment]
Thank you @Profpatsch this is really good work!!! I think I'll add some timeout setting and/or command to flush remote caches. Also for local files from a same workspace cache invalidation should be quite straightforward.

**Comment by Gabriel439** [comment]
@PanAeon: Then I can go ahead and take care of mentoring the student.  All I need is some time to familiarize myself with the codebase before the project begins

**Comment by PanAeon** [comment]
@Gabriel439 I have pushed extension to the [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=panaeon.vscode-dhall-lsp-server).
Only diagnostics on file save is provided (although I think that 'errors as you type' would be an overkill at this moment). 
Right now users can build the server executable from source using stack (lts-13.0), instructions are provided. I think the next thing I'll do is set-up Travis CI. I plan uploading the executables to the Bintray. If you have a ready template for the `stack` on TravisCI that would be super useful.

**Comment by Gabriel439** [comment]
@PanAeon: Awesome!  Thank you so much for doing this 🙂

**Comment by Gabriel439** [comment]
@PanAeon: Would it be possible to merge https://github.com/PanAeon/dhall-lsp-server as a subproject of https://github.com/dhall-lang/dhall-haskell?  The main reasons I ask are:

* This would allow me to easily reuse the CI infrastructure from the `dhall-haskell` to create pre-built LSP executables for Linux/Windows/OS X (so that users don't have to build the project themselves from source)
* You'd get fixes to your project for free if I make any breaking changes to the `dhall` Haskell package because a successful build of your project would become a requirement for merging any change to the core package

**Comment by PanAeon** [comment]
Well, I think it's success, for me at least. :) I'll try to do this in the next couple of days.

**Comment by PanAeon** [comment]
This is the pull request https://github.com/dhall-lang/dhall-haskell/pull/843 I had to change resolver for Appveyor to `nightly-2018-12-17`, because of the bug of `ghc-8.6.3` on Windows.

**Comment by Gabriel439** [comment]
I'll mark this as closed by https://github.com/dhall-lang/dhall-haskell/pull/843

There will probably be more feature we could potentially add, but those can be tracked in follow-up tickets for more specific requests

@PanAeon: Thanks again for all your work on this! :slightly_smiling_face:
