### ISSUE TITLE
Type Equivalents 

### ISSUE THREAD

**Issue by Michael-Kateregga** [dhall-lang/dhall-lang#313]
Hello,

What would be the Dhall equivalent for a Haskell type:

   `data Person = Name | Email | Phone`

I tried:

   `  let Name   : Type = Text`
   `in let Email   : Type = Text`
   `in let Phone : Type = Text`
   `in Person = constructors < Name : Name | Email : Email | Phone : Phone >`

but this didn't match up in the `input` call when I tried to decode it in Haskell. I also didn't set `type Name = String, type Email = String, type Phone = String` in Haskell because I don't think it was necessary, I want to use the constructors as they are. However, I defined `data Person` (see above)  and `Type Person` for decoding the Dhall file using `input`

Any advise would be great!

**Comment by sellout** [comment]
```haskell
data Person = Name | Email | Phone
```
should be
```dhall
< Name : {} | Email : {} | Phone : {} >
```
in Dhall.

Each union alternative requires a type, but you can use unit (`{}`) if you want a simple enumeration.

You should get rid of `constructors` there, too – it’s a feature that’s going away, and doesn’t help you map your types in this case.

**Comment by sellout** [comment]
Oh, also I don’t know if that Dhall & Haskell will actually align using the Generic-based `Interpret` instances, but those two types _are_ morally equivalent.

**Comment by Michael-Kateregga** [comment]
> ```haskell
> data Person = Name | Email | Phone
> ```
> 
> should be
> 
> ```
> < Name : {} | Email : {} | Phone : {} >
> ```
> in Dhall.
> 
> Each union alternative requires a type, but you can use unit (`{}`) if you want a simple enumeration.
> 
> You should get rid of `constructors` there, too – it’s a feature that’s going away, and doesn’t help you map your types in this case.

@sellout The reason why I was using constructors is because I have a Haskell function that takes input:

` Person {name = Name`
              `, contact = [Email, Phone]}`

That input is what I am aiming to define in Dhall and decode in Haskell for that function.

**Comment by Michael-Kateregga** [comment]
@sellout Basically what I want is to have the following input to a Haskell function be defined in Dhall:

`
testData = Person { department  = "Tester"
                              , tag               = STAFF
                              , details          = [ Name    
                                                       , Email      
                                                       , Phone      
                                                       ] 
                              } 
`
where

`
data Tag = STAFF | EXECUTIVE 

data Details = Name | Email | Phone
`

**Comment by FintanH** [comment]
@Michael-Kateregga we can break this down from your code above.

So `Person` seems to be a record type in Haskell defined as
```haskell
data Person = Person
	{ department :: Text
	, tag :: Tag
	, details :: [Details]
	}
```

This can be translated to Dhall using its record type
```haskell
-- defined in Person.dhall
{ department : Text, tag : ./Tag.dhall, details : List (./Details.dhall) }
```

We can then define the sum types, i.e. `Tag` and `Details`. As you've seen before we do this using `< Foo : Type | Bar : Type >`. For your case there is no data in those constructors so we use the unit type or empty record:
```haskell
-- defined in Tag.dhall
< STAFF : {} | EXECUTIVE : {} >
```

```haskell
-- defined in Details.dhall
< Name : {} | Email : {} | Phone : {} >
```

Then to construct a `Person`, if you are on a latest cut of Dhall, you can do:
```haskell
let Person = ./Person.dhall
let Tag = ./Tag.dhall
let Details = ./Details.dhall
in { department = "Tester"
   , tag = Tag.Staff {=}
   , details = [ Details.Name {=}, Details.Email {=}, Details.Phone {=} ] 
   } : Person
```

**Comment by Michael-Kateregga** [comment]
> @Michael-Kateregga we can break this down from your code above.
> 
> So `Person` seems to be a record type in Haskell defined as
> 
> ```haskell
> data Person = Person
> 	{ department :: Text
> 	, tag :: Tag
> 	, details :: [Details]
> 	}
> ```
> 
> This can be translated to Dhall using its record type
> 
> ```haskell
> -- defined in Person.dhall
> { department : Text, tag : ./Tag.dhall, details : List (./Details.dhall) }
> ```
> 
> We can then define the sum types, i.e. `Tag` and `Details`. As you've seen before we do this using `< Foo : Type | Bar : Type >`. For your case there is no data in those constructors so we use the unit type or empty record:
> 
> ```haskell
> -- defined in Tag.dhall
> < STAFF : {} | EXECUTIVE : {} >
> ```
> 
> ```haskell
> -- defined in Details.dhall
> < Name : {} | Email : {} | Phone : {} >
> ```
> 
> Then to construct a `Person`, if you are on a latest cut of Dhall, you can do:
> 
> ```haskell
> let Person = ./Person.dhall
> let Tag = ./Tag.dhall
> let Details = ./Details.dhall
> in { department = "Tester"
>    , tag = Tag.Staff {=}
>    , details = [ Details.Name {=}, Details.Email {=}, Details.Phone {=} ] 
>    } : Person
> ```

@FintanH Thank you for this well detailed example but Errors such as `Tag.Staff`, `Details.Email` etc. not being records.

**Comment by Michael-Kateregga** [comment]
@FintanH  Thank you for this well detailed example but you will get `Errors` such as `Tag.Staff`, `Details.Email` etc. not being records.

**Comment by FintanH** [comment]
Cool, so you're probably on a previous version of Dhall. For future reference it's useful if you give the details of your setup so checking with `dhall version` to see what version you're on :)

```haskell
let Person = ./Person.dhall
in let Tag = constructors (./Tag.dhall)
in let Details = constructors (./Details.dhall)
in { department = "Tester"
   , tag = Tag.STAFF {=}
   , details = [ Details.Name {=}, Details.Email {=}, Details.Phone {=} ] 
   } : Person
```

Should fix those errors. The `constructors` keyword creates a record a function to construct your union type. So `constructors (./Tag.dhall)` will result in a record (roughly) with fields `{ STAFF : {} -> Tag, EXECUTIVE : {} -> Tag }`

**Comment by Michael-Kateregga** [comment]
@FintanH Thanks I'm using v. 1.15.1

**Comment by FintanH** [comment]
@Michael-Kateregga Can confirm the above works with 1.15.1 :)

**Comment by Michael-Kateregga** [comment]
@FintanH everything works just perfect!!!! My project is accomplished!!! Thank you!

**Comment by FintanH** [comment]
Great to hear! I'll close this issue :)

**Comment by Michael-Kateregga** [comment]
> Great to hear! I'll close this issue :)

@FintanH Hi Fintan, does it always have to be `{}`, suppose I have `Text` types as well, how will this behave?

**Comment by Michael-Kateregga** [comment]
> First what it would look like in Haskell:

@FintanH thank you, I thought as much!!
