### ISSUE TITLE
Add Mira Networks (http://www.miranetworks.net/) at https://github.com/dhall-lang/dhall-lang/wiki/Dhall-in-production

### ISSUE THREAD

**Issue by Michael-Kateregga** [dhall-lang/dhall-lang#317]
We use dhall-haskell to define our logs for parsing. The software generates a specific log parser in either Python, Haskell, Elm or Erlang.

**Comment by Gabriel439** [comment]
Awesome!  I just added the entry: https://github.com/dhall-lang/dhall-lang/wiki/Dhall-in-production

Thank you 🙂

**Comment by Michael-Kateregga** [comment]
> Awesome! I just added the entry: https://github.com/dhall-lang/dhall-lang/wiki/Dhall-in-production
> 
> Thank you

We still exploring the language, there is so much one could use dhall for!!!
