### ISSUE TITLE
Some parser failure cases are parsed by dhall haskell impl  

### ISSUE THREAD

**Issue by jneira** [dhall-lang/dhall-lang#318]
* I've tested all cases in https://github.com/dhall-lang/dhall-lang/tree/master/tests/parser/failure and some of them are parsed without error with the haskell impl (current master version and 1.9.1 release):
  -  annotation.dhall:  #290 
  - missingSpace.dhall: #294
  - spaceAfterListAppend.dhall: #288

It seems dhall-haskell-1.9.1 doesnt follow the spec 4.0.0 for those changes (all of them was merged with #287 before the release)

**Comment by f-f** [comment]
@jneira np! I believe in this case the Haskell implementation is not compliant, all the three failures you listed are correctly failing in `dhall-clj` ([e.g. latest master build log here, lines 223-228](https://ci.appveyor.com/project/f-f/dhall-clj/branch/master))

**Comment by Gabriel439** [comment]
Yeah, the Haskell implementation is not compliant here because fixing this requires significant changes to the parsing code.

**Comment by ocharles** [comment]
The three failures mentioned in the issue are all merged now - is this sufficient to close this issue?

**Comment by sjakobi** [comment]
Note that the Haskell implementation still doesn't correctly handle a few expected parse failures: https://github.com/dhall-lang/dhall-haskell/blob/4d0058b71d29d7de15fa5d75aa57d05e8ecc1e93/dhall/tests/Dhall/Test/Parser.hs#L57-L76

**Comment by ocharles** [comment]
Ah, thanks - sounds like it's still an open issue.

**Comment by sjakobi** [comment]
I now believe that this issue should be either be moved to `dhall-haskell` or simply closed – `dhall-haskell` is keeping track of its non-compliance fairly well by recording test failures as `expectedFailures`: https://github.com/dhall-lang/dhall-haskell/search?q=expectedFailures&type=Code

**Comment by Gabriel439** [comment]
Yeah, I think it's fine to close this.
