### ISSUE TITLE
dhall-lang.org defaults to http and does not upgrade to https

### ISSUE THREAD

**Issue by Profpatsch** [dhall-lang/dhall-lang#320]
The new website is set to unencrypted by default.

**Comment by ocharles** [comment]
If you're hosting with nginx via NixOS's stock modules, it's trivial to get HTTPS for free using Lets Encrypt.

**Comment by Gabriel439** [comment]
It is using Let's Encrypt.  It's just missing a redirect from the HTTP to HTTPS version

**Comment by ocharles** [comment]
`forceSSL = true` should be all you need there.

**Comment by Gabriel439** [comment]
Yeah, I'm just waiting until I get home so I can redeploy the change from my personal laptop
