### ISSUE TITLE
`env:MY_VAR as Text` expression cannot be assigned to `Optional Text` field

### ISSUE THREAD

**Issue by ktonga** [dhall-lang/dhall-lang#337]
I have an optional property (derived from a `Maybe` field in Haskell) like this:

```purescript
{ optionalProp : Optional Text }
```

And I want to optionally assign to it the value of an env var if it is present:

```purescript
{ optionalProp = env:MY_OPT_VAR as Text }
```

But I can't since if the variable is missing the loading of the config fails. Neither can I use `None` constructor together with `?` because types don't align.

Am I missing something?

**Comment by f-f** [comment]
@ktonga I believe wrapping your import with a `Some` would work?

```haskell
{ optionalProp = Some (env:MY_OPT_VAR as Text) ? None Text }
```

**Comment by ktonga** [comment]
I tried the old list syntax (i'm on a version where Some/None are not yet available), a bit verbose but it works.

Thanks.
