### ISSUE TITLE
Typo in Wiki page example code for "how to add a new built-in function"

### ISSUE THREAD

**Issue by statusfailed** [dhall-lang/dhall-lang#341]
The wiki page on [how to add a new built-in function](https://github.com/dhall-lang/dhall-lang/wiki/How-to-add-a-new-built-in-function) contains some example code.

However, compiling this code as-is gives me the following error:

    Main.hs:34:69: error:
        • Couldn't match type ‘Maybe (Expr s0 a0)’
                         with ‘Identity (Maybe (Expr s Dhall.TypeCheck.X))’
          Expected type: Expr s Dhall.TypeCheck.X
                         -> Identity (Maybe (Expr s Dhall.TypeCheck.X))
            Actual type: Expr s Dhall.TypeCheck.X -> Maybe (Expr s0 a0)
        • In the first argument of ‘ReifiedNormalizer’, namely ‘normalizer’
          In the second argument of ‘Lens.set’, namely
            ‘(ReifiedNormalizer normalizer)’
          In the first argument of ‘(.)’, namely
            ‘Lens.set Dhall.normalizer (ReifiedNormalizer normalizer)’
       |
    34 |                   Lens.set Dhall.normalizer      (ReifiedNormalizer normalizer)
       |                                                                     ^^^^^^^^^^

I got it to work by changing this:

    Lens.set Dhall.normalizer (ReifiedNormalizer normalizer)

To this:

    Lens.set Dhall.normalizer (ReifiedNormalizer $ Identity . normalizer)

and adding this import:

    import Data.Functor.Identity (Identity(..))

It seems to work fine after making these changes.

**Comment by Gabriel439** [comment]
@statusfailed: This is fixed now.  I made a similar change, which was to use `pure` instead of `Identity`
