### ISSUE TITLE
Normalizing `env:` imports

### ISSUE THREAD

**Issue by joneshf** [dhall-lang/dhall-lang#349]
I was writing an expression today (a simplified version):

```Dhall
{ api_key = env:API_KEY as Text }
```

When I went to freeze it, it froze the `env:` import, a la:

```sh
$ API_KEY=foo dhall freeze <<< '{ api_key = env:API_KEY as Text }'
{ api_key =
    env:API_KEY sha256:b2213295d564916f89a6a42455567c87c3f480fcd7a1c15e220f17d7169a790b as Text
}%
```

That freezes the value of `foo`. Looking at the semantics, that all seems right. Imports are resolved first, normalized, then frozen. In other words, I don't think there's any bug here.

My question is, what is the purpose of an `env:` import? Generally speaking, environment variables change. To some extent, they're expected to change. Is thinking about `env:` improts as we think about environment variables in other languages/tools/ecosystems (that they are knobs to change the behavior of a configuration/program) the wrong way to think about them in Dhall? Should there be another way to depend on environment variables akin to how we think of them in other languages/tools/ecosystems? I.e. something that doesn't require the normalization of `env:` imports? In my specific case, I converted to a function. But I'm wanting to understand the bigger picture.

**Comment by Gabriel439** [comment]
Thinking about this more, another reason I think users probably don't want to freeze environment variables and local paths is that:

* They are cheap to resolve (unlike remote imports), so they don't really benefit from caching

* They are already trusted (by necessity) so they don't benefit from the security of the integrity check

  If the user did not trust their filesystem or environment variables then they can't trust the `dhall` interpreter they are running

**Comment by Gabriel439** [comment]
Pull request up here: https://github.com/dhall-lang/dhall-haskell/pull/808

**Comment by Gabriel439** [comment]
Fixed by https://github.com/dhall-lang/dhall-haskell/pull/808
