### ISSUE TITLE
Wiki: typo in "built-in function" page

### ISSUE THREAD

**Issue by paulRbr** [dhall-lang/dhall-lang#350]
In the [`Optional/fold` function example](https://github.com/dhall-lang/dhall-lang/wiki/Built-in-types,-functions,-and-operators#example-30), the input parameter `Some ["ABC"]` is wrong. The expected type is `Optional Text`:

```
$ dhall <<< 'Optional/fold Text (Some ["ABC"]) Text (λ(t : Text) → t) ""'
```
should be replace by
```
$ dhall <<< 'Optional/fold Text (Some "ABC") Text (λ(t : Text) → t) ""'
```

**Comment by f-f** [comment]
@paulRbr thanks for reporting! 

Fixed in [this revision](https://github.com/dhall-lang/dhall-lang/wiki/Built-in-types,-functions,-and-operators/ccc265128f9de366f2c51e33f3ddd081c189c285), I'll close 😊

**Comment by paulRbr** [comment]
Perfect, thanks !
