### ISSUE TITLE
Escaping Interpolation in Multi-line strings doesn't work

### ISSUE THREAD

**Issue by tsutsarin** [dhall-lang/dhall-lang#352]
How to properly escape interpolation syntax `${foo}` in multi-line strings (those ensloced in double single-quotes `'' ''`)?

My use case is to template terraform hcl files. I know, that I can compile dhall to json files on which terraform can be invoked, but currently I'm experimenting with dhall, so using json instead of hcl is a no-go for me.

Example hcl file:
```
locals {
  instance_ids = "${concat(aws_instance.blue.*.id, aws_instance.green.*.id)}"
}
```
That I'm trying to convert to dhall text template like this:
```
''
locals {
  instance_ids = "\${concat(aws_instance.blue.*.id, aws_instance.green.*.id)}"
}
''
```

And it doesn't work:
```
$ dhall-to-text <<< './tf-example'
dhall-to-text: 
↳ ./tf-example

Error: Invalid input

./tf-example:3:47:
  |
3 |   instance_ids = "\${concat(aws_instance.blue.*.id, aws_instance.green.*.id)}"
  |                                               ^
unexpected '*'
expecting '/'

```

Info:
```
$ dhall-to-text version
1.0.15
```

P.S. I'm new to dhall-lang

**Comment by f-f** [comment]
@tsutsarin the multiline literals have a different escaping mechanism ([this is the relevant section of the standard about it](https://github.com/dhall-lang/dhall-lang/blob/master/standard/multiline.md#escaping)): they use `''` to escape things.

So your template should look like this:
```haskell
''
locals {
  instance_ids = "''${concat(aws_instance.blue.*.id, aws_instance.green.*.id)}"
}
''
```

And this is the result of `dhall-to-text`:
```bash
$ dhall-to-text <<< './tf-example'
locals {
  instance_ids = "${concat(aws_instance.blue.*.id, aws_instance.green.*.id)}"
}
```

**Comment by tsutsarin** [comment]
@f-f Thank, works as expected! Didn't about that page and standard docs (I supposed all info is on the wiki).
Closing.
