### ISSUE TITLE
Small library, worth linking in readme?

### ISSUE THREAD

**Issue by andrewchambers** [dhall-lang/dhall-lang#358]
I wrote this this library to configure my go servers via dhall. Rather than try to implement a dhall interpreter, I just run dhall-to-json. Is it worth linking from the main readme?

https://github.com/andrewchambers/go-dhallconfig

**Comment by Gabriel439** [comment]
@andrewchambers: Yep!  Any binding is worth mentioning in the `README`, even if it just wraps command-line utilities.  This helps people better understand what is the state of the art for each language

**Comment by Gabriel439** [comment]
I have a pull request up to mention `go-dhallconfig` here: https://github.com/dhall-lang/dhall-lang/pull/361
