### ISSUE TITLE
Load a file as a string.

### ISSUE THREAD

**Issue by andrewchambers** [dhall-lang/dhall-lang#360]
I have something like this:

```
sshPrivateKey = ./id_rsa;
```

where key.dhall contains a string literal with the key data. Of course, the problem with that, is the ssh key is no longer usable as an ssh key..

I propose something like:

```
sshPrivateKey = import-string /home/me/id_rsa
```
or as a function

```
sshPrivateKey = load-string "/home/me/id_rsa"
```

Sorry if this is already possible, I didn't see anything like this.

**Comment by Gabriel439** [comment]
@andrewchambers: You're in luck!  If you add `as Text` after an import it does exactly what you want. i.e.:

```haskell
sshPrivateKey = ./id_rsa as Text
```

**Comment by andrewchambers** [comment]
Dang, I missed that, thank you :).

**Comment by Gabriel439** [comment]
You're welcome! 🙂
