### ISSUE TITLE
Shift context judgement

### ISSUE THREAD

**Issue by joneshf** [dhall-lang/dhall-lang#367]
I was reading through the semantics and ran into something that I need clarification on. In the [shift context][] section, there are two judgements:

```
─────────────────
↑(d, x, m, ε) = ε


↑(d, x, m, Γ₀) = Γ₁   ↑(d, x, m, T₀) = T₁
─────────────────────────────────────────
↑(d, x, m, (Γ₀, x : T₀)) = Γ₁, x : T₁
```

Should there also be a judgement for the case where the variable does not match?

```
↑(d, x, m, Γ₀) = Γ₁   ↑(d, x, m, T₀) = T₁
─────────────────────────────────────────
↑(d, x, m, (Γ₀, y : T₀)) = Γ₁, y : T₁
```

[shift context]: https://github.com/dhall-lang/dhall-lang/blob/c409b11bcd5e94497d3fb65a271822a874e4944d/standard/semantics.md#shift-context

**Comment by Gabriel439** [comment]
@joneshf: Oh, whoops.  That is a mistake on my part.  I'll change it to use `y` for the second variable so that the judgment doesn't imply that the two variables need to be the same

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-lang/pull/369
