### ISSUE TITLE
Comment on the tutorial

### ISSUE THREAD

**Issue by paraseba** [dhall-lang/dhall-lang#37]
I just went through the tutorial for the first time, haven't used Dhall "for real" yet. Following a few things I wish the tutorial included:

- A recommendation for how to order type parameters in functions of several arguments. For example something like "type parameters are usually introduced as late as possible in the list of arguments of a function, on the left of the first argument that needs the type".
- A comment on how Dhall restricts general recursion to guarantee termination. What can and cannot be done with Dhall functions?. For extra point, written in a style that most readers would understand, trying to avoid complex CS lingo.
- Example of implementing a non-trivial function. For example, how to write `replicate`, that would require introducing `build`, etc. 
- Brief explanation of why is Dhall a good configuration language. Why non turing complete (many people will interpret that as a negative thing initially)?  Why is having a "language" for config usefull? Why functions? And we can even have comments!

Hope this helps.

**Comment by Gabriel439** [comment]
Sorry for the delay.  Right now I'm focused primarily on standardizing the language and creating a website for Dhall that presents Dhall in several different ways, but I still have a few comments on your suggestions:

Regarding examples of non-trivial functions, I think the best way for users to learn that is to study the Prelude (which has `replicate`, for example)

For your last comment, I added a case study to the README here:

https://github.com/dhall-lang/dhall-lang

That case study motivates why you want a configuration language and shows off various features (like imports, comments, and types).  The case study doesn't yet cover the benefits of being non-Turing-complete, yet, but I plan on addressing that as part of expanded documentation for the website

**Comment by paraseba** [comment]
Well this is great! The case study is very clear and motivates most of Dhall design decisions. Thanks for adding it!

Feel free to close this issue.

**Comment by Gabriel439** [comment]
Alright :)
