### ISSUE TITLE
Grammar parses != in right-associative way

### ISSUE THREAD

**Issue by f-f** [dhall-lang/dhall-lang#373]
According to the standard [all operators are left-associative](https://github.com/dhall-lang/dhall-lang/blob/e7ec16929dc23d563a15601881c4665fc32073ff/standard/dhall.abnf#L89)

For example, the following expression:
```haskell
True == False != False
```
should parse in this way:
```haskell
(True == False) != False

-- Or in CBOR encoding:
-- [3 3 [3 2 true false] false]
```

However, the only parse the grammar allows in this case is the following:
```haskell
True == (False != False)

-- Or in CBOR encoding:
-- [3 2 true [3 3 false false]]
```

The issue should be [here](https://github.com/dhall-lang/dhall-lang/blob/e7ec16929dc23d563a15601881c4665fc32073ff/standard/dhall.abnf#L702), as an "equal expression" can contain "not-equal-expression"s, but not viceversa 🤔

**Comment by Gabriel439** [comment]
My understanding is that associativity only specifies how multiple occurrences of the same operator are parenthesized.  If you combine different operators then operator precedence governs how they are parenthesized and that takes precedence (pun intended) over associativity.

**Comment by f-f** [comment]
Oh right, makes sense. Then I guess the grammar is also the proper reference for operator precedence (as it limits the possible parses one can get, as in this case)

But then it looks like the parsing by the Haskell implementation not using the right operator precedence: in the [`parser/success/operators` test](https://github.com/dhall-lang/dhall-lang/blob/471037f6012edf92a8025397e699b93150984847/tests/parser/success/operatorsA.dhall) the `True == False != False` is parsed as `(True == False) != False`, which is not allowed by the grammar

**Comment by Gabriel439** [comment]
Oh, that's a bug in the Haskell implementation.  It has the precedence of the `!=` and `==` operators backwards:

https://github.com/dhall-lang/dhall-haskell/blob/8663bfe2967fbad07590a17e90abe60c4ab0c170/dhall/src/Dhall/Parser/Expression.hs#L175-L181

I can fix that

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/825
