### ISSUE TITLE
Tabs in multiline strings

### ISSUE THREAD

**Issue by singpolyma** [dhall-lang/dhall-lang#374]
''
    	stuff
    ''

Does not get the leading whitespace removed like it does when using expandtab style.

**Comment by f-f** [comment]
Hey @singpolyma!

Yes, the whitespace is correctly not removed in this case.  
As [the standard specifies here](https://github.com/dhall-lang/dhall-lang/blob/master/standard/multiline.md#indentation), there should be the same amount of whitespace also before the closing quotes for it to work.

E.g. in your case this is how it should look like:
```haskell
''
        stuff
        ''
```

And evaluating the above we get:

```haskell
''
stuff
''
```

**Comment by singpolyma** [comment]
@f-f oh perfect, thanks!

**Comment by f-f** [comment]
You're welcome! 🙂

**Comment by singpolyma** [comment]
@f-f hmm... so, it seems like if I have a blank line in my multiline string, then it does not work unless that line contain the leading whitespace itself, which is generally frowned upon by tools

**Comment by f-f** [comment]
Yeah this is a good point. Since this feature is directly inspired by Nix, I wonder how Nix handles this case?
