### ISSUE TITLE
Use binary encoding in parser tests

### ISSUE THREAD

**Issue by f-f** [dhall-lang/dhall-lang#384]
I noticed the parser tests in the Haskell implementation are not making use of the "b-side" (that is, the json-cbor-encoded representation), so I started implementing it.
However, in the process I noticed the json encoding has a series of issues for which there is a certain amount of "data loss".

As an example, this gives an incorrect result:
```bash
$ cat "./tests/parser/success/doubleB.json" | dhall decode --json
[ 1.1, -1.1, _@10, _@11, -1.1 ]
```

That is, the doubles `10.0` and `11.0` get are mistakenly considered anonymous variables. And this happens because the Aeson decoding of that file just returns `Data.Aeson.Number`s:
```haskell
Array [Number 4.0,Null,Number 1.1,Number -1.1,Number 10.0,Number 11.0,Number -1.1]
```

So then when `cborg-json` tries to understand if they are ints or floats, [it has to run `Data.Scientific.floatingOrInteger`](https://www.stackage.org/haddock/lts-13.9/cborg-json-0.2.1.0/src/Codec.CBOR.JSON.html#encodeValue), returning `Int`s for `10.0` and `11.0`.

This doesn't happen with the binary encoding, as it's not lossy as JSON is. So I propose we move the expectation side of the parser tests to be CBOR-binary encoded instead of JSON-CBOR-encoded.

[In the comment where I first proposed these parser tests](https://github.com/dhall-lang/dhall-haskell/issues/568#issuecomment-436139474) I mentioned encoding the files in JSON, as for humans it's easier to read than binary.
However, I think in this case "less readability" is a tradeoff worth doing for getting "more correct tests". I already introduced "Binary" tests in #376 anyways, so this would just be a consolidation of the two.

**Comment by Gabriel439** [comment]
@f-f: Sure, I think it's fine to switch to binary for the expected output.  One thing that might help is to provide a script in the repository that checks the expected outputs and if they differ then it renders the different CBOR expressions as JSON for ease of debugging.
