### ISSUE TITLE
Order of fields when CBOR-encoding

### ISSUE THREAD

**Issue by f-f** [dhall-lang/dhall-lang#387]
While implementing #384 across the Haskell and Clojure implementations I realized that when describing the encoding of Records/Unions in the [binary document](https://github.com/dhall-lang/dhall-lang/blob/master/standard/binary.md) we don't specify in which order the fields should be serialized.

Specifically the Haskell implementation serializes fields in the same order as it encounters them while parsing, and the Clojure one just in an unordered way. And this means that the hashes for the same expression might be different across implementations.

In practice this doesn't seem to be a big issue, as different implementations might be able to import code that is protected by hash between each other (I guess since the hash is coherent with the content of the bytestring? I did some tests and it looks like the two implementations are able to read each other's protected imports 🤔)

Though from the standard point of view we'd have the issue that the same expression could serialize to two different binary representations (and hashes) depending on the implementation, which is maybe undesiderable (at least it would mean that in #384 we'd have to compare "CBOR representations" instead of bytes, which might be more readable)

So we might want to specify something here, but at the same time I'm also concerned about the efficiency of the conversion to the binary representation (which should be as performant as possible IMO), as sorting might get expensive

**Comment by Gabriel439** [comment]
I'm in favor of sorting the keys because I believe the hashes should work across different implementations

**Comment by f-f** [comment]
Great! I'll put together the pull requests to the standard and the Haskell implementation then 👍

**Comment by f-f** [comment]
@Gabriel439 I think this is a breaking change, as it changes some hashes. Should we include it in #383?

**Comment by Gabriel439** [comment]
@f-f: Yes, I'm fine delaying the 6.0.0 release until this is merged

**Comment by Gabriel439** [comment]
Whoops, clicked the wrong comment button 🙂

**Comment by Gabriel439** [comment]
Thinking about this more, I think the technically correct thing to do is for serialization to preserve field order.  For the purpose of computing semantic integrity checks, this is equivalent to sorting them since β-normalization sorts fields.  However, if you were to serialize an expression outside of the context of a semantic integrity check then it should preserve whatever order the fields originally were in if the expression were not β-normalized.

**Comment by f-f** [comment]
@Gabriel439 wouldn't this add the implicit constraint that all implementations must preserve field ordering when parsing maps? (and I guess in general in their AST, as there's no need so far to change this representation through the phases)

If we'd start requiring "preserving an ordering" in the standard it could be preferable to preserve lexicographic ordering, since then we wouldn't have to specify things like sorting the fields in some way when beta-normalizing or serializing

My preference would be for not specifying the ordering - as I feel this is close to being an "implementation detail" - and just requiring the sorting of keys when serializing. In this way an implementation can choose to have their keys sorted, unsorted, ordered by insertion, etc.

**Comment by Gabriel439** [comment]
@f-f: Alright, we can leave the ordering pre-β-normalization unspecified
