### ISSUE TITLE
Existing Dhall files and grammar conflict on hex digit capitalization

### ISSUE THREAD

**Issue by jmitchell** [dhall-lang/dhall-lang#389]
# Problem

The grammar [currently defines `HEXDIG`](https://github.com/dhall-lang/dhall-lang/blob/48104eba51093b060b8528fff6922e71ce88424f/standard/dhall.abnf#L142) the same way as [RFC 5234, Appendix B.1](https://tools.ietf.org/html/rfc5234#appendix-B.1):

    HEXDIG = DIGIT / "A" / "B" / "C" / "D" / "E" / "F"

Notice lower-case letters `a-f` aren't permitted.

Existing Dhall files, including some in the parser tests, use lower-case `HEXDIG`s:

* `hash`es for `import-hashed` in [parenthesizeUsingA.dhall](https://github.com/dhall-lang/dhall-lang/blob/57ad822796af635cbd0acec82442be93f8ecd5be/tests/parser/success/parenthesizeUsingA.dhall)
* `h16`s for an `IPv6address` in [urlsA.dhall](https://github.com/dhall-lang/dhall-lang/blob/48104eba51093b060b8528fff6922e71ce88424f/tests/parser/success/urlsA.dhall#L8)

_NB: this different from what PR #388 addresses._

# Classification

Is this a bug in the grammar, tests, or both?

If the grammar is considered fine as-is, `dhall-haskell` and perhaps other parsers will need to be fixed. This would likely be a breaking change for many Dhall files in the wild too, so I'm leaning toward amending the grammar.

# Recommendation

After looking through all the references to `HEXDIG` in `dhall.abnf` I believe it's sensible to change `HEXDIG` to:

    HEXDIG = DIGIT / "A" / "B" / "C" / "D" / "E" / "F" / "a" / "b" / "c" / "d" / "e" / "f"

**Comment by Gabriel439** [comment]
@jmitchell: RFC 5234 specifies that ABNF strings are case-insensitive:

>    NOTE:
> 
>       ABNF strings are case insensitive and the character set for these
>       strings is US-ASCII.
> 
>    Hence:
> 
>          rulename = "abc"
> 
>    and:
> 
>          rulename = "aBc"
> 
>    will match "abc", "Abc", "aBc", "abC", "ABc", "aBC", "AbC", and
>    "ABC".
> 
>       To specify a rule that is case sensitive, specify the characters
>       individually.
> 
>    For example:
> 
>          rulename    =  %d97 %d98 %d99
> 
>    or
> 
>          rulename    =  %d97.98.99
> 
>    will match only the string that comprises only the lowercase
>    characters, abc.

... so `"A"` is actually equivalent to `%x41 / %x61`.  That means that the Dhall grammar's current `HEXDIG` rule doesn't need to be modified since it already matches lowercase hexadecimal digits

**Comment by jmitchell** [comment]
Oh right, my mistake. :)

If we wanted to make that more explicit we could use the `%i` prefix from [RFC 7405](https://tools.ietf.org/html/rfc7405#section-2.1). Strings without the prefix are still supported and implicitly mean the same thing, so it wouldn't necessarily be that helpful. I'll fix my ABNF parser generator.
