### ISSUE TITLE
[Bug] Attempting to use custom headers results in endless network requests

### ISSUE THREAD

**Issue by ari-becker** [dhall-lang/dhall-lang#396]
### Setup
Version: 1.20.1
`access-token.dhall`
```dhall
[
 { header = "Authorization", value = "token ${env:GITHUB_TOKEN as Text}" }
]
```
`imports.dhall`
```dhall
{
 Prelude = https://raw.githubusercontent.com/dhall-lang/dhall-lang/v5.0.0/Prelude/package.dhall using ./access-token.dhall
}
```
### Execution
invocation:
```bash
GITHUB_TOKEN=<censored> dhall <<< './imports.dhall'
```
Actual result: non-terminating loop with no output to stdout. Sending SIGINT eventually (not immediately) results in termination, with the following output to stdout:
```
↳ ./imports.dhall
  ↳ https://raw.githubusercontent.com/dhall-lang/dhall-lang/v5.0.0/Prelude/package.dhall using ./access-token.dhall
    ↳ https://raw.githubusercontent.com/dhall-lang/dhall-lang/v5.0.0/Prelude/access-token.dhall using ./access-token.dhall

↳ ./imports.dhall
  ↳ https://raw.githubusercontent.com/dhall-lang/dhall-lang/v5.0.0/Prelude/package.dhall using ./access-token.dhall
    ↳ https://raw.githubusercontent.com/dhall-lang/dhall-lang/v5.0.0/Prelude/access-token.dhall using ./access-token.dhall

↳ ./imports.dhall
  ↳ https://raw.githubusercontent.com/dhall-lang/dhall-lang/v5.0.0/Prelude/package.dhall using ./access-token.dhall
    ↳ https://raw.githubusercontent.com/dhall-lang/dhall-lang/v5.0.0/Prelude/access-token.dhall using ./access-token.dhall

<... repeats...>
```
 
Expected result: Successful resolution

### Additional info
* Invoking `curl -H 'Authorization: token <censored>` https://raw.githubusercontent.com/dhall-lang/dhall-lang/v5.0.0/Prelude/package.dhall` successfully retrieves `package.dhall` (i.e. network issues are unlikely).
* Dropping the `using ./access-token.dhall` results in expected successful resolution
* Copy-pasting the access token into `access-token.dhall` instead of using an environment variable results in the same issue
* Using a bad token (e.g. `GITHUB_TOKEN=bad dhall <<< './imports.dhall'`) results in expected `Error: Remote file not found`
* Using a bad remote path (e.g. `https://raw.githubusercontent.com/dhall-lang/dhall-lang/v5.0.0/non-existent`) results in expected `Error: Remote file not found`

This bug was originally encountered when trying to use the `using` functionality to access Dhall expressions that are in a private GitHub repository.

**Comment by f-f** [comment]
@Gabriel439 thanks for the detailed explanation!

Should we wait to release until we merge the fix for this?

**Comment by Gabriel439** [comment]
@f-f: No, I don't think we should block the impending release on this fix.  We can always release shortly afterwards if people really need us to cut a new release

**Comment by oded-dd** [comment]
+1

**Comment by oded-dd** [comment]
@Gabriel439 Any progress?

**Comment by Gabriel439** [comment]
@oded-dd: This is in my queue of things to standardize which I'm slowly working through.  If I had to estimate this I might get to this within the next month, but it can vary a lot depending on other factors.

**Comment by oded-dd** [comment]
@Gabriel439 Amazing. Thank you for your answer.

**Comment by oded-dd** [comment]
We use dhall as part of our day to day work heavily (basically we dhalify our entire product) but this bug block us. 
Any chance it can be prioritize? Thx

**Comment by Gabriel439** [comment]
@oded-dd: So what I think I can do is at least put up a pull request with a partial fix to unblock you until a proper fix is ready.  However, it still might take a few days because this is trickier to fix than I thought.

**Comment by Gabriel439** [comment]
Alright, I have a fix up here: https://github.com/dhall-lang/dhall-haskell/pull/967

... which requires a matching change to the standard to be reviewed and merged first:

https://github.com/dhall-lang/dhall-lang/pull/560

**Comment by ari-becker** [comment]
So great to see! Thanks so much for the fix - looking forward to putting this to good use.
