### ISSUE TITLE
Learn Dhall in Y minutes

### ISSUE THREAD

**Issue by jmitchell** [dhall-lang/dhall-lang#397]
I notice Dhall isn’t represented at [Learn X in Y minutes](https://learnxinyminutes.com). Is there interest in getting listed?

Contributions are accepted [here](https://github.com/adambard/learnxinyminutes-docs) (see [contributing guide](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)). Take a look at the [where X=YAML](https://learnxinyminutes.com/docs/yaml/) page for comparison.

The primary artifact we’d need is a commented Dhall file which illustrates key features in a natural progression. Maybe the [Cheatsheet](https://github.com/dhall-lang/dhall-lang/wiki/Cheatsheet) or  [Dhall.Tutorial](https://hackage.haskell.org/package/dhall-1.20.1/docs/Dhall-Tutorial.html) would be a good starting point for drafting that.

**Comment by Gabriel439** [comment]
Alright, I finally got around to this.  The pull request is up here: https://github.com/adambard/learnxinyminutes-docs/pull/3545

**Comment by Profpatsch** [comment]
Great introduction!

**Comment by Gabriel439** [comment]
Since the pull request is stagnant, I added the same tutorial to the Dhall wiki for now:

* [Learn Dhall in Y minutes](https://github.com/dhall-lang/dhall-lang/wiki/Learn-Dhall-in-Y-minutes)

**Comment by Gabriel439** [comment]
Alright, it's merged now, so I'll mark this fixed.
