### ISSUE TITLE
partially defined types (wilcard types / generic)

### ISSUE THREAD

**Issue by feliksik** [dhall-lang/dhall-lang#398]
I am looking for a way to define the type of a map, but have one field 'untyped', or or 'Any' type.
```
let TemplatedFile : Type = {
    destination : Text,
    data : Any
}
```

Is this possible?
If not, I have to drop the typing altogether (which is unfortunate), but I don't think I can even use functions then?

**Comment by jneira** [comment]
The short answer could be no, dhall needs all values typed and there is no `Any`. 

But you have some options to be "generic". The more similar to `Any` imo would be using `Text` itself, cause you can convert any type to Text. But dhall doesnt have equality for Text an [you cant do much with it](https://github.com/dhall-lang/dhall-lang/wiki/Built-in-types%2C-functions%2C-and-operators#text).

Another, more interesting option could be using [generics (parametric polymorphism](http://hackage.haskell.org/package/dhall-1.20.1/docs/Dhall-Tutorial.html#g:13)):
```
let template = λ(a : Type) → λ(x : a) → { destination = "foo", data = a}
let templTxt = template Text "text"
let templNat = template Natural 1
in .....
```
There would be more options (using [Unions](http://hackage.haskell.org/package/dhall-1.20.1/docs/Dhall-Tutorial.html#g:12) f.e.) but it would depend of your actual use case.

**Comment by feliksik** [comment]
Great, thanks a lot for the explanation! (you write `data = a` but that should be `data = x `). 

I still have to figure out how to do this with functions now receiving this generic type... thanks for the pointer to the docs, I actually hadn't found them yet.

**Comment by Gabriel439** [comment]
I will mark this closed since I believe the original question is answered.  Feel free to reopen if you have additional questions
