### ISSUE TITLE
Bug in binary.md for decoding imports

### ISSUE THREAD

**Issue by singpolyma** [dhall-lang/dhall-lang#402]
> decode([ 24, null, 0, 0, "authority" "path₀", "path₁", …, "file", "query", "fragment" ]) = http://authority/path₀/path₁/…/file?query#fragment

and similar, I believe should read:

> decode([ 24, null, 0, 0, null, "authority" "path₀", "path₁", …, "file", "query", "fragment" ]) = http://authority/path₀/path₁/…/file?query#fragment

Since when the headers are not present they should be `null` (as per the encoding section)

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-lang/pull/405
