### ISSUE TITLE
Why allow fragments in import URIs?

### ISSUE THREAD

**Issue by singpolyma** [dhall-lang/dhall-lang#403]
Why are fragments allowed in import URIs?  A fragment is never sent to the server with HTTP(S) (the only allowed schemes right now) and I haven't found anything saying that dhall some something locally with it...

**Comment by ocharles** [comment]
Why aren't fragments sent over HTTP(S)? Theres no reason to not allow fragments, servers can do whatever they want with them - the path part of HTTP is just a set of bytes, no?

**Comment by singpolyma** [comment]
> Why aren't fragments sent over HTTP(S)?

Because the spec(s) say(s) not to. F‎or example:

> ‎the fragment identifier is separated from the rest of the URI prior to a dereference, and thus the identifying information within the fragment itself is dereferenced solely by the user agent, regardless of the URI scheme.

https://tools.ietf.org/html/rfc3986#section-3.5

**Comment by Gabriel439** [comment]
@singpolyma: Sure, we can get rid of fragments from the grammar (and the binary format) if they have no effect on import resolution

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-lang/pull/406
