### ISSUE TITLE
[Help Request/Doc Clarification] Translating recursive optional types

### ISSUE THREAD

**Issue by ari-becker** [dhall-lang/dhall-lang#409]
Follow up from #370 since I don't want to turn that bug report into a help issue.

I've been trying to follow the guide, [How to translate recursive code to Dhall](https://github.com/dhall-lang/dhall-lang/wiki/How-to-translate-recursive-code-to-Dhall) as @Gabriel439 suggested, but I'm struggling with trying to adapt my code. I've since open-sourced the pre-recursive-adaptation code ([dhall-concourse](https://github.com/coralogix/dhall-concourse)), an example of which is the [Get step](https://github.com/coralogix/dhall-concourse/blob/master/types/Step.Get.dhall). The original domain model can be found in the [Concourse documentation](https://concourse-ci.org/steps.html).

The canonical example from the guide ( a `Person` "John" with children `Person`s "Mary" and "Jane") seems (to me) to only work because the rendering expression `everybody` produces a `List Text`.  Regardless of whether the recursion is two levels deep or a hundred levels deep, the result is still a `List Text` because the type is not dependent upon the length of the list. 

However, if the desire is to render a nested record, then it seems impossible to define a unified type of any rendered record since the type of the rendered record would depend upon the depth of the recursion - this being impossible since Dhall does not as of yet support dependent types.

To illustrate where the source of my frustration is coming from right now, consider the following simplified recursive type which I would like to translate into a non-recursive type:

```haskell
let Level = { name : Text, on_success : Optional Level }
``` 

with the idea being the ability to describe :
```haskell
{ name = "zero", on_success = Some { name = "one", on_success = None Level } }
```

My current naive scratch file of an approach is as follows:
```haskell
let type_template =
        λ(_param : { step : Type })
      → { name : Text, on_success : Optional _param.step }

let zeroth_level =
        { name = "zero", on_success = None {} }
      : type_template { step = {} }

let first_level =
        { name =
            "zero"
        , on_success =
            Some { name = "one", on_success = None {} }
        }
      : type_template { step = { name : Text, on_success : Optional {} } }

let union = < ZerothLevel : type_template { step = {} } | FirstLevel : type_template { step = { name : Text, on_success : Optional {} } } >

in  { zeroth_level = zeroth_level , first_level = first_level , unified = [ union.ZerothLevel zeroth_level , union.FirstLevel first_level ] }
```

The `union` bit being important because if I tried to render `unified = [ zeroth_level , first_level ]` I would get an error that `List` elements must be of the same type. 

This succeeds at rendering, but clearly, the `union` type is insufficient since it requires me to enumerate ahead of time the number of layers of recursion. At the same time, I need a union type if it would ever be possible to put the `Level`s into a `List` (to go back to my real use-case, in Concourse a `Job` is a record with a field `plan` which is of type `List Step`).

I'm not really sure where to go from here - does anybody have any suggestions?

**Comment by f-f** [comment]
I'm also interested in this case, as it's really similar to only recursive datatype we have in `dhall-kubernetes`, here's the issue that tracks it: https://github.com/dhall-lang/dhall-kubernetes/issues/47

**Comment by Profpatsch** [comment]
Recursion in dhall is mostly only possible by using recursion schemes from what I’ve found. There is a [library called `dada`](https://github.com/sellout/dada) that implements them for dhall, but it’s basically not documented at all, so I don’t want to point at it too hard.

I’ve had some success learning about them with this fantastic blog post series: https://blog.sumtypeofway.com/an-introduction-to-recursion-schemes/

**Comment by Nadrieril** [comment]
Your example is pretty much exactly the example from the doc, with `Optional` instead of `List`. If we follow that, we get:
```
let Level
    : Type
    =   ∀(Level : Type)
      → ∀(MakeLevel : { next_level : Optional Level, name : Text } → Level)
      → Level

let all_the_levels
    : Level → List Text
    = let concat = http://prelude.dhall-lang.org/List/concat
      let Optional/toList = http://prelude.dhall-lang.org/Optional/toList
      in    λ(x : Level)
          → x
            (List Text)
            (   λ(p : { next_level : Optional (List Text), name : Text })
              → [ p.name ] # concat Text (Optional/toList (List Text) p.next_level)
            )

let example
    : Level
    =   λ(Level : Type)
      → λ(MakeLevel : { next_level : Optional Level, name : Text } → Level)
      → MakeLevel
        { next_level =
            Some (MakeLevel {
                    next_level = None Level,
                    name = "one"
                    })
        , name = "zero"
        }
```

Now if you want you can put `Level`s in a list:
```
let example
    : List Level
    = [
        λ(Level : Type)
          → λ(MakeLevel : { next_level : Optional Level, name : Text } → Level)
          → MakeLevel {
            name = "zero",
            next_level = None Level
        },
        λ(Level : Type)
          → λ(MakeLevel : { next_level : Optional Level, name : Text } → Level)
          → MakeLevel {
            name = "zero",
            next_level = Some (MakeLevel {
                next_level = None Level,
                name = "one"
            })
        }
    ]
```

And map over them, or do other things:
```
let List/map = http://prelude.dhall-lang.org/List/map
in List/map Level (List Text) all_the_levels example
```

The important idea is that `Level` _is_ the complicated function type at the top, and you have to manipulate it as such. But you should be able to do most things you would have wanted to do with the recursive type.

Does that answer your question ? Does it make any sense ?

**Comment by Gabriel439** [comment]
To expand on @Nadrieril's answer: you can also split each of the types and constructors in separate files, too.  They don't all have to be defined in a single file "in one go".  It's a little bit trickier to implement, but from the user's standpoint there is no difference in how they consume the recursive type.

For example:

```haskell
-- ./Level.dhall

let Level
    : Type
    =   ∀(Level : Type)
      → ∀(MakeLevel : { on_success : Optional Level, name : Text } → Level)
      → Level

in  Level
```

```haskell
-- ./MakeLevel.dhall

let Level : Type = ./Level.dhall

let MakeLevel
    : { on_success : Optional Level, name : Text } → Level
    =   λ(x : { on_success : Optional Level, name : Text })
      → λ(Level : Type)
      → λ(MakeLevel : { on_success : Optional Level, name : Text } → Level)
      → let y =
              { name =
                  x.name
              , on_success =
                  Optional/fold
                  Level@1
                  x.on_success
                  (Optional Level)
                  (λ(l : Level@1) → Some (l Level MakeLevel))
                  (None Level)
              }
        
        in  MakeLevel y

in  MakeLevel
```

```haskell
-- ./example.dhall

let Level = ./Level.dhall

let MakeLevel = ./MakeLevel.dhall

let example
    : Level
    = MakeLevel
      { name =
          "zero"
      , on_success =
          Some (MakeLevel { name = "one", on_success = None Level })
      }

in  example
```

```haskell
$ dhall <<< './example.dhall' 
  λ(Level : Type)
→ λ(MakeLevel : { name : Text, on_success : Optional Level } → Level)
→ MakeLevel
  { name =
      "zero"
  , on_success =
      Some (MakeLevel { name = "one", on_success = None Level })
  }
```

**Comment by ari-becker** [comment]
> The important idea is that `Level` _is_ the complicated function type at the top, and you have to manipulate it as such. But you should be able to do most things you would have wanted to do with the recursive type.
> 
> Does that answer your question ? Does it make any sense ?

I mean, it's correctly interpreted, but it doesn't help me. Ultimately, I need something to render down to, if it were legal:

```haskell
[ { name = "zero", on_success = None Level }
  , { name = "zero", on_success = Some { name = "one", on_success = None Level } }
  , { name =
      "zero"
    , on_success =
      Some
    { name =
      "one"
      , on_success =
      Some { name = "two", on_success = None Level }
    }
  }
]
```
because that's the form that `dhall-to-yaml` requires to produce:
```yaml
- name: zero
- name: zero
  on_success:
    name: one
- name: zero
  on_success:
    name: one
    on_success:
      name: two
```

The `dhall-to-yaml` tool doesn't know what to do with:
```haskell
  λ(Level : Type)
→ λ(MakeLevel : { next_level : Optional Level, name : Text } → Level)
→ MakeLevel
  { next_level =
      Some (MakeLevel {
              next_level = None Level,
              name = "one"
              })
  , name = "zero"
  }
```
because it's a function.

**Comment by Nadrieril** [comment]
Ohh, I didn't get that was what you meant by "render to". Indeed, save from rendering it to Text yourself, I don't think dhall currently supports that...

**Comment by Gabriel439** [comment]
So I think this is still possible, by building on top of the solution I mentioned here:

* https://github.com/dhall-lang/dhall-lang/issues/336#issuecomment-451503204

While `dhall-to-json`/`dhall-to-yaml` can't transform arbitrary recursive types to JSON/YAML, I can set them up so that they can transform *that specific* `JSON` recursive type mentioned in that comment to JSON/YAML.  They can detect the present of that specific recursion idiom and convert it appropriately.

### Approach 1: Convert `Level` to `JSON` - Render using `dhall-to-yaml`

What that means for the Concourse integration is that all it would need to do is to convert from its internal representation to the `JSON` type, like this:

```haskell
let Level = ./Level.dhall

let JSON = https://raw.githubusercontent.com/dhall-lang/dhall-lang/5b5c770eccc0aa0f8fc44d7ddd85704afc46217a/Prelude/JSON/JSON

let J = https://raw.githubusercontent.com/dhall-lang/dhall-lang/5b5c770eccc0aa0f8fc44d7ddd85704afc46217a/Prelude/JSON/package.dhall

let toJSON : Level → JSON
     = λ(l : Level)
     → l
       JSON
       ( λ(x : { on_success : Optional JSON, name : Text })
       → J.object
           [ { mapKey = "on_success"
             , mapValue = Optional/fold JSON x.on_success JSON (λ(j : JSON) → j) J.null
             }
           , { mapKey = "name"
             , mapValue = J.string x.name
             }
           ]
       )

in  toJSON
```

```haskell
-- ./example.dhall

let Level = ./Level.dhall

let MakeLevel = ./MakeLevel.dhall

let toJSON = ./toJSON.dhall

let J = https://raw.githubusercontent.com/dhall-lang/dhall-lang/5b5c770eccc0aa0f8fc44d7ddd85704afc46217a/Prelude/JSON/package.dhall

let example
    : Level
    = MakeLevel
      { name =
          "zero"
      , on_success =
          Some (MakeLevel { name = "one", on_success = None Level })
      }

in  toJSON example
```

```haskell
$ dhall <<< './example.dhall'            
  λ(JSON : Type)
→ λ(string : Text → JSON)
→ λ(number : Double → JSON)
→ λ(object : List { mapKey : Text, mapValue : JSON } → JSON)
→ λ(array : List JSON → JSON)
→ λ(bool : Bool → JSON)
→ λ(null : JSON)
→ object
  [ { mapKey =
        "on_success"
    , mapValue =
        object
        [ { mapKey = "on_success", mapValue = null }
        , { mapKey = "name", mapValue = string "one" }
        ]
    }
  , { mapKey = "name", mapValue = string "zero" }
  ]
```

... and then `dhall-to-yaml` would recognize that shape and convert it to YAML (not yet implemented)

### Approach 2 - Convert `Level` to `JSON` - Render using `dhall-to-text`

If you don't care about inspecting the intermediate YAML, then you can actually render to JSON entirely within Dhall (since YAML is a superset of JSON), like this:

```haskell
-- ./example2.dhall

let Level = ./Level.dhall

let MakeLevel = ./MakeLevel.dhall

let toJSON = ./toJSON.dhall

let J = https://raw.githubusercontent.com/dhall-lang/dhall-lang/5b5c770eccc0aa0f8fc44d7ddd85704afc46217a/Prelude/JSON/package.dhall

let example
    : Level
    = MakeLevel
      { name =
          "zero"
      , on_success =
          Some (MakeLevel { name = "one", on_success = None Level })
      }

in  J.render (toJSON example)
```

```haskell
$ dhall-to-text <<< './example2.dhall' 
{ "on_success": { "on_success": null, "name": "one" }, "name": "zero" }
```

The advantage of this approach is that it works today and doesn't depend on `dhall-to-yaml` at all

### Approach 3 - Use `JSON` directly

You technically don't need to use `Level` as your internal representation.  You could use `JSON` directly as your intermediate representation (i.e. `Level = JSON`).  That might be simpler to implement if you don't tend to target any format other than JSON.

**Comment by ari-becker** [comment]
The second approach doesn't work so well for this project because the `Level` example is a small subset of a building block of the domain, and ultimately it means that anything using a recursive optional type would be "infected" by that type and could only be rendered to Text. Especially since `dhall-concourse` is intended to be a library project (which is also why I don't like the third approach - I'm trying to preserve type safety since `on_success` does not take an arbitrary JSON object), I'm very hesitant to take that approach.

So, I like the first approach the best, as it seems to allow for the preservation of the domain's types (before calling `toJSON`) while offering an escape hatch so that the end result can be rendered. Can we consider this a feature request, then?

**Comment by Gabriel439** [comment]
@ari-becker: Yes, I can implement the first approach in `dhall-to-yaml`.  It should be pretty straight-forward to do

**Comment by Gabriel439** [comment]
I finally got around to this and the fix to add support for arbitrary JSON is up here: https://github.com/dhall-lang/dhall-haskell/pull/1007
