### ISSUE TITLE
tests/normalization/success/multiline/interpolationB.dhall is wrong

### ISSUE THREAD

**Issue by singpolyma** [dhall-lang/dhall-lang#412]
`tests/normalization/success/multiline/interpolationB.dhall` currently says:

    "${Natural/show 1} foo\n bar\n"

But since these are the normalization tests, that should be fully normalized to:

    "1 foo\n bar\n"

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-lang/pull/415
