### ISSUE TITLE
tests/normalization/success/simple/listBuildB.dhall bug?

### ISSUE THREAD

**Issue by singpolyma** [dhall-lang/dhall-lang#413]
I believe https://github.com/dhall-lang/dhall-lang/blob/v6.0.0/tests/normalization/success/simple/listBuildB.dhall has a bug -- it describes a normalized result containing type annotations, where `semantics.md` says that type annotations are normalized by removing them.

However, perhaps these are not type annotations but rather one of the syntax edge cases that looks the same but is treated specially?  If so, then (and I will move the report there if this is the case) there is a bug in `dhall-haskell`.  The previous `dhall` binary I had would binary encode this file to binary in a way that did not decode to a type annotation, but the newest release of the `dhall` binary encodes the same file to include type annotations.

**Comment by Gabriel439** [comment]
@singpolyma: You're right that it's a bug in the test.  Type annotations are not required for non-empty lists, they are also not part of the syntax for non-empty lists, and normalization should remove any type annotations.

I believe the latest version of the Haskell implementation does not preserve that type annotation any longer (either when normalizing the expression or encoding it).

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-lang/pull/415
