### ISSUE TITLE
Some beta-normalization unit tests

### ISSUE THREAD

**Issue by singpolyma** [dhall-lang/dhall-lang#414]
The acceptance suite already here is great, but it's not *super* useful when still building a new implementation.  I just TDD'd my way through all of beta normalization, and have a language-agnostic test suite (using dhall binary format A and B files) here: https://git.sr.ht/~singpolyma/dhall-ruby/tree/master/test/normalization/beta -- tests should cover every beta normalization rule spelled out in semantics.md.  I'm happy to have this included in the `dhall-lang` repository if there is interest.

One thing to note is that, as unit tests, the expressions in these files are not super *complete*.  On many of them, the `dhall` binary complains loudly about the presence of free variables, etc.

Expressions are tested using as few other types of expressions as possible.  For example, the test that the arguments to `//` are normalized looks like this:  `(x // {=}) // (y // {=}) === x // y` which allows this test to be run on an implementation that has only implemented variables, empty records, and the operator being implemented.  This should allow a new implementation to TDD their way to beta normalization in whatever order they choose to implement in.

**Comment by Gabriel439** [comment]
@singpolyma: Yeah, feel free to simplify and/or expand the test suite.  I'd welcome upstreaming the work you linked to into this repository's test suite

**Comment by singpolyma** [comment]
https://github.com/dhall-lang/dhall-lang/pull/416
