### ISSUE TITLE
Equality of NaN

### ISSUE THREAD

**Issue by Nadrieril** [dhall-lang/dhall-lang#425]
As we know, NaN is a weird value, and in particular NaN != NaN. This has bitten me in the parser tests, because one of the tests includes a NaN value, and the test fails because NaN fails to be equal to itself.
In equality testing in dhall, e.g. in the `if b then a else a` simplification, I would guess we don't want this behaviour but rather we want something closer to bit-by-bit comparison.
So my question is: in propositional equality, how should we compare Doubles ? And should we remove the NaN from this test ?

**Comment by f-f** [comment]
@Nadrieril this is one of the reasons why the Parser tests [instruct to compare the binary representation of the parsed expression](https://github.com/dhall-lang/dhall-lang/tree/master/tests#running-parser-tests), as comparing `NaN` is not possible, but comparing bytes is

**Comment by Profpatsch** [comment]
Isn’t this one of the main reasons Rust has both `PartialOrd` and `Ord`?

**Comment by Nadrieril** [comment]
@f-f I see. But I wanted to test both, in order to test both the encoder and the decoder...

**Comment by f-f** [comment]
@Nadrieril would "roundtrip tests" suffice for that?
I.e. take bytes, decode, encode back, check for the same bytes

**Comment by Nadrieril** [comment]
It might hide some bugs but would be better than nothing. It's much more annoying to debug though. Since dhall explicitely avoids any ways to manipulate Doubles, I was hoping that we could simply decide to compare them naively for equality.

**Comment by Nadrieril** [comment]
@Profpatsch Indeed. I hadn't realized that the AST in dhall-rust didn't implement Eq, but that must be the reason why.

**Comment by Gabriel439** [comment]
So from the language point of view it doesn't have an effect because you can't have type-level `Double`s due to the absence of dependent types and you therefore can't trigger a judgmental equality check on them.  So there is always an option to leave `NaN` equality unspecified since it doesn't affect type-checking or normalization.

However, if we had to specify it I would go with defining equality on `Double`s to be the equality of their CBOR representations.  That would imply equality of `NaN`.

**Comment by Nadrieril** [comment]
I'm with you that we should do bitwise comparison.
I think it does affect normalization, in the `if x then y else y` simplification step. Currently, it's not specified whether `if x then NaN else NaN` should normalize to `NaN` or stay the same. If we do as you propose, it would normalize to `NaN`, which seems sensible.

**Comment by Gabriel439** [comment]
Oh yeah, that's right.  We can trigger the judgmental equality check due to the simplifications

**Comment by Nadrieril** [comment]
Using the CBOR encoding is a great idea; I made a PR to implement this suggestion.
