### ISSUE TITLE
Why is empty merge allowed?

### ISSUE THREAD

**Issue by singpolyma** [dhall-lang/dhall-lang#433]
It seems that a merge on an empty union is a bottom in the type system?  That is:

    \(x: <>) -> merge {} x : AnyTypeAtAll

This is "safe" because a value of type `<>` is impossible to actually construct, but is it *useful*?

**Comment by Nadrieril** [comment]
It can be useful to have a bottom type (and thus the absurd function you just constructed) when manipulating polymorphic functions or higher-kinded types. The Haskell community regularly finds interesting uses for it for example.

**Comment by FintanH** [comment]
But bottom isn't useful in a total programming language, is it? 😬

**Comment by ocharles** [comment]
It certainly is as it represents false. It is a very important type in
proof theory.

**Comment by Nadrieril** [comment]
It could be, for example you can't construct bottom, but you can construct a list of bottoms, and it's necessarily the empty list. More generally, you can use it with sum types to "disable" some of the branches. Rust uses that sometimes, even though you almost never construct bottoms in Rust

**Comment by Nadrieril** [comment]
I use that in dhall-rust actually: the type of a dhall expression is parameterized by a type of imports. When I parse an expression, this type parameter contains something that describes a URL. But when I do type checking, I only manipulate expressions where this type is the bottom type, which ensures that all imports have been resolved

**Comment by FintanH** [comment]
Oh I see, right! I can see what you meant by "absurd function" now too :)

**Comment by ocharles** [comment]
One more example of where such a type can be useful: [Elm's `Never` type](https://package.elm-lang.org/packages/elm/core/latest/Basics#Never).

**Comment by Gabriel439** [comment]
In my opinion, the most important reason to include `<>` is for uniformity in the language design, regardless of its utility.  To make an analogy, omitting `<>` from the language would be like implementing only `Semigroup` for a type that also supported a valid `Monoid` instance.

Besides the theoretical elegance of keeping it, there are practical reasons, too.  As others have noted:

* You can abstract over a value of type `<>` or the equivalent `forall (a : Type) → a` type to [type-check incomplete code](https://github.com/dhall-lang/dhall-lang/wiki/How-to-type-check-and-normalize-incomplete-code)

* You can use it to encode type-level `Not` as `λ(a : Type) → a → <>`, which is used for "proof by contradiction" (i.e. if the type `Not a` is inhabited then you have proven that the type `a` is not inhabited)

* You can use `<>` in exactly the same way that Haskell programmers uses `Void`/`absurd`

  For example, to make certain constructors of a sum type uninhabited in certain contexts, like how the `dhall` package uses the `X` type

... but for me the most important reason is the theoretical elegance: leaving it out of the language makes the language needlessly less uniform.
