### ISSUE TITLE
[Feature Request] New operator - forbid merge if result would have a different type from LHS

### ISSUE THREAD

**Issue by ari-becker** [dhall-lang/dhall-lang#436]
I'm finding a common pattern in my code, where for the purposes of illustration `RecordType` and `makeDefault` are included here, but in the code they are imported from elsewhere:
```
let RecordType =
      { field1 : Text, field2 : Text, overridable : Optional Natural }

let makeDefault =
        λ(_param : { field1 : Text, field2 : Text })
      → { field1 =
            _param.field1
        , field2 =
            _param.field2
        , overridable =
            None Natural
        } : RecordType

in      makeDefault { field1 = "foo", field2 = "bar" }
      ⫽ { overrideable = Some 10 }
    : RecordType
```

The issue is in the last two lines. I would like to override the field `overrideable`, however, I would like a guarantee from the type system that a) `overrideable` is a field that already exists on the left-hand-side of the operator, and that b) the value assigned to the `overrideable` field on the right-hand-side is of the same type as the value assigned to the `overrideable` field on the left-hand-side, raising a type error if this is not the case.

Currently, I work around the lack of such an operator by adding the `RecordType` annotation on the last line (to check that I have not changed the type in the second-to-last line), but when I need to add these annotations every time I merge records to ensure that I haven't accidentally changed the record type, it feels like boilerplate. Ideally, there would be a different merge operator which guarantees `(foo : Foo) newmergeoperator { bar = anything } : Foo` so that the extra annotation can be dropped entirely in favor of using the additional merge operator.

Additionally - I wonder if this would improve the interpreter's performance, since only the fields being merged need to be type-checked, instead of every field in the record being type-checked against the annotated type.

Relates to #382 and other work to improve the ergonomics of optional fields in records.

**Comment by Gabriel439** [comment]
Yes, I would be fine with both restricting that the overriden field exists and has the same type.

One thing that I was thinking about in response to this was whether or not this would interfere with the identity/associativity laws for the `//` operator.  In particular, I was concerned that the left identity law would no longer hold:

```
{=} // x = x
```

... and also the associativity law, but I won't go into that one.

However, I realized that it would still be fine after your proposed restriction because (A) this proposal doesn't change the normalization behavior (only type-checking behavior) and (B) the laws still hold if you view them as being conditional on the expression type-checking.  In other words, if `{=} // x` type-checks then `x` must be `{=}` therefore the equation is still true because `{=} // {=} = {=}`

**Comment by Gabriel439** [comment]
So I ran into some situations at work where requiring the overriden field to be present in the left record would have broken a lot of our code.

The specific use case we ran into was something like this:

```dhall
let default = { foo = None Text, bar = None Natural }

let x = default // { foo = Some "abc", baz = 1 }

…
```

In other words, we have some default record that we plan to both (A) override existing fields and (B) extend with new fields.  Currently we can do both with the `//` operator, but with that requirement we would need to do it with two separate operators:

```dhall
let default = { foo = None Text, bar = None Natural }

let x = default // { foo = Some "abc" } /\ { baz = 1 }

…
```

My bigger concern is the potential for large disruption because I imagine we're probably not the only ones using `//` in this way.

**Comment by Profpatsch** [comment]
What about a new operator, say `///`, which has the proposed semantics?

**Comment by Nadrieril** [comment]
I'm starting to worry about the confusion from having several similar but not identical operators around. I'd rather have some kind of Haskelly infix notation like ``default `overrideRecord` override``

**Comment by ari-becker** [comment]
@Gabriel439 @Profpatsch right, with this feature request I wasn't intending to ask to change the semantics of the `//` operator, rather to ask for a new operator (maybe `///`, maybe something else) which would provide the additional guarantees. I don't imagine changing the semantics of the `//` operator (for backwards compatibility, at least), although I do imagine that in many cases where `//` is currently used, replacing it with the new operator would both more clearly communicate intent as well as provide additional safety.

**Comment by Gabriel439** [comment]
One thing we should consider is if we should approach the syntax in a different way.  For example, what if you could assign to a field or a subset of fields, like this:

```dhall
record.x <- 1
record.{ x, y } <- { x = 0, y = 1 }
record.({ x : Natural, y : Natural }) <- { x = 0, y = 1 }
```

The idea is that if the intent is that the fields already exist within the record then perhaps use record projection syntax to specify which fields to override

The above is just a straw-man syntax, just to get the ideas flowing

**Comment by Nadrieril** [comment]
I like this idea ! A syntax like this could also subsume `//`: simply write `record <- override`.
I find that this syntax is also clearer and more discoverable than having both `//` and `///` as operators, though the imperative feel would create confusion

**Comment by ari-becker** [comment]
I like this idea, and it makes it easier to "turn on" type-checking when desired. It disambiguates between:

```dhall
let record = { x = 1, y = "hi" }
record.x <- 2 -- permitted, result: { x = 2 , y = "hi" }
record.x <- True -- permitted, result: { x = True, y = "hi" }
record.{x : Natural} <- 3 -- permitted, result: { x = 3 , y = "hi" }
record.{x : Natural} <- True -- forbidden, results in type error
```

The only question I have is, because of how record projection currently works, then `record.{x : Bool} <- True` would be a type error, because `x` is a `Natural` and not a `Bool`, right? It may confuse people who think that the type within the projection may correspond to the type of the value which they wish to use to overwrite and not the type of the value within the pre-existing record.

**Comment by singpolyma** [comment]
I'm very unsure of the benefit of this new operator at all -- it adds no new ability, and you can already type annotate the output of // if you want to be sure of what it is...

**Comment by Nadrieril** [comment]
Does the record completion operator `T::r` resolve this issue ?

**Comment by ari-becker** [comment]
@Nadrieril yeah, because ultimately the way that you make sure that the field isn't extraneous is by ensuring that it is in `T`.
I'll close this to help clean up - if somebody watching feels strongly about the `<-` syntax then they should open a new issue and link to this one.
