### ISSUE TITLE
Feature request: zip function

### ISSUE THREAD

**Issue by smatting** [dhall-lang/dhall-lang#441]
From what I can tell there is no built-in zip function. It would be of course very useful to have, but I suspect there might be good reason why it doesn't exist.

**Comment by Nadrieril** [comment]
There is already [`unzip`](https://prelude.dhall-lang.org/List/unzip) in the Prelude, I'm pretty sure we could add `zip` as well.

**Comment by Gabriel439** [comment]
The main reason I haven't added `zip` is because if you zip two lists of different lengths it can lead to elements being dropped (at least, if you implement it like the `zip` from the Haskell Prelude), which has sometimes been a cause of errors in my experience.  That's part of the reason I added `List/indexed` to try to support the most common use case of zipping a list with its numeric indices.

However, I'm not strongly opposed to `zip` but I wanted to make sure there was a compelling use case for it before adding it.  When initially drafting the built-ins I tried to be as conservative as possible because it's easier to add new built-ins than remove them.

**Comment by sellout** [comment]
I’ve just added `List/zip` to dada: https://raw.githubusercontent.com/sellout/dada/kind-polymorphism/List/zip

```
$ dhall <<< "./List/zip Natural Bool [1, 2, 3] [True, False]"
[ { _1 = 1, _2 = True }, { _1 = 2, _2 = False } ]

$ dhall <<< "./List/zip Natural Bool [1, 2, 3] [True, False, False, True]"
[ { _1 = 1, _2 = True }, { _1 = 2, _2 = False }, { _1 = 3, _2 = False } ]
```

**Comment by sellout** [comment]
(note that this is on a branch, not master … I’ll fix that soon)

**Comment by smatting** [comment]
In my use case I'm actually in need for the the function that yields consecutive pairs from a list (\xs -> zip xs (tail xs)).

**Comment by sellout** [comment]
```
$ dhall <<< "let list = [1, 2, 3, 4, 5, 6, 7]
             in  ./List/zip Natural Natural list (./List/tail Natural list)"
[ { _1 = 1, _2 = 2 }
, { _1 = 2, _2 = 3 }
, { _1 = 3, _2 = 4 }
, { _1 = 4, _2 = 5 }
, { _1 = 5, _2 = 6 }
, { _1 = 6, _2 = 7 }
]
```

**Comment by Gabriel439** [comment]
You can also implement this in one pass like this:

```haskell
let siblings =
        λ(a : Type)
      → λ(xs : List a)
      → let Pair = { left : a, right : a }
        
        let pairs =
              List/build
              Pair
              (   λ(list : Type)
                → λ(cons : Pair → list → list)
                → λ(nil : list)
                → let State = { previous : Optional a, pairs : list }
                  
                  let result =
                        List/fold
                        a
                        xs
                        State
                        (   λ(y : a)
                          → λ(ys : State)
                          → { previous =
                                Some y
                            , pairs =
                                Optional/fold
                                a
                                ys.previous
                                list
                                (   λ(p : a)
                                  → cons { left = y, right = p } ys.pairs
                                )
                                ys.pairs
                            }
                        )
                        { previous = None a, pairs = nil }
                  
                  in  result.pairs
              )
        
        in  pairs

in  siblings
```

```haskell
$ dhall <<< './siblings.dhall Natural [1, 2, 3, 4, 5]' 
[ { left = 1, right = 2 }
, { left = 2, right = 3 }
, { left = 3, right = 4 }
, { left = 4, right = 5 }
]
```

**Comment by smatting** [comment]
Thank you, Gabriel! Btw, studying your `siblings` functions finaly made me grok this whole `build`/`fold` paradigm.

**Comment by Gabriel439** [comment]
You're welcome! 🙂

**Comment by michelk** [comment]
Is it possible to enumerate a list like?

e.g.
```dhall
./List/zip Natural Bool [1 ..] ["a", "b", "c"]
```

**Comment by Gabriel439** [comment]
@michelk: The language has a `List/indexed` built-in that you can use for this purpose:

```dhall
⊢ List/indexed Text [ "a", "b", "c" ]

[ { index = 0, value = "a" }
, { index = 1, value = "b" }
, { index = 2, value = "c" }
]
```

**Comment by michelk** [comment]
Cool, thanks.

**Comment by Gabriel439** [comment]
@michelk: You're welcome! 🙂
