### ISSUE TITLE
Recursively merge records preferring the RHS when they conflict

### ISSUE THREAD

**Issue by alexhumphreys** [dhall-lang/dhall-lang#448]
Maybe I've missed something, but there's 

1. the ∧ operator which recursively merges record values
2. The ⫽ operator which non-recursively merges record values, preferring fields from the right record when they conflict

Is there anyway to recursively merge records, _and_ prefer values from the right hand side when they conflict? 

Something for the following situation basically:

```haskell
let foo =
  { bar =
    { baz =
      { thingIWantToKeep = 123
      , thingIWantToChange = False
      }
    }
  , other = "values should also be kept"
  }

-- This drops the `thingIWantToKeep` field
let updated = foo // { bar = { baz = { thingIWantToChange = True }}}

-- This drops everything except the most nested part
-- and I'd have to reassemble the record somehow
let updated2 = foo.bar.baz // { thingIWantToChange = True }

-- This causes a Field collision
-- let updated3 = foo /\ { bar = { baz = { thingIWantToChange = True }}}

in foo
```

Ran into this while trying to overwrite some values in the `initContainer` field of a kubernetes Deployment, so a pretty big nested data structure.

**Comment by alexhumphreys** [comment]
Oops, hadn't seen the issue #340. Don't think I actually need recursion to do what I'm doing, and I'm not sure recursion would make this problem any easier from a standard point of view, so I can close this as a duplicate of #340.

**Comment by f-f** [comment]
@alexhumphreys also I think that once we fix https://github.com/dhall-lang/dhall-kubernetes/issues/46 this should hopefully get less painful :) (it should happen soon, implementation is in progress)

**Comment by alexhumphreys** [comment]
@f-f That's good to hear! I'll keep an eye on that issue.
