### ISSUE TITLE
ABNF lost support for union alternatives without fields

### ISSUE THREAD

**Issue by singpolyma** [dhall-lang/dhall-lang#457]
https://github.com/dhall-lang/dhall-lang/commit/9b259d3867c214ced3b38de3b318ca61b3d0e61f#diff-08f598810aa82efee254d96a55b67fdcR681

vs

https://github.com/dhall-lang/dhall-lang/blob/master/standard/dhall.abnf#L649

I expect this is basically a merge error since they happened one right after the other.

/cc @Nadrieril

**Comment by Nadrieril** [comment]
Ah you're right, I made the mistake there: https://github.com/dhall-lang/dhall-lang/pull/442/commits/912c2b5e3b140cc37fc36e5065a48165e73c6d2e.
https://github.com/dhall-lang/dhall-lang/pull/455 happens to fix it though, so I think I'll just wait for it to be merged.
Thanks for catching my mistakes ! Hopefully you caught all of them now.
