### ISSUE TITLE
How should bignums be handled ?

### ISSUE THREAD

**Issue by Nadrieril** [dhall-lang/dhall-lang#461]
The standard does not specify a size limit for integers and naturals. [This seems to be the case for JSON as well](https://stackoverflow.com/a/13502497), so that seems reasonable.
However, I'm not sure what this implies:
- either every standard-compliant implementation must support arbitrary-sized numbers, in which case there we should add an appropriate passing test in the test suite;
- or we could decide on some upper-bound, and add a relevant faliing test;
- or this is deliberately left open to each implementation, in which case it would be helpful to document it somewhere.

**Comment by Gabriel439** [comment]
@Nadrieril: I'd go with "deliberately left open to each implementation"

**Comment by Nadrieril** [comment]
Should we document this somewhere then ? Or is it maybe not relevant for the standard ?

**Comment by Gabriel439** [comment]
Here's my attempt to document this: https://github.com/dhall-lang/dhall-lang/pull/474
