### ISSUE TITLE
Extend merge to work on Optional and Bool

### ISSUE THREAD

**Issue by Nadrieril** [dhall-lang/dhall-lang#463]
Follow up to https://github.com/dhall-lang/dhall-lang/issues/421.
`Optional` and `Bool` are special constructs in dhall, but they essentially behave like the sum types `< Some : T | None >` and `< False | True >`. This issue proposes to support using the `merge` operator on those types as if they were the corresponding sum types.

**Comment by sjakobi** [comment]
Would it be sufficient to standardize `merge` for `Bool` as syntactic sugar for `if-then-else`?

In the case of `Optional` this seems more tricky, since we'd need to find the involved types to produce the corresponding `Optional/fold`-expression.

**Comment by Nadrieril** [comment]
I was actually thinking that we could make if-then-else and Optional/fold syntactic sugar for merge

**Comment by sjakobi** [comment]
There are some special simplifications for if-then-else:

```
l ⇥ True   r ⇥ False   t₀ ⇥ t₁
──────────────────────────────
if t₀ then l else r ⇥ t₁
```

```
l₀ ≡ r   l₀ ⇥ l₁
────────────────────────
if t then l₀ else r ⇥ l₁
```

If we'd want to keep these rules for the corresponding merge-expressions, merge for Bools would be quite different from merges on other types.

So IMO it's better to desugar Bool-merges to if-then-else.

Desugaring Optional/fold to merge seems more attractive to me. Is this what you were thinking of, @Nadrieril?

```dhall
  λ(a : Type)
→ λ(x : Optional a)
→ λ(optional : Type)
→ λ(just : a → optional)
→ λ(nothing : optional)
→ merge { None = nothing, Some = just } x
```

I think we could eventually even get rid of the `Optional/fold` builtin then.

**Comment by Gabriel439** [comment]
One issue I can foresee is that permitting both `if`/`then`/`else` and `merge` would lead to a pretty substantial stylistic difference.  I would prefer to guide people to use `if`/`then`/`else` consistently across the ecosystem rather than encourage stylistic fragmentation

**Comment by sjakobi** [comment]
Personally, I'm mostly interested in merge for Optional – it would be just way simpler than the corresponding `Optional/fold`.

**Comment by Nadrieril** [comment]
> One issue I can foresee is that permitting both if/then/else and merge would lead to a pretty substantial stylistic difference.

Fair enough, though this difference already exists in most languages with pattern-matching: there is the option of using both `if` and `case`/`match`/... . In practice `if` is almost always preferred, so I wouldn't expect much stylistic fragmentation. Something similar could be said for `Some` vs `Optional/build` but I don't see that being an issue either.

> There are some special simplifications for if-then-else:

Ugh, I always found these simplifications way too ad-hoc, and now I know why ><. Anyhow, I'd be happy with `merge` only for Optional for now.

> Desugaring Optional/fold to merge seems more attractive to me. Is this what you were thinking of, @Nadrieril?

Yep, exactly !

**Comment by SiriusStarr** [comment]
I would also love to see `merge` for `Optional`.  I don't feel strongly one way or the other on it for `Bool`s.

**Comment by Gabriel439** [comment]
Yeah, I think `merge` working on `Optional` would improve the user-experience a lot, too (if only so that users don't need to specify the expected result type)

**Comment by sjakobi** [comment]
`merge` for `Optional`s has been standardized in #860 and I've opened https://github.com/dhall-lang/dhall-lang/issues/869 to discuss removing `Optional/fold`.

Is anyone still interested in discussing `merge` for `Bool`s (despite https://github.com/dhall-lang/dhall-lang/issues/463#issuecomment-563341537)? Otherwise I'd suggest we close this issue.
