### ISSUE TITLE
dhall-lang/tests/import/success/ fieldOrderA.dhall why?

### ISSUE THREAD

**Issue by singpolyma** [dhall-lang/dhall-lang#470]
This test checks that an imported record has its fields sorted... but I'm not sure why that should be the case.  The test instructions do not say to normalize, and we're not passing through binary format... am I missing a case where records are sorted?

**Comment by singpolyma** [comment]
Oh, I see, it's because they have the same hash so the test is actually checking that you are pulling from the cache properly.  Should probably add a comment to that effect

**Comment by singpolyma** [comment]
Hmm, no, I'm back to not being sure what this test is for.  If it was caching, the fields would be in the *other* order since the first encountered import is the "misordered" one

**Comment by Gabriel439** [comment]
This issue (https://github.com/dhall-lang/dhall-haskell/issues/548) and the corresponding changes to the standard (https://github.com/dhall-lang/dhall-lang/pull/223) and Haskell implementation (https://github.com/dhall-lang/dhall-haskell/pull/552) motivate why that test exists

**Comment by singpolyma** [comment]
Oh! It's because the standard assumes all caches will be in binary format, I see
