### ISSUE TITLE
Ambiguous test: whitespaceBuffet

### ISSUE THREAD

**Issue by f-f** [dhall-lang/dhall-lang#476]
I just caught up in `dhall-clj` with all the changes to the grammar, and everything is great except the [`whitespaceBuffet` test](https://github.com/dhall-lang/dhall-lang/blob/master/tests/parser/success/whitespaceBuffetA.dhall): it looks like there's some ambiguity somewhere and two parses are allowed (I can post the parse trees if needed):
- `Natural/even`
- `Natural/even 2`

..and only the second is correct.

I'm not sure if this is a bug (i.e. can be fixed), or if I just have to specify some lookahead somewhere?

/cc @Nadrieril @philandstuff @singpolyma how are you handling this?

**Comment by Nadrieril** [comment]
This parses correctly for me; the only place I need lookahead is in `simple_label` but I don't thing it would change anything here.
I'd be interested to see the parse tree, I'm not sure what's allowing the second parse. Are you able to reduce the test to a smaller example by any chance ?

**Comment by Nadrieril** [comment]
Is `{- -} 0 {- -}` ambiguous or is it an issue with the nesting of block comments ?

**Comment by f-f** [comment]
@Nadrieril this reproduces (note the space before the function name): 
```
 Natural/even {-  -} 2 {- -}
```

Parse trees:
- [`Natural/even`](https://gist.github.com/f-f/29576a9b559f32ef724121d2c48ad6c0#file-naturaleven-clj) (wrong)
- [`Natural/even 2`](https://gist.github.com/f-f/29576a9b559f32ef724121d2c48ad6c0#file-naturaleven2-clj) (right)

**Comment by singpolyma** [comment]
> the only place I need lookahead is in `simple_label` 

I also have lookahead for the nonreserved-identifier rule

**Comment by Nadrieril** [comment]
I see. This is indeed ambiguous since we don't disallow `{-` in the second alternative of `block-comment-chunk`. It should be solvable with negative lookahead, but I'm afraid this might not be the only place of ambiguity. The grammar says that a parser should ["prefer the first parse according to the ordering of alternatives"](https://github.com/dhall-lang/dhall-lang/blob/af74785a3fd8f7c5ae212af7557ef64b52407a5f/standard/dhall.abnf#L25-L27), would this be an option in your parser ?

**Comment by Nadrieril** [comment]
I _think_ something like
```
block-comment = "{-" block-comment-continue

block-comment-char =
      %x20-10FFFF
    / tab
    / end-of-line

block-comment-continue =
    "-}"
    / (
        block-comment block-comment-continue
        / !"{-" block-comment-char block-comment-continue
    )
```
should work

**Comment by f-f** [comment]
> The grammar says that a parser should "prefer the first parse according to the ordering of alternatives", would this be an option in your parser?

@Nadrieril that's the funny thing: if I remove the space at the beginning of the expression then I get the `App` parse first. Adding the space the two parses switch order and the wrong one becomes first.

**Comment by Nadrieril** [comment]
Oh that's very weird. I'm very confused why it would do that at all. And my parser doesn't do that on the same grammar, which is suprising. Do you understand why this initial space would change anything ? Looking at the grammar, it should be eaten by the first `whsp` of `complete-expression` so I don't see how it could influence the rest of the parse...

**Comment by f-f** [comment]
@Nadrieril I don't know, but it's not the first time it happens. I think it's just better to remove ambiguity altogether than try to investigate this thing, so I opened #482 with your suggestion (which works well)

**Comment by Nadrieril** [comment]
@f-f Fair enough :)
I expect you might encounter ambiguity in other places as well though. The one that comes to mind is string interpolation, where the interpolation can be parsed as text. You might want to add similar lookahead there.
