### ISSUE TITLE
Problem parsing let expressions with PEGs

### ISSUE THREAD

**Issue by philandstuff** [dhall-lang/dhall-lang#478]
I'm just updating dhall-golang to pull in the grammar changes from #442 and I had a problem where I couldn't parse `let x = y in z`.

What was happening is that in the rule

```
expression =
    ;...
    / 1*(let whsp1 nonreserved-label whsp [ ":" whsp1 expression whsp ] "=" whsp expression whsp) in whsp1 expression
```

the penultimate `expression` rule (which should just match `y`) was greedily matching `y in z` (as `(y in) z)`.  This left nothing for the `in` rule to match.

For the moment, I've put a negative lookahead to prevent my `identifier` rule from matching `in`, but I'm not sure this is the right solution.

**Comment by singpolyma** [comment]
> For the moment, I've put a negative lookahead to prevent my `identifier` rule from matching `in`, but I'm not sure this is the right solution.

Yes, this is documented in the ABNF on the simple-label rule with some suggested negative lookahead.‎

**Comment by f-f** [comment]
I can confirm that using the `simple-rule` with lookahead suggested in the grammar works well for me too.
I am also trying to use something like `nonreserved-label = !reserved label` (where the `reserved` rule contains `Bool`, `Natural/even`, etc), but it's not complete (I'll look at it with a fresh brain tomorrow). But I think adding another unused `reserved` rule to the grammar together with the lookahead suggestion for `nonreserved-label` would be nice.

Also @philandstuff I'd suggest pulling the latest master instead, there's a new `let-binding` rule that was quite helpful

**Comment by philandstuff** [comment]
Doh! I had implemented that simple-label rule, but a stray zero-or-more quantified (instead of one-or-more) meant that the keyword-prefixed simple labels also matched actual keywords. Thanks for help finding the problem.

**Comment by singpolyma** [comment]
> I am also trying to use something like `nonreserved-label = !reserved label` (where the `reserved` rule contains `Bool`, `Natural/even`, etc), but it's not complete (I'll look at it with a fresh brain tomorrow). But I think adding another unused `reserved` rule to the grammar together with the lookahead suggestion for `nonreserved-label` would be nice.

I have such a "reserved" rule locally. Using it for negative lookahead exactly matches the strategy suggested for simple-label to allow reserved prefixes.
