### ISSUE TITLE
environmentVariablesB.dhallb: why is this string escaped in CBOR representation?

### ISSUE THREAD

**Issue by philandstuff** [dhall-lang/dhall-lang#502]
environmentVariablesB.dhallb thinks that `env:"\"\\\a\b\f\n\r\t\v"` should be CBOR-encoded as:

    85                                   # array(5)
       18 18                             # unsigned(24)
       F6                                # primitive(22)
       00                                # unsigned(0)
       06                                # unsigned(6)
       72                                # text(18)
          5C225C5C5C615C625C665C6E5C725C745C76 # "\\\"\\\\\\a\\b\\f\\n\\r\\t\\v"

but.. why is the string escaped in this binary representation? I can't see anything in binary.md that says we should do this.  Shouldn't the test have this value instead?:

    85                       # array(5)
       18 18                 # unsigned(24)
       F6                    # primitive(22)
       00                    # unsigned(0)
       06                    # unsigned(6)
       69                    # text(9)
          225C07080C0A0D090B # "\"\\\a\b\f\n\r\t\v"

**Comment by philandstuff** [comment]
(using the lovely http://cbor.me website for generating this annotated CBOR output :heart: )

**Comment by Gabriel439** [comment]
@philandstuff: This is a case where the standard is underspecified.  Normally I would propose that quoted environment variable names should be encoded the same way as quoted identifiers but those also appear to be underspecified 🙂

My  intuition is that we should go with the latter form (i.e. keep the original code points from the variable name verbatim without escaping them).  My reasoning is that there is no need to escape anything stored in CBOR and it's easier to standardize.

**Comment by philandstuff** [comment]
I'm not sure I agree that the standard is underspecified. dhall.abnf says that posix environment variable escapes have a particular meaning (eg `\a` means the alert character), and binary.md says to encode as a CBOR string.

For example: the ABNF says you should parse `env:"\a"` as a string with a single character U+0007, and binary.md says that you should serialize it as a CBOR array whose fifth element is a CBOR string that contains U+0007.  I don't see how any interpretation is reasonable.

So I think the only thing that needs to happen is to fix the test. I'll raise a PR to do that.
