### ISSUE TITLE
Interpolation simplification rule

### ISSUE THREAD

**Issue by Gabriel439** [dhall-lang/dhall-lang#505]
The Haskell implementation of Dhall currently has a non-standard behavior where it simplifies `"${x}"` to `x`.  I was wondering if it would be okay to upstream this behavior into the standard

**Comment by f-f** [comment]
Agreed, also the Clojure implementation does this simplification

**Comment by singpolyma** [comment]
This would not be too hard for me to add, and it would get us back to `"" ++ x ==> x`
