### ISSUE TITLE
Allow trailing delimiters

### ISSUE THREAD

**Issue by Nadrieril** [dhall-lang/dhall-lang#512]
As far as I understand, one of the major pain points when writing JSON by hand (and thus one of the reasons for migrating to YAML) is the lack of trailing commas.
I understand trailing delimiters were omitted from Dhall [because they complexify the grammar](https://github.com/dhall-lang/dhall-haskell/issues/27#issuecomment-330892244). However, with the current focus of displacing YAML, I think Dhall would benefit from supporting trailing (and/or leading ?) delimiters.
As anecdotal evidence, a friend of mine mentionned the lack of trailing commas as one of the reasons Dhall did not feel mature to them.

**Comment by Profpatsch** [comment]
We had them once before and removed them again. Searching for the issues left as an exercise for the reader. :)

**Comment by Nadrieril** [comment]
The link above points to one of these discussions :)

**Comment by Gabriel439** [comment]
@Nadrieril: Would `dhall format` use trailing delimiters?

**Comment by Nadrieril** [comment]
@Gabriel439 It could, but doesn't have to. I was thinking that leading delimiters would allow for
```
let list = [
  , item1
  , item2
]
```
which keeps the clarity of leading commas but also makes reordering/commenting/inserting elements completely uniform.
But that's just an idea; it's completely fine if the recommended formatting style removes trailing/leading delimiters. This issue is not about style, but rather about convenience.

**Comment by Gabriel439** [comment]
So I'm still mildly opposed to this, but I could be convinced to change my mind.

My reasoning is that in my eyes this doesn't provide a strong benefit and adds cost by complicating the grammar and adding a new knob for how to format things.  In particular, I'm not convinced that the presence or absence feature will change people's minds about whether to adopt the language.

**Comment by Nadrieril** [comment]
It seems the main concern is grammar complexity. So for the sake of concreteness, I had a go at it to see what the grammar change would look like. Here's for record literals and types (off the top of my head; I haven't tested it):
```diff
@@ -685,12 +685,16 @@ empty-record-literal = "="
 empty-record-type = ""
 
 non-empty-record-type-or-literal =
-    any-label whsp (non-empty-record-literal / non-empty-record-type)
+    [ "," whsp ] any-label whsp (non-empty-record-literal / non-empty-record-type)
 
-non-empty-record-type = ":" whsp1 expression *(whsp "," whsp record-type-entry)
+non-empty-record-type = "=" whsp1 expression non-empty-record-type-continue
+non-empty-record-type-continue =
+    whsp "," [ whsp record-type-entry non-empty-record-type-continue ]
 record-type-entry = any-label whsp ":" whsp1 expression
 
-non-empty-record-literal = "=" whsp expression *(whsp "," whsp record-literal-entry)
+non-empty-record-literal = "=" whsp expression non-empty-record-literal-continue
+non-empty-record-literal-continue =
+    whsp "," [ whsp record-literal-entry non-empty-record-literal-continue ]
 record-literal-entry = any-label whsp "=" whsp expression
 
 union-type-or-literal =
```
Union literals will be more complicated (but hopefully we should deprecate those at some point), but union types and lists will be similar.
The main difference I see is that I had to implement repetition manually. That shouldn't change anything for automatically-generated parsers, and for manually-generated ones, I'm hoping they can just switch from `sepBy "," record_literal_entry` to `sepByTrailing "," record_literal_entry` or something similar.

**Comment by Nadrieril** [comment]
My feeling about this is that it's one of those papercuts that doesn't make a massive difference but that can accumulate to recurring mild annoyance. If you look at the list of features of [json5](https://json5.org/), you'll see that about half are about avoiding such papercuts. That makes me think that such tiny changes can have some impact on how the language feels as a whole.

**Comment by singpolyma** [comment]
The first large header one sees when visiting dhall-lang.org says "Human-friendly" -- I think if we are serious about this goal then at *least* trailing delimiters is a must.  I would go one further and say that extra delimiters anywhere should be allowed, so this would be allowed:

```
[ , 1 ,, 2 , 3 ,,,, 4 , ]
```

One reason for this is that this is a source format meant to be written by humans, and different humans have different opinions about how code should be formatted.  Some here like leading commas, some trailing, there is no reason for the language to enforce a style choice and doing so is (anecdotally) harming adoption.  These "extra" delimiters would exist only at the source/parse level -- binary format and normalization are unchanged, so `dhall format` et al also remain unchanged for people who prefer to use them.

**Comment by Gabriel439** [comment]
Actually, the point about deprecating union literals changed my mind, because that was the main thing that was non-trivial to implement correctly the first time I implemented trailing delimiters.

How about we make removing the old-style union literals a precondition of this change?

I'm not as convinced about allowing extra delimiters in a row, though, because it seems to provide less benefit and likely deteriorates parsing errors.

**Comment by singpolyma** [comment]
Old-style union literals are on their way out anyway, and unions are hardly the place where anyone is asking for this, so that seems fine to me.

If we don't get commas-in-a-row that's probably the "least needed" thing -- trailing alone would at least bring us in line with how many communities code.

**Comment by Profpatsch** [comment]
Be aware that allowing for more “human friendliness” nearly always goes with extreme inefficiencies and complication of the technical specs, as well as computational overhead (aka introducing more branching to operations, like parsing).

**Comment by Nadrieril** [comment]
Do we have a timeline for deprecating the old union literals ?

**Comment by Gabriel439** [comment]
@Nadrieril: I'm writing one up right now.  I opened up https://github.com/dhall-lang/dhall-lang/issues/542 as the definitive issue to track the discussion on that

**Comment by joshburkart** [comment]
I'd really like this! In particular, I think allowing for trailing delims would make copy pasting easier. E.g. below I can't copy paste to move the `b = 8` line earlier in the record.

```
{
    a = 7,
    b = 8
}
```

(You guys probably already recognize this... Hope I'm not just adding noise...)

**Comment by Gabriel439** [comment]
Now that old-style union literals are removed we can begin standardizing this

**Comment by onetom** [comment]
I've seen brutal amount of conversations about the handling of commas, but I couldn't find any documentation about why are they not optional.

Is there any official rationale why commas are simply not optional?
It works quite well in Clojure / [EDN](https://github.com/edn-format/edn)...

Pretty-printers add commas to map data structures, but remove them from sequence types:

```clojure
'{a 1 b 2 c 3} => {a 1, b 2, c 3}
'[a, 1, b, 2, c, 3] => [a 1 b 2 c 3]
'(a, 1, b, 2, c, 3) => (a 1 b 2 c 3)
[1, 2, 3] => [1 2 3]
```

**Comment by Nadrieril** [comment]
@onetom In dhall, function application is written `f x`. So `[ f x ]` would be ambiguous: is it a list with two elements `[ f, x ]` or is it a list with a single element which is a function application `[ (f x) ]` ?
Nix has both Haskell-like function application and space-separated lists. It defaults to parsing the above as `[ f, x ]`. I personally find that immensely annoying and would much rather have commas.

**Comment by Gabriel439** [comment]
Fix is up here for leading delimiters (but not trailing ones): https://github.com/dhall-lang/dhall-haskell/pull/1355
