### ISSUE TITLE
`(merge x y) : T`

### ISSUE THREAD

**Issue by Nadrieril** [dhall-lang/dhall-lang#524]
I have just run into an interesting corner case: how to typecheck `(merge x y) : T`.
In my implementation, `merge x y : T` is handled as a special case to make disambiguating `\(x: <>) -> merge {=} x: T` possible, and so `(merge x y) : T` is something different. In particular, `\(x: <>) -> (merge {=} x): T` fails typechecking.
I feel like this is what the standard says, because it tries to treat `merge x y : T` specially, but the fact that the whole standard is written with syntactic expressions makes this a bit ambiguous. The Haskell implementation in particular parses `(merge x y) : T` and `merge x y : T` the same so I'm not sure.
A similar case is `([]) : List T`, which is not allowed.
EDIT: corrected confusion around `<>`

**Comment by philandstuff** [comment]
Sorry, fat fingers.

I’m confused. `merge` takes a record value and a union value, but in `merge {} <>`, `{}` is a record type and `<>` is a union type?

**Comment by Nadrieril** [comment]
Right of course sorry. I meant `\(x: <>) -> merge {} x: T`

**Comment by Nadrieril** [comment]
I edited the OP to correct this

**Comment by philandstuff** [comment]
Strictly I think you need `{=}` not `{}`, but I understand much better now thanks

**Comment by Nadrieril** [comment]
Ah sorry, I keep mixing those up ><

**Comment by singpolyma** [comment]
It is my understanding that this should only matter for the `<>` case, and in that case I agree that `(merge x <>) : T` is a type error.

**Comment by Gabriel439** [comment]
My intention when I wrote the spec was that `merge x y : T` was not the same as `(merge x y) : T`.  The only reason that a special syntactic form exists for `merge x y : T` was to simplify type-checking `merge x (y : <>) : T` (similar to why there is a special syntactic form for empty lists).  However, the standard could be changed to not require the special syntactic form for either one.

**Comment by Nadrieril** [comment]
I'm completely on board with `merge x y : T` being different from `(merge x y) : T`. It does considerably simplify typechecking.
The reason for my concern was the behavior of the Haskell implementation, but you clarified in https://github.com/dhall-lang/dhall-lang/pull/523#pullrequestreview-233748539 that it is non-standard.

**Comment by Nadrieril** [comment]
My question was to know what the standard dictated, and it has been answered.
I have also included a test for this behavior in https://github.com/dhall-lang/dhall-lang/pull/523 (now merged).
