### ISSUE TITLE
Merge typecheck and type-inference tests?

### ISSUE THREAD

**Issue by Nadrieril** [dhall-lang/dhall-lang#536]
I _think_ we split up type-inference and typecheck tests because `Sort` could not be used as a type annotation. Now that it can, can we merge back those tests together ? Or was there another reason for the split ?

**Comment by singpolyma** [comment]
‎The reason for the split is so we can test that an implementation infers the exact type it should in interesting cases, and not just a compatible type.

**Comment by Nadrieril** [comment]
That doesn't sound like a good idea to me, do you have an example were that would be useful ?

**Comment by singpolyma** [comment]
A function should have an inferred type with variables the same name as the function itself, for example. Any alpha-renaming will typecheck.

**Comment by Nadrieril** [comment]
That means it is considered important that e.g. `None` has type `forall(A: Type) -> Optional A` instead of `forall(T: Type) -> Optional T` ? Or that `\(x: Bool) -> x` has type `forall(x: Bool) -> Bool` rather than `Bool -> Bool` ? It feels to me that this could be left to the implementation to decide since that doesn't change correctness or functionality.

**Comment by singpolyma** [comment]
> It feels to me that this could be left to the implementation to decide since that doesn't change correctness or functionality.

An implementation could certainly be usable for most purposes with different-but-compatible inference, but the standard *does* specify a particular algorithm with particular, testable output.‎ Implementations that want to bend on that a bit can just skip the type-inference folder, or treat it as extra typecheck tests. The split allows implementations that want to conform more strictly to test that conformance, but no one is being forced to run them.

**Comment by Nadrieril** [comment]
Ah ok, now I understand. I always interpreted the standard as specifying the types up to equivalence but you're right that it does specify a very precise algorithm.
Do we need the typecheck tests then ? I feel like they could all be type-inference tests.

**Comment by singpolyma** [comment]
‎> Do we need the typecheck tests then ? I feel like they could all be type-inference tests.

We may be able to move some of them, but we need *some* typecheck-style tests to make sure compatible-but-different types can be applied and checking will work out. Though maybe some type-inference tests explicitly on type annotations where equivalence matters would be sufficient.

**Comment by Nadrieril** [comment]
> Though maybe some type-inference tests explicitly on type annotations where equivalence matters would be sufficient.

I was thinking that too.

Note that if we really want type-inference tests to respect the type-inference algorithm to the letter, we need to be very careful when writing those tests to respect details like the order of fields and which type gets outputted when multiple could be.
For example, do you return `T` or `U` when typing `if b then (x: T) else (y: U)` ? The Haskell implementation does the wrong thing here. I think that's a lot of effort for little benefit.

**Comment by Nadrieril** [comment]
Actually the Haskell implementation does the right thing on `if` sorry. So maybe generating the test results using the Haskell implementation is enough for that. If that's the case then no problem.

**Comment by Nadrieril** [comment]
From [this comment](https://github.com/dhall-lang/dhall-lang/pull/538#discussion_r283105088) and others it is now clear to me that the precise algorithm described by the type inference rules is important and taken into account. So I withdraw my concerns about this being unneeded.

To come back to the subject matter : I believe that type-inference tests are strictly more general than typecheck tests (since we can always have a type-inference test with a type annotation in it), so unless there is a good reason not to, I'll do a PR to convert existing typecheck tests into type-inference ones.
I am expecting to be unable to work on dhall in the coming weeks however, so don't hold your breath.

**Comment by Gabriel439** [comment]
I'm in favor of consolidating them if one testing mechanism subsumes the other
