### ISSUE TITLE
Deprecate old-style union literals

### ISSUE THREAD

**Issue by Gabriel439** [dhall-lang/dhall-lang#542]
This is an issue to centralize various discussions we've had about removing support for old-style union literals.  I believe we all agree on this, but the relevant discussions have been buried in various unrelated issues and pull requests.  If you disagree with removing support for old-style unions then now is the time to speak up!

The main motivations behind phasing out the old syntax are:

* Uniformity with how empty union literals are represented

  ... since they don't support the old-style syntax

* Having a canonical representation for union literals

  Currently the two representations are not judgmentally equal, which is a language wart we're
  tolerating until the old syntax is removed

* Simplify implementations

  One less representation to support makes life easier for existing and new maintainers

* Leave the door open for anonymous products

  We're not certain if we want unions to support anonymous products, but if we do then the
  new-style union literals leave the door open for that, whereas the old-style union literals
  don't

I'm currently drafting a Wiki page for the migration, which will link to this as the authoritative issue.

**Comment by Gabriel439** [comment]
Alright, the wiki page for the migration is up here: https://github.com/dhall-lang/dhall-lang/wiki/Migration:-Deprecation-of-old-union-literal-syntax

I tentatively scheduled the removal of the old-style union literals for standard version 9.0.0, so that we can include the official deprecation notice in the change log for standard version 8.0.0.

**Comment by philandstuff** [comment]
Union literals have been removed now.
