### ISSUE TITLE
How to add a new builtin... to dhall-haskell

### ISSUE THREAD

**Issue by singpolyma** [dhall-lang/dhall-lang#544]
Does https://github.com/dhall-lang/dhall-lang/wiki/How-to-add-a-new-built-in-function really belong on the language repo wiki?

I don't mind it, but it seems to be the only part of the wiki that's dhall-haskell specific.

**Comment by Gabriel439** [comment]
Yeah, I can move it to the Haskell repository

**Comment by Gabriel439** [comment]
I have a pull request out to move that into the Haskell package: https://github.com/dhall-lang/dhall-haskell/pull/951

It might be worth keeping the page around, if only to link to each implementation's way of adding built-ins, since this is a pretty common request by users.

**Comment by Gabriel439** [comment]
I updated the page to link to language-specific instructions:

https://github.com/dhall-lang/dhall-lang/wiki/How-to-add-a-new-built-in-function

Feel free to link to instructions for your bindings, too, if they support customization
