### ISSUE TITLE
Allow incomplete polymorphism

### ISSUE THREAD

**Issue by singpolyma** [dhall-lang/dhall-lang#545]
```haskell
\(a: Type) -> List/fold a [1]
```

This is currently a type error under Dhall, because `a` != `Natural` ... except that `a` is actually unknown and *could* be `Natural`, why not delay the type error until we know that?

Of course:

```haskell
(\(a: Type) -> List/fold a [1]) Natural
```

is also currently a type error.  I would propose that it not be.

**Comment by Gabriel439** [comment]
@singpolyma: One reason to enforce parametricity is to be able to guarantee free theorems.  For example, given the type `∀(a : Type) → a → a` I know that there is only one possible function that can implement that type, but that no longer holds under what you propose.  Similarly, you would no longer be able to prove that `∀(a : Type) → a` is uninhabited.

**Comment by singpolyma** [comment]
Hmm... what I'm trying to do is come up with a dhall-compatible encoding of a program with type "holes" that can be filled in by a user manually, or by a bidirectional inference algorithm.  So my first thought was this -- if the program has at its outside the type variables that need to be inferred yet, then a human could write the applications and it becomes valid Dhall (if this change were made that is) and also a type inference algorithm could add the applications to emit valid Dhall also.

**Comment by Gabriel439** [comment]
@singpolyma: Yeah, I think the only way that this would work would be to implement something that is essentially the same as implementing bidirectional type inference within Dhall
