### ISSUE TITLE
Integer/toSignAndNatural

### ISSUE THREAD

**Issue by singpolyma** [dhall-lang/dhall-lang#547]
What do people think of a builtin:

`Integer/toSignAndNatural : Integer -> { sign: Bool, natural: Natural }`

**Comment by Gabriel439** [comment]
@singpolyma: What's the use case you have in mind for this?

**Comment by ocharles** [comment]
I would probably prefer something more like `Integer/toSignedNatural : Integer -> < Positive : Natural | Negative : Natural >`, if we were to have this.

**Comment by ocharles** [comment]
I would say this would make working around https://github.com/dhall-lang/dhall-lang/issues/508 easier, too.

**Comment by singpolyma** [comment]
@ocharles oh yeah, that's better.

I'll admit that #508 was the initial inspiration for this, and just also thinking about `Integer` not having any operations and what would it look like to have safe operation possible to define: of course it would look like operating on a signed natural, but we cannot go back and forth without something like this.  With just this addition `Integers` become possible to compare, etc, if you really want/need using `Natural/fold` but then you can get the Integer back at the end.

**Comment by Gabriel439** [comment]
It's still not clear to me what are the use cases for `Integer` manipulation within the language, though

**Comment by ocharles** [comment]
Well it would be nicer for users of `dhall-execline` to just write `exit -5` rather than `exit (Exit.Negative 5)`. I can't use `-5` though, because I have to eventually produce some `Text`, and I need to map `-5` to `"-5"` (fine) and `5` to `"5"` (currently not possible).

**Comment by Gabriel439** [comment]
Then what about an `Integer/showUnsigned` built-in?

**Comment by singpolyma** [comment]
> Then what about an `Integer/showUnsigned` built-in?

That would solve the particular case but be much less generic/reusable.

I'm not 100% sold on this builtin myself yet, but I would err on the side of one that can do more if we need one.‎

**Comment by Gabriel439** [comment]
The main reason I'm trying to limit the power of the built-in is to discourage `Integer`-based programming (i.e. similar to discouraging `Text` manipulation), so from my point of view the fact that it's less powerful is a feature.

**Comment by ocharles** [comment]
I don't think my little prototype quite warrants the addition of something as specific as that. It's probably best to just leave all of this for now.

**Comment by Profpatsch** [comment]
> `dhall-execline`

w00t

**Comment by ocharles** [comment]
@Profpatsch thanks for the hint about `execline`!
