### ISSUE TITLE
Binary encoding of integrity check

### ISSUE THREAD

**Issue by singpolyma** [dhall-lang/dhall-lang#548]
Currently the binary encoding is like this:

    [ "sha256", "base16Hash" ]

This is fairly inefficient compared to the rest of the binary encoding, since it uses a unicode string of hex digits to encoding a binary string, even though CBOR has binary strings, and a unicode string `"sha256"` to represent the hash function, even though the rest of the encoding uses integer tags.

I would like to suggest we change the encoding to this smaller encoding:

    [ 18, 32, b"raw hash" ]

Or alternately, even smaller:

    b"\x12\x20raw hash"

The integer label `18` comes from the [multihash](https://github.com/multiformats/multihash#table-for-multihash) spec, which seems worthwhile to reuse vs inventing our own label, and in fact the binary-string-only version proposed above is a valid multihash (but does not require implementations to know about multihash or use a multihash library or anything of the kind, since we only support SHA256 for now so an implementation can simply check for the leading two bytes representing the algorithm tag and the hash length)

This change would not affect integrity checks since imports are resolved before computing the semantic hash.

**Comment by Gabriel439** [comment]
@singpolyma: Yeah, this sounds like a great idea to me!
