### ISSUE TITLE
Grammar confusion.

### ISSUE THREAD

**Issue by pthariensflame** [dhall-lang/dhall-lang#55]
Reading the Dhall grammar, the following line stood out to me

``` abnf
text-literal = (double-quote-literal / single-quote-literal) / whitespace
```

Is that second `/` supposed to be there?  *I.e.*, is a `text-literal` really meant to be any of `double-quote-literal` *or* `single-quote-literal` *or* `whitespace`?  Given the weirdness of that, and the apparently needless parentheses, I'm not so sure this was intentional…

**Comment by Gabriel439** [comment]
Oops!  Yes, that's a mistake in the grammar.  It should be:

```abnf
text-literal = (double-quote-literal / single-quote-literal) whitespace
```

Let me put out a quick pull request to fix this
