### ISSUE TITLE
GHCjs as working JavaScript bindings?

### ISSUE THREAD

**Issue by singpolyma** [dhall-lang/dhall-lang#550]
Is this worth mentioning in the README?  I know it powers the try functionality on the website, but could it be used by JavaScript developers as a usable language binding worth talking about more?

**Comment by Gabriel439** [comment]
@singpolyma: It's probably not usable by JavaScript developers.  The Haskell code isn't set up to be called from JavaScript and the way the website works is that it's mostly Haskell code calling into JavaScript.  This is why I haven't broadcast it for use cases other than the website

**Comment by luchiniatwork** [comment]
@Gabriel439 is the code of the website available somewhere? I would love to study it.

**Comment by f-f** [comment]
@luchiniatwork you can find it [here](https://github.com/dhall-lang/dhall-haskell/tree/master/dhall-try) in the `dhall-haskell` repo

**Comment by luchiniatwork** [comment]
Thanks @f-f ... as you can imagine, you got me hooked.

**Comment by f-f** [comment]
@luchiniatwork you're welcome 😄
