### ISSUE TITLE
Wrong hash for concatMapSep in package.dhall (?)

### ISSUE THREAD

**Issue by googleson78** [dhall-lang/dhall-lang#563]
The `package.dhall` for `Text` seems to contain the wrong hash for `concatMapSep`.

Repro:

`check.dhall`
```haskell
let concatMapSep = https://prelude.dhall-lang.org/Text/concatMapSep sha256:46b81a9e211fb8278bf2793e75e8175fef79e0e3e478ef1016e3233ecc2ddfe6
in 0
```

Output:
```bash
blademaster :: /tmp/dhall » dhall --annotate <<< './check.dhall'

↳ ./check.dhall

Error: Import integrity check failed

Expected hash:

↳ 46b81a9e211fb8278bf2793e75e8175fef79e0e3e478ef1016e3233ecc2ddfe6

Actual hash:

↳ cde27252cbb7819a3b26fd404846596d06c0fa2ff7493023a0f9637660f61764


1:                    https://prelude.dhall-lang.org/Text/concatMapSep sha256:46b81a9e211fb8278bf2793e75e8175fef79e0e3e478ef1016e3233ecc2ddfe6

/tmp/dhall/check.dhall:1:20
```

**Comment by Gabriel439** [comment]
@googleson78: You're right. In fact, there are several imports in `./Prelude/Text/package.dhall` that need their hashes updated.

I'm doing two things to resolve this:

* First, I'm creating a `--cache` flag to `dhall freeze` to automate the Prelude idiom of creating protected imports with unprotected fallbacks for caching purposes
* Second, once that is complete I'll update CI for this repository to enforce that the Prelude matches what `dhall freeze --cache` would generate

**Comment by Gabriel439** [comment]
Alright, the pull request is up for the `--cache` flag to `dhall freeze`: https://github.com/dhall-lang/dhall-haskell/pull/980

**Comment by Gabriel439** [comment]
And here is the matching change to this repository's CI to enforce that the Prelude stays up to date: https://github.com/dhall-lang/dhall-lang/pull/571
