### ISSUE TITLE
Syntax highlighting on GitHub

### ISSUE THREAD

**Issue by tfausak** [dhall-lang/dhall-lang#57]
It would be nice if `.dhall` files (like [this one](https://github.com/dhall-lang/dhall-haskell/blob/be10607f96f694ad3092eff40ef74c9c5d227bcd/tests/parser/double.dhall)) were syntax highlighted on GitHub. The instructions for [adding a language](https://github.com/github/linguist/blob/7be6fb013864b59e7c9ba76e3c0062dd95cedc76/CONTRIBUTING.md#adding-a-language) don't seem too bad. I do wonder if Dhall is popular enough yet to be added.

**Comment by Gabriel439** [comment]
> We try only to add new extensions once they have some usage on GitHub. In most cases we prefer that extensions be in use in hundreds of repositories before supporting them in Linguist

Dhall needs to be more widely used first

**Comment by tfausak** [comment]
Fair enough. I'll do my part! 😄
