### ISSUE TITLE
Projection by expression type inference

### ISSUE THREAD

**Issue by singpolyma** [dhall-lang/dhall-lang#590]
```
Γ ⊢ e :⇥ { ts… }
Γ ⊢ s : T
s ⇥ {}
────────────────
Γ ⊢ e.(s) : {}


Γ ⊢ e :⇥ { x : T₀, ts… }
Γ ⊢ s : T₀
s ⇥ { x : T₀, ss… }
Γ ⊢ e.({ ss… }) : T₁
───────────────────────────
Γ ⊢ e.(s) : { x : T₀, ss… }
```

This seems... not quite right to me?  These rules say that the selector must have the same type as the first field in the record.  My first instinct was it should say:

`Γ ⊢ s : Type`

But it probably can also be Kind or Sort?

**Comment by singpolyma** [comment]
I'm also concerned about the requirement to normalize `s` here... I believe that isn't just a context-free normalization of s, but rather one in the context of all variable bindings that may be above this expression.  Otherwise:

```dhall
let s = { x : Natural }
in
{ x = 1 }.(s)
```

does not typecheck because `s` normalized context-free will just be `s`

**Comment by Gabriel439** [comment]
@singpolyma: That looks like a typo.  I think it's supposed to be `Γ ⊢ s : T` like in the first judgment, meaning that it only needs to be well-typed, but we don't care which type.  The only reason for it is to ensure that the β-normalization on the following line terminates.

You don't need to do anything special to handle context correctly, though.  The reason why is that the β-normalization rules for `let` expressions will substitute the `s` into the projection before it is normalized, like this:

```dhall
let s = { x : Natural }
in  { x = 1 }.(s)

-- β-reduce the `let` expression
{ x = 1 }.({ x : Natural })

-- Now β-reduce the projection
{ x = 1 }
```

**Comment by philandstuff** [comment]
@Gabriel439 that’s fine when you’re beta-normalizing, but what about when you’re typechecking? My understanding is that when you’re typechecking, you don’t perform substitution on `let`s.

In @singpolyma’s example, we typecheck the `let` by adding `s : Type` to the context and then typechecking the body. When we typecheck the body, we normalize `s` (and get `s`) and then we’re stuck and can’t make progress, because we didn’t get a record type.

**Comment by Nadrieril** [comment]
@philandstuff : in typechecking we actually do substitute let expressions. It's necessary to support type aliases. There is a more detailed explanation [in the relevant section of the standard](https://github.com/dhall-lang/dhall-lang/blob/master/standard/type-inference.md#let-expressions)

**Comment by philandstuff** [comment]
Huh, I hadn't fully appreciated that. Thanks for the explanation!

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-lang/pull/597
