### ISSUE TITLE
First class support for streams?

### ISSUE THREAD

**Issue by dumblob** [dhall-lang/dhall-lang#594]
I'm looking for an efficient and standardized native way (i.e. guaranteed to be supported by all dhall implementations which state full dhall compatibility) of sending stream data over a dhall channel.

Is such use case supported? I.e. can subscriber read and process data without waiting for other data from producer? E.g. XML and "hierarchical" formats don't support this as until the final "closing" tag gets read, one doesn't have guarantee, that the already read data are consistent.

I couldn't find this information anywhere :cry:.

**Comment by singpolyma** [comment]
CBOR is very streaming-friendly in my experience, so we should get that for free.

**Comment by f-f** [comment]
@dumblob to expand on @singpolyma's answer: the standard defines a binary format for Dhall, based on [CBOR](https://tools.ietf.org/html/rfc7049), so you should be able to just stream bytes on the wire.
However, I'd say at a higher level it's not possible to "not wait for the end of the data", because the expression will need to be typechecked as a whole (i.e. I'm not aware of techniques that allow partial typechecking in our case)

**Comment by singpolyma** [comment]
‎You will need to wait for a whole Dhall item in order to typecheck yes, so it depends on what streaming support you need.

If you have gigabytes of data in a single item, Dhall may not be a good fit.

If you have many small items, it should work well.

Also, some kinds of partial typechecking (or skipping typechecking) may work for some applications, but we would need more details.

**Comment by Gabriel439** [comment]
CBOR supports [indefinite-length lists](https://tools.ietf.org/html/rfc7049#section-2.2.1), so if your top-level Dhall expression is a list of values, you could begin by sending `0x9F` to begin the indefinite-length list, then send each element of the list as a CBOR-encoded Dhall value, then terminate the list when you're done by sending `0xFF`.  That lets you lazily stream as many values as you want, while still preserving the property that the stream is a valid CBOR expression.

**Comment by singpolyma** [comment]
> That lets you lazily stream as many values as you want, while still preserving the property that the stream is a valid CBOR expression.

You can do it that way, though for a streaming application I'd suggest using a CBOR stream and not bothering with the indefinite-length list wrapper.‎

**Comment by dumblob** [comment]
>You can do it that way, though for a streaming application I'd suggest using a CBOR stream and not bothering with the indefinite-length list wrapper.‎

The goal was actually the higher level view of data, but I have to admit, that the solution from @Gabriel439 feels somehow hacky :cry: (not "first class citizen" - i.e. resort to the underlying "hidden" serialization, though well defined and part of the dhall standard).

Anyway, if there are no other options for streaming and no such support is planned for dhall, feel free to close this issue.

**Comment by singpolyma** [comment]
> Anyway, if there are no other options for streaming and no such support is planned for dhall, feel free to close this issue.

What other option would you want that first-class support by the standard format for machine use?‎

**Comment by dumblob** [comment]
Well, instead of (this is a sketch, not a working example) writing the following in a POSIX shell:

```sh
{
  printf 'dhall preamble\n'
  while printf 'dhall code to stream\n'; sleep 1; done
} |
  dhall-wire-encode |
  send-over-network |
  receive-from-network |
  dhall-wire-decode | {
    read preamble_to_throw_away
    while read x; do printf "%s" "$x"; done
  }
```
(`dhall-wire-encode`, `dhall-wire-decode`, `send-over-network`, `receive-over-network` are just placeholders for demonstration purposes, not real apps)

I'll need to deal with some dhall "internals":
```sh
{
  printf 'dhall preamble\n' | dhall-wire-encode;
  printf '0x9F'  # magic constant from CBOR, ehm, I mean, dhall internals
  while printf 'dhall code to stream\n' | dhall-wire-encode; sleep 1; done
  printf `0xFF`  # another magic constant from CBOR, ehm, I still mean, dhall internals
} |
  send-over-network |
  receive-from-network |
  dhall-wire-decode | {
    read preamble_to_throw_away
    # here is the big question whether the dhall deserialization library will cope well with lazy lists
    while read x; do printf "%s" "$x"; done
  }
```
(and this is just high-level example, but in practice it'll get probably lower level)

Not speaking about what if the mapping dhall->CBOR somehow changes in the future, even slightly, but this "streaming hack" will already be widespread enough...

**Comment by singpolyma** [comment]
As I've said twice now, you don't need those "magic numbers", you can just emit cbor items in a stream, basically exactly as you outline in your ideal case.

**Comment by dumblob** [comment]
I must be confused. How to emit CBOR items if CBOR is just the dhall underlying technology I don't want to touch in any way? Any examples?

**Comment by Gabriel439** [comment]
@dumblob: The `dhall` command line tool provides an `encode` subcommand for encoding arbitrary Dhall expression to CBOR:

```
$ dhall encode <<< '[1, 2, 3]'
```

**Comment by Gabriel439** [comment]
Sorry, I forgot to mention that there is a matching `dhall decode` command that you can use on the other end:

```bash
$ dhall encode <<< '[1, 2, 3]' | dhall decode
[ 1, 2, 3 ]
```

**Comment by singpolyma** [comment]
It would really help to know the actual use case.

**Comment by dumblob** [comment]
>It would really help to know the actual use case.

Producer produces a long (or even infinite) stream of different data (sometimes shorter text, sometimes different numbers, sometimes pictures, sometimes some colors, etc.) fully described (and ["encoded"](https://github.com/dhall-lang/dhall-lang/issues/418 )) in dhall. All the streamed data are generated by different complex mathematical and other formulas and each of them takes different time (milliseconds to minutes) to generate. The generation is generally dependent on the previous computed state, so it doesn't seem easily possible to analyze the full state and "temporarily skip" or "background" some generation tasks. Therefore everything gets generated in order.

Consumer needs to immediately display the generated stuff (as soon as possible after the one piece, e.g. a picture, got generated by the producer) and simultaneously save the data to a "stream log" used to reconstruct the full history at arbitrary past time.

How would you implement the stream with dhall without resorting to some CBOR stuff or alike (because then I could use CBOR directly and the added value of dhall would quickly approach zero considering maintenance, updates, etc.).

**Comment by Profpatsch** [comment]
So you have a stream of heterogeneous data typed in dhall. That’s not a problem, as long as it’s a finite (and known) amount of variants, because you can always convert it to a homogeneous dhall type by putting every case into a tagged union; so you have type `T1` and `T2`, you can do: 

```
< ForType1 : T1, ForType2: T2 >
```

which is the type you tranfer over the wire (with `dhall decode` and `dhall encode`).

**Comment by dumblob** [comment]
@Profpatsch sounds promising.

Any way how to make the unions less verbose for each of the "data records"? I assume currently I would need to list all the possible types (e.g. about 30 of them) for each record on the consumer side before putting them into the heterogeneous list.

How to derive the original type from such union type on the consumer end without resorting to switch-case like construct?

**Comment by singpolyma** [comment]
> How would you implement the stream with dhall without resorting to some CBOR stuff or alike (because then I could use CBOR directly and the added value of dhall would quickly approach zero considering maintenance, updates, etc.).

You either have to "resort" to CBOR or to UTF-8 because those are the only standard Dhall encodings :)

Really either could work (dhall source form or dhall binary form) but binary form seems more ergonomic for this kind of thing (machine to machine transfer).

The Dhall library in use would have to support reading from an IO stream or similar instead of expecting a complete bytestring to be present. Would be easy for me to add such support in dhall-ruby (and probably I should for other reasons anyway).

**Comment by Profpatsch** [comment]
> How to derive the original type from such union type on the consumer end without resorting to switch-case like construct?

You have to switch-case anyway, because you cannot know otherwise what the type of data is that arrives over the socket.

**Comment by sjakobi** [comment]
What's the status of this issue? It seems that all the questions were answered.

**Comment by dumblob** [comment]
@sjakobi true, thanks :wink:.
