### ISSUE TITLE
Awesome dhall promotion

### ISSUE THREAD

**Issue by RyanSiu1995** [dhall-lang/dhall-lang#598]
Hi All,
Sorry for posting sth promotion but I don't know where I should post this.
In order to expand the community of dhall lang, I have created a awesome list for dhall lang here, https://github.com/RyanSiu1995/awesome-dhall.
Anyone who are interested in dhall lang are welcome to enrich the list!
Thank you!!!

**Comment by singpolyma** [comment]
See also:

‎https://github.com/dhall-lang/dhall-lang/wiki/Awesome-Dhall

**Comment by Gabriel439** [comment]
I could update the wiki to point to @RyanSiu1995's repository

**Comment by RyanSiu1995** [comment]
@Gabriel439 Awesome! I have moved those items are not in my repo from wiki. Please feel free to update the wiki!
Thanks a lot!

**Comment by ocharles** [comment]
Just my 2p, but while at ZuriHac someone asked if there was an "Awesome Dhall" anywhere. I did a search for repositories on GitHub and couldn't find anything, and couldn't really remember where it was. I eventually found it on the wiki. I do think it's more "idiomatic" to have an awesome-dhall repository. Perhaps @RyanSiu1995's should move into `dhall-lang`, or do we want to keep it community?

**Comment by Gabriel439** [comment]
I'm okay with either approach.  If they want to keep it separate that's fine, and if they want to add it to the `dhall-lang` organization I can help with that, too.

**Comment by Gabriel439** [comment]
Also, I just updated the "Awesome Dhall" wiki page to point to the repository

**Comment by RyanSiu1995** [comment]
I'm fine with either approach as well. My idea is to make the awesome-dhall much more accessible to other developers.
I will make a pull request on [awesome](https://github.com/sindresorhus/awesome) after a few month passes.
Please feel free to move the repo if you guys think there is a necessity on it.

**Comment by Gabriel439** [comment]
@RyanSiu1995: Alright, then let's move the repository underneath the `dhall-lang` organization, if only to officially endorse it.  I think you have to initiate the transfer, though, and I believe you should retain administrative ownership of the project after the transfer

**Comment by singpolyma** [comment]
Sent from my BlackBerry 10 smartphone on the Fido network.
  Original Message  
From: Ollie Charles
Sent: Monday, June 24, 2019 15:38
To: dhall-lang/dhall-lang
Reply To: dhall-lang/dhall-lang
Cc: Stephen Paul Weber; Comment; singpolyma@singpolyma.net
Subject: Re: [dhall-lang] Awesome dhall promotion

Just my 2p, but while at ZuriHac someone asked if there was an "Awesome Dhall" anywhere. I did a search for repositories on GitHub and couldn't find anything, and couldn't really remember where it was. I eventually found it on the wiki. I do think it's more "idiomatic" to have an awesome-dhall repository. Perhaps @RyanSiu1995's should move into `dhall-lang`, or do we want to keep it community?

**Comment by singpolyma** [comment]
Sent from my BlackBerry 10 smartphone on the Fido network.
  Original Message  
From: Gabriel Gonzalez‎
Sent: Monday, June 24, 2019 15:42
To: dhall-lang/dhall-lang
Reply To: dhall-lang/dhall-lang
Cc: Stephen Paul Weber; Comment; singpolyma@singpolyma.net
Subject: Re: [dhall-lang] Awesome dhall promotion

I'm okay with either approach. If they want to keep it separate that's fine, and if they want to add it to the `dhall-lang` organization I can help with that, too.

**Comment by ocharles** [comment]
The wiki now points to @RyanSiu1995's repository, I think this can be closed.

**Comment by f-f** [comment]
@ocharles I think the general agreement in the thread was to move it under the `dhall-lang` org, so I'd keep this open until then

**Comment by ocharles** [comment]
That would be my preference. @RyanSiu1995 could you initiate that transfer?

**Comment by RyanSiu1995** [comment]
I am not the member of dhall org so I can't initiate the transfer for the
moment. Is there any means that allow me to initiate the transfer without
joining the group?

**Comment by Gabriel439** [comment]
@RyanSiu1995: I just added you to this project, so see if you can initiate the transfer now

**Comment by RyanSiu1995** [comment]
Nope, I cannot initiate.
I have got the following error
`You don’t have the permission to create repositories on dhall-lang`

**Comment by Gabriel439** [comment]
@RyanSiu1995: Alright, try again

**Comment by RyanSiu1995** [comment]
It still fails with the same error

**Comment by Gabriel439** [comment]
@RyanSiu1995: Maybe we can try the other way around.  If you add me as an admin to your project I might be able to initiate the transfer

**Comment by RyanSiu1995** [comment]
Added. Please try~

**Comment by Gabriel439** [comment]
@RyanSiu1995: I'm unable to access the settings page of the `awesome-dhall` project

**Comment by RyanSiu1995** [comment]
I have initiated the repo transfer to you first so that you can transfer it to dhall-lang

**Comment by Gabriel439** [comment]
Alright, that worked: https://github.com/dhall-lang/awesome-dhall

Also, I figured out what I was doing wrong previously.  I granted you privileges to the `dhall-lang` repository by mistake when it should have been for the `dhall-lang` organization

**Comment by ocharles** [comment]
Hurrah! Sounds like we're good to close this now
