### ISSUE TITLE
README suggestions

### ISSUE THREAD

**Issue by jml** [dhall-lang/dhall-lang#6]
Hi! I've wanted something like dhall for a long time. My primary use case is configuring other applications, like grafana (check out https://github.com/weaveworks/grafanalib for how I did it instead) & Kubernetes.

I think the README currently doesn't help as much as it might. 

Big ideas:
- Your primary audience is people writing new programs in Haskell who want to use a new config format. I think you should change the audience to be people who are sick of writing repetitive config files in YAML & JSON and want a sane way of doing that
- README needs to start from user problems, rather than dhall solutions
- README must be a pitch to convince people to investigate further

Here are some detailed suggestion:

- the first two lines are great
- don't lead with "Features", instead lead with problems that dhall solves, e.g.
  - "Need a safe, concise way to generate repetitive YAML or JSON? With dhall you can turn the repetition into function definitions, and trust the type system to catch errors before they hurt users."
  - "Adding a new config file to your app? Using dhall-lang as the format means"
  - I find the Q&A format easier to write, but the idea is starting with problems that your end users are facing or ways that you can make their life better, rather than how clever dhall is
- The README repeatedly uses "I". That's cool, but say who "I" is.
- Please please move the core documentation off of hackage. Browsing the implementation's library documentation to learn how to use something makes it feel like its only for insiders. This goes double when the implementation language is Haskell. 
- "I recommend the following progression" — I think this really undersells dhall
  - There's a large devops audience who could benefit, for whom "If your language does not yet support Dhall" just sounds like they are being grudgingly allowed to use this software
- Replace the overview with a "getting started" guide
  - Start with a single self-contained, concrete, representative example that's not too complicated and shows a couple of features worth highlighting
  - Move the REPL stuff to a fully separate "Learning the language" section
  - No one wants to evaluate expressions in a REPL. They evaluate expressions in a REPL because they are trying to do something else. 
  - Move all the details about language bindings to their respective documentation systems. A colleague told me "dhall is a Haskell thing", based on skimming this. 
  - Don't even mention the word "compliers". Instead have headings like "Converting dhall to JSON", "Converting dhall to YAML", "Converting dhall to Nix"

I hope this helps. Take or leave this any or all of this advice as you will. I'd love to send a PR, but I don't have the time and there's not much point unless you agree in principle with the direction I'd like to take.

**Comment by jml** [comment]
Oh, also, "how to install dhall" instructions for common platforms (Linux, macOS, Windows).

**Comment by Gabriel439** [comment]
Sounds good!

I think the main blind spot I had when writing the `README` was underestimating the value of the JSON/YAML conversion.  I had always viewed that as a second-class workaround for the lack of a direct language binding and not a first-class solution to recommend to users.  However, from reading your feedback it sounds like I should instead rebrand Dhall as an alternative to Jsonnet that's safer and supports other integrations, too

I also agree with the other feedback about how to market use cases and solve specific problems at the beginning of the tutorial.  I'll put up a pull request soon updating the `README` that you can review

**Comment by errordeveloper** [comment]
I have to say that your blog has a few pretty concrete stories, but that's a lot of reading... I'm intending to have a good look at the blog at some point.

**Comment by BatmanAoD** [comment]
@jml @Gabriel439 Forgive me for asking a stupid question, but it looks like the README still doesn't provide a link or any instructions for installing the command-line interpreter. It looks like maybe the `dhall` executable itself is part of dhall-lang/dhall-haskell, which at first I didn't even think to look at, since I am not (yet) a Haskell-er? But, unfortunately, as a non-Haskell-er, I'm not even sure how to build/install the standalone package. A little help, please?

**Comment by Gabriel439** [comment]
@BatmanAoD: Yeah, I will update the README with instructions soon.  Here's my rough first draft of what I'll add to the `README`:

In the short-term, here are a few ways to install the interpreter:

* Recommended: Install the Haskell package using Haskell's `stack` build tool
    * Instructions for installing `stack` here: https://haskellstack.org/
    * Then run: `stack setup && stack install dhall`
* Install the Haskell package using Haskell's `cabal` build tool:
    * You can obtain `cabal` from the minimal installer here: https://www.haskell.org/downloads
    * Then run: `cabal update && cabal install dhall`
* Installing the package using Nix
    * Instructions for installing Nix here: https://nixos.org/nix/download.html
    * `nix-env --install --attr haskellPackages.dhall`

Installation paths that I'd like to provide (or that others can contribute if they have time before I do):
* `brew`
    * Surprisingly, there is already a `brew` package for `dhall-json`, but not `dhall`:
        * https://github.com/Homebrew/homebrew-core/blob/master/Formula/dhall-json.rb
        * It should be easy to crib from the above derivation to provide support for `dhall`
* Debian package
    * I think this is just a matter of asking the Debian Haskell group to package it.  They're pretty helpful
* Pre-built binaries hosted on the release page of this repository
* Try the Dhall interpreter in the browser (using `ghcjs` to compile to Javascript)

**Comment by BatmanAoD** [comment]
Thank you!

I realize this isn't really something you can help with, but `stack` seems to have some issues on Windows with certain antirivus software (GHC won't be automatically installed due to a permissions issue, and after installing it manually, I ran into another permissions issue trying to do the actual install; some searching led me to a couple of threads that suggest antivirus is to blame). So unfortunately I'll have to put trying dhall on hold for now.

**Comment by Gabriel439** [comment]
@BatmanAoD: No problem!  You can report the `stack` issue here if there's not already a related issue: https://github.com/commercialhaskell/stack/issues

**Comment by BatmanAoD** [comment]
Yep, there is one, but it's been closed since the antivirus-disabling solution seems to work for most people. So at some point I'll either try again on a VM or talk to IT about making a scanning exception for Stack. https://github.com/commercialhaskell/stack/issues/1917

**Comment by BatmanAoD** [comment]
Indeed, after disabling my virus scanner I was able to install GHC and dhall.

**Comment by Gabriel439** [comment]
@BatmanAoD: One other question: if there had been a binary executable to install would that have made things easier?  In other words, would you not have had to disable the virus scanner?

**Comment by BatmanAoD** [comment]
I believe that would have worked fine; I don't typically experience this sort of problem, and I don't think I've ever seen it for Windows `msi` binaries or other "native" installers.

**Comment by BatmanAoD** [comment]
I believe that would have worked fine; I don't typically experience this sort of problem, and I don't think I've ever seen it for Windows `msi` binaries or other "native" installers.

**Comment by Gabriel439** [comment]
Alright, then I'll try to provide binary releases for various platforms, too

**Comment by BatmanAoD** [comment]
That will definitely be helpful!

**Comment by Gabriel439** [comment]
I will close this out as I believe most of the original suggestions have been addressed in some way.  In particular, we now have a https://docs.dhall-lang.org/ which has a more comprehensive set of educational resources and the `README` links to that now.

**Comment by errordeveloper** [comment]
@Gabriel439 thanks for closing with an informative note!

**Comment by Gabriel439** [comment]
@errordeveloper: You're welcome! 🙂
