### ISSUE TITLE
[Feature Request] Merge Naturals

### ISSUE THREAD

**Issue by ari-becker** [dhall-lang/dhall-lang#602]
I ran into an issue at work where we're trying to determine, for a given Kubernetes cluster, what size the control-plane nodes should be, which is determined by the numerical sizes of other components in the cluster.

According to the Kubernetes [documentation](https://kubernetes.io/docs/setup/best-practices/cluster-large/#size-of-master-and-master-components) (leaving aside that the generation of nodes it recommends is out of date), the following guidelines are recommended:

```text
1-5 nodes: m3.medium
6-10 nodes: m3.large
11-100 nodes: m3.xlarge
101-250 nodes: m3.2xlarge
251-500 nodes: c4.4xlarge
more than 500 nodes: c4.8xlarge
```

To represent this, I'd like to write a function that looks something like this (syntax up for discussion, of course):
```dhall
let controlPlaneNodeSize
  : Natural -> Text
  = λ(numWorkerNodes : Natural)
  → merge
    { [ 0 → 5 ] = "m3.medium"
    , [ 6 → 10 ] = "m3.large"
    , [ 11 → 100 ] = "m3.xlarge"
    , [ 101 → 250 ] = "m3.2xlarge"
    , [ 251 → 500 ] = "c4.4xlarge"
    , [ 501 → Infinity ] = "c4.8xlarge"
    }
    numWorkerNodes
in controlPlaneNodeSize
```

Of course, to preserve totality, such a merge would require:
a) The union of the set of all ranges within any `merge` block must be `[ 0 -> Infinity ]`. For example, the following should produce a type error:
```dhall
merge
{ [ 0 → 100 ] = "small"
, [ 101 → 200 ] = "large"
}
someNatural -- what if someNatural were 300?
```
b) No two ranges within the set of all ranges within any `merge` block may overlap. For example, the following should produce a type error:
```dhall
merge
{ [ 0 → 1000 ] = "small"
, [ 500 → 5000 ] = "large"
, [ 5001 → Infinity ] = "huge"
}
someNatural -- if someNatural is 750, then what should someNatural merge to? "small" or "large"?
```

The current workaround is to compute this outside of Dhall, which is annoying.

edit: I realize that `Infinity` as a literal is of type `Double` currently, so, some `Natural` equivalent of `Infinity`.

**Comment by singpolyma** [comment]
You can do this now in Dhall using the less than ("lt") function from https://github.com/sellout/dada/blob/master/Natural/lt

**Comment by joneshf** [comment]
A complete example of using `Natural/lt`:

```Dhall
let lt
    : Natural → Natural → Bool
    = https://raw.githubusercontent.com/sellout/dada/43597581f412cf143eab7cd9bf62a6d41cd93828/Natural/lt sha256:bd598693ec511aae9894fa40a829ccb4628bdb71ed23fcafa72cfc4d8b85433d

let controlPlaneNodeSize
    : Natural → Text
    =   λ(numWorkerNodes : Natural)
      →       if lt numWorkerNodes 6
        
        then  "m3.medium"
        
        else  if lt numWorkerNodes 11
        
        then  "m3.large"
        
        else  if lt numWorkerNodes 101
        
        then  "m3.xlarge"
        
        else  if lt numWorkerNodes 251
        
        then  "m3.2xlarge"
        
        else  if lt numWorkerNodes 501
        
        then  "c4.4xlarge"
        
        else  "c4.8xlarge"

in  controlPlaneNodeSize
```

Of course if you had a `Natural/lte`, or `Natural/between`, it might read a bit closer to the problem domain.

**Comment by ari-becker** [comment]
@singpolyma @joneshf Interesting... glad to know there's a solution that fits my use-case.

I'll leave it up to the mods if they think this issue should be closed (because a workable solution for my use-case exists) or should stay open (if they think the feature request has merit regardless).

**Comment by Gabriel439** [comment]
I've been thinking about what is the narrowest high-performance built-in we could add to make this more efficient and lead to smaller/more-readable normal forms.

The conclusion I came to was that we could add a
`Natural/subtract` built-in of type:

```dhall
Natural/subtract : Natural → Natural → Natural
```

... with two caveats:

* `Natural/subtract x y = y - x` (i.e. the number to subtract is the first argument, just like Haskell's `subtract`

  The main reason for this is purely from a mathematical elegance perspective, because then it leads to the nice functor laws:

  ```dhall
  Natural/subtract (x + y) = Natural/subtract x . Natural/subtract y

  Natural/subtract 0 = id
  ```

  ... and we could also provide a `Natural/minus` in the Prelude with the argument order that people expect.

* `Natural/subtract` truncates to 0 (i.e. `Natural/subtract 1 0 = 0`)

If you had that, then you can implement all of the inequality operators in terms of `Natural/subtract` and the already-existing `Natural/isZero` built-in.  For example:

```dhall
let Natural/lte = λ(x : Natural) → λ(y : Natural) → Natural/isZero (Natural/subtract y x)

let Natural/lt = λ(x : Natural) → λ(y : Natural) → Natural/lte (x + 1) y

…
```

It would also simplify the implementation of the commonly used `predecessor` function, which would now just be `Natural/subtract 1`

**Comment by ocharles** [comment]
I'm very uneasy about truncating Naturals

**Comment by Gabriel439** [comment]
@ocharles: My reasoning is that inequality operators are essentially truncating naturals anyway (to either a `Bool` or `Ordering`)

**Comment by singpolyma** [comment]
I think if we're interested in making this more obvious to people, the right place to start is to add something to Prelude. subtract, minus, lt, whichever. Adding to Prelude is very light for implementations and the language. Adding builtins is very heavy by comparison and adds warts to the language.

**Comment by Gabriel439** [comment]
@singpolyma: My understanding is that adding something like `lt`/`subtract` to the Prelude doesn't solve the problem, because they are extremely inefficient.  I don't think we should add something to the Prelude that is so easy to misuse

**Comment by singpolyma** [comment]
>@singpolyma: My understanding is that adding something like `lt`/`subtract` 
>to the Prelude doesn't solve the problem, because they are extremely 
>inefficient.  I don't think we should add something to the Prelude that is 
>so easy to misuse

Do we have any reason to believe that the naive normalization of lt or 
subtract is too inefficient to use for the use case at hand?  I understand 
that without an implementation optimizing them they'll maybe be too 
inefficient in some cases, but in general config file numbers are quite 
small.

**Comment by Gabriel439** [comment]
@singpolyma: Yes, even for small `Natural` numbers it is very inefficient.  For example, I can't normalize the following expression because it exhaust all the memory on my machine (16 GB):

```dhall
let Natural/lt =
      https://raw.githubusercontent.com/sellout/dada/43597581f412cf143eab7cd9bf62a6d41cd93828/Natural/lt sha256:56f1a7d813b15a61bfbce7abb29ec720418e448e0a80518bcd33ffe6860716e0

in  Natural/lt 5000 5000
```

**Comment by Profpatsch** [comment]
Is subtraction on naturals that truncates to 0 a sensible mathematical concept?

**Comment by Gabriel439** [comment]
@Profpatsch: I think it's sensible.

To illustrate why, let's ask a related question: "Is concatenation of lists that truncates to 1 a sensible mathematical/algebraic concept?".

If you do that, you get the `Maybe` type, which can be thought of as a list of at most 1 element.  In fact, this is the reason why `dhall` used the `List`-like syntax for `Optional`s for so long.

A large number of algebraic operations on `Maybe` are essentially the exact same as operations on lists truncated to the first element with `listToMaybe`:

```haskell
listToMaybe empty = empty

listToMaybe (x <|> y) = listToMaybe x <|> listToMaybe y

listToMaybe . return = return

listToMaybe . f >=> listToMaybe . g = listToMaybe . (f >=> g)
```

Here's a concrete example:

```haskell
example :: (Monad m, Alternative m) => m (Integer, Integer)
example = do
    x <- pure 1 <|> pure 2
    y <- empty <|> pure 3
    return (x, y)
```

If you interpret that as a list, you get: `[ (1, 3), (2, 3) ]`.  If you interpret that as a `Maybe` you get `Just (1, 3)`, which is the same list truncated to at most one element.

**Comment by joneshf** [comment]
The general idea is [saturation arithmetic][] with the lower bound being 0 and upper bound being infinity. Naturals have a bit more structure and form a [monus][]. There's a [example][] of how you might define it, as well. 

[example]: https://en.wikipedia.org/wiki/Monus#Natural_numbers
[monus]: https://en.wikipedia.org/wiki/Monus
[saturation arithmetic]: https://en.wikipedia.org/wiki/Saturation_arithmetic

**Comment by Bj0rnen** [comment]
A truncated subtraction definitely makes sense as a primitive for naturals, but I would be surprised if something named `Natural/minus` or `Natural/subtract` worked that way. The above comment indicates that `Natural/monus` and `Natural/truncSubtract` or something like that would be better names.

**Comment by Gabriel439** [comment]
TIL about [monus](https://en.wikipedia.org/wiki/Monus)

If people don't object I can propose adding a `Natural/truncatedSubtract` as a built-in and a `Natural/monus` to the Prelude like @Bj0rnen suggests

**Comment by sellout** [comment]
@joneshf
> Of course if you had a Natural/lte, or Natural/between, it might read a bit closer to the problem domain.

The kind-polymorphism branch of dada does replace `Natural/lt` with `Natural/le` (which is also slightly faster). It should be what master is at this point, I just haven’t gotten around to finalizing that.

@Gabriel439
> I can't normalize the following expression because it exhaust all the memory on my machine

🤔 I’ve found `Natural/le` (and `Natural/lt`) to be close to constant-space, but n(log n) time. `Natural/le 5000 5000` takes about 5s on my laptop, `Natural/le 15000 15000` is about 60s. Both run in under 100 MiB of memory. Granted, still not something that compares to a built-in performance, but certainly not stressing my machine.

**Comment by sellout** [comment]
Also, @ari-becker, `Natural/le m n` scales relative to `min m n`, so `Natural/le m 500` should be instantaneous no matter how many nodes you have.

**Comment by ocharles** [comment]
I've come into this again, when trying to model again positive ratios through the type `{num : Natural, denom : Natural }`. I need to witness the ordering on `Ratio`s, which is:

```haskell
			  λ(a : Ratio)
			→ λ(b : Ratio)
			→ Natural/lt (b.num * a.denom) (a.num * b.denom)
```

Naturally this can be comparing some very big `Natural`s... even though you're comparing some very small numbers! E.g., `0.0001 > 0.001` is `1/10000 > 1/1000`, which is `1000 < 10000` - if that's literally a fold over `Natural`s this is seriously computationally expensive.

**Comment by MonoidMusician** [comment]
Sorry, I don't mean to bikeshed, but is a better (shorter) name than `Natural/truncatedSubtract` possible? I know it's nice to prefer full names, but that just seems excessive – that's 25 characters. (I'm not sure what else one would expect from a function named `Natural/subtract` (16 chars) other than truncated subtraction, especially once you know its type is total, `Natural -> Natural -> Natural`.)

**Comment by f-f** [comment]
I would also much prefer `subtract` instead of `truncatedSubtract`

**Comment by ocharles** [comment]
It was argued above: 

> I would be surprised if something named Natural/minus or Natural/subtract worked that way

And I'm inclined to somewhat agree.

But I don't have a huge stake in this other than I need it to exist. +/- 0 on whatever name we choose!

**Comment by Gabriel439** [comment]
I think we should continue this discussion on https://github.com/dhall-lang/dhall-lang/pull/650

**Comment by philandstuff** [comment]
Now that `Natural/subtract` is a thing, can this issue be closed @ari-becker?

**Comment by ari-becker** [comment]
@philandstuff 
@ocharles opened #674 , so let's put off closing this until that's merged in

**Comment by sjakobi** [comment]
#674 has been merged – let's close this! :rocket:
