### ISSUE TITLE
Syntax summary doesn't contain record projection by expression

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-lang#606]
I had expected to find record projection by expression listed in https://github.com/dhall-lang/dhall-lang/blob/master/standard/README.md#expressions.

**Comment by Nadrieril** [comment]
This is in the process of getting fixed : https://github.com/dhall-lang/dhall-lang/pull/601 :)

**Comment by sjakobi** [comment]
Fixed in https://github.com/dhall-lang/dhall-lang/commit/f0cd7157ee19296b8968003ce0524adc06fbb441.
