### ISSUE TITLE
I need to edit a Dhall file in VSCode

### ISSUE THREAD

**Issue by i-am-the-slime** [dhall-lang/dhall-lang#609]
It tells me that I need to point it to some `dhall-lsp-server` or whatever.
I did `brew install dhall` and that seems to have worked. I skimmed the README it doesn't mention LSP. The FAQ on the website don't mention it either. What do I do?

PS: the website looks like this on Safari:

<img width="1435" alt="Screenshot 2019-06-28 at 13 55 14" src="https://user-images.githubusercontent.com/1588055/60340657-76ea4500-99ac-11e9-9019-a7fc6fef049c.png">

**Comment by Gabriel439** [comment]
There's not yet a `brew` package for `dhall-lsp-server` because it's not yet on Hackage.  Once it is, we'll add a `brew` package for it.  Until then you will either need to wait or build from source:

https://github.com/dhall-lang/dhall-haskell#building-from-source

**Comment by Gabriel439** [comment]
Also, I'm leaving this issue open to track the Safari rendering issues, which I hope to fix soon

**Comment by Gabriel439** [comment]
Sorry for the delay, but the fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1160
