### ISSUE TITLE
Keep `let`s with multiple binders out of semantics

### ISSUE THREAD

**Issue by EggBaconAndSpam** [dhall-lang/dhall-lang#615]
The `dhall-haskell` implementation represents multi-lets, i.e. expressions of the form `let... let... in...`, explicitely in the AST. This turns out to be rather annoying to work with, see for example [Dhall.Lint](https://github.com/dhall-lang/dhall-haskell/blob/master/dhall/src/Dhall/Lint.hs). At the same time, I don't see what we gain from keeping multi-lets around in the AST at all?

More importantly, is there a reason why `dhall-lang` talks about multi-lets anywhere outside of the grammar for Dhall expressions?

I propose the following:
- Simplifiy the standard to consider `let... let... in...` _syntactic sugar_ (in the same sense that `x` is syntactic sugar for `x@0`) and revert most of [Add support for `let` expressions with multiple `let` bindings ](https://github.com/dhall-lang/dhall-lang/commit/022105eefee605f6e5b862b9d7816862b9db73e2).

Down the line, I would like to make the following changes in `dhall-haskell`:
- Change `Dhall.Parser` to parse multi-lets as nested lets binding one variable each
- In `Dhall.Core` change `Let (NonEmpty (Binding s a)) (Expr s a)` to `Let (Binding s a) (Expr s a)` (or inline `Binding` directly)

As far as I am concerned, this issue is purely a matter of aesthetics. Is there anything I am missing?

**Comment by ocharles** [comment]
> Change Dhall.Parser to parse multi-lets as nested lets binding one variable each

Typically such a thing is done as a desugaring phase. I would suggest we do that. If we want, we could use a Trees that Grow approach to have one `Expr` AST to rule them all, with a parser tag and a desugared tag.

**Comment by sjakobi** [comment]
> The `dhall-haskell` implementation represents multi-lets, i.e. expressions of the form `let... let... in...`, explicitely in the AST. This turns out to be rather annoying to work with, see for example [Dhall.Lint](https://github.com/dhall-lang/dhall-haskell/blob/master/dhall/src/Dhall/Lint.hs).

Can you expand on what you find annoying about multi-lets? The link to `Dhall.Lint` is unclear to me.

**Comment by EggBaconAndSpam** [comment]
> > Change Dhall.Parser to parse multi-lets as nested lets binding one variable each
> 
> Typically such a thing is done as a desugaring phase. I would suggest we do that. If we want, we could use a Trees that Grow approach to have one `Expr` AST to rule them all, with a parser tag and a desugared tag.

But why not just keep things simple? In the end, the information whether a binder came from its own `let` or from somewhere inside a multi-let is only ever used in the linter to nag about it ;)

**Comment by ocharles** [comment]
Doing one thing at a time *is* keeping things simple. A parser should be parsing, not translating into different syntax trees.

>  In the end, the information whether a binder came from its own let or from somewhere inside a multi-let is only ever used in the linter to nag about it ;)

Not strictly true, we may wish to have an "exact" printer in the future, that prints exactly what you give it.

**Comment by EggBaconAndSpam** [comment]
> Not strictly true, we may wish to have an "exact" printer in the future, that prints exactly what you give it.

Good point! Hadn't thought about that at all.

**Comment by EggBaconAndSpam** [comment]
> Can you expand on what you find annoying about multi-lets? The link to `Dhall.Lint` is unclear to me.

The problem here was that an earlier version of the linter didn't handle multilets correctly (it only ever looked at the first variable in any let block). Trying to implement the `removeUnusedBindings` rule directly turns out to get really complicated, which is why the current implementation needs a preprocessing step.

Not the best example, I admit, but the idea was to point out how easily multilets can introduce complexity.

**Comment by Gabriel439** [comment]
It's mainly so that we can preserve the original syntax exactly when doing, say, `dhall format`

However, the Haskell implementation is not completely consistent on this point.  For example, we don't preserve whether a string literal is an ordinary or multi-line string literal.

**Comment by singpolyma** [comment]
dhall-ruby does implement both flattening and unflattening for multilet to let and vice versa, as well as desugaring let to lambda application.

I would be on board with a change to have multilet just be sugar for nested let, would simplify implementation in some cases.

**Comment by Gabriel439** [comment]
We could certainly change the standard to just desugar multi-let to ordinary let.  It would simplify the let-related judgments.  The standard doesn't have to concern itself with preserving syntax

**Comment by EggBaconAndSpam** [comment]
> Typically such a thing is done as a desugaring phase. I would suggest we do that. If we want, we could use a Trees that Grow approach to have one `Expr` AST to rule them all, with a parser tag and a desugared tag.

Thanks @ocharles for pointing me to [Trees that Grow](http://www.jucs.org/jucs_23_1/trees_that_grow)! That name rang a bell but I'd not looked at the paper before.

**Comment by singpolyma** [comment]
> We could certainly change the standard to just desugar multi-let to ordinary let. It would simplify the let-related judgments. The standard doesn't have to concern itself with preserving syntax

I think if we do this we can still use the multilet binary format for all nested lets, just like we flatten applications in binary.

This change would simplify at least my typechecker.‎

**Comment by Gabriel439** [comment]
@singpolyma: Oh yeah, I agree that flattening nested `let`s for the binary format is still a good idea

**Comment by sjakobi** [comment]
Can this be closed now that #618 has been merged? To discuss the Haskell implementation, there is https://github.com/dhall-lang/dhall-haskell/issues/1185.

**Comment by f-f** [comment]
I think so, I'll close. Thanks @EggBaconAndSpam!

**Comment by Nadrieril** [comment]
I didn't realize at first but this is a slight breaking change: before, `let a=1 in let b=2 in 3` and `let a=1 let b=2 in 3` would have had different binary encodings, but now they have the same one. Should we maybe add a test for that ?

**Comment by philandstuff** [comment]
`let`s are removed by beta-normalisation, so the (by far) most common use cases of binary encoding - ie for caching and semantic hashing - aren’t affected by this change.

**Comment by Gabriel439** [comment]
Yeah, I plan to write this up as a "technically breaking change" in the `CHANGELOG` for the next release
