### ISSUE TITLE
What font to use to display DOUBLE SOLIDUS OPERATOR (2afd)?

### ISSUE THREAD

**Issue by muff1nman** [dhall-lang/dhall-lang#616]
Maybe slightly off topic, but I'm having a hard time finding a font that can display the DOUBLE SOLIDUS OPERATOR (2afd). What font do others use?

**Comment by muff1nman** [comment]
Finally found one that works: Symbola http://users.teilar.gr/~g1951d/

**Comment by Gabriel439** [comment]
For what it's worth: on OS X the default Terminal application uses "Dejavu Sans Mono" and Firefox uses "San Francisco"

**Comment by neongreen** [comment]
@muff1nman  Since recently, [Iosevka](https://github.com/be5invis/Iosevka/) supports all Dhall special symbols:

<img src="https://user-images.githubusercontent.com/1523306/70165859-ab3cfc80-16d4-11ea-9956-ef95845aa9df.png" width="400px">
