### ISSUE TITLE
Normalization of record projection

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-lang#622]
Just a few ideas I'd like to get feedback on:

#### Sorting of fields

```
λ(x : { a : Bool, b : Bool, c : Bool }) → x.{ c, a }
```
should normalize to
```
λ(x : { a : Bool, b : Bool, c : Bool }) → x.{ a, c }
```

#### Remove projection when it covers the entire record

```
λ(x : { a : Bool }) → x.{ a }
```
should normalize to
```
λ(x : { a : Bool }) → x
```

---

**EDIT:** This is already in the standard:

> #### Simplify projection by type to projection by fields
> 
> ```
> λ(x : { a : Bool, b : Bool }) → x.({ a : Bool })
> ```
> should normalize to
> ```
> λ(x : { a : Bool, b : Bool }) → x.{ a }
> ```

**Comment by Gabriel439** [comment]
@sjakobi: Yeah, those all seem like good ideas to me

**Comment by MonoidMusician** [comment]
> **Remove projection when it covers the entire record**
I've thought about this one before, and our conclusion was that this would require accessing type checking from normalization (i.e. interleaving the two) which is something that we don't want to do, at least at the present. So I think this one is out of reach with our current system.

The other two look good to me.

**Comment by sjakobi** [comment]
> > **Remove projection when it covers the entire record**
> 
> I've thought about this one before, and our conclusion was that this would require accessing type checking from normalization (i.e. interleaving the two) which is something that we don't want to do, at least at the present. So I think this one is out of reach with our current system.

Once the projection typechecks, isn't it enough to compare the size of the record with the number of fields in the projection? When the numbers are the same, the projection covers the entire record. A check like this should be fine for normalization, no?

Am I missing something?

**Comment by sjakobi** [comment]
> Am I missing something?

Sure I was! :)

We'd be talking about an abstract record with unknown size at normalization… Maybe we could eventually annotate expressions during typechecking with data like this. But we don't have the setup to do that right now!

**Comment by singpolyma** [comment]
> Simplify projection by type to projection by fields

This should be done already.

**Comment by Gabriel439** [comment]
Oh yeah, @singpolyma is right.  The standard already currently implements projection by type in terms of projection by keys.  See: https://github.com/dhall-lang/dhall-lang/blob/613347a526fb960e5895539631ebc107c172aaf2/standard/beta-normalization.md#records

Specifically:

```
s ⇥ { ss… }
keys(s) ⇥ s₁
t.{s₁} ⇥ ts₁
────────────
t.(s) ⇥ ts₁
```

**Comment by sjakobi** [comment]
Oh, thanks! I think I misunderstood that judgment. I'll remove it from the issue description.

**Comment by Gabriel439** [comment]
Thinking about this more, I believe @Nadrieril is right and we won't be able to (easily) remove projection when it covers the entire record.  Like they said, this requires interleaving type-checking with normalization in the case where the record to project is abstract, and provides no benefit when the record to project is concrete.

**Comment by Nadrieril** [comment]
@Gabriel439 I believe you meant to mention @MonoidMusician

I would add that we discussed something related here: https://github.com/dhall-lang/dhall-lang/issues/506
