### ISSUE TITLE
Allow annotations on empty lists other than "List …"

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-lang#623]
Code like `let T = … in [] : T` is currently disallowed – the annotation must be of the form `List …`:

https://github.com/dhall-lang/dhall-lang/blob/2c0f2389e11597131b8ce021344322e5ed3a9131/standard/dhall.abnf#L642-L647

This situation feels a bit constraining but I don't have a good motivating example.

Is this a constraint we want to lift?

**Comment by Gabriel439** [comment]
Yes, I believe we should lift this constraint.  This restriction is  a relic from back when `Optional`s used `List`-like syntax.

This would fix issues like https://github.com/dhall-lang/dhall-haskell/issues/770

**Comment by f-f** [comment]
> This would fix issues like dhall-lang/dhall-haskell#770

And https://github.com/dhall-lang/dhall-haskell/issues/414

Agreed that it would be nice to remove this constraint 👍
