### ISSUE TITLE
Undocumented breaking change with multiline strings

### ISSUE THREAD

**Issue by jvanbruegge** [dhall-lang/dhall-lang#632]
When updated to the newest version of dhall, some files did not compile any more due to parser errors:
```dhall
let multiline = ''
sometext '' ++ someExpression ++ ''more text
other text''
```
The issue is the "more text", the new parser expects a newline after `''`, the old one did not. I could not find this in the changelog, so maybe this is an accident.

It is not that bad because TIL that multiline strings still allow for interpolation, so the code above can be converted to (the much nicer):
```dhall
let multiline = ''
sometext ${someExpression}more text
other text''
```

Conclusion: IMO, adding this to the changelog is enough as a prettier solution exists

**Comment by f-f** [comment]
@jvanbruegge this change happened in [v5.0.0](https://github.com/dhall-lang/dhall-lang/releases/tag/v5.0.0), when multi-line strings were standardized for the first time (note that they also had a breaking change in latest, which seems to be unrelated here)

Before the `v5.0.0` release multi-line strings were not in the standard, so the breaking change happened in the `dhall-haskell` implementation of a "non-standard feature"

**Comment by jvanbruegge** [comment]
Ahh, I see, that's why I could not find it. Closing this then
