### ISSUE TITLE
Binary encoding : Duplicate usage of the label 27

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-lang#643]
Both empty lists with funny annotations and `toMap` expressions use the CBOR label 27 now:

```
encode(T₀) = T₁
────────────────────────────
encode([] : T₀) = [ 27, T₁ ]
```

```
encode(t₀) = t₁
─────────────────────────────
encode(toMap t₀) = [ 27, t₁ ]


encode(t₀) = t₁   encode(T₀) = T₁
──────────────────────────────────────
encode(toMap t₀ : T₀) = [ 27, t₁, T₁ ]
```

I had overlooked the changes for `toMap` when merging https://github.com/dhall-lang/dhall-lang/pull/630.

Should we switch to 28 for the empty lists?

**Comment by Gabriel439** [comment]
@sjakobi: Yeah, that sounds fine
