### ISSUE TITLE
Mixed records of values and types

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-lang#658]
@Gabriel439 [recently](https://github.com/dhall-lang/dhall-lang/pull/634#issuecomment-512564012) brought up the issue of mixed records when I asked whether the prelude's `package.dhall` should also include types.

The basic idea seems pretty simple:

> Basically, you change the type-checking judgments for records so that the type of a record type is just the upper bound of the type of its field types (which I understand is what Agda does to support this). In other words:
> 
>     { foo = 1 } : { foo : Integer } : Type
> 
>     { bar = Bool } : { bar : Type } : Kind
> 
>     { foo = 1, bar = Bool } : { foo : Integer, bar : Type } : Kind 

In fact, Dhall used to have mixed records, but they were removed in #120 as @Gabriel439 [explains](https://github.com/dhall-lang/dhall-lang/pull/634#issuecomment-513479733).

Now, with CCω, we could bring them back.

Is there any reason why we shouldn't?

**Comment by ocharles** [comment]
I'm working on this in https://github.com/dhall-lang/dhall-haskell/pull/1173. Standard changes to come once I've got the implementation correct.

**Comment by sjakobi** [comment]
#689 standardized this.
