### ISSUE TITLE
Normalization for ⫽ and projection

### ISSUE THREAD

**Issue by fizruk** [dhall-lang/dhall-lang#661]
I have encountered a problem that leads to a significant slowdown when loading Dhall configs (it takes minutes sometimes!).

Here's a simplified version of what I'm doing:

```dhall
let Prelude/List/map =
      https://raw.githubusercontent.com/dhall-lang/Prelude/35deff0d41f2bf86c42089c6ca16665537f54d75/List/map

-- Types used below. We will effectively write "migrations" T1 -> T2 -> T3 -> T4.
let T1 = { a : Natural }
let T2 = { a : Natural, b : Text }
let T3 = { z : List { a : Natural, b : Text } }
let T4 = { z : List { b : Text, c : List Natural } }

let f = λ(old : T1) → old ⫽ { b = "Hello" }
let g = λ(old : T2) → { z = [ old, old.{ a } ⫽ { b = "Bye" } ] : List T2 }
let h_ = λ(old : T2) → old.{ b } ⫽ { c = [ old.a ] : List Natural }
let h =
        λ(old : T3)
      → { z = Prelude/List/map T2 { b : Text, c : List Natural } h_ old.z }

-- all "migrations" combined
let k = λ(old : T1) → h (g (f old))

in k
```

Now this code when normalized produces a few duplications:

```dhall
  λ(old : { a : Natural })
→ { z =
      [ (old ⫽ { b = "Hello" }).{ b } ⫽ { c = [ (old ⫽ { b = "Hello" }).a ] }
      ,   ((old ⫽ { b = "Hello" }).{ a } ⫽ { b = "Bye" }).{ b }
        ⫽ { c = [ ((old ⫽ { b = "Hello" }).{ a } ⫽ { b = "Bye" }).a ] }
      ]
  }
```

However, if I replace all `old` and `old.{ ... }` (to the left of every `⫽`) with corresponding explicit records like this:

```diff
- let f = λ(old : T1) → old ⫽ { b = "Hello" }
+ let f = λ(old : T1) → { a = old.a } ⫽ { b = "Hello" }
- let g = λ(old : T2) → { z = [ old, old.{ a } ⫽ { b = "Bye" } ] : List T2 }
+ let g = λ(old : T2) → { z = [ old, { a = old.a } ⫽ { b = "Bye" } ] : List T2 }
- let h_ = λ(old : T2) → old.{ b } ⫽ { c = [ old.a ] : List Natural }
+ let h_ = λ(old : T2) → { b = old.b } ⫽ { c = [ old.a ] : List Natural }
```

Then it all gets normalized very well:

```dhall
  λ(old : { a : Natural })
→ { z = [ { b = "Hello", c = [ old.a ] }, { b = "Bye", c = [ old.a ] } ] }
```

So my understanding is that there are missing normalization rules for projection and `⫽`.

**Comment by sjakobi** [comment]
Interesting!

An additional rule that simplifies e.g. `x.{ a, b }` to `{ a = x.a, b = x.b }` should do the trick. I'll give this a try in the Haskell implementation.

**Comment by fizruk** [comment]
> Interesting!
> 
> An additional rule that simplifies e.g. `x.{ a, b }` to `{ a = x.a, b = x.b }` should do the trick. I'll give this a try in the Haskell implementation.

I believe that it will not solve cases when I am not using `old.{...}` and simply write `old // { ... }`.

**Comment by sjakobi** [comment]
Ok. Expanding a projection into a new record literal gets us to 

```
  λ(old : { a : Natural })
→ { z =
      [ { b = (old ⫽ { b = "Hello" }).b, c = [ (old ⫽ { b = "Hello" }).a ] }
      , { b = "Bye", c = [ (old ⫽ { b = "Hello" }).a ] }
      ]
  }
```

We'll also need field selection to inspect the arguments of `⫽`.

**Comment by sjakobi** [comment]
> We'll also need field selection to inspect the arguments of `⫽`.

In fact, we only need to inspect the second argument.

I wonder whether expanding `x.{ a, b } to { a = x.a, b = x.b }` is a good idea in general though. We should probably only do it within a field selection.

**Comment by sjakobi** [comment]
`x.{ ys… }` currently only simplifies to a record literal if `x` is a record literal. (See https://github.com/dhall-lang/dhall-lang/blob/master/standard/beta-normalization.md#records)

Generally expanding `x.{ a, b, … }` to `{ x.a, x.b, … }` might cause problems when we repeatedly evaluate `x`.

It should always be ok to normalize `x.{ a }` to `{ x = x.a}` though.

**Comment by sjakobi** [comment]
@fizruk You might be interested in the discussion at #274 that explains why (at least 8 months ago) there's a preference not to add more normalization rules to the language standard.

As there does seem to be some demand for stronger normalization, I think it might make sense to have an alternative normalizer implementing additional normalization rules. That should be fairly easy to build on top of the Haskell `dhall` library.

**Comment by sjakobi** [comment]
The recently added simplifications get us to

```
  λ(old : { a : Natural })
→ { z =
      [ (old ⫽ { b = "Hello" }).{ b } ⫽ { c = [ old.a ] }
      ,   ((old ⫽ { b = "Hello" }).{ a } ⫽ { b = "Bye" }).{ b }
        ⫽ { c = [ old.a ] }
      ]
  }
```

What remains to be done is to simplify

    (old ⫽ { b = "Hello" }).{ b } ⫽ { c = [ old.a ] }

to 

    { b = "Hello", c = [ old.a ] }

and 

    ((old ⫽ { b = "Hello" }).{ a } ⫽ { b = "Bye" }).{ b } ⫽ { c = [ old.a ] }

to

     { b = "Bye", c = [ old.a ] }

Both cases would be fixed by having a rule roughly like

```
(x // { k = v }).{ k }
––––––––––––––––––––––
{ k = v }
```

I'll make a proposal for something along these lines.
