### ISSUE TITLE
`Text` vs. `as Text`

### ISSUE THREAD

**Issue by angerman** [dhall-lang/dhall-lang#67]
I've just found out that I can do `let value = "x" in "value = ${value}"`.
But I can not do `let value = "x" in (./template as Text)`
where `template` contains `"value = ${value}"`.

The first results in `x`; the second in `${value}`.

This would be really nice to have for `dhall-to-text` as it would allow
separating the template from the driver.

**Comment by Gabriel439** [comment]
This limitation is intentional.  Imported Dhall expressions (such as `./template`) have to be closed (i.e. no free variables like `value` in your example) so that they can be type-checked in isolation.

**Comment by angerman** [comment]
Is there a way around it? E.g. to inject some textual value verbatim prior to the typechecker?

I‘d rather not have a `\(...) -> ''` first and `''` last line in say a HTML file.

**Comment by Gabriel439** [comment]
Yes, but only if you're willing to use the Haskell API to build your own tool.  The Haskell API provides a `typeWith` function that you can use to type-check expressions using your own custom context.  Similarly, there is a `normalizeWith` that you can use to inject custom values

**Comment by angerman** [comment]
Could `dhall-to-text` gain a primitive for that, hypothetically speaking?

**Comment by Gabriel439** [comment]
Yeah, I'd be fine with providing a utility function that bundles `typeWith`+`normalizeWith`+`{adding single quotes before parsing}`

**Comment by asivitz** [comment]
I would love this. I was thinking about making a Dhall compiler for Hakyll, and would probably end up implementing this myself if it weren't in the Dhall lib.

**Comment by f-f** [comment]
Should we move this issue to `dhall-haskell`? As far as I understand it is about adding a flag (`--wrap-text`?) to `dhall-to-text`

**Comment by Gabriel439** [comment]
@f-f: Yes, my understanding is that this is a `dhall-haskell`-related issue, although I think the request here is for a new function in the Haskell API for ease of templating rather than a new command-line option.

**Comment by Nadrieril** [comment]
Having the ability to import templates from files sounds cool though.
I imagine the following: if `file` contains `A ${string} with ${interpolations}`, then `(./file as Template) { string = "blah", interpolations = "blih" }` would normalize to the string `A blah with blih`.

**Comment by Gabriel439** [comment]
@Nadrieril: See the discussion on the linked pull request:

https://github.com/dhall-lang/dhall-haskell/pull/205

... and also the discussion on this related issue:

https://github.com/dhall-lang/dhall-haskell/issues/676

**Comment by Nadrieril** [comment]
Oh. Too bad, I liked this idea, but you make convincing points

**Comment by ocharles** [comment]
https://github.com/dhall-lang/dhall-haskell/pull/205 says

> I'll go ahead and close this since it's unlikely to be added to the language standard

Should this issue also be closed?

**Comment by Gabriel439** [comment]
Yeah, I will close this issue, too
