### ISSUE TITLE
Pinned versions of Prelude at prelude.dhall-lang.org?

### ISSUE THREAD

**Issue by ari-becker** [dhall-lang/dhall-lang#670]
Currently https://prelude.dhall-lang.org/package.dhall points to the latest version of Prelude, which is part of the 9.0.0 release.

We just had a few CI builds crash since they had frozen the imports to the hash value corresponding to the 8.0.0 release, and besides, the version of `dhall-haskell` supporting 9.0.0 isn't quite yet out.

Can we get support for something like `https://prelude.dhall-lang.org/v8.0.0/package.dhall`, directing to the pinned version?

Current workaround is to import `https://raw.githubusercontent.com/dhall-lang/dhall-lang/v8.0.0/Prelude/package.dhall`, which is mostly the same thing except, if I recall correctly, `prelude.dhall-lang.org` responds with the CBOR binary instead of text.

**Comment by singpolyma** [comment]
`prelude.dhall-lang.org` is just a redirect AFAIK to allow for shorter import URLs.  However I think being able to refer to a particular version there would be useful anyway.

**Comment by Gabriel439** [comment]
I'm working on it.  I just need to learn enough `nginx`-fu to get this working

**Comment by quasicomputational** [comment]
@Gabriel439, is the config online somewhere, ideally able to accept PRs?

**Comment by Gabriel439** [comment]
@quasicomputational: Yes!  You can find the configuration here: https://github.com/dhall-lang/dhall-lang/blob/master/nixops/logical.nix#L157-L290
