### ISSUE TITLE
String interpolation for `env:"VAR"`

### ISSUE THREAD

**Issue by alexhumphreys** [dhall-lang/dhall-lang#676]
It's possible import an environment variable like so:
```dhall
{ home = env:"PATH" as Text }
```

I'm wondering is something like this possible?

```dhall
let map = https://raw.githubusercontent.com/dhall-lang/dhall-lang/3efe5695d06e429067a842af27e642fc97ae08e5/Prelude/List/map

let keys =
  [ "HOME"
  , "PWD"
  , "PATH"
  ]

let assignValue = \(key : Text) ->
  { k = key, v = (env:"${key}" as Text)} -- env var name passed via dhall variable

in map Text { k : Text, v : Text } assignValue keys
```

From looking around the repo I'm guessing the `"PATH"` passed to `env:"PATH"` isn't a normal string with interpolation, and handles [posix variables](https://github.com/dhall-lang/dhall-lang/blob/3e236d8c6b969b5ae5a484c831751da4f54d1b54/tests/parser/success/unit/import/environmentVariablePosixA.dhall) or something?

If this isn't possible currently, would this be useful?

My specific use case is using [vaultenv](https://github.com/channable/vaultenv#secret-specification) to populate env vars which I then pass to `dhall-to-yaml` for a yaml config. I ran into this when I tried to make a list of the env vars I need in dhall, then use that one dhall list to render both the `vaultenv` config using `dhall text`, and the yaml config with `dhall-to-yaml`.

**Comment by f-f** [comment]
@alexhumphreys for security reasons it's not possible to "template" imports, and indeed the `"PATH"` in `env:"PATH"` is not a Dhall string per se, as imports are resolved before any Dhall evaluation takes place (there is one special case: HTTP imports headers)

We kind of discussed this issue in https://github.com/dhall-lang/dhall-lang/issues/169, and at the time I ended up solving the issue by doing "multiple passes" of Dhall evaluation (generating more Dhall in the process), as detailed in https://github.com/dhall-lang/dhall-lang/issues/169#issuecomment-414916674
Would this solve your usecase?

**Comment by alexhumphreys** [comment]
Ah those security reasons make a lot of sense alright. I should be able to work something out with that multiple pass solution though. Thanks for the quick reply!

**Comment by f-f** [comment]
You're welcome 🙂
