### ISSUE TITLE
Type for a List guaranteed to be non-empty?

### ISSUE THREAD

**Issue by ari-becker** [dhall-lang/dhall-lang#691]
I've run into some cases recently where the target has a requirement for a `List` which is guaranteed to have at least one list entry, i.e. to be non-empty. If the target is provided with an empty list, then it throws an error.

It seems like the only way to do this currently is to have some kind of `{ first : X , rest : List X }` requirement exposed and then call `Prelude.List.concat X [ [ first ] , rest ]` in some intermediate or final rendering function, but this feels clunky, particularly if the input is naturally already in list form and then would need to split off not just the head (`Prelude.List.head`, ok...) but the tail into `rest` (which isn't immediately obvious how to do, if the language needed a truncating `Natural/subtract` then doing so would probably require a truncating `List/remove` which returned an empty list upon trying to remove an element from an empty `List`, but I digress).

Ideally I'd have some kind of `[] : PopulatedList` or maybe something with the new dependent typing support, like `[] : List | length > 0 | Text` (if that didn't interfere with union grammar).

SIde note: I could have sworn that this was asked before, but couldn't find anything, so, sorry if this is a duplicate.

**Comment by Nadrieril** [comment]
`{ first : X , rest : List X }` is how [it's done in Haskell](https://hackage.haskell.org/package/semigroups-0.18.1/docs/Data-List-NonEmpty.html), so I'd say it would make sense to add this type to the Prelude.
I'm pretty sure the dependent type approach can't work for now; we currently can't prove anything non-trivial.

**Comment by FintanH** [comment]
We've defined some handy `NonEmptyList` functionality here: https://github.com/FormationAI/dhall-bhat/tree/master/NonEmptyList

**Comment by Gabriel439** [comment]
Yeah, I'd just go with `{ head : a, tail : List a }`.  This is exactly how Haskell does it.

**Comment by ari-becker** [comment]
OK cool, I'll close this then. Putting a little more thought into it, I guess it's difficult by design to go from a `List` to a `PopulatedList` kind of object since then `head` would have to be Optional and that would defeat the purpose.
