### ISSUE TITLE
Precedence of ===

### ISSUE THREAD

**Issue by Nadrieril** [dhall-lang/dhall-lang#701]
Currently, the equivalence operator `===` binds very strongly, which means that for example `1 + 1 === 2` parses as `1 + (1 === 2)`. I don't find that intuitive, since we will often want to have operations on either side of the equivalence, but never on the outside. Could we change its precedence so it binds weaker than all the other operators instead ?

**Comment by Gabriel439** [comment]
Sure.  The only reason I gave it such low precedence was so that parsers would attempt to parse `===` before `==`, but that could be fixed

**Comment by sjakobi** [comment]
> for example `1 + 1 === 2` parses as `1 + (1 === 2)`.

I was just surprised by this – it would be nice to get this fixed!

**Comment by Nadrieril** [comment]
Fixed in #954
