### ISSUE TITLE
Proposal: allow `.` (dot) in labels

### ISSUE THREAD

**Issue by amarrella** [dhall-lang/dhall-lang#702]
Hello, I think that currently the standard doesn't allow dots in labels.

Since the introduction of `toMap` I would like to migrate my old Kubernetes templates (based on the excellent `dhall-kubernetes`) to use the new `toMap` syntax but plenty of labels in the kubernetes world contain dots and `/` (reverse dns notation mostly). While `/` doesn't seem to have problems, I think the standard doesn't support dots.

Would it be possible to introduce them to the allowed characters in https://github.com/dhall-lang/dhall-lang/blob/master/standard/dhall.abnf#L201 ?

Let me know what you think :)
Thanks again for this project!
Alessandro

**Comment by ocharles** [comment]
You need to quote the labels:

```dhall
{ `hello.world` = True }
```

**Comment by amarrella** [comment]
Oh i was trying to do it directly on the shell but it didn't work due to the meaning of ` there.

I tried again by writing that into a file and it worked. That's great! Thank you! :) 

I'll close the issue

**Comment by ocharles** [comment]
Great, happy to help!
