### ISSUE TITLE
Import path as absolute path to file

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-lang#71]
What do you think about `as FilePath`? It would be really nice to be able to write configuration files that encode a path existence check. Obviously this can be done in my library if I have `Text` fields, but then my users are forced to write string literals, when Dhall actually has syntax for file paths.

**Comment by ocharles** [comment]
I guess if https://hackage.haskell.org/package/dhall-1.8.2/docs/Dhall-Parser.html exported `pathParser :: Parser Path` I could use `exprA (Left <$> absoluteFileParser <|> Right <$> pathParser)`, and then a custom stage to expand absolute file paths into text literals or imports as necessary. Still, seems like it could be common enough for Dhall to learn this.

**Comment by Gabriel439** [comment]
Yeah, this seems like a good idea to me and I think it would be simple to standardize and implement because that information.  My only suggestion is to wait until I finish the import semantics standardization (ETA: ~1 month at current rate) so that this can be proposed as a diff to that standard

Also, would this still have type `Text` or did you intend this to return a new `FilePath` type?

Also, one minor suggestion I have is to shorten the name to `as Path`

**Comment by ocharles** [comment]
Cool, I'm happy to wait - no rush on my side. A `FilePath` type seems more sensible, assuming that `http://foo as Path` doesn't type check. Could do `as URI` and have local paths expand to absolute `file:///` paths too. Was mostly spit-balling though, I have no real feelings on the colour of the bike shed.

**Comment by Gabriel439** [comment]
Note that if you have a relative path within a Dhall expression it could expand out to either a filesystem path or URI depending on how the surrounding expression was imported.  I'm assuming that if you had separate `as Path` and `as URI` features, you would be okay with the behavior changing (i.e. possibly rejecting the relative path literal) depending on where the expression was hosted?  Maybe you would even consider that a feature (i.e. ensure that it doesn't expand out to a URI)

I'm also assuming that there would be matching `Path/toText` and `URI/toText` built-ins, too

**Comment by Gabriel439** [comment]
Or perhaps I should use `as File` instead of `as Path` to make it clear that it comes from the filesystem, whereas `Path` can be the more general term for something that could be either a `URI` or `File`

**Comment by Gabriel439** [comment]
Oh yeah, good point.  `File` would suggest reading the contents of the file, not the path to it.

**Comment by ocharles** [comment]
Another thought on this, it would be quite nice if I could have properly typed URLs for `dhall-to-cabal` too:

```dhall
homepage = https://github.com/ocharles/dhall-to-cabal as URL
```

or something. Perhaps related to this.

**Comment by Gabriel439** [comment]
Yeah, I was assuming that this would include `as URL`, too

**Comment by ocharles** [comment]
@kirelagin has done a great job laying the ground work here. What sections of the standard documents need to change? I tried looking for `as Text`, but couldn't really see it.

**Comment by Gabriel439** [comment]
@ocharles: This is because `as Text` has not yet been standardized because I keep forgetting to :slightly_smiling_face: 

The relevant part of the standard to change would be somewhere around here:

https://github.com/dhall-lang/dhall-lang/blob/master/standard/semantics.md#import-resolution-judgment

I can get around to it myself soon, if necessary

**Comment by ocharles** [comment]
If you can do `Text`, I can follow suit with `URL` and `(File)Path`.

**Comment by f-f** [comment]
@Gabriel439 related: do we have a checklist somewhere of "stuff that is implemented but needs to be standardized"? If not, let's have an umbrella-issue in `dhall-lang` for it

I think we are missing only:
- `as Text`
- multiline strings

**Comment by Gabriel439** [comment]
@f-f: Alright, I created the relevant issues and added the "standardize me" label to track them:

https://github.com/dhall-lang/dhall-lang/labels/standardize%20me

**Comment by f-f** [comment]
It looks like we stumbled on a use-case for this one in https://github.com/spacchetti/spago/issues/244

The problem we have there is that relative paths are included in configurations as `Text`. The application gets them as they were typed bby the user, but the fact that Dhall files can have relative import means that in some cases the paths will not be correct anymore. So a "relative → absolute" resolution based on the location of the Dhall file (and not on the `CWD` of the program) as described above would solve this

I can take a stab at standardizing this, but I have some questions:
- Are we fine with having a new `Location` type or should we have several, like `FilePath`, `URI`, etc. If so, why should we have more than one?
- As the PR linked above implemented, I think `env:SOMEVAR as Location` would cause an error?

**Comment by Gabriel439** [comment]
I think whether or not to have two separate types comes down to whether or not we want the type of the expression to change if imported remotely vs locally.

The argument in favor of one type is that code still functions when hosted remotely vs locally (similar to the reason we support custom header forwarding and relative import resolution for remote imports).

The argument against is that code might only work for a path and break for a URL, so the type changing when imported remotely is a feature from that point of view.

**Comment by Gabriel439** [comment]
Another way to approach this could be for `as Location` to instead return a union of a type like this:

```
someImport as Location : < Local : Text | Remote : Text | Environment : Text | Missing >
```

... that way you don't need any additional types/conversion-functions and code can choose to handle as many cases as the tool supports.  In other words, if a tool can handle both `Local` and `Remote` paths then it can implement support for that.

**Comment by f-f** [comment]
@Gabriel439 @ocharles PR for standardizing this up in #585

**Comment by f-f** [comment]
I'll reopen this to continue discussing `as AbsolutePath` as detailed in https://github.com/dhall-lang/dhall-lang/pull/585#discussion_r294060311

**Comment by philandstuff** [comment]
This has been open for over a year.  I'm going to close.  If there's still a desire for `as AbsolutePath`, feel free to reopen or open a new issue.
