### ISSUE TITLE
Remove support for `@`

### ISSUE THREAD

**Issue by Gabriel439** [dhall-lang/dhall-lang#72]
One of the lesser-known features of Dhall's import system that it inherited from Morte is that you can import a directory if that directory has a file named `@` (Similar to how `default.nix` works for Nix).  However, as part of standardizing the import semantics I would like to remove support for this feature because it considerably complicates the semantics (for example: computing paths relative to an `@` file) and also deteriorates error messages (for example, if an import fails it has to fall back to also trying `./@` which can lead to confusing errors).

I'm mainly opening this issue to broadcast that I will likely remove this feature as a breaking change.  Feel free to object if you are particularly attached to this feature.

**Comment by ocharles** [comment]
Yes please. I feel `default.nix` was a mistake, and I'm still yet to really understand the point of it.

**Comment by Gabriel439** [comment]
Closing as this is fixed in the sense that the standard will not add this feature and the Haskell implementation has removed support for this

**Comment by Profpatsch** [comment]
> I feel default.nix was a mistake

I originally thought so, too, but recently I’ve come to appreciate that I always know where to look first when I open a folder with nix files.
