### ISSUE TITLE
Type inference for recursive record merges

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-lang#721]
It seems to me that https://github.com/dhall-lang/dhall-lang/commit/0476e452d48bf0899408c4f9cc0220d8b3139ee0 requires changes in the expected output of the type-inference tests. The test description says:

> The tests should:
>
> * parse A and B
> * infer the type of A
> * the inferred type of A should exactly match B

My interpretation is that `{ x : Bool } ⩓ { y : Natural }` does _not_ exactly match `{ x : Bool, y : Natural }`

By this interpretation the correct inferred type for 

    {=} ∧ { x = True }

no longer is

    { x : Bool }

Instead it should be

    {} ⩓ { x : Bool }

Is my reasoning correct? Or is it a misunderstanding that the type inference spec also defines the normalization of the inferred type?

**Comment by Nadrieril** [comment]
Ah, you are very correct. This was an oversight on my part: I intended to normalize the output of the record type merge so that type inference stays as it was
