### ISSUE TITLE
How to interpret "Normalizing an expression doesn't change its type"?

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-lang#726]
This is one of the [soundness rules](https://github.com/dhall-lang/dhall-lang/blob/cf74e7cfe999595d5f9c1683e75a226ca1288147/.github/CONTRIBUTING.md#soundness-of-proposed-changes) in the CONTRIBUTING document.

What is it supposed to mean?

A) The type of an expression should _exactly match_ the type of the normalized expression
or
B) Both types should be [equivalent](https://github.com/dhall-lang/dhall-lang/tree/cf74e7cfe999595d5f9c1683e75a226ca1288147/standard#equivalence) after normalization.

If (A) is the correct interpretation, a few type inference judgments would probably have to change, starting with [record projection by type](https://github.com/dhall-lang/dhall-haskell/issues/1274). #724 might help, too.

**Comment by Nadrieril** [comment]
I'd go with B), because I feel the "exactly match" relation doesn't make a lot of semantic sense. The only time we could care about it is when outputting a type to a user, and even then I would prefer that implementations be free to output an equivalent type if that could e.g. improve legibility

**Comment by Gabriel439** [comment]
Yeah, I meant (B) when I wrote that

**Comment by sjakobi** [comment]
Thanks for the clarification! :+1:

**Comment by Gabriel439** [comment]
@sjakobi: You're welcome! 🙂
