### ISSUE TITLE
"merge handlers" should typecheck on its own

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-lang#727]
The union type can be inferred from the handlers record.

    \(u : <Foo | Bar>) -> merge { Foo = True, Bar = False } u

could then be shortened to

    merge { Foo = True, Bar = False }

**Comment by MonoidMusician** [comment]
Yes, this has been discussed before in https://github.com/dhall-lang/dhall-lang/issues/106. Having unions with optional fields makes it harder now though.

**Comment by sjakobi** [comment]
Ah, thanks for the link – closing as a duplicate.
