### ISSUE TITLE
Can we drop the mandatory type annotations on Optional and List?

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-lang#73]
Title says it all, these feel like a bit of a wart in what is otherwise a lovely format to work in.

**Comment by Gabriel439** [comment]
Note that type annotations are not required on non-empty lists

I'm reasonably sure they will be required on empty lists and optionals for the foreseeable future.  However, `Optional` could be reworked to possibly omit them on non-empty `Optional` values

**Comment by ocharles** [comment]
I see now that this is really to drive the typing judgement because you don't do inference. One question is to first ask if that's set in stone, or would we be open to adding some type inference?

**Comment by felix91gr** [comment]
Hmm. Type inference is very CPU intensive and it’s not trivial to implement
efficiently.

That said, dhall isn’t turing-complete, so there may be some really easy
way to do type inference that I don’t know of. What’s there in the
literature?

**Comment by Gabriel439** [comment]
For me the main constraint is how difficult it is to standardize any type-checking algorithm that uses type inference.  I'm not ruling it out but I'd like to see additional backends for Dhall before making large changes to the semantics

**Comment by f-f** [comment]
@ocharles since https://github.com/dhall-lang/dhall-lang/pull/227 `Optional`s containing a value don't need a type annotation, and I'd say this is the most we can do for now. So we can probably close this?

**Comment by ocharles** [comment]
I'd be OK with that. I still think ultimately the lack of type inference is something we'll need to address, but this issue isn't the place for it. Closing!
