### ISSUE TITLE
customHeadersUsingBoundVariable test

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-lang#748]
https://github.com/dhall-lang/dhall-lang/blob/06b2dfca29c3801441b468a7bce0d3b42d2a2494/tests/type-inference/failure/customHeadersUsingBoundVariable.dhall#L1-L15

Which part of the standard says that this is illegal?

In particular, I don't find anything in type-inference.md, so I'm wondering why this is part of the type-inference tests.

**Comment by Gabriel439** [comment]
@sjakobi: It's in `imports.md`, specifically in the import resolution judgment for custom headers:

```
(Δ, parent) × Γ₀ ⊢ requestHeaders ⇒ resolvedRequestHeaders ⊢ Γ₁
ε ⊢ resolvedRequestHeaders : H  ; ← Here
…
──────────────────────────────────────────────────────────────────────────  ; * child ∉ Δ
(Δ, parent) × Γ₀ ⊢ https://authority directory file using requestHeaders ⇒ e₁ ⊢ Γ₂
```

That says that when type-checking the custom headers expression you have to type check it with an empty context.

**Comment by sjakobi** [comment]
> That says that when type-checking the custom headers expression you have to type check it with an empty context.

Ah, thanks. Maybe we should add a verbal note to point this out.

I'd also like to move the `customHeadersUsingBoundVariable` test (and [`importBoundary`](https://github.com/dhall-lang/dhall-lang/blob/06b2dfca29c3801441b468a7bce0d3b42d2a2494/tests/type-inference/failure/importBoundary.dhall)) into the import tests. The motivation is that in the `dhall-haskell`'s test setup for type-inference failure tests, we currently have to handle both import resolution errors _and_ errors from the following type-checking phase. Handling multiple failure modes can mask issues where tests (expectedly) fail for the wrong reason. I'm currently fixing such an issue in https://github.com/dhall-lang/dhall-haskell/pull/1326.

Or are there good reasons why these tests should be part of the type-inference tests?

**Comment by Gabriel439** [comment]
I think those tests make sense to put under import tests
