### ISSUE TITLE
Cannot import Optional

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-lang#75]
I found the following quite surprising:

```
[nix-shell:~/work/dhall-to-cabal]$ dhall <<< '[] : Optional Natural'
Optional Natural

[] : Optional Natural

[nix-shell:~/work/dhall-to-cabal]$ echo 'Optional Natural' > foo

[nix-shell:~/work/dhall-to-cabal]$ dhall <<< './foo'
Type

Optional Natural

[nix-shell:~/work/dhall-to-cabal]$ dhall <<< '[] : ./foo'

Error: Invalid input

(stdin):1:2: error: expected: expression,
    whitespace
[] : ./foo
```

Is this intended?

I actually ran into this in `dhall-to-cabal`, where I wrote:

```dhall
      , library     =
          [ { build-dependencies =
                [ common-deps.base
                , common-deps.Cabal
                , common-deps.dhall
                , common-deps.text
                , common-deps.bytestring
                , { bounds = majorVersion [ +0, +5 ], package = "containers" }
                , { bounds = majorVersion [ +0, +12 ], package = "vector" }
                , { bounds = majorVersion [ +1, +7 ], package = "trifecta" }
                , { bounds = majorVersion [ +0, +3 ], package = "text-format" }
                ]
            , exposed-modules    = [ "Distribution.Package.Dhall" ]
            , hs-source-dirs     = [ "lib" ]
            , name               = [] : Optional Text
            , other-modules      = [] : List Text
            }
          ] : ./dhall/types/Library
```

And got

```
...
... with this type or kind:                                                     
                                                                                
↳ Optional { build-dependencies : List { bounds : VersionRange, package : Text }, exposed-modules : List Text, hs-source-dirs : List Text, name : Optional Text, other-modules : List Text }                                                                
                                                                                
... but the inferred type or kind of the expression is actually:                
                                                                                
↳ List { build-dependencies : List { bounds : VersionRange, package : Text }, exposed-modules : List Text, hs-source-dirs : List Text, name : Optional Text, other-modules : List Text }
```

That is, it expected `Optional` but for some reason got infered as `List` - even though the import is an `Optional` type. `Library` contains:

```dhall
Optional
{ build-dependencies : List { bounds : VersionRange, package : Text }
, exposed-modules    : List Text
, hs-source-dirs     : List Text
, name               : Optional Text
, other-modules      : List Text
}
```

**Comment by Gabriel439** [comment]
Yes, this is definitely intentional.  The `Optional` in `[] : Optional t` is required by the parser, not the type-checker.  You cannot import the `Optional` part of the type because that's the part that distinguishes a `List` from an `Optional` in the grammar.

For the same reason, you can't do:

```haskell
[] : (let t = Optional Integer in t)
```

However, you can import the type parameter of the `Optional`.  In other words, this is valid:

```haskell
[] : Optional ./foo
```

**Comment by Gabriel439** [comment]
The relevant parts of the standard grammar are here:

https://github.com/dhall-lang/dhall-lang/blob/master/standard/dhall.abnf#L562-L564

**Comment by ocharles** [comment]
Ok, maybe scope for a better error message then?

On 20 Jan 2018 5:00 pm, "Gabriel Gonzalez" <notifications@github.com> wrote:

The relevant parts of the standard grammar are here:

https://github.com/dhall-lang/dhall-lang/blob/master/
standard/dhall.abnf#L562-L564

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dhall-lang/dhall-lang/issues/75#issuecomment-359185604>,
or mute the thread

**Comment by Gabriel439** [comment]
The main reason that the parsing error message is not more accurate is because the parser has to backtrack when parsing an empty `Optional` value or `List`.  See: https://github.com/dhall-lang/dhall-lang/blob/master/standard/dhall.abnf#L554

Fixing that to not require backtracking would either require increasing the complexity of the grammar or (I think) possibly switching to a LALR parser

**Comment by Gabriel439** [comment]
I will go ahead and close this as I think it's superseded by changes to the `Optional` literals to now use `Some` and `None`.  Although we do still support the old `Optional` syntax it is deprecated and will eventually be removed.
