### ISSUE TITLE
`References/Semantics` link is broken

### ISSUE THREAD

**Issue by vvv** [dhall-lang/dhall-lang#751]
To reproduce:
- Open https://dhall-lang.org
- Click `References` in the upper part of the page
- Click `Semantics`

The resulting page https://github.com/dhall-lang/dhall-lang/blob/master/standard/semantics.md does not exist.

**Comment by sjakobi** [comment]
Hmm. For me "Semantics" links to https://github.com/dhall-lang/dhall-lang/blob/master/standard/README.md, which seems fine.

**Comment by Gabriel439** [comment]
Yeah, I also get a link to https://github.com/dhall-lang/dhall-lang/blob/master/standard/README.md

**Comment by vvv** [comment]
Right... I also get proper link in another browser.  This must have been the case of stale browser cache or something like that.

Sorry for raising false alarm.

**Comment by Gabriel439** [comment]
@vvv: No worries!  We appreciate the time taken to submit reports anyway 🙂
