### ISSUE TITLE
-0.0

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-lang#752]
I've noticed that in the Haskell implementation, `-0.0` and `0.0` are distinct values, that are not equivalent:

```
⊢ assert : -0.0 === 0.0

Error: Assertion failed

…

1│ assert : -0.0 === 0.0

(stdin):1:1
```

The encoding is consistent with the CBOR standard:

```
$ echo '0.0' | dhall encode | xxd
00000000: f900 00                                  ...
$ echo '-0.0' | dhall encode | xxd
00000000: f980 00
```

The binary encoding spec doesn't explicitly mention `-0.0`, but I might have guessed that it would be included in this rule, and be treated just like `0.0`:

```
─────────────────────────────  ; n.n = 0.0
encode(n.n) = n.n_h(0x0000)
```

**Comment by Gabriel439** [comment]
Yeah, we could add a rule explicitly saying to code `-0.0` as if it were `0.0`

**Comment by sjakobi** [comment]
OTOH, since `Double` is (and ought to stay?) an opaque type, maybe it's fine to accept that `0.0` and `-0.0` are are distinct.

Anyone have an opinion on this?

I guess I don't really care, but I think it would be good if the standard was clear about it and we had tests.

**Comment by singpolyma** [comment]
`-0.0` is a valid IEEE value so if `Double` is meant to mean what it means in Haskell (or what `double` means in C) then it ought to be a valid value.

**Comment by sjakobi** [comment]
@singpolyma `-0.0` certainly is a valid `Double`. The question is what its binary encoding should be, and ergo whether it should be equivalent to `0.0` or not.

**Comment by Gabriel439** [comment]
I slightly prefer them sharing the same encoding because according to https://en.wikipedia.org/wiki/Signed_zero the IEEE754 standard requires that `0` and `-0` compare as equal

**Comment by Nadrieril** [comment]
@Gabriel439 you'd want them to compare equals in the dhall equivalence predicate you mean ? I'm not sure what the usecase would be. Relying on float equality is very often a mistake, I'd rather not encourage it by trying to be clever in our handling of floats.
I'd rather follow CBOR as closely as possible

**Comment by Gabriel439** [comment]
@Nadrieril: Yeah, thinking about this more I think you are right and we should probably stick with CBOR.  The thing that convinced me is that we already violate the IEEE754 standard by defining `NaN`

**Comment by philandstuff** [comment]
I can think of two options I’d be happy with:

- treat -0.0 and 0.0 and two completely distinct values
- don’t support negative zeros at all; if a user inputs -0.0 that’s either
just a regular zero or a parse error.

My argument for the second is that negative zeros basically exist to be the
result of certain kinds of calculation, particularly underflows. But we
never do any floating point calculations so we don’t need negative zero.

**Comment by sjakobi** [comment]
> My argument for the second is that negative zeros basically exist to be the result of certain kinds of calculation, particularly underflows. But we never do any floating point calculations so we don’t need negative zero.

I think it's imaginable that someone uses Dhall as a data format and may want to preserve negative zeros.

I think we should treat `-0.0` and `0.0` as distinct values.

**Comment by Gabriel439** [comment]
Alright, then let's tentatively go with treating them as distinct values and just add tests to codify that

**Comment by sjakobi** [comment]
I'm preparing a patch.

**Comment by NorfairKing** [comment]
@sjakobi @Gabriel439
The IEEE spec for doubles requires that `0` and `-0` are treated as the same value.
They're also the same in maths, but let's not get into that argument.
There are some interesting things to consider when you're thinking about doubles;

- If you don't intend to follow the spec, let's also dissallow all the NaN values, +infinity and -infinity.
  These values mess with a lot of the mathematical properties of rational numbers.
- Be prepared for the fact that `0` and `-0` will be hash collisions.

**Comment by sjakobi** [comment]
@NorfairKing Note that Dhall doesn't support any arithmetic for Doubles, so it need not be overly concerned over IEEE754.

The only "operations" it allows are `Double/show` and checking their equivalence on the type level with `assert : a ≡ b`. This equivalence is defined via the binary encoding. Since the binary encoding is primarily used to cache Dhall expressions, it's necessarily reflexive. That's why we also have `NaN ≡ NaN`.

**Comment by NorfairKing** [comment]
While I really appreciate that you want `=` to be reflexive for Doubles in Dhall, This is non-standard. 
I'd rather disallow `NaN` entirely.

**Comment by f-f** [comment]
@NorfairKing as @sjakobi pointed out, we are not bound to follow IEEE754 in this case, as we are not performing any arithmetic on Doubles.

The only thing we care about is that all values should be representable (including the different zeros, NaN and the infinities). However by collapsing `-0.0` and `0.0` we'd lose the ability to represent `-0.0` if a user wishes to do so

Or do you have a usecase in mind for which the two zeros need to be treated as the same value?

**Comment by NorfairKing** [comment]
@f-f I have no use-case in mind in particular, and I also have no decision power here, but treating `-0.0` and `0.0` differently or `NaN` as equal to itself is non-standard and might cause confusion. 
An alternative is to separate "Representationally equal" from "Equal according to IEEE754" with a different equals sign, but that may be too much complexity.
I just wanted to give my opinion as someone who has dealt with a lot of `Double` problems in the past. Feel free to ignore :)

**Comment by NorfairKing** [comment]
Note also that, until recently, `-0.0` and `0.0` were equal in haskell but would hash to different values.
And `NaN` is not equal to itself in Haskell here, but if you consider it equal in Dhall, it will still hash to different values in Haskell.

**Comment by Gabriel439** [comment]
@NorfairKing: We don't use Haskell's hash when hashing Dhall expressions.  A Dhall `NaN` always produces the same hash regardless of which underlying Haskell `NaN` it is backed by.

**Comment by NorfairKing** [comment]
@Gabriel439 Super!
