### ISSUE TITLE
Unify the behavior of [] and None

### ISSUE THREAD

**Issue by TravisWhitaker** [dhall-lang/dhall-lang#759]
Although `[]` and `None` are used in similar ways, users need to remember that `[]` magically _requires_ a type annotation (I assume this is just part of the grammar for `[]`?):

```
⊢ :t []

Error: An empty list requires a type annotation

1: []

(stdin):1:1
```

While `None`, although a keyword, behaves like a typical function:

```
⊢ :t None

∀(A : Type) → Optional A
```

I've seen users get stuck trying to do this:

```
⊢ :t None : Optional Natural

Error: Expression doesn't match annotation

- Optional …
+ … → …

1: None : Optional Natural

(stdin):1:1
```

As well as this, thinking that the argument to `None` works like a type annotation:

```
⊢ :t None (Optional Natural)

Optional (Optional Natural)
-- but the user meant Optional Natural!
```

Once they learn this, they're bound to try this:

```
⊢ :t [] Natural

Error: An empty list requires a type annotation

1: [] 
```

It'd be nice if `[]` was just the function `λ(t : Type) → [] : List t`. Although this would break almost all existing code, the transition is very simple and could probably be automated in all cases, similar to the removal of the leading `+` on `Natural` literals.

This leads to a nice symmetry between Optionals and Lists. In order to construct the empty value, one needs to call a function supplying the contained type. In the non-empty case, the type can determined in a syntax-directed way, since `[ _ ]` and `Some _` aren't syntactically valid if they aren't paired with an expression (they're not functions).

**Comment by Gabriel439** [comment]
I think the right solution here is to add a `Prelude.List.empty : ∀(a : Type) → List a` rather than treating an empty list literal as a function.  Even when compared with `None` it still does not seem intuitive to me to special-case the empty list literal as a function.

**Comment by sjakobi** [comment]
> I think the right solution here is to add a `Prelude.List.empty : ∀(a : Type) → List a` rather than treating an empty list literal as a function.

I've included `List.empty` in https://github.com/dhall-lang/dhall-lang/pull/764.

**Comment by TravisWhitaker** [comment]
> I've included List.empty in #764.

Nice, Having `empty` that works like `None` seems like a good solution.

**Comment by sjakobi** [comment]
@TravisWhitaker Did the addition of `List.empty` satisfy you sufficiently that this issue could be closed?

**Comment by TravisWhitaker** [comment]
For sure, `List.empty` takes care of this. Thanks!
