### ISSUE TITLE
User documentation of built-in types and functions

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-lang#766]
There are multiple resources intended to show the full list of built-in functions and types:

* https://github.com/dhall-lang/dhall-lang/wiki/Cheatsheet
  I just updated this page, and believe that it lists all the builtins now.

* https://github.com/dhall-lang/dhall-lang/wiki/Built-in-types%2C-functions%2C-and-operators
  Currently misses at least `*/show`, `Natural/subtract` and `toMap`.

* [`Dhall.Tutorial`](http://hackage.haskell.org/package/dhall-1.26.1/docs/Dhall-Tutorial.html#g:20) 
  Also misses  `*/show`, `Natural/subtract`, `toMap`.

I'm wondering whether it's important that all 3 be kept up-to-date. In particular, the builtins wiki page and the tutorial are structured nearly identically. Since the the wiki is easier to update, can we replace the builtins section in `Dhall.Tutorial` with a link to the wiki?

**Comment by Gabriel439** [comment]
Yes, we should move the reference section near the end out of the `Dhall.Tutorial` and instead link to the Wiki

**Comment by sjakobi** [comment]
Now that https://github.com/dhall-lang/dhall-lang/pull/767 has landed, we should also update the docs to mention `::`.

**Comment by Gabriel439** [comment]
Alright, I did a pass on both pages and I think both are up-to-date now

**Comment by sjakobi** [comment]
Thank you @Gabriel439! :)

**Comment by Gabriel439** [comment]
@sjakobi: You're welcome! 🙂
