### ISSUE TITLE
Prelude.JSON.{keyValue,keyText} should live in Prelude.Map

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-lang#770]
Both construct `Map.Entry`s, so they should be located with that type.

https://github.com/dhall-lang/dhall-lang/blob/ef644a00e77a3c2c6c503e18e65865fd6d74fc2a/Prelude/JSON/keyValue#L1-L17

https://github.com/dhall-lang/dhall-lang/blob/ef644a00e77a3c2c6c503e18e65865fd6d74fc2a/Prelude/JSON/keyText#L1-L14

**Comment by Gabriel439** [comment]
Yeah, that seems reasonable to me.  For phase 1 of this change I think `Prelude.JSON.key{Value,Text}` should just import `Prelude.Map.key{Value,Text}` and then for phase 2 we can remove the JSON ones.

**Comment by sjakobi** [comment]
Seems like a good plan!

I actually wanted to implement this already, but noticed that due to the hash updates I'm blocked by https://github.com/dhall-lang/dhall-lang/pull/764. I was wondering whether we could maybe reduce the discussion period for Prelude changes to 3 days or so?

**Comment by f-f** [comment]
@sjakobi you can merge that one already since you have a majority vote and 3 days have passed 🙂

**Comment by sjakobi** [comment]
> @sjakobi you can merge that one already since you have a majority vote and 3 days have passed

Ah thanks for the clarification! I changed some formatting 2 days ago, so I should probably wait another day.

**Comment by f-f** [comment]
@sjakobi I thinkn the merging rules are ambiguous on this, so I'd say it's fine to merge if it's only formatting changes
