### ISSUE TITLE
Proposal: javadoc/jsdoc style comment annotation conventions for self-documenting types

### ISSUE THREAD

**Issue by JohannesRudolph** [dhall-lang/dhall-lang#779]
I think it might be very handy to have an "official" comment convention for types/fields that's similar to Javadoc/Jsdoc.

The prelude already sets a good example for this by using `{- formatted comments -}` in the right places, also including markdown text: https://github.com/dhall-lang/dhall-lang/blob/master/Prelude/JSON/Type

This would be very handy for self-documenting configuration types/APIs and driving "IntelliSense" style IDE features i.e. via dhall-lsp.

Is anybody else interested in making something like this happen? I'd like to collect more use cases/examples/suggested syntax before deciding if its worth moving forward by i.e. making a specific proposal.

**Comment by ocharles** [comment]
In https://discourse.dhall-lang.org/t/documenting-dhall-expressions/64/4 I suggested that we actually have a new type of comment specifically for documentation - `---`.

**Comment by Gabriel439** [comment]
I think the first step is to clarify what the requirement is.  The only reason I ask is because if the goal is to improve Intellisense then that might entail a different design than if the goal is just consistent formatting of human-authored comments

**Comment by sjakobi** [comment]
https://github.com/dhall-lang/dhall-lang/issues/760 is also related.

I agree with @ocharles that we should have some distinction between documentation comments and comments that are not intended for user documentation. Otherwise users might have to come up with ways to hide comments from the documentation tool, which seems just annoying.

For simplicity it would also be nice if documentation comments could look just like regular comments for implementations that don't care about the distinction, but I don't think that's particularly important.

Regarding the "attachment" of documentation to code I wonder how far we can get with the Prelude convention of having a single documentation comment at the top of the file for the expression below.

**Comment by Gabriel439** [comment]
Just to clarify: is the goal here to specify a subset of comments that are rendered by documentation generators (analogous to `-- |` for `haddock`-specific comments in Haskell)?

**Comment by sjakobi** [comment]
> is the goal here to specify a subset of comments that are rendered by documentation generators

That's my goal, for one. :)

**Comment by JohannesRudolph** [comment]
Tags that can be picked up by Documentation generators are useful for sure.
This would allow a use case where a dhall model can generate product
configuration documentation. There’s probably value in reusing an existing
generator that supports markdown style comments, I see no reason why the
dhall ecosystem would need to have its own implementation if other
ecosystems already have decent solutions.

Another use case is Language Servers that provide code editor assistance,
these can also pick up tags like @see or [markdown] style links to related
dhall expressions and provide editor navigation assistance.

Simon Jakobi <notifications@github.com> schrieb am Di. 29. Okt. 2019 um
02:07:

**Comment by FranklinYu** [comment]
Is this (partially) implemented in https://github.com/dhall-lang/dhall-haskell/tree/master/dhall-docs? The examples in [the documentation](https://hackage.haskell.org/package/dhall-docs) look pretty good, covering most of the functionalities I wanted.

**Comment by Gabriel439** [comment]
Yeah, I think this can be closed now that we have the `dhall-docs` tool, assuming that the requirement was to have an opinionated way of structuring comments for generating documentation.
