### ISSUE TITLE
Prelude.Location.Type fails to resolve

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-lang#783]
I'm opening this here as I'd like to rule out that `dhall` is misbehaving before concluding that the Prelude has an error.

```bash
$ echo 'https://prelude.dhall-lang.org/v10.0.0/Location/Type' | dhall
dhall: 
Error: Failed to resolve imports. Error list:


↳ https://prelude.dhall-lang.org/v10.0.0/Location/Type

Referentially opaque import: missing sha256:f428188ff9d77ea15bc2bcd0da3f8ed81b304e175b07ade42a3b0fb02941b2aa as Location


↳ https://prelude.dhall-lang.org/v10.0.0/Location/Type

Referentially opaque import: missing as Location


 9│               missing sha256:f428188ff9d77ea15bc2bcd0da3f8ed81b304e175b07ade42a3b0fb02941b2aa as Location
10│              ? missing as Location
11│           

https://prelude.dhall-lang.org/v10.0.0/Location/Type:9:15
```

The relevant change to `Prelude.Location.Type` seems to be https://github.com/dhall-lang/dhall-lang/commit/1ed98c33ce5078161109885f0b16b3828958f4e2#diff-ecf935a4b1ff7b26d39bf9da0a6c00b7 as a part of the introduction of assertions.

**Comment by sjakobi** [comment]
I'm wondering why this wasn't caught earlier. Don't we run CI with empty caches?

**Comment by Gabriel439** [comment]
@sjakobi: It's because CI doesn't import the Prelude remotely.  The Prelude is imported via a local relative path

**Comment by sjakobi** [comment]
For reference: https://github.com/dhall-lang/dhall-lang/pull/781 took care of the bug in the Prelude, but the standard still needs fixing.
