### ISSUE TITLE
Container management integrations

### ISSUE THREAD

**Issue by Gabriel439** [dhall-lang/dhall-lang#79]
Three separate users responded to the survey that they were using Dhall for managing containers using either Kubernetes or Docker Swarm

*   > WHAT: Generating docker swarm and other configs from common templates with
    > specific variables inserted safely.

    > WHY: JSON and yaml suck, want to know about errors at compile time.

*   > WHAT: Kubernetes

    > WHY: Schema validation. Kubernetes is known for blowing up in your face at
    > runtime by doing evaluation and parsing at the same time

*   > WHAT: configuration - use haskell integration and spit out json/yaml on
    > some projects  (to kubernetes configs for instance)

    > WHY: I love pure fp and dealing with configs wastes a lot of my time and
    > is often error prone

I'm opening this issue to note that there might be value in providing a more specific
Dhall integration with either Kubernetes or Docker Swarm for managing large numbers 
of containers with repetitive configurations.

**Comment by f-f** [comment]
We're in the process of porting our Kubernetes infrastructure to Dhall-Kubernetes, and will probably ship it to production during the next weeks.
While doing this, I forked [dhall-kubernetes](https://github.com/arianvp/dhall-kubernetes) and added a good amount of patches to it (and more will probably come as we'll use it more). Fork is [here](https://github.com/f-f/dhall-kubernetes).

Given that I wouldn't like to maintain a fork, I was wondering if it would be a good idea to merge my fork into the main repo (before it diverges too much), and move the repo under the umbrella of this organization, so we have a concentrated effort for making the integration with Kube easier.

@arianvp does it sound like a good idea? (btw, thanks for starting the project)

**Comment by arianvp** [comment]
Heya! That sounds great to me. Do note that this was a bit of a hackathon-project and as you had probably noticed, was never finished. However, thanks for continuing on it! I'm okay with moving ownership of the repository.

**Comment by Gabriel439** [comment]
@f-f: Yeah, feel free to move this under the `dhall-lang` project.  Also, if your company is okay with it I can list them as a commercial user of Dhall here whenever that launches:

https://github.com/dhall-lang/dhall-lang/wiki/Dhall-in-production

**Comment by f-f** [comment]
@arianvp super awesome, thanks :)
I opened the PR [here](https://github.com/arianvp/dhall-kubernetes/pull/2), let's merge and then we can move the repo over here.

> if your company is okay with it I can list them as a commercial user of Dhall here whenever that launches

@Gabriel439 cool, I'll check if it's good and add us to the wiki page

**Comment by arianvp** [comment]
@Gabriel439 if you add me to the `dhall-lang` organisation, then i'll transfer the repo here.

**Comment by Gabriel439** [comment]
@arianvp: Added!

**Comment by f-f** [comment]
@Gabriel439 since now we have things like `dhall-kubernetes` and `dhall-terraform`, should we close this issue? We could open more tool-specific ones as needs arise

**Comment by Gabriel439** [comment]
Yep!  I'll go ahead and close this
