### ISSUE TITLE
Modernise logo

### ISSUE THREAD

**Issue by i-am-the-slime** [dhall-lang/dhall-lang#794]
Somehow I can't seem to get along with Dhall's current logo. I tried to modernise it a little bit but if you don't like it, that's fine.

I tried to stick to the general theme of the quill and inkwell but modernised it (there is a fountain pen tip now :)). The fountain pen tip forms an exclamation mark with the full stop which (in Haskell) indicates strictness. Compared to YAML, Dhall is quite strict! The exclamation point also works as a standalone icon (for square or round uses on Twitter for example). The font is a ~mutilated~ heavily customised Montserrat.

![DhallLogo](https://user-images.githubusercontent.com/1588055/67623140-5929d100-f822-11e9-85a4-a93ea340ccf4.png)
![DhallLogoIcon](https://user-images.githubusercontent.com/1588055/67623141-5c24c180-f822-11e9-9355-47faad7c5c6c.png)

Anyway, let me know if you are interested in the SVG files.

**Comment by Gabriel439** [comment]
@i-am-the-slime: I like it! 🙂 

I'll treat this issue sort of like a [change to the standard](https://github.com/dhall-lang/dhall-lang/blob/master/.github/CONTRIBUTING.md#how-do-i-change-the-language) so I'll wait up to a week to give other people a chance to comment and/or vote on the change

**Comment by sjakobi** [comment]
Thanks for the invitation to the bikeshed! :D 

> I tried to stick to the general theme of the quill and inkwell

Where does that theme actually come from? How is it related to Dhall as a language?

> The fountain pen tip forms an exclamation mark with the full stop which (in Haskell) indicates strictness. Compared to YAML, Dhall is quite strict!

I think that looks lovely, but I would have never come up with that connection. The strictness of `!` strictness annotations is also a very different kind of strictness than the type-strictness of Dhall compared to YAML.

IMHO the `ll`-ligature also looks a bit too much like a `U`, I find it a bit hard to read.

**Comment by Gabriel439** [comment]
@sjakobi: The quill and inkwell theme comes from the language's namesake: [Dhall](http://torment.wikia.com/wiki/Dhall)

**Comment by sjakobi** [comment]
> The quill and inkwell theme comes from the language's namesake: [Dhall](http://torment.wikia.com/wiki/Dhall)

Well, this connection would be partially lost with the switch to a fountain pen tip – which I wouldn't mind!

**Comment by singpolyma** [comment]
I find the "modernize" description a bit odd, and was initially against this.

However, the current logo does not shrink down to 16x16 well, which is a common use case (in favicons, pseudo-emoji, etc) and this one seems like it will be more recognizable at that size.

So tentative yes from me.

**Comment by f-f** [comment]
@i-am-the-slime looks amazing! 👏 

The only remark I have is also about the `ll` ligature: the imbalance between the two `l` is a bit funky, so I'd like the two `l` to look the same (and I don't have an opinion on having space between them or linking them, i.e. picking the first `l` or the second one)

**Comment by i-am-the-slime** [comment]
<img width="1082" alt="Screenshot 2019-10-27 at 12 04 53" src="https://user-images.githubusercontent.com/1588055/67633592-04359b80-f8b2-11e9-9b5c-4228c7592bc4.png">
Here's some LL Cool J.

**Comment by sjakobi** [comment]
> Here's some LL Cool J.

LGTM! :)

**Comment by sjakobi** [comment]
Closing. Thanks again @i-am-the-slime! :)

**Comment by Profpatsch** [comment]
Great logo!
