### ISSUE TITLE
Standard pretty-printer for dhall

### ISSUE THREAD

**Issue by jml** [dhall-lang/dhall-lang#8]
There should be a single canonical format for dhall code, and there should be a tool that converts dhall files to be in that format, ala `gofmt`. 

Reason: no one should have to care about formatting of configuration files.

**Comment by Gabriel439** [comment]
Yep, totally agree with this one.  I had an issue for this in the original Haskell repository (https://github.com/dhall-lang/dhall-haskell/issues/61), which I'll close as a duplicate in favor of this issue

**Comment by Gabriel439** [comment]
I have a pull request out implementing this in: https://github.com/dhall-lang/dhall-haskell/pull/137

**Comment by jml** [comment]
Thanks! I've done a review, fwiw.
