### ISSUE TITLE
prelude.dhall-lang.org URLs result in 404

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-lang#817]
The following links currently return 404s:

* https://prelude.dhall-lang.org/v11.1.0/package.dhall
* https://prelude.dhall-lang.org/v10.0.0/package.dhall
* https://prelude.dhall-lang.org/package.dhall

https://prelude.dhall-lang.org/v11.1.0 and https://prelude.dhall-lang.org/ still correctly redirect to GitHub.

**Comment by Gabriel439** [comment]
This is fixed now.  This was a result of me trying to fix https://github.com/dhall-lang/dhall-haskell/issues/1511.  I thought I had reverted my change but I had forgotten to do so.

After reverting the change those links work now.
