### ISSUE TITLE
version of JSON.renderYAML that doesn't escape object keys

### ISSUE THREAD

**Issue by retnuh** [dhall-lang/dhall-lang#830]
Hi there, it's pretty common in Kubernetes land to want to inline a block of YAML.  For simple cases, it would be nice to use a JSON object and call `JSON.renderYAML` (or a variant thereof).  However, currently object keys are always escaped, which doesn't play well with inlining.  For example:

```
let JSON = https://raw.githubusercontent.com/dhall-lang/dhall-lang/master/Prelude/JSON/package.dhall
let k8s = https://raw.githubusercontent.com/dhall-lang/dhall-kubernetes/fee24c0993ba0b20190e2fdb94e386b7fb67252d/schemas.dhall sha256:0a362a64a631fe7911f71438fa05acdcdf6469850cce4f910e4cf126315d1011

let ev1 = JSON.object
    [ { mapKey = "topicArn", mapValue = JSON.string "someARN" }
    , { mapKey = "hook"
      , mapValue =
          JSON.object 
          [ { mapKey = "endpoint", mapValue = JSON.string "/fixme" }
          , { mapKey = "port", mapValue = JSON.string "12000" }
          , { mapKey = "url", mapValue = JSON.string "http://FIXME.FIXME"}
          ]
      }
    , { mapKey = "region", mapValue = JSON.string "us-east-1" }
    ]

let cm = k8s.ConfigMap :: {
  , apiVersion = "v1"
  , kind = "ConfigMap"
  , metadata = k8s.ObjectMeta :: { 
      , name = "foo-event-source" 
      , labels = [{ mapKey = "argo-events-event-source-vesion", mapValue = "v0.11"}]
    }
  , data = [
    , { mapKey = "foo-event-source-1", mapValue = JSON.renderYAML ev1  }
  ]
}

in cm
```

Produces:

```
$ dhall-to-yaml --omitEmpty --file ex.dhall
apiVersion: v1
data:
  foo-event-source-1: |
    ! "topicArn": "someARN"
    ! "hook":
      ! "endpoint": "/fixme"
      ! "port": "12000"
      ! "url": "http://FIXME.FIXME"
    ! "region": "us-east-1"
kind: ConfigMap
metadata:
  labels:
    argo-events-event-source-vesion: v0.11
  name: foo-event-source
```

Which doesn't work, because the leading `! ` become part of the text.  As such, it would be nice to have a version that produces:

```
$ dhall-to-yaml --omitEmpty --file ex.dhall
apiVersion: v1
data:
  foo-event-source-1: |
    "topicArn": "someARN"
    "hook":
      "endpoint": "/fixme"
      "port": "12000"
      "url": "http://FIXME.FIXME"
    "region": "us-east-1"
kind: ConfigMap
metadata:
  labels:
    argo-events-event-source-vesion: v0.11
  name: foo-event-source
```

I suppose some options are a boolean parameter to `renderYAML`, or another function `renderUnescapedKeysYAML` or `renderInlineYAML`, etc.

**Comment by matheus23** [comment]
> Which doesn't work, because the leading ! become part of the text.

This seems weird to me. A leading `!` should still be valid yaml.

However, I was planning to publish a more flexible `renderYAML` function outside the Prelude namespace anyway, as there is quite a big design space for this function.

I had it sitting around in my filesystem for a while and finally got around to publishing it: https://github.com/matheus23/dhall-blocks

You can see exactly the escaping you're looking for in the readme example. Let me know if you need anything else.

**Comment by retnuh** [comment]
> > Which doesn't work, because the leading ! become part of the text.
> 
> This seems weird to me. A leading `!` should still be valid yaml.

Hmm maybe it actually would work; I may be able to test that out later.

> However, I was planning to publish a more flexible `renderYAML` function outside the Prelude namespace anyway, as there is quite a big design space for this function.
> 
> I had it sitting around in my filesystem for a while and finally got around to publishing it: https://github.com/matheus23/dhall-blocks
> 
> You can see exactly the escaping you're looking for in the readme example. Let me know if you need anything else.

Nice one, thanks!
