### ISSUE TITLE
How to create a Schema?

### ISSUE THREAD

**Issue by keirlawson** [dhall-lang/dhall-lang#831]
I'm wondering if it is possible to create a redistributable type for my application that can then be used by users of the application to validate that their configuration matches the specified types? So far as I can see it looks like type declarations (via `let`) need to be paired with their direct usage (via `in`), so I'm wondering if there is some way to say "this entire file should match this type"?

**Comment by sjakobi** [comment]
Types can be handled much like types in Dhall, e.g.

```dhall
-- Example.dhall
let Example = { foo : Bool, bar : Text }

in Example
```

or just

```dhall
{ foo : Bool, bar : Text }
```

. Users can then use that type for example like this:

```dhall
let Example = ./Example.dhall -- or e.g. https://example.com/Example.dhall

in { foo = True, bar = "bla" } : Example
```

**Comment by keirlawson** [comment]
Fantastic, thanks!
