### ISSUE TITLE
Strange variable names in the Optional builtins

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-lang#851]
```
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Γ ⊢ Optional/fold : ∀(a : Type) → Optional a → ∀(optional : Type) → ∀(just : a → optional) → ∀(nothing : optional) → optional


─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Γ ⊢ Optional/build : ∀(a : Type) → (∀(optional : Type) → ∀(just : a → optional) → ∀(nothing : optional) → optional) → Optional a
```

`just` and `nothing` sound more like Haskell than Dhall. Should these variables be called `some` and `none` instead?

**Comment by amarrella** [comment]
A thing i also find confusing is also the `optional : Type` as this is the type of the results _without_ the optional. I would just call it `b`.

**Comment by sjakobi** [comment]
@amarrella See https://github.com/dhall-lang/dhall-lang/issues/731. I think it's a bit confusing too.

**Comment by Gabriel439** [comment]
I'm fine renaming `just`/`nothing` `some`/`none`, but I strongly believe that the `optional` name should stay the same.  #731 explains why (as @sjakobi noted).

**Comment by Gabriel439** [comment]
Also https://docs.dhall-lang.org/howtos/How-to-translate-recursive-code-to-Dhall.html helps build an intuition of why they should be named in this way

**Comment by sjakobi** [comment]
Removing `Optional/fold` and `Optional/build` fixed this.
