### ISSUE TITLE
Hexadecimal Naturals

### ISSUE THREAD

**Issue by NMerkley** [dhall-lang/dhall-lang#858]
I have been using Dhall to generate configuration files that describe all of the messages on a vehicle CAN bus. These CAN messages are typically referenced by their ID in hexadecimal, so I would prefer to be able to enter them that way instead of converting before writing the config file. I also need to do a small amount of arithmetic on these identifiers, so just using a Text is out of the question

I've looked around in the documentation and tried a number of things in the repl, but don't see any way to represent a Natural in a base other than decimal. Is there a reason for this?

**Comment by Gabriel439** [comment]
@NMerkley: No particular reason.  We can extend the language to add support for hexademical literals

**Comment by sjakobi** [comment]
Adding hexadecimal literals seems reasonable to me. Would we use the usual `0x` prefix?

So far we reuse the syntax for `Natural` literals for `Integer`s:

https://github.com/dhall-lang/dhall-lang/blob/70c6c0463c5185abe75d3f4138c68afc5cbdf603/standard/dhall.abnf#L489-L491

Would we want to keep this and then have `Integer` literals like `-0x1F2a`?

**Comment by Gabriel439** [comment]
@sjakobi: Yeah, extending the `natural-literal` rule in the grammar to support hexademical literals seems like the most graceful way to add this.  The only caveat I can think of is that the `natural-literal` rule is also permitted in variable indices (e.g. the `n` in `x@n`), so we should decide if we want to permit hexadecimal indices (e.g. `x@0x1`), which seems like it would be fine.

**Comment by sjakobi** [comment]
> so we should decide if we want to permit hexadecimal indices (e.g. `x@0x1`), which seems like it would be fine.

Seems like a nice feature for the next obfuscated Dhall contest! ;)

But yeah, that seems fine to me too.

**Comment by Gabriel439** [comment]
@NMerkley: There is one wrinkle here; the internal representation wouldn't distinguish between hexadecimal literals or decimal literals.   That means, for example, that if an expression were serialized and deserialized there would be no way to tell that the original `Natural` literal was written as hexadecimal.  Similarly, for the Haskell implementation formatting code would convert hexadecimal literals to a decimal representation.

I don't know if that would be a problem for you or not.

**Comment by NMerkley** [comment]
> formatting code would convert hexadecimal literals to a decimal representation.

That's unfortunate, but it makes sense. It's not a real problem just one of convenience.

Thanks though, I'll be happy to have this feature

**Comment by Gabriel439** [comment]
The proposed change to the standard is up here: https://github.com/dhall-lang/dhall-lang/pull/859
