### ISSUE TITLE
What is the precision of Double?

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-lang#86]
The grammar suggests infinite precision, but `dhall-haskell` just uses a (Haskell) `Double`. Which is right? Should `dhall-haskell` use `Scientific` instead?

**Comment by Gabriel439** [comment]
Yes, I agree that it should be using `Scientific` instead.  That would be consistent with using unlimited precision `Integer`s and `Natural`s

**Comment by Gabriel439** [comment]
Also, more important than consistency is correctness.  I don't want a user to get bitten by loss of precision if it was easy to avoid.
