### ISSUE TITLE
Record puns

### ISSUE THREAD

**Issue by anttih** [dhall-lang/dhall-lang#867]
I'd like to propose new syntax for record literals:

```
{ key } = { key = key }
```

So, for example:

```
let key = "value" in { key } : { key : Text }
```

I think this greatly reduces noise when returning a big record.

**Comment by sjakobi** [comment]
For reference: This is kind of the inverse of #74. 

This looks like it could be easy to standardize and implement since it appears to be just syntactic sugar:

`{ x }` is syntactic sugar for `{ x = x }`.

It might slightly complicate parsing though, I'm not quite sure.

**Comment by sjakobi** [comment]
I guess we'd also want to allow mixed use of puns and classic record field syntax:

```dhall
let foo = 1

in { foo, bar = 2 }
```

**Comment by SiriusStarr** [comment]
This partially alleviates #866 as well, since it makes constructing records very convenient (as long as one can match the field names, which is often the case).  I'm a fan.

**Comment by sjakobi** [comment]
On second thought, maybe it's not _that_ easy to implement: After parsing, you'd have these record literals that may or may not have value, but after type checking you'd rather work with records where _each_ field has a value…

**Comment by Nadrieril** [comment]
@sjakobi If it's just syntactic sugar I'd expect it to get expanded before typechecking, so that only parsing has to change.

**Comment by Gabriel439** [comment]
This is something I've wanted for a while

I also agree with @Nadrieril that this could be treated as syntactic sugar

**Comment by Profpatsch** [comment]
I really want that!

**Comment by sjakobi** [comment]
@anttih Would you be interested in standardizing this yourself?

A proper proposal should probably be accompanied by an implementation. If that first implementation were in Haskell, I (and probably Gabriel too) would be happy to assist with advice.

**Comment by anttih** [comment]
@sjakobi Unfortunately I don't have the time currently.

**Comment by Nadrieril** [comment]
I'm planning on doing this soon

**Comment by Nadrieril** [comment]
Do we expect `{ x.y.z }` to parse ? I feel like it could be read as either `{ x.y.z = x.y.z }` or `{ x.y.z = z }` but neither feels very natural

**Comment by jvanbruegge** [comment]
I would expect the latter

**Comment by sjakobi** [comment]
Following the existing desugaring logic I'd expect `{ x.y.z }` to expand to `{ x = { y = { z } } }`, i.e. `{ x.y.z = z }`. But it's not very obvious, and it mixes two kinds of sugar, so I'd expect it to cause _some_ confusion at least.

My inclination would be not to standardize this syntax for now.

**Comment by sjakobi** [comment]
In principle we could also consider supporting puns in `with`-expressions, e.g.

```dhall
record with x
```

…as a shortcut for

```dhall
record with x = x
```

But as long as we don't allow puns for nested fields (e.g. `{ x.y }` or, in this case, `record with x.y`), I don't expect that anyone would want to use that.
