### ISSUE TITLE
Improve nix install docs for projects that depend on dhall-haskell

### ISSUE THREAD

**Issue by jmitchell** [dhall-lang/dhall-lang#87]
Directions in the [getting started](https://github.com/dhall-lang/dhall-lang/wiki/Getting-started%3A-Generate-JSON-or-YAML) wiki page say to install `dhall-json` like this:

```
nix-env --install --attr dhall-json
```

Running that in a local clone of [dhall-lang/dhall-json](https://github.com/dhall-lang/dhall-json) resulted in the following error:

```
Setup: Encountered missing dependencies:
dhall >=1.9.0 && <1.10
```

Can the docs be improved to avoid this problem? It would help those who aren't yet familiar with nix and just want to get things working. The directions in various `dhall-*` projects should be reviewed too.

One potential solution is to add a symlink in `~/.nix-defexpr`:

```
ln -s $DHALL_HASKELL_CLONE_DIR/release ~/.nix-defexpr/dhall
```

**Comment by jmitchell** [comment]
After trying to reproduce the issue from scratch I realize my current solution is actually a little more involved. I have the following symlinks in `~/.nix-defexpr`:

```
dhall -> s/dhall-lang/dhall-haskell/release
dhall-bash -> s/dhall-lang/dhall-bash/release
dhall-json -> s/dhall-lang/dhall-json/release
dhall-nix -> s/dhall-lang/dhall-nix/release
dhall-text -> s/dhall-lang/dhall-text/release
```

And now I can install `dhall-json` by running `nix-env -i dhall-json` from any directory.

**Comment by Gabriel439** [comment]
What version of `nixpkgs` are you using?

**Comment by jmitchell** [comment]
I'm using `release-17.09`. I notice in `master` dhall's version is 1.8.2, which is outside the required version bounds.

I discovered at some point after the `~/.nix-defexpr` hackery that `dhall --version` unexpectedly reported `1.6.0`, the version from `release-17.09`. I can build and install `dhall-haskell` v1.9.1 using `release.nix` from its repo and get `dhall --version` to report 1.9.1. However, I actually don't have a user-friendly way to install the latest `dhall-json` yet.

**Comment by Gabriel439** [comment]
Ah, got it!  Yeah, I can update the instructions to support installing the latest version

**Comment by Profpatsch** [comment]
I recommend against the usage of `nix-env` if possible, since it introduces state. Especially when trying to develop Haskell packages (which I’m assuming you did, because you had a local clone of `dhall-json`) you should follow the [developer instructions in the `nixpkgs` manual](https://nixos.org/nixpkgs/manual/#users-guide-to-the-haskell-infrastructure).

**Comment by jmitchell** [comment]
For now I'm primarily interested in a supported workflow for installing the latest `dhall*` binaries using nix. My intent is to tinker with the utilities and custom dhall configs before doing any development. I suspect that's a common scenario for users.

**Comment by Profpatsch** [comment]
Then executing `nix-shell -p dhall dhall-json dhall-nix dhall-text dhall-bash -I nixpkgs=/path/to/nixpkgs/checkout/on/recent/master/or/unstable` should do what you want and throw you inside a shell with all executables in the `PATH`.

**Comment by Gabriel439** [comment]
@jmitchell: I updated the `release.nix` for each project to specify a `dhall-1.9.0` dependency, which should fix the problem that you ran into
