### ISSUE TITLE
Prelude.JSON.number should have alternatives for Natural, Integer

### ISSUE THREAD

**Issue by ari-becker** [dhall-lang/dhall-lang#872]
[`Prelude.JSON.number`](https://github.com/dhall-lang/dhall-lang/blob/v12.0.0/Prelude/JSON/number) currently only accepts a `Double` parameter.
There should be a way to present a `JSON` with a `Natural` or an `Integer`.

This is important because the JSON standard permits a `number` without a fraction or exponent, e.g. `{"foo":1}`. Currently, because rendering a `Prelude.JSON.string` implies quoting the `Text` (and thus prevents, say, `Prelude.JSON.string (Prelude.Natural.show 1)` as an escape hatch), it does not seem possible to render `{"foo":1}` with the `Prelude.JSON` library as it exists now.

---

Discovered while attempting to model [Grafana dashboards](https://grafana.com/docs/grafana/latest/reference/dashboard/), which uses `Natural` as a selector in many areas, for example:
```text
graphTooltip | 0 for no shared crosshair or tooltip (default), 1 for shared crosshair, 2 for shared crosshair AND shared tooltip
```
which I wanted to model as:
```dhall
let JSON = (https://prelude.dhall-lang.org/package.dhall).JSON
let GraphTooltip =
  let GraphTooltip = < NoSharing | SharedCrosshairOnly | SharedCrosshairAndTooltip >
  in  { Type = GraphTooltip
      , render = \(graphTooltip: GraphTooltip) ->
                          merge
                          { NoSharing = JSON.number 0
                          , SharedCrosshairOnly = JSON.number 1
                          , SharedCrosshairAndTooltip = JSON.number 2
                          }
                          graphTooltip
      }
in GraphTooltip
```
but of course, this results in a type error whereby `0` is a `Natural`, not a `Double`.

**Comment by sjakobi** [comment]
@ari-becker So Grafana doesn't accept `0.0` for `0` or `1.0` for `1` in the `graphTooltip` field?! That would seem like a violation of the JSON standard, no?

I agree though that it would be nice if integers could be rendered without decimals. How about we add `integer` that renders `-1` as `-1` and `+1` as `1`?

In that case, `number` should possibly be renamed to avoid confusion – maybe to `decimal`?

**Comment by ari-becker** [comment]
@sjakobi I'm not entirely sure whether `0.0` or `1.0` are acceptable substitutes in practice, at least because Grafana's dashboard JSON schema is poorly documented. Even if they are acceptable substitutes today, they may not be acceptable substitutes tomorrow, if the internal implementation's parsing becomes more strict but claims compliance with the documented standard. From my perspective as somebody trying to generate Grafana dashboards, I don't really care whether Grafana is written by people who care about compliance, I just want to be confident that my configuration is going to work :) (also because here in the real world there aren't really any better alternatives)

Why not just avoid `JSON.number` and replace it with `JSON.double`, `JSON.integer`, and `JSON.natural` (while de facto keeping `JSON.number` around for compatibility with existing code)?

**Comment by ari-becker** [comment]
For what it's worth, another example location where this showed up in my work: [Packer's AMI builder](https://www.packer.io/docs/builders/amazon-ebs.html#volume_size) requires defining a `volume_size` with a number; AWS's API forbids fractional numbers for the size of EBS disks.

Murphy's law guarantees that at least *somebody* out there is non-compliant and will refuse to parse `{"foo":1.0}` as equivalent to `{"foo":1}`.

**Comment by sjakobi** [comment]
> Why not just avoid `JSON.number` and replace it with `JSON.double`, `JSON.integer`, and `JSON.natural` (while de facto keeping `JSON.number` around for compatibility with existing code)?

Right! To me the question is how we should extend `JSON.Type` and what can be implemented without modifying `JSON.Type` in terms of the primitives `JSON.Type` provides:

We'll need a `JSON.integer` primitive, which we can re-use to implement `JSON.natural`.

If we had a function of type `Double -> Optional Integer`, we could even change `JSON.number` to render integral `Double`s without decimals. That would make `Double`s less opaque though, so I'm not sure whether the necessary standard change would be accepted.

**Comment by ari-becker** [comment]
> If we had a function of type `Double -> Optional Integer`, we could even change `JSON.number` to render integral `Double`s without decimals. That would make `Double`s less opaque though, so I'm not sure whether the necessary standard change would be accepted.

Even accepting your premise for the sake of discussion - wouldn't the addition of a `Double/toInteger` built-in be a far heavier change than simply changing the `Prelude`'s `JSON.Type`, which doesn't require a standard change? Am I missing something?

**Comment by sjakobi** [comment]
> Even accepting your premise for the sake of discussion - wouldn't the addition of a `Double/toInteger` built-in be a far heavier change than simply changing the `Prelude`'s `JSON.Type`, which doesn't require a standard change? Am I missing something?

You're quite right. Right now we have a nice 1-on-1 mapping from Dhall to JSON in `JSON.Type`, and I think it makes sense to explore alternatives before giving it up.

But extending `JSON.Type` as necessary seems to be the pragmatic way forward.

Do you want to make a PR so we can discuss this further on the code?

**Comment by ari-becker** [comment]
@sjakobi See the opened PR

**Comment by Gabriel439** [comment]
Sorry that I'm late to this discussion, but I agree with the idea of changing the JSON type to support storing (at least) `Integer`s.  My reasoning is that otherwise there would be no way to store unlimited precision `Integer`s in a JSON expression.

Carefully note that the JSON standard is purely a grammar and doesn't say anything about what value the grammar corresponds to within the host language.  This leads to the infamous problem where JavaScript can't correctly handle JSON expressions storing 64-bit integers since JavaScript represents them all as `Double`s.  Dhall currently has the same problem, too, which the proposed change fixes.
