### ISSUE TITLE
Github Wiki should point to new wiki

### ISSUE THREAD

**Issue by hanshoglund** [dhall-lang/dhall-lang#878]
[Googling ](https://www.google.com/search?client=firefox-b-d&q=dhall+wiki) "Dhall wiki" points to https://github.com/dhall-lang/dhall-lang/wiki, and this page makes no mention of the new location https://docs.dhall-lang.org/index.html.

**Comment by Gabriel439** [comment]
This is fixed now.  I just updated the main page of the GitHub wiki to mention docs.dhall-lang.org
