### ISSUE TITLE
Set data type?

### ISSUE THREAD

**Issue by Profpatsch** [dhall-lang/dhall-lang#88]
[Purcel](https://github.com/joneshf/purcel) uses the type 

```
{ package : Text
, modules : List Module
, dependencies : List Module
}
```

for packages. Using `List` in this context is okay-ish, but a dependency list is really a collection of unique dependencies, a `Set`.
I haven’t thought about this a lot, but stuff like this might be a good reason to support sets in dhall, along
with the normal (axiomatic?) set operators.

One problem I can think about is that `Set/union` needs to check for equality to merge two sets and might be a pain to implement.

**Comment by Gabriel439** [comment]
The main reason I don't implement Sets and Maps is that they require a way to test for equality and there are many types that I deliberately don't want to allow to be compared for equality, like `Text`.

**Comment by Profpatsch** [comment]
That’s what I was referring to, yes. Of course the normalizer *could* include equality checks for `Text` when normalizing `Set/union` (without exposing an equality function into dhall per se).

But then it might be possible to use that to check for equality, I’m not sure. I can’t think of a way to do that without equality on sets themselves.

**Comment by Gabriel439** [comment]
Well, if you want to perform any useful operations on sets (like convert to a `List` or compute the size) then that will expose a way to check for equality

It also requires there being a way for the user to tell which values can be compared for equality and which can't (such as functions)

**Comment by paulyoung** [comment]
Should this be revisited now that there's `Dhall.Map`?

**Comment by singpolyma** [comment]
> Should this be revisited now that there's `Dhall.Map`?

The Map type is a list, duplicate keys are resolved in an implementation-dependent manner (often last-key-wins) -- in the same way *every* List could be interpreted by a harness as a set.‎

**Comment by Gabriel439** [comment]
I will close this out as it still doesn't seem likely that we'll introduce this in the near future.  In particular, this still runs the risk of accidentally introducing a `Text` equality, which we're trying to avoid.

Currently, the state of affairs is that, like `Prelude.Map.Type`, we push the uniqueness-handling into the marshaling package for each Dhall binding.

**Comment by ProofOfKeags** [comment]
Do you have any literature that elaborates on why Text equality is bad? Seems non-obvious and could benefit those of us scratching our heads about it.

**Comment by Gabriel439** [comment]
@ProofOfKeags: Yes.  See: https://docs.dhall-lang.org/discussions/Design-choices.html#text-manipulation
