### ISSUE TITLE
Duck typing for function parameters?

### ISSUE THREAD

**Issue by ari-becker** [dhall-lang/dhall-lang#884]
Consider the following:

```dhall
let Duck = { foo : Text }
let duck = { foo = "foo" , bar = "bar" }
let quack = \(param : Duck) -> param.foo
in quack duck
```

This fails to type-check because `duck` has an extra field `bar`. My issue is, let's say I have a common configuration type `Config` for arbitrary large `n` number of repositories which I can guarantee will have a `config.dhall : Config` in them, and for which I want to have a common process configured by the `config.dhall` in each directory. How can I evolve the `Config` type without breaking the process for each of the target repositories every time I update the `Config` type?

One work-around approach today is to is to re-create a `new-config.dhall` from each `config.dhall`, by doing e.g.

```dhall
-- config.dhall
{ foo = "foo" , bar = "bar" }
```
```dhall
-- Config.dhall
{ Type = { foo : Text } , default = {=} }
```
```dhall
-- transform.dhall
let Config = ./Config.dhall
let config = ./config.dhall -- does not require a type-check, unlike function parameters
in Config::( config.{ foo } )
```
```dhall
-- process.dhall
let Config = ./Config.dhall
in
\(config : Config.Type) -> config.foo
```
and
```bash
dhall --file transform.dhall > new-config.dhall
dhall <<< "./process.dhall new-config.dhall"
```

But this gets very clunky for large nested configurations, very quickly. Being able to write functions where the type of the function parameter is a duck type would be a huge help.

**Comment by amarrella** [comment]
I think this is related to https://github.com/dhall-lang/dhall-lang/issues/828

**Comment by Gabriel439** [comment]
Yeah, this is essentially the same issue as #828 and the general term for this feature is "row polymorphism".  I'll close this out in favor of that issue, but I'll rename the title to make it more discoverable
