### ISSUE TITLE
Some options in 'Getting started tutorial ' don't exist

### ISSUE THREAD

**Issue by nhicher** [dhall-lang/dhall-lang#894]
Hello,
I've just finished the tutorial with dhall-to-json 1.6.1 and found few issues:
- line 213: using --pretty doesn't change the output for me, but I found the --compact option to have the same output than in exercises.
- line 217: not sure if the output of --help should be in the file, that's need to update the tutorial if new options are added.
- line 728 to 742: --omitNull doesn't exist, the default output remove null values:
 $ dhall-to-json --compact <<< '[ { x = 1, y = None Natural }, { x = 2, y = Some 3 } ]'
[{"x":1},{"x":2,"y":3}]

Thanks for the tutorial, that's really useful. Where can I find the main language tutorial (last line of the tutorial file)?

Thanks

**Comment by Gabriel439** [comment]
I have a pull request up with fixes here: https://github.com/dhall-lang/dhall-lang/pull/895
