### ISSUE TITLE
HTTPS for dhall-lang.org

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-lang#90]
http://dhall-lang.org works but https://dhall-lang.org doesn't. Could it?

**Comment by Gabriel439** [comment]
I'm not sure, but I don't know of a way to do so.  I implement it in my DNS provider as a temporary redirect and that doesn't seem to work with HTTPS

**Comment by Gabriel439** [comment]
Also, in the long run that will eventually go to a dedicated landing page for Dhall

**Comment by ocharles** [comment]
Ah, DNS won't work I don't think as the certificate won't be valid for the correct domain. I wasn't sure if you were running `nginx` to do a HTTP redirection.

**Comment by Gabriel439** [comment]
I could do use `nginx` to do the redirection, though.  I already have it set up for `hydra.dhall-lang.org` and it would be pretty easy to reuse it for `dhall-lang.org`, too

**Comment by ocharles** [comment]
If it's not too much work, it would be great - I'd like to start hyperlinking to Dhall-lang in general, and would prefer to just use HTTPS and forget about it.

**Comment by Gabriel439** [comment]
Alright, this should be working now
