### ISSUE TITLE
< x : Type | y > doesn't typecheck

### ISSUE THREAD

**Issue by philandstuff** [dhall-lang/dhall-lang#904]
[I asked about this on discourse](https://discourse.dhall-lang.org/t/type-of-x-type-y/145) and @Nadrieril seems to agree this is an issue:

`< x : Type | y >` doesn't typecheck according to the current inference rules.

Maybe we can fix it by allowing unions of mixed kinds?

**Comment by Gabriel439** [comment]
@philandstuff: Yeah, I believe there shouldn't be an issue with allowing them.  We can do it the same way records work
