### ISSUE TITLE
Allow combining record types

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-lang#92]
In `dhall-to-cabal`, we have a bunch of types that are all almost identical:

* https://github.com/dhall-lang/dhall-to-cabal/blob/master/dhall/types/Benchmark.dhall
* https://github.com/dhall-lang/dhall-to-cabal/blob/master/dhall/types/Executable.dhall
* https://github.com/dhall-lang/dhall-to-cabal/blob/master/dhall/types/TestSuite.dhall

They all have some common `BuildInfo` fields, and then add one or two extra fields. If I try and factor out `BuildInfo`, I get

```
Error: You can only combine records

./BuildInfo.dhall  ⫽ { main-is : Text, scope : ./Scope.dhall  }

dhall/defaults/../types/Executable.dhall:1:1
```

Does it have to be this way?

**Comment by Gabriel439** [comment]
Yeah, I think it's probably fine to generalize `//` and `/\` to work on types.  I'd have to implement it to say for sure but if it works then I will put up a proposed change to the semantics

**Comment by Gabriel439** [comment]
Okay, so looking into this more closely I think this would work better if there were a new operator for this purpose.  The reason why you don't want to overload the operator is that it complicates the semantics.  For example, naively overloading the operator to work on both record values and record types behaves weirdly if you have a record value whose field is a record type, such as:

```haskell
{ foo = { bar : Bool } } ∧ { foo = { baz : Text } }
```

If you define the semantics of `∧` to trivially recurse over the fields you run the risk of accidentally merging the wrong kind of values:

```haskell
{ foo = { bar : Bool } } ∧ { foo = { baz : Text } }

-- Oops!  It started by combining record values and not it's combinine record fields
= { foo = { bar : Bool } ∧ { baz : Text } }

= { foo = { bar : Bool, baz : Text } }
```

It's less confusing if it's a new operator name.  The only non-trivial part is deciding what it should be named.

My suggestion is to name it `//\\` (ASCII) / `⩓` (UTF8 U+2A53) and have it behave like the type-level analog of `∧`.  I don't think we need a type-level analog of `//`

**Comment by Gabriel439** [comment]
Alright, I have a prototype of this in a branch here:

https://github.com/dhall-lang/dhall-haskell/compare/gabriel/combine_types

I will open up a proposal to update the standard soon to match that
