### ISSUE TITLE
Broken link on docs.dhall-lang.org

### ISSUE THREAD

**Issue by conklech** [dhall-lang/dhall-lang#920]
At https://docs.dhall-lang.org/howtos/How-to-integrate-Dhall.html, the link to the Haskell `dhall` package under Language Support is broken; it points to 

https://github.com/dhall-lang/dhall-haskell/blob/master/dhall/README

should be 

https://github.com/dhall-lang/dhall-haskell/blob/master/dhall/README.md

Curiously, the version of the document in this repository has the correct URL.

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-lang/pull/921
