### ISSUE TITLE
401 import resolution

### ISSUE THREAD

**Issue by JesterXL** [dhall-lang/dhall-lang#926]
We have an internal Github, and they've enforced login. So dhall import's result in a 401.

I'm wondering if I can either:

A: just publish to our internal Artifactory, then all scripts that need it will use local authentication, or IAM role authentication.

B: just publish to an internal Dhall server that is QA only and allows access to just the publish Dhall files based on Github namespace.

Naturally I hate B because people's URL's won't have any correlation to code.

Anyway, open to ideas.

**Comment by Gabriel439** [comment]
@JesterXL: Is it possible to log into the internal GitHub using HTTP headers?  Because Dhall supports header-based authentication, like this:

```
https://example.com using (toMap { Authorization = "token ${env:GITHUB_TOKEN as Text}" })
```

**Comment by JesterXL** [comment]
Dude... I ❤️ you so much right now.... thanks!

**Comment by Gabriel439** [comment]
@JesterXL: You're welcome! 🙂

**Comment by JesterXL** [comment]
Ok, I'm close; I need to base64 encode the resulting string in the header; is there something in Prelude I can use?

**Comment by JesterXL** [comment]
No wait, ignore me, it works!!!!111oneone

**Comment by Gabriel439** [comment]
@JesterXL: No worries 🙂
