### ISSUE TITLE
RNG in Range?

### ISSUE THREAD

**Issue by rhagenson** [dhall-lang/dhall-lang#939]
Is it possible to build a Dhall function that generates a random number within a given range?

In pseudo-Dhall, I am wanting to do something of the form:

```dhall
let Random = seedYear -> lower -> upper -> Number
let a = Random 2020 0 100
let b = Random 2020 0 100
let c = sqrt (a*a + b*b)
in c
```

---

The intent of my question is to generate "random" diagnostic multiple choice questions where I can create a YAML/JSON bank of a given academic year's questions. Something sort of like:

```json
[
  {
    "question": "What is the hypotenuse of a right triangle with base $a$ and height $b$?",
    "tags": ["sample", "question", "theorem", "right-triangle"],
    "answers": [
        {
          "answer": "$c$",
          "correct": true,
          "reason": "$c$ = sqrt ($a$ * $a$ + $b$ * $b$)"
        },
        {
          "answer": "$c^2$",
          "correct": false,
          "reason": "The square root of $c^2$ was not taken to arrive at the final answer"
        },
    ],
    "department": "Mathematics",
  },
]
```
Assume all instances of `a`, `b`, `c` are filled in with their value equivalent from the config. The `reason`s would be put on the answer key to be disseminated post-quiz/exam so students can ID the gap between their incorrect answer and the correct answer.

**Comment by Gabriel439** [comment]
@rhagenson: This is not possible with the standard set of built-in functions, which you can find here:

* [Built-in types, functions, and operators](https://docs.dhall-lang.org/references/Built-in-types.html)

However, the Haskell implementation does provide support for building a custom evaluator with an extended set of built-ins, and you can find instructions for how to do that here:

* [How to add a new built-in function](https://docs.dhall-lang.org/howtos/How-to-add-a-new-built-in-function.html)

Keep in mind that because Dhall does not provide guarantees about evaluation order, so adding impure built-ins may cause weird behavior if the implementation changes the evaluation strategy for performance reasons (similar to why `unsafePerformIO` is dangerous in Haskell)

**Comment by sjakobi** [comment]
The only possible source of non-determinism in Dhall is from imports. It's actually a feature of Dhall that, modulo varying imports, any Dhall expression will normalize to the same value. (And as insurance against variation in imports, you can annotate them with the hashes of their contents:

    $ echo 'https://prelude.dhall-lang.org/v14.0.0/package.dhall' | dhall freeze
    https://prelude.dhall-lang.org/v14.0.0/package.dhall sha256:c1b3fc613aabfb64a9e17f6c0d70fe82016a030beedd79851730993e9083fde2

)

You could try building a PRNG in pure Dhall, but with arithmetic essentially limited to addition, subtraction and multiplication, even that would be a bit tricky.

**Comment by rhagenson** [comment]
@Gabriel439 thank you for linking out to the built-ins! 
@sjakobi thank you for contextualizing the trickiness!

I think using Dhall in this way might be a bit of a misuse. I was looking for an excuse to using Dhall rather extensively, but this particular usecase might be working against Dhall rather than with it. It seems I will just have to find some other excuse! :smile:

**Comment by alexhumphreys** [comment]
Can't speak for how legit this website is, but after some googling I found https://www.random.org, which has a http api you can use to import random numbers with a seed/range into dhall: 
```
let a = https://www.random.org/integers/?num=1&min=1&max=10&col=1&base=10&format=plain&rnd=id.foo : Natural
let b = https://www.random.org/integers/?num=1&min=1&max=10&col=1&base=10&format=plain&rnd=id.bar : Natural
let c = (a*a + b*b)
in {a = a, b = b, c = c} === {a = 1, b = 7, c = 50}
```
Not sure what you can do about the `sqrt` function, but maybe something like this is of use?

**Comment by rhagenson** [comment]
@alexhumphreys that is really cool! I will need to look into that API further as a possible solution.

**Comment by Gabriel439** [comment]
@alexhumphreys: There are two issues with that approach:

* The interpreter will cache imports, so repeatedly importing the same URL will produce the same result
* URL parameters cannot be templated

**Comment by alexhumphreys** [comment]
From the `seedYear` parameter in the OP `Random` function, I was working (well, more like fooling about) on the assumption getting the same result was desired: those `rnd=id.foo` and `rnd=id.bar` query params in the URLs are seeds, so those URLs are already producing the same result on repeat requests. Hadn't realised imports always cache though, good to know!

And yeah, the lack of URL parameter templating makes something like this pretty awkward.

**Comment by rhagenson** [comment]
My question has been sufficiently resolved with the many pieces of advice of everyone. Given this resolution, I am going to close this issue. Thank you to everyone for their guidance!

**Comment by Gabriel439** [comment]
@rhagenson: You're welcome! 🙂

**Comment by sjakobi** [comment]
One more thing: You could also try modelling your "questions" as functions with a type like

    Natural -> { question : Text, answer : { ... } }

or 

    Params -> { question : Text, answer : { ... } }

where `Params` is a record of randomly generated inputs.

You could then use the instance

    (ToDhall a, FromDhall b) => FromDhall (a -> b)

or [`function`](http://hackage.haskell.org/package/dhall-1.30.0/docs/Dhall.html#v:function) to generate the random parameters on the Haskell side and apply them to the unmarshalled functions.

I'm curious what kind of solution you'll eventually go with. Please keep us updated! :)
