### ISSUE TITLE
double-literal should finish with whitespace

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-lang#94]
In the standard grammar, `integer-literal` and `natural-literal` all end with `whitespace`, but `double-literal` doesn't. This appears necessary to validly parse https://raw.githubusercontent.com/dhall-lang/dhall-haskell/master/tests/parser/double.dhall, as the last element ends with whitespace.

**Comment by Gabriel439** [comment]
Yeah, that's definitely an error in the grammar
