### ISSUE TITLE
should `identifier` also have trailing whitespace?

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-lang#95]
The following

```
λ(a : Type) → λ(a : Type) → a@1\n
```

Doesn't seem parsable by the ABNF. We finish parsing an `identifier`, but hit a new line - but apparently nothing follows an `identifier`.

**Comment by ocharles** [comment]
Or maybe it's wrong that my file wide grammar is `whitespace* expression EOF`?

**Comment by Gabriel439** [comment]
You're right.  It's an error in the grammar.  The grammar needs to be updated to allow whitespace at the end of an `identifier`

**Comment by f-f** [comment]
This seems to be fixed by #96, closing.
