### ISSUE TITLE
Support for finding key/value pairs 

### ISSUE THREAD

**Issue by frgomes** [dhall-lang/dhall-lang#952]
This request consists on providing a host function which exposes the functionality of finding a value which matches a given key in a ``List Map/Entry K V``.

# Background

I've defined ``Application/Type`` like this:

```dhall
let KV = https://prelude.dhall-lang.org/Map/Entry Text Text
in { name : Text
   , image : Text
   , config : List KV
   }
```
... which describes an application deployable from a given container image and requires a certain configuration made of a list of key/value pairs.

A typical use case consists on generating a ``ConfigMap``, which can be easily attained by this:

```dhall
let generateConfigMap =
          \(o : Application.Type)
      ->  { apiVersion = "v1"
          , kind = "ConfigMap"
          , data = o.config
          }
```

# Statement of Problem

Another use case consists on generating resources which require a specific configuration item.

I would like to have the ability to find the value of an specific configuration item and employ its value. Something like this:

```dhall
let generatePersistentVolumeClaim =
          \(o : Application.Type)
      ->  { apiVersion = "v1"
          , kind = "PersistentVolumeClaim"
          , metadata =
              { name = "storage", namespace = "${o.name}-vol0" }
          , spec =
              { accessModes = [ "ReadWriteMany" ]
              , resources.requests.storage = ${o.config.find("storage_size")} ++ "Gi"
              }
          }
```
The important bit here is the _hypothetical_: ``o.config.find( "storage_size" )``.

#  Ways to circumvent

## Employing a record

I could employ a record like this: ``{ storage_size = "10", ... }``. However, the key ``storage_size`` only makes sense to a given application. This solution is not generic and does not scale. I need a generic way which allows me to configure all applications I'm aware of and even all applications I'm not aware of.

## Employing a list

Another tentative would be creating a ``List Text`` which contain the configuration values and then I just need to "remember" that the 7th parameter is ``storage_size``. Well... "having to remember" is not a good thing since you may fail to remember. Also, someone may change your code and such person cannot remember something he/she was never made aware of.

## Employing environment variables

Another way to circumvent would be setting environment variables and then all I have to do is employ ``env:storage_size`` instead. I find this solution a dirty hack which probably does not require additional explanations why.

## Employing a ConfigMap

The idea consists on creating a ``ConfigMap`` from a list of key/value pairs, exactly as already demonstrated in the beginning of this ticket. Once a ``ConfigMap`` is defined in Kubernetes, other resources have the ability to query the contents of a given ``ConfigMap``. In this case, the dhall code should generate code which performs queries on a ``ConfigMap``, instead of expanding configurations, as it would be usual. The downside is that this expedient is dependent on Kubernetes and it would not attend other use cases.

# Request for Improvement

I'm aware that text comparison is intentionally not implemented. However, finding a given record of interest is a common use case in certain contexts.

Tentative function prototypes would be:

```dhall
let Map/select : 
       forall(K : Type) 
    -> forall(V : Type)
    -> forall(key : K)
    -> forall(xs : List Map/Entry K V)
    -> List V

let Map/find : 
       forall(K : Type) 
    -> forall(V : Type)
    -> forall(key : K)
    -> forall(default: V)
    -> forall(xs : List Map/Entry K V)
    -> V
```

An usage example would be:

```dhall
let values = List/head Map/select Text Text "storage_size" config

let value = Map/find Text Text "storage_size" "10" config
```

**Comment by sjakobi** [comment]
As stated, there's no way around text equality with these functions. Even if we'd find a way to implement `Map/select` or `Map/find` without _using_ text equality, either function could be used to _implement_ text equality.

Coincidentally there's an ongoing discussion on adding functions for text manipulation, possibly including text equality on our Discourse: https://discourse.dhall-lang.org/t/text-manipulation-functions/176

For now I'm wondering whether you'd consider using a union for the config keys instead of `Text`. For a union you can [define equality yourself](https://discourse.dhall-lang.org/t/sum-type-value-equal-predicate/185).

**Comment by Gabriel439** [comment]
@frgomes: Would it be possible to parametrize the `Application/type` on the type of the `config` field, like this:

```dhall
let Application
      : Type -> Type
      = \(config : Type) -> { name : Text, image : Text, config : config }
```

... so that then you can write:

```dhall
let generatePersistentVolumeClaim =
          \(o : Application { storage_size : Natural })
      ->  { apiVersion = "v1"
          , kind = "PersistentVolumeClaim"
          , metadata =
              { name = "storage", namespace = "${o.name}-vol0" }
          , spec =
              { accessModes = [ "ReadWriteMany" ]
              , resources.requests.storage = ${Natural/show o.config.storage_size} ++ "Gi"
              }
          }
```

The main reason I suggest doing things in this way is that:

* You'd be able to statically guarantee that the `storage_size` field is present
* The field type wouldn't be constrained to be `Text`.  You could use a more precise type like `Natural` (such as in the above example)

**Comment by frgomes** [comment]
@sjakobi: Thanks a lot for the pointers.

@Gabriel439: Your suggestion works pretty well for generation of ``ConfigMap``s. However, in the case of generators for ``PersistentVolumeClaim``s, looks like I would have to write as many generators as there are applications I'm aware of.

Do you see a way to generalize the generators for ``PersistentVolumeClaim``s, please?

```dhall
let Application
    : Type -> Type
    = \(config : Type) -> { name : Text, image : Text, config : config }

let Args = { storage_size : Natural }

let MailArgs = Args //\\ { ANTIVIRUS : Text, MESSAGE_SIZE_LIMIT : Natural }

let MailApp
    : Type
    = Application MailArgs

let mailArgs
    : MailArgs
    = { storage_size = 10, ANTIVIRUS = "clamav", MESSAGE_SIZE_LIMIT = 50000000 }

let mail
    : MailApp
    = { name = "mail", image = "thunerbird:1.0", config = mailArgs }

let ContactsArgs = Args //\\ { DATABASE : Text }

let ContactsApp
    : Type
    = Application ContactsArgs

let contactsArgs
    : ContactsArgs
    = { storage_size = 4, DATABASE = "contacts" }

let contacts
    : ContactsApp
    = { name = "contacts", image = "addressbook:2.0", config = contactsArgs }

let genConfigMap =
          \(config : Type)
      ->  \(xs : config)
      ->  { apiVersion = "v1", kind = "ConfigMap", data = xs }

let genPvcMail =
          \(o : Application MailArgs)
      ->  { apiVersion = "v1"
          , kind = "PersistentVolumeClaim"
          , metadata = { name = "storage", namespace = "${o.name}-vol0" }
          , spec =
              { accessModes = [ "ReadWriteMany" ]
              , resources.requests.storage =
                  "${Natural/show o.config.storage_size}" ++ "Gi"
              }
          }

let genPvcContacts =
          \(o : Application ContactsArgs)
      ->  { apiVersion = "v1"
          , kind = "PersistentVolumeClaim"
          , metadata = { name = "storage", namespace = "${o.name}-vol0" }
          , spec =
              { accessModes = [ "ReadWriteMany" ]
              , resources.requests.storage =
                  "${Natural/show o.config.storage_size}" ++ "Gi"
              }
          }

let configMap = genConfigMap MailArgs mailArgs

let pvcMail = genPvcMail mail

let pvcContacts = genPvcContacts contacts

in  pvcContacts
```

**Comment by Gabriel439** [comment]
@frgomes: The closest thing I can think of would be:

```dhall
let Application
    : Type -> Type
    = \(config : Type) -> { name : Text, image : Text, config : config }

let Args = { storage_size : Natural }

let MailArgs = Args //\\ { ANTIVIRUS : Text, MESSAGE_SIZE_LIMIT : Natural }

let MailApp
    : Type
    = Application MailArgs

let mailArgs
    : MailArgs
    = { storage_size = 10, ANTIVIRUS = "clamav", MESSAGE_SIZE_LIMIT = 50000000 }

let mail
    : MailApp
    = { name = "mail", image = "mailserver:1.0", config = mailArgs }

let ContactsArgs = Args //\\ { DATABASE : Text }

let ContactsApp
    : Type
    = Application ContactsArgs

let contactsArgs
    : ContactsArgs
    = { storage_size = 4, DATABASE = "contacts" }

let contacts
    : ContactsApp
    = { name = "contacts", image = "addressbook:2.0", config = contactsArgs }

let genConfigMap =
          \(config : Type)
      ->  \(xs : config)
      ->  { apiVersion = "v1", kind = "ConfigMap", data = xs }

let genPvc =
          \(o : Application { storage_size : Natural })
      ->  { apiVersion = "v1"
          , kind = "PersistentVolumeClaim"
          , metadata = { name = "storage", namespace = "${o.name}-vol0" }
          , spec =
              { accessModes = [ "ReadWriteMany" ]
              , resources.requests.storage =
                  "${Natural/show o.config.storage_size}" ++ "Gi"
              }
          }

let genPvcMail =
          \(o : Application MailArgs)
      ->  genPvc (o with config = o.config.{ storage_size })

let genPvcContacts =
          \(o : Application ContactsArgs)
      ->  genPvc (o with config = o.config.{ storage_size })

let configMap = genConfigMap MailArgs mailArgs

let pvcMail = genPvcMail mail

let pvcContacts = genPvcContacts contacts

in  pvcContacts
```

**Comment by frgomes** [comment]
@Gabriel439 : I think the language the way it is attends well the use case of "applications I'm aware of". The other use case (applications informed dynamically by users of my platform) would require an application which writes configurations. But this matter is absolutely off topic.

Thanks a lot for your help.
 :+1:

**Comment by frgomes** [comment]
The example you've provided does not compile and I was not able to find any example/documentation involving the ``with`` keyword which could help me on that. Sorry, but I was not able to get a clue from the ABNF grammar. :-(

**Comment by Gabriel439** [comment]
@frgomes: You'll need the latest version of the interpreter.  The `with` keyword is a recent addition to the language

**Comment by frgomes** [comment]
Thank you so much! :+1:

**Comment by Gabriel439** [comment]
@frgomes: You're welcome! 🙂
