### ISSUE TITLE
Update encoding of floating point values to RFC7049bis

### ISSUE THREAD

**Issue by Nadrieril** [dhall-lang/dhall-lang#953]
The CBOR Working Group is working on an update to RFC7049, the original cbor RFC. This update recommends the following (see [here](https://tools.ietf.org/html/draft-ietf-cbor-7049bis-04#section-4.6)):
>  The preferred encoding for a floating point value is the shortest
   floating point encoding that preserves its value, e.g., 0xf94580 for
   the number 5.5, and 0xfa45ad9c00 for the number 5555.5, unless the
   CBOR-based protocol specifically excludes the use of the shorter
   floating point encodings.  For NaN values, a shorter encoding is
   preferred if zero-padding the shorter significand towards the right
   reconstitutes the original NaN value (for many applications, the
   single NaN encoding 0xf97e00 will suffice).

Since, as far as I know, we made a rather arbitrary choice of how to encode floats in the binary format, it would make sense to follow this recommendation ? Some cbor libraries already use this encoding (notably the rust one, which is why I'm investigating this :angel:).

**Comment by Gabriel439** [comment]
@Nadrieril: Yeah, that seems reasonable to me

**Comment by x448** [comment]
Both RFC 7049 and 7049bis allow a lot of flexibility (to the point CBOR-based protocols often fail to specify enough, so different implementations become incompatible).

Months ago, I requested clarification from 7049bis about floats while helping a [CBOR library in Go](https://github.com/fxamacker/cbor/blob/master/README.md) add float16 (and 7049bis features).  Ultimately ended up providing 4 options for NaN and 5+ for time.

![alt text](https://github.com/fxamacker/images/raw/master/cbor/v2.2.0/cbor_encoptions.svg?sanitize=1 "CBOR Encoding Options")
