### ISSUE TITLE
Allow commas in unions

### ISSUE THREAD

**Issue by Nadrieril** [dhall-lang/dhall-lang#955]
Unions are a rather unique feature of Dhall, so there isn't a commonly accepted syntax for them, as there would be for e.g. lists. I think the Dhall syntax for them is rather nice, except for one detail: the delimiters. I keep mistakenly writing unions like `< a, b >` instead of `< a | b >`. It's a bit of a papercut for me and I would guess I am not the only one.
Since the vertical bar does not appear to be especially more or less clear than a comma would be, could we allow commas in union types ?

**Comment by Gabriel439** [comment]
@Nadrieril: I think we should stick with the bar because it's a convention that many other languages follow.  For example, Haskell, PureScript, Elm, ML, Scala 3, F#, and TypeScript all use the bar to delimit sum type alternatives.  Rust and Swift are the only languages I'm aware of that do not follow this convention

**Comment by Nadrieril** [comment]
We seem to agree that the priority is making the syntax recognizable and closer to what exists in other languages. Let me explain why I think commas would actually be more recognizable and closer to conventions used in other languages. (I hope I don't sound too vindictive, I don't actually care that much but I'd like to convey my intuitions. Here goes)

The difference that I believe underlies this issue is the difference between operators and enumerations. 

When I see a declaration like:
```haskell
data Foo = Left A | Right B
```
the `|` feels like an operator. There are many intuitions that come with an operator: for example, I think of precedence with other operators. Obviously the choice of the symbol is semantically meaningful. I also expect the absence of the operator (as in `data Foo = Left A`) to be a noop.

In contrast, when I see
```rust
enum Foo {
	Left(A),
	Right(B),
}
```
it's clear that there's an enumeration going on. The intuitions are different here. First, the semantics is not in the commas but in the surrounding syntax (here the `enum` keyword). Precedence is clearly not a concern, commas make it clear that they have ultimate precedence. Trailing and leading delimiters seem natural, whereas I would be surprised by `1 + 2 +`. Finally, having a single element in the enumeration preserves the semantic context: an enum with a single variant is distinct from the wrapped type on its own.

Note that for all of the languages you mention this distinction applies: those that use bars (Haskell, Scala, ...) don't use them between braces; they are meant to feel like an operator. And those that use commas (Rust, Swift) obviously have some surrounding syntax as a boundary.

Now let's apply this to Dhall. When I see
```
< a | b | c >
```
without context, I instinctively imagine there are two constructs at play: one is enclosing an expression in brackets `< e >` and the other is an operator `|`. When I see
```
< a, b, c >
```
however, I identify the commas as denoting an enumeration and I look for some enclosing syntax that would define its boundaries and semantics.

So that's my intuition: for me, dhall unions fall clearly in the latter category. Using commas would better convey how this construct works in the language.

**Comment by sjakobi** [comment]
I think it's a plus that `< a | b >` is so visually distinct from lists (`[ a, b ]`) and record puns (`{ a, b }`). Commas should IMHO be _less_ overloaded, not _more_.

To allow both `< a | b >` and `< a, b >` would IMHO be quite confusing.

To migrate all unions to use commas as delimiters would IMHO be relatively painful for relatively little gain.

**Comment by Profpatsch** [comment]
This is of course a bike-shedding question, but from a technical standpoint it makes the parsers more complicated and slightly less efficient if multiple versions are allowed.
Also, which version would the pretty printer implement?

Syntax questions are mostly moot from my point of view, so I’ll shut up now. :)

**Comment by Nadrieril** [comment]
Well, there are two different questions: one is choosing which solution seems best, in an ideal world where we were starting from scratch. The other question is how we would transition and it the benefits are worth the cost of transition.
It might be that we agree that commas would be better but that it's not worth it to change. I'm not sure myself honestly. But I'd be interested to know where we stand on both questions separately.

**Comment by Gabriel439** [comment]
@Nadrieril: Even in an ideal world starting from scratch I prefer `|`s.  Indeed, back when I was authoring Dhall from scratch I considered both commas and bars for unions and preferred bars, for the reasons I mentioned above

**Comment by Nadrieril** [comment]
Well, seems like its settled then
