### ISSUE TITLE
Specify "as Location" in more detail

### ISSUE THREAD

**Issue by philandstuff** [dhall-lang/dhall-lang#960]
PR #933 changed the tests so that the expression `env:FOO as Location`, which previously resolved to `<...>.Environment "env:FOO"`, now resolves to `<...>.Environment "FOO"`.

The standard does not help me to decide which of these is correct.  All it says is:

> import its location as a value of type
`< Local : Text | Remote : Text | Environment : Text | Missing >` instead of
importing the file a Dhall expression

but doesn't go into much more detail than that.

We should make it clearer in the standard what the actual `as Location` semantics are.

**Comment by Gabriel439** [comment]
I have a fix up for this here: https://github.com/dhall-lang/dhall-lang/pull/972
