### ISSUE TITLE
There is no normalization rule for forall's that do not name their argument

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-lang#97]
https://github.com/dhall-lang/dhall-lang/blob/master/standard/semantics.md#functions lacks the following rule

```
A₀ → A₁   B₀ → B₁
─────────────────
A₀ → B₀ ⇥ A₁ → B₁
```

I note that in the informal syntax, we should consider `A → B` is short-hand for `∀(_ : A) → B`)`, but there are plenty of other cases in the semantics where this distinction is actually made clear in the rules.

**Comment by ocharles** [comment]
> but there are plenty of other cases in the semantics where this distinction is actually made clear in the rules.

Actually, I'm wrong - it's `let` with bindings that annotate their types vs. no annotation where a distinction is made.

So maybe nothing needs to change here.

**Comment by Gabriel439** [comment]
Yeah, I think the semantics are consistent here and they say to treat a missing quantified variable as `_`

**Comment by ocharles** [comment]
Alrighty, let's keep this how it is for now.
