### ISSUE TITLE
Releases of prelude

### ISSUE THREAD

**Issue by andrewthad** [dhall-lang/dhall-lang#977]
Since HTTP imports don't get cached across multiple invocations of `dhall`, I like to just have the prelude on my filesystem. To get the prelude, I clone this repo and then copy out the relevant directory. Something I'd thought of that would cut out a step and make it a little easier to get the prelude on their local filesystem would be if the prelude was packaged up as a github release, with one release per prelude version.

Feel free to close this if it's not something you're interested in using this repository for. It's certainly not a make-or-break kind of thing.

**Comment by SiriusStarr** [comment]
FWIW, if you freeze the import it will be cached across multiple invocations of `dhall`; my (possibly incorrect?) understanding is that if you have a hashed import, it checks if it's in the cache first and imports it from there instead of the semantic hash checks out.

**Comment by Gabriel439** [comment]
@SiriusStarr: Yes, that is correct.  See:

* [Language Tour - Installing packages](https://docs.dhall-lang.org/tutorials/Language-Tour.html#installing-packages)

**Comment by andrewthad** [comment]
Thanks everyone, that addresses my issue! And also I've realized that github releases are already used by this repo for a different purpose. Closing.
