### ISSUE TITLE
Include rail-road grammar diagrams to compliment the ABNF

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-lang#98]
[GrammKit](http://dundalek.com/GrammKit/) can generate so called "rail-road" diagrams from some grammars. Dhall.js uses PEG.js for its parser, which is a supported input to GrammKit. The result is https://ocharles.org.uk/dhall-grammar.html. We can probably tidy this up, but I think it would be a great addition to the public facing documentation and standards.

**Comment by ocharles** [comment]
I note with things like https://ocharles.org.uk/dhall-grammar.html#simpleLabel that it doesn't distinguish between things that shouldn't parse - that whole `reserved` block is a look-ahead that must fail, so it shouldn't show up here. This might suggest a separate grammar, like the ABNF, that can actually be read by GrammKit (or replacing the ABNF by something else).

**Comment by ocharles** [comment]
I see https://github.com/dundalek/GrammKit/issues/9 discusses that exact issue, and they are working out potential improvements. It turns out the negative look ahead is shown, but the double vertical lines is a bit too subtle.

**Comment by Gabriel439** [comment]
Yeah, I think this is a good idea.  An appropriate place to host this is underneath the reference subsection of the Dhall wiki:

https://github.com/dhall-lang/dhall-lang/wiki

**Comment by Gabriel439** [comment]
Actually, you don't even need to "host" it there per se.  You can just have the wiki link to wherever you host it (i.e. on your site or in the `dhall-js` project if you prefer).

**Comment by ocharles** [comment]
It'd be nice to remove an indirection and have it directly on the wiki. I think GrammKit can generate Markdown, so I'll explore that. I will probably have to host the images externally, if it generates them, but I'm fine with that.

**Comment by ocharles** [comment]
I also wonder if it should be checked it, and versioned in parallel with changes to the ABNF file.

**Comment by Gabriel439** [comment]
Yeah, you can feel free to check it in.  The place it would go is underneath the `standard/` directory since it is another presentation of the standard grammar

**Comment by ocharles** [comment]
Cool, assign this to me and I'll get a PR up.

**Comment by ocharles** [comment]
I'm unlikely to get round to fixing this. Sorry all! Closing for now.
