### ISSUE TITLE
Inference for tackling error "List elements should all have the same type"

### ISSUE THREAD

**Issue by frgomes** [dhall-lang/dhall-lang#985]
I'm converting YAML files to JSON and then to DHALL using just a simple conversion tool plus some trickery which embellishes JSON files so that they become valid DHALL files.

The resulting DHALL files are made of lots of lists made of slightly different records. Most of the time a few records are slightly different among a bunch of all other records which are all of same structure. This obviously causes compilation failures.

In order to tackle these compilation failures I have to inform an enumeration entry type to every entry of a given list which contains records of different shapes. I would like to say that the list itself is made of records matching the enumeration type.

For example, instead of:

```dhall
let Record =
      < Named : { id : Natural, name : Text }
      | Plain : { id : Natural }
      >

let recs =
          [ Record.Named { id = 5, name = "five" }
          , Record.Plain { id = 7 }
          ]
```

... which requires manually editing every single record, I would like to do:

```dhall
let Record =
      < Named : { id : Natural, name : Text }
      | Plain : { id : Natural }
      >

let recs : List Record =
          [  { id = 5, name = "five" }
          ,  { id = 7 }
          ]
```

... which requires me just to tell that ``recs`` is of type  ``List Record``.

This would make my life far easier since I have a dhall file with nearly 10,000 lines which will require literally hundreds of edits just to inform every single record type.

**Comment by Gabriel439** [comment]
@frgomes: This might not work the way you propose, mainly because the type-checking step precedes the conversion to JSON/YAML and the two steps are independent, so the expression won't make it past the type-checker.

However, there might be another solution that lets you use a more uniform syntax for the list, which is to use the record completion operator, like this:

```dhall
let Record =
      { Type = { id : Natural, name : Optional Text }
      , default = { name = None Text }
      }

let recs
    : List Record.Type
    = [ Record::{ id = 5, name = Some "five" }
      , Record::{ id = 7 }
      ]

in  recs
```

For more details on this operator, see:

* [Dhall Manual - Defaults](https://github.com/Gabriel439/dhall-manual/blob/b22f9381256780b32041929187cc67c9857ef5e2/manuscript/03-Defaults.md)

**Comment by frgomes** [comment]
@Gabriel439 :: Thanks for your suggestion.

Maybe your suggestion could work with the data structures I have. I really don't know, since they have multiple nesting levels, being so complex that it would take me a lot of time and effort just to figure out if that would work out or not.

From the perspective of ergonomics, I would still have to perform lots of edits in order to make it type-check. In the end, it's a matter to choose between one style or the other, both requiring lots of edits anyway.

I circumvented the original problem I've described initially by not using Dhall at all, which is OK in this case in particular, but could be troublesome in other circumstances.

I had hope that the type checker could eventually figure out from the type informed that all records of a list must necessarily match one of the alternatives of the union type, something like the fictitious/exploratory syntax below. However, I admit that implementing such thing is far from trivial.

```dhall
let Record =
      < Named : { id : Natural, name : Text }
      | Desc : { id : Natural, name : Text, desc : Text }
      | Priority : { id : Natural, priority : Natural }
      | Plain : { id : Natural }
      >

-- this is fictitious, exploratory syntax
let recs
    : List Record
    = (List Record):: [ 
        { id = 5, name = "five" }
      , { id = 5, name = "five", desc = "the 5th"  } 
      , { id = 5, priority = 0 }
      , { id = 7 }
      ]

in  recs
```

In my exploratory example above, I've considered employing your suggestion, but this implies on using Optional fields, which led me to #778 and #382, which convinced me that I should stick with an union type.

In my use case in particular, I would have to understand a pretty complex data structure and arrive to a very complex union type. However, this sound better to me than having to manually edit a huge file and manually insert type hints all over the place.

I leave with you the decision of closing this ticket... or eventually not :-)

Once again, thanks a lot and regards,

**Comment by Gabriel439** [comment]
@frgomes: Just out of curiosity, where did the original file of ~10,000 line come from?  The reason I ask is that there is a `json-to-dhall` tool that will convert JSON to Dhall for you and apply the relevant union wrappers if you specify a union as the desired Dhall type.

**Comment by frgomes** [comment]
@Gabriel439 : My huge file is mostly made of CRDs plus more code, etc.

The problem I had is regarding how to convert the .yaml below to .dhall:
https://github.com/jetstack/cert-manager/releases/download/v0.14.3/cert-manager.crds.yaml

I've tried ``json-to-dhall`` long before but I had to provide the schema to the tool, which is not practical in most circumstances, imho.

Something just occurred to me now:

If I use ``jq`` in order  to select subtrees of a .json file, I could transform these .json snippets into .dhall snippets, obtain all schemas I need so that later I can define an union type made of these schemas.

I've said above that I find ``json-to-dhall`` inconvenient. I've created an ugly shell script which does the work for me when I don't have knowledge of the schema involved. The shell script does a pretty good job in most cases, except cases like this very ticket here. Using this shell script, I could generate a .dhall, obtain its type via ``dhall type`` and then later I define an union type made of the schemas obtained.

This is my ugly shell script:

```bash
function codegen_json_to_dhall_preprocess {
    for f in $* ; do
        sed -E 's|:[ \t]+false|: False|g' -i $f
        sed -E 's|:[ \t]+true|: True|g' -i $f
        sed    's|{}|{=}|g' -i $f
        sed -E 's|(^[ \t]+)"(.+)":|\1\2 =|g' -i $f
    done
}

function codegen_json_to_dhall_generator {
    local type=$1
    shift
    
    for f in $* ;do
        local x=$(basename $f .json);

        cat << EOD >> generator.dhall
let gen${x} =
\(o : ${type}) ->
EOD

        cat $f >> generator.dhall
        echo "" >> generator.dhall
    done

    local array=()
    for f in $* ;do
        local x=$(basename $f .json)
        array+=($x)
    done
    
    cat << EOD >> generator.dhall
let generate =
          \(o : ${type})
      ->  { p${array[0]} = gen${array[0]} o
EOD


    for f in  ${array[@]:1} ;do echo ", p${f} = gen${f} o" >> generator.dhall ;done

    cat << EOD >> generator.dhall
          }

in  generate
EOD

    dhall format --inplace generator.dhall
}

function codegen_dhall_postprocess {
    for f in $* ; do
        sed '/, annotations = null/d' -i $f
    done
}
```

**Comment by ari-becker** [comment]
@frgomes I'm curious - why are you trying to convert the cert-manager CRD to Dhall?
We've moved all of our Kubernetes manifests to Dhall (we maintain e.g. https://github.com/coralogix/dhall-prometheus-operator ), but even still, whenever we need to use the CRD for an externally-maintained Kubernetes operator, we've written our build scripts to just download the CRD yaml directly from the relevant operator's GitHub repository. We neither refer to the fields in the CRD in our other Dhall-ified manifiests nor would we see ourselves maintaining the CRD by hand (since we just apply whatever upstream publishes).

I'm asking because it sounds like a use-case we would have, if there's a good reason to do it, so maybe your explanation would help us.

**Comment by joneshf** [comment]
I've some thoughts:

1. As mentioned in a [previous comment about optional fields](https://github.com/dhall-lang/dhall-lang/issues/382#issuecomment-526641371), there's a different between a field that is optionally there and a field that's always there with a optional value. The impedance mismatch is the root of what's causing this issue and the other similar issues.

    Maybe if records are not going to get optional **fields** there's some other type we can create that will get optional fields? This is akin to how we added maps to the language to solve a problem.
1. If defining a schema for `json-to-dhall`/`yaml-to-dhall` is hard, maybe `json-to-dhall`/`yaml-to-dhall` can learn to infer the schema? I feel like it should be possible, since other languages have type inference for records. The question is whether `json-to-dhall`/`yaml-to-dhall` want to add support for this feature.

**Comment by Gabriel439** [comment]
@joneshf: I'd accept a pull request adding schema inference to `{json,yaml}-to-dhall`.  I've tried this in the past, but the hardest part is deciding what do in the case of a record field mismatch like:

```json
[ { "x": 1, "y": true }, { "x": 2, "z": "ABC" } ]
```

Should it use `Optional` fields or encode the record as a `Map`?  Both cases are pretty common in the wild and you sometimes see both idioms within the same configuration file.

For all of the other decisions I have a pretty clear heuristic for how to pick the type to infer, but that's the one decision I keep getting stuck on.

**Comment by joneshf** [comment]
What would the schema for that be if you were doing it by hand?

**Comment by Gabriel439** [comment]
@joneshf: It depends on the context.  If it's just a pass-through value then the type would be a `Map`, but if it were a record with a bunch of default-valued fields then it would be `Optional` fields.

**Comment by frgomes** [comment]
@ari-becker : You are correct. I don't really need to convert CRDs to Dhall. I'm just downloading the CRDs and applying them when a new cluster is provisioned. The point is that I was operating in "autopilot" and I've just applied the very same procedure I apply to all other things. Only later I've realized that I don't need to process or generate this kind of data.

**Comment by joneshf** [comment]
@Gabriel439 Gotcha. Well if there's no canonical schema, it seems like a record with optional values would be more useful. It's easier to replace a record with a map than to replace a map with a record.

@frgomes if `json-to-dhall`/`yaml-to-dhall` were able to infer a schema if you didn't give it one, would that be useful? You might need to alter it afterward to be more correct. From the discussion above, you might end up with something like:

```Dhall
…
let Record : { id : Natural, name : Optional Text }
let recs =
          [ { id = 5, name = Some "five" }
          , { id = 7, name = None Text }
          ]
…

**Comment by ari-becker** [comment]
> @joneshf: I'd accept a pull request adding schema inference to `{json,yaml}-to-dhall`. I've tried this in the past, but the hardest part is deciding what do in the case of a record field mismatch like:
> 
> ```json
> [ { "x": 1, "y": true }, { "x": 2, "z": "ABC" } ]
> ```
> 
> Should it use `Optional` fields or encode the record as a `Map`? Both cases are pretty common in the wild and you sometimes see both idioms within the same configuration file.
> 
> For all of the other decisions I have a pretty clear heuristic for how to pick the type to infer, but that's the one decision I keep getting stuck on.

Sounds to me like the tool should prefer `Optional` fields, as it retains the most type-level information. If the user needs a `Map` later, well, that's why we have utilities like `toMap`, right?

**Comment by Gabriel439** [comment]
@joneshf @ari-becker: Alright, I have a pull request up adding `{json,yaml}-to-dhall` support for inferring the schema:

https://github.com/dhall-lang/dhall-haskell/pull/1773

**Comment by lisael** [comment]
Regarding the original issue, the proposed change could be generalized to Union constructor inference (so I call it). If all the alternatives of a union have a different type, Dhall could be able to infer which alternative fits:

```dhall
let Record = <
  | Plain : Natural  -- could be a non-record type ?
  | Named : { name : Text, value : Natural }
  >

let a = assert : Record 2 === Record.Plain 2
let b = assert : Record { name = "spam", value = 42 } === Record.Named { name = "spam", "value" = 42 }
```

Maybe slightly better with an explicit operator, say `&`

```dhall
let a = assert : Record & 2 === Record.Plain 2
```
I didn't make a RFC at the time, because I think that the condition of every alternative with a different type is very specific and the use-cases are limited. Maybe it doesn't worth the change. As other use-cases arise, let me drop this here.

**Comment by frgomes** [comment]
@joneshf : Yes, if ``json-to-dhall`` could infer the schema and output it... that would save a lot of repetitive work.

In the case of record field mismatch as @ari-becker  mentioned, maybe ``json-to-dhall`` could simply fail for the time being whilst a better solution is baking. In this case in particular, the tool would still be very useful since I could extract subtrees of the full .json file and obtain the inferred schemas for them. Then, the next step consists on putting all inferred schemas together as part of  union type.

**Comment by Gabriel439** [comment]
@frgomes: I have a pull request up that adds `{json,yaml}-to-dhall` support for inferring the schema in https://github.com/dhall-lang/dhall-haskell/pull/1773

Once that is merged I can easily extend it to add support for outputting the schema, too.

**Comment by Gabriel439** [comment]
I'll mark this fixed since the latest release of `{json,yaml}-to-dhall` now has support for schema inference.  You can both:

* omit the schema and let them infer the correct Dhall value:

  ```bash
  $ cat example.yaml
  - id: 5
    name: "five"
  - id: 7

  $ yaml-to-dhall --file ./example.yaml 
  [ { id = 5, name = Some "five" }, { id = 7, name = None Text } ]
  ```

* ask the tools to product the inferred schema which you can then edit and reuse:

  ```bash
  $ yaml-to-dhall type --file ./example.yaml 
  List { id : Natural, name : Optional Text }
  ```

**Comment by frgomes** [comment]
For the benefit of people landing on this page:

Taking this example .json data:
```json
[
  { "id" : 5, "name" : "five" }
, { "id" : 5, "name" : "five", "desc" : "the 5th"  } 
, { "id" : 5, "priority" : 0 }
, { "id" : 7 }
]
```

We can infer its type:
```
$ json-to-dhall type --file x.json
List
  { desc : Optional Text
  , id : Natural
  , name : Optional Text
  , priority : Optional Natural
  }
```

Then we generate or bake manually a x.dhall file with data employing this knowledge:
```dhall
$ cat x.dhall
let Record = {
    id : Natural
  , name : Optional Text
  , desc : Optional Text
  , priority : Optional Natural
  }

let recs : List Record =
[ { id = 5, name = Some "five", desc = None Text, priority = None Natural }
, { id = 5, name = Some "five", desc = Some "the 5th", priority = None Natural }
, { id = 5, name = None Text, desc = None Text, priority = Some 0 }
, { id = 7, name = None Text, desc = None Text, priority = None Natural }
]

in recs
```

Then we can generate .json or .yaml from it:
```bash
$ dhall-to-yaml --file y.dhall 

- id: 5
  name: five
- desc: the 5th
  id: 5
  name: five
- id: 5
  priority: 0
- id: 7
````
